### DISCUSSION TITLE
viewing the alert that triggered by the wazuh 6 months ago

### DISCUSSION THREAD

**Discussion by mostwanted5** [wazuh/wazuh#17311] [General]
is it possible to view and analyse the alerts in wazuh dashboard when i re upload a log file like alert.json or archive.json that is deleted long ago from wazuh.

**Comment by s-ocando** [comment]
Hi @mostwanted5,

Yes, you can use the old alert files to re-inject alerts into your Wazuh dashboard for further analysis. Here's a link to an old blog post that includes detailed instructions on how to do so: [Recover your data using Wazuh alerts backups](https://wazuh.com/blog/recover-your-data-using-wazuh-alert-backups/).

This blog post includes a script named `recovery.py` that you can use to extract old alert files into a new file, for example, `recovery.json`.  To ensure the smooth operation of your cluster, you can configure the script to write these old alerts at a designated Events Per Second (EPS) rate.

Configure Filebeat to read the recovery file by editing `/usr/share/filebeat/module/wazuh/alerts/manifest.yml` and adding the path to the new file:

```
module_version: 0.1

var:
  - name: paths
    default:
      - /var/ossec/logs/alerts/alerts.json
      - /tmp/recovery.json
  - name: index_prefix
    default: wazuh-alerts-4.x-

input: config/alerts.yml

ingest_pipeline: ingest/pipeline.json
``` 

Restart Filebeat so changes can take effect, and run the script to start writing the recovery file and re-indexing your alerts.

Let us know if you have any further questions.
