### DISCUSSION TITLE
How can we fix "3099 - ERROR3099 - Invalid credentials" error?

### DISCUSSION THREAD

**Discussion by HieudzNo1** [wazuh/wazuh#23542] [Q&A] [answered]
Hi #community
Can anyone help me with this error "3099 - ERROR3099 - Invalid credentials" ?
I'm very new with wazuh, thanks a lot!

**Comment by rauldpm** [comment, marked as answer]
Hi @HieudzNo1, this error is mainly due to an invalid credential in the Wazuh dashboard `wazuh.yml` configuration, where the `wazuh-wui` user configuration is set.

You can find this configuration at the end of the file in: `/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml`

On a basic installation, without changing passwords, you should see something like:

```
hosts:
  - default:
      url: https://localhost
      port: 55000
      username: wazuh-wui
      password: wazuh-wui 
      run_as: false
```

This configuration has been obtained from the Wazuh OVA 4.7.4, it is possible that depending on your type of deployment, the password is different, for example, in a deployment through the installation assistant, the passwords are randomized for each user, you can find those passwords in a `tar.gz` file generated in the same directory where the `wazuh-install.sh` script has been executed.

Please make sure that the password used is correct, I will be able to give you more concrete steps if you provide more information about your environment and type of deployment.
