### ISSUE TITLE
Remove custom relative paths from the Wazuh API configuration

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#11409]
To avoid issues and maintain consistency with the Wazuh log files, we are removing this section from the Wazuh API configuration file (`api.yaml`):

```yaml
# Logging configuration
# Values for API log level: disabled, info, warning, error, debug, debug2 (each level includes the previous level).
 logs:
  path: "logs/api.log"

```

From now on, the Wazuh API log will always be stored under the `WAZUH_PATH/logs` directory. Currently, only its log level will be configurable.

This will also be applied to the HTTPS private key and certificates, as only the filename will be configurable and it will be taken for granted that the given names will exists under `WAZUH_PATH/api/configuration/ssl`:

Before

```yaml
 https:
  key: "api/configuration/ssl/server.key"
  cert: "api/configuration/ssl/server.crt"
  ca: "api/configuration/ssl/ca.crt"

```

After

```yaml
 https:
  key: "server.key"
  cert: "server.crt"
  ca: "ca.crt"
```

As before, if the configured file does not exist under the expected directory, it will be created by the Wazuh API with the given name.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)
