### ISSUE TITLE
Kibana using the built-in 'kibana_system' account does not have required permissions

### ISSUE THREAD

**Issue by jkman340** [wazuh/wazuh#11401]
I have Wazuh integrated with an existing ElasticStack instance.  I am currently using the 'kibana_system' built-in user for Kibana to access Elasticsearch.  With this setup, the user does not have the required permissions to setup the wazuh-monitoring indices.

I found this https://groups.google.com/g/wazuh/c/qZmJNYGz5s8 on the Wazuh google groups that documented some of the additional roles needed. I created a new user with the kibana_system role plus a new role with the following permissions (per link above) and then used that user in my kibana.yml configuration.
```
    {
      "cluster": [ "manage", "manage_index_templates" ],
      "indices": [
        {
          "names": [ ".old-wazuh", ".wazuh", ".wazuh-version", "wazuh-*" ],
          "privileges": ["all"]
        }
      ]
    }
```
This allowed the wazuh-monitoring indices to be created and I am not getting any more pop-up errors.

Is this the correct permission set neeeded?  Is this officially documented anywhere for other users?

**Comment by s-ocando** [comment]
Hi! In the default Wazuh installation, we use the `kibanaserver` user and assign it the following `manage_wazuh_index` role:
```
# Wazuh monitoring and statistics index permissions
manage_wazuh_index:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
  - index_patterns:
    - "wazuh-*"
    dls: ""
    fls: []
    masked_fields: []
    allowed_actions:
    - "read"
    - "delete"
    - "manage"
    - "index"
  tenant_permissions: []
  static: false
```  
For more information, see https://github.com/wazuh/wazuh-packages/pull/1748/. 
You may continue using the role you've created as it works as expected, or you may restrict permissions by creating a role analogous to the stock role.
