### ISSUE TITLE
Include requirement rules inside checks in SCA

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#11488]
### Description

CIS benchmarks include checks and entire sections that should be interpreted based on particular conditions that SCA is not able to apply. In a SCA policy, every check will be evaluated if the requirements section is met.

The granularity of the requirements section should be extended to single checks or groups of them. Here is an example with a note extracted from a CIS benchmark for Amazon Linux 2:

![image](https://user-images.githubusercontent.com/29475387/147266404-0cfb803c-4d79-4a61-899d-f65142b27e05.png)

Firewall checks are repeated for `FirewallD`, `NFTables` and `IPTables` taking into account that the user will skip the corresponding sections according to the firewall that is really installed.

This can be achieved in SCA in different ways. For example, we could include a new field in the check content to skip or run the check based on defined rules:

```yml
- id: 20598
  title: "Ensure iptables packages are installed."
  ...
  compliance:
    - cis: ["3.5.3.1.1"]
    - cis_csc: ["9.4"]
    - pci_dss: ["1.1"]
    - tsc: ["CC8.1"]
  condition: all
  rules:
    - 'c:rpm -q iptables -> r:iptables-'
  requirement_condition: all
  requirement_rules:
    - 'c:rpm -q firewalld -> r:^package firewalld is not installed'
    - 'c:rpm -q nftables -> r:^package nftables is not installed'
```

In this case, the check would be skipped when the requirement is not satisfied.
