### ISSUE TITLE
Release 4.3.0 - Manual tests - Centralized configuration - Agent groups

### ISSUE THREAD

**Issue by mikykeane** [wazuh/wazuh#12886]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |    Centralized configuration - Agent groups               |
| **Category**            |    Configuration                                 |
| **Deployment option**   |  Installation guide                                          |
| **Main release issue**  |   https://github.com/wazuh/wazuh/issues/10954                                           |
| **Release candidate #** |  RC5                                          |

## Test description

Test the functionality of agent groups for centralized configuration:
- Try different groups for different OS
- Try tags in the same group, to apply different blocks of configuration to different OS or agents.
- Try creating groups with different files of different types and sizes (try to reach the limits)
- Check if propagation times are acceptable
- Other potential tests

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here]().

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|                |             |                     |                |

All tests have passed and the fails have been reported or justified. Therefore, I conclude that this issue is finished and OK for this release candidate.

## Auditors' validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @vikman90 
- [ ] @santiago-bassett 
- [ ] @davidjiglesias

**Comment by mikykeane** [comment]
##  Test 1: Install indexer using the installation guide

|Component|Installation|Operating system|
|---|---|---|
|Indexer|Manual installation|CentOS 7.9|

### :purple_circle: Documentation Notes - Step by step installation

When beginning the installation, looking at the documentation, although all necessary links were provided. As shown in the image: 
![image](https://user-images.githubusercontent.com/4438081/161511962-fa63a0f8-8cbb-4929-bd62-bf58de612c8b.png)

If we look at the the Wazuh Agent installation section, the format makes it more intuitive and know where to click. Users that do not read the documentation carefully might find themselves clicking on the agent installation before installing the Wazuh Manager. 

![image](https://user-images.githubusercontent.com/4438081/161512344-5e9c29ba-100f-4b50-ac88-6b12ce0dd231.png)

I would suggest having a similar menu for the Wazuh central components too. As it makes it more intuitive to know where to click. 



Here: 

![image](https://user-images.githubusercontent.com/4438081/161515651-64a25158-a66d-420f-ac00-5aac709025c5.png)

It is not clear in what nodes should these commands be executed. Should it be executed in all Wazuh Indexer nodes? Does it matter? These should be clear to the user executing the commands. 


### Configuration

<details>
<summary>config.yml</summary>

```yml
nodes:
  # Wazuh indexer nodes
  indexer:
    name: indexer1
    ip: 192.168.6.3
    name: indexer2
    ip: 192.168.6.4

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:
    name: master43
    ip: 192.168.6.0
    node_type: master
    name: worker43
    ip: 192.168.6.2
    node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    name: indexer1
    ip: 192.168.6.3
```

</details>


### :red_circle:  Installation steps

1. Downloaded script `wazuh-certs-tool.sh` 
2. Fill _config.yml_.
3. Generate certificates:
   <details>
    <summary><code>bash ./wazuh-certs-tool.sh -A</code></summary>

    ```
    # bash ./wazuh-certs-tool.sh -A
    03/30/2022 17:51:30 INFO: Admin certificates created.
    04/30/2022 17:51:30 INFO: Wazuh indexer certificates created.
    04/30/2022 17:51:31 INFO: Wazuh server certificates created.
    04/30/2022 17:51:31 INFO: Wazuh dashboard certificates created.
    ```
    </details>

4. Compressed and deleted certificates directory. 
5. Installed dependencies and added repositories. 
6. Installed indexer on every indexer node:
    <details>
    <summary><code>yum install -y wazuh-indexer</code></summary>

    ```
        [root@indexer1 vagrant]# yum install -y wazuh-indexer
        Loaded plugins: fastestmirror
        Loading mirror speeds from cached hostfile
         * base: mirror.airenetworks.es
         * extras: mirror.airenetworks.es
         * updates: mirror.tedra.es
        wazuh_pre_release                                                                             | 3.4 kB  00:00:00     
        wazuh_pre_release/primary_db                                                                  | 155 kB  00:00:02     
        Resolving Dependencies
        --> Running transaction check
        ---> Package wazuh-indexer.x86_64 0:4.3.0-1 will be installed
        --> Finished Dependency Resolution
        
        Dependencies Resolved
        
        =====================================================================================================================
         Package                      Arch                  Version                   Repository                        Size
        =====================================================================================================================
        Installing:
         wazuh-indexer                x86_64                4.3.0-1                   wazuh_pre_release                361 M
        
        Transaction Summary
        =====================================================================================================================
        Install  1 Package
        
        Total download size: 361 M
        Installed size: 614 M
        Downloading packages:
        wazuh-indexer-4.3.0-1.x86_64.rpm                                                              | 361 MB  00:01:07     
        Running transaction check
        Running transaction test
        Transaction test succeeded
        Running transaction
          Installing : wazuh-indexer-4.3.0-1.x86_64                                                                      1/1 
        Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
          Verifying  : wazuh-indexer-4.3.0-1.x86_64                                                                      1/1 
        
        Installed:
          wazuh-indexer.x86_64 0:4.3.0-1                                                                                     
        
        Complete!

    ```
    </details>

7. Changed settings according to the documentation:
    <details>
    <summary>/etc/wazuh-indexer/opensearch.yml </summary>

    ```yml
            network.host: "0.0.0.0"
            node.name: "indexer1"
            cluster.initial_master_nodes:
            - "indexer1"
            #- "node-2"
            #- "node-3"
            cluster.name: "wazuh-cluster"
            #discovery.seed_hosts:
            #  - "node-1-ip"
            #  - "node-2-ip"
            #  - "node-3-ip"
            node.max_local_storage_nodes: "3"
            path.data: /var/lib/wazuh-indexer
            path.logs: /var/log/wazuh-indexer
            
            plugins.security.ssl.http.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
            plugins.security.ssl.http.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
            plugins.security.ssl.http.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
            plugins.security.ssl.transport.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
            plugins.security.ssl.transport.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
            plugins.security.ssl.transport.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
            plugins.security.ssl.http.enabled: true
            plugins.security.ssl.transport.enforce_hostname_verification: false
            plugins.security.ssl.transport.resolve_hostname: false
            
            plugins.security.audit.type: internal_opensearch
            plugins.security.authcz.admin_dn:
            - "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
            plugins.security.check_snapshot_restore_write_privileges: true
            plugins.security.enable_snapshot_restore_privilege: true
            plugins.security.nodes_dn:
            - "CN=indexer1,OU=Wazuh,O=Wazuh,L=California,C=US"
            - "CN=indexer2,OU=Wazuh,O=Wazuh,L=California,C=US"
            #- "CN=node-3,OU=Wazuh,O=Wazuh,L=California,C=US"
            plugins.security.restapi.roles_enabled:
            - "all_access"
            - "security_rest_api_access"
            
            plugins.security.system_indices.enabled: true
            plugins.security.system_indices.indices: [".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]
            
            ### Option to allow Filebeat-oss 7.10.2 to work ###
            compatibility.override_main_response_version: true

    ```
    </details>

8. Deployed certificates
9. Started wazuh-indexer. 
10. Initialized cluster
    <details>
    <summary><code>/usr/share/wazuh-indexer/bin/indexer-security-init.sh</code></summary>
    
    ```
            [root@indexer1 vagrant]# /usr/share/wazuh-indexer/bin/indexer-security-init.sh
            Security Admin v7
            Will connect to 0.0.0.0:9300 ... done
            Connected as CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US
            OpenSearch Version: 1.2.4
            OpenSearch Security Version: 1.2.4.0
            Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
            Clustername: wazuh-cluster
            Clusterstate: GREEN
            Number of nodes: 1
            Number of data nodes: 1
            .opendistro_security index does not exists, attempt to create it ... done (0-all replicas)
            Populate config from /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/
            Will update '_doc/config' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/config.yml 
               SUCC: Configuration for 'config' created or updated
            Will update '_doc/roles' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/roles.yml 
               SUCC: Configuration for 'roles' created or updated
            Will update '_doc/rolesmapping' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/roles_mapping.yml 
               SUCC: Configuration for 'rolesmapping' created or updated
            Will update '_doc/internalusers' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/internal_users.yml 
               SUCC: Configuration for 'internalusers' created or updated
            Will update '_doc/actiongroups' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/action_groups.yml 
               SUCC: Configuration for 'actiongroups' created or updated
            Will update '_doc/tenants' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/tenants.yml 
               SUCC: Configuration for 'tenants' created or updated
            Will update '_doc/nodesdn' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/nodes_dn.yml 
               SUCC: Configuration for 'nodesdn' created or updated
            Will update '_doc/whitelist' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/whitelist.yml 
               SUCC: Configuration for 'whitelist' created or updated
            Will update '_doc/audit' with /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/audit.yml 
               SUCC: Configuration for 'audit' created or updated
            Done with success

     ```
     </details>

11. Seeing the following Warnings when executing `systemctl status wazuh-indexer -l`: 
   
 ```
        Apr 04 11:21:23 indexer1 systemd[1]: Starting Wazuh-indexer...
        Apr 04 11:21:32 indexer1 systemd-entrypoint[28825]: WARNING: An illegal reflective access operation has occurred
        Apr 04 11:21:32 indexer1 systemd-entrypoint[28825]: WARNING: Illegal reflective access by io.protostuff.runtime.PolymorphicThrowableSchema (file:/usr/share/wazuh-indexer/plugins/opensearch-anomaly-detection/protostuff-runtime-1.7.4.jar) to field java.lang.Throwable.cause
        Apr 04 11:21:32 indexer1 systemd-entrypoint[28825]: WARNING: Please consider reporting this to the maintainers of io.protostuff.runtime.PolymorphicThrowableSchema
        Apr 04 11:21:32 indexer1 systemd-entrypoint[28825]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
        Apr 04 11:21:32 indexer1 systemd-entrypoint[28825]: WARNING: All illegal access operations will be denied in a future release
        Apr 04 11:21:34 indexer1 systemd[1]: Started Wazuh-indexer.

  ```
12. :red_circle:  Tested API commands. Nodes did not connect as a cluster. 
```
[root@indexer1 vagrant]# curl -k -u admin:admin https://192.168.6.3:9200/_cat/nodes
10.0.2.15 12 87 0 0.01 0.02 0.05 dimr * indexer1
```

13. While troubleshooting this issue. I tried executing the `indexer-security-init.sh` on node 2 to check if it worked. This caused an error. I opted to uninstall and reinstall again node2. During the installation I got an error on a loop: 

```
      Root cause: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{eMbe1VJTRheZxoWGjHP2Dg}{0.0.0.0}{0.0.0.0:9300}]] (org.opensearch.client.transport.NoNodeAvailableException/org.opensearch.client.transport.NoNodeAvailableException)
       * Try running securityadmin.sh with -icl (but no -cl) and -nhnv (If that works you need to check your clustername as well as hostnames in your TLS certificates)
       * Make sure that your keystore or PEM certificate is a client certificate (not a node certificate) and configured properly in opensearch.yml
       * If this is not working, try running securityadmin.sh with --diagnose and see diagnose trace log file)
       * Add --accept-red-cluster to allow securityadmin to operate on a red cluster.
    Cannot retrieve cluster state due to: None of the configured nodes are available: [{#transport#-1}{eMbe1VJTRheZxoWGjHP2Dg}{0.0.0.0}{0.0.0.0:9300}]. This is not an error, will keep on trying ...
      Root cause: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{eMbe1VJTRheZxoWGjHP2Dg}{0.0.0.0}{0.0.0.0:9300}]] (org.opensearch.client.transport.NoNodeAvailableException/org.opensearch.client.transport.NoNodeAvailableException)
       * Try running securityadmin.sh with -icl (but no -cl) and -nhnv (If that works you need to check your clustername as well as hostnames in your TLS certificates)
       * Make sure that your keystore or PEM certificate is a client certificate (not a node certificate) and configured properly in opensearch.yml
       * If this is not working, try running securityadmin.sh with --diagnose and see diagnose trace log file)
       * Add --accept-red-cluster to allow securityadmin to operate on a red cluster.
    [root@indexer2 vagrant]# Cannot retrieve cluster state due to: None of the configured nodes are available: [{#transport#-1}{eMbe1VJTRheZxoWGjHP2Dg}{0.0.0.0}{0.0.0.0:9300}]. This is not an error, will keep on trying ...
      Root cause: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{eMbe1VJTRheZxoWGjHP2Dg}{0.0.0.0}{0.0.0.0:9300}]] (org.opensearch.client.transport.NoNodeAvailableException/org.opensearch.client.transport.NoNodeAvailableException)
       * Try running securityadmin.sh with -icl (but no -cl) and -nhnv (If that works you need to check your clustername as well as hostnames in your TLS certificates)
       * Make sure that your keystore or PEM certificate is a client certificate (not a node certificate) and configured properly in opensearch.yml
       * If this is not working, try running securityadmin.sh with --diagnose and see diagnose trace log file)
       * Add --accept-red-cluster to allow securityadmin to operate on a red cluster.
    [root@indexer2 vagrant]# Cannot retrieve cluster state due to: None of the configured nodes are available: [{#transport#-1}{eMbe1VJTRheZxoWGjHP2Dg}{0.0.0.0}{0.0.0.0:9300}]. This is not an error, will keep on trying ...
```

I could not avoid this issue no matter if I did `Control + C` nor any command. It would keep showing. Example of trying to exit: 

```
    * Add --accept-red-cluster to allow securityadmin to operate on a red cluster.
    ^C
    [root@indexer2 vagrant]# Cannot retrieve cluster state due to: None of the configured nodes are available: [{#transport#-1}{eMbe1VJTRheZxoWGjHP2Dg}{0.0.0.0}{0.0.0.0:9300}]. This is not an error, will keep on trying ...
      Root cause: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{eMbe1VJTRheZxoWGjHP2Dg}{0.0.0.0}{0.0.0.0:9300}]] (org.opensearch.client.transport.NoNodeAvailableException/org.opensearch.client.transport.NoNodeAvailableException)
       * Try running securityadmin.sh with -icl (but no -cl) and -nhnv (If that works you need to check your clustername as well as hostnames in your TLS certificates)
       * Make sure that your keystore or PEM certificate is a client certificate (not a node certificate) and configured properly in opensearch.yml
       * If this is not working, try running securityadmin.sh with --diagnose and see diagnose trace log file)
       * Add --accept-red-cluster to allow securityadmin to operate on a red cluster.

``` 
`exit` command still didnt help:  

```
[root@indexer2 vagrant]# exit
exit
Vim: Caught deadly signal TERM
Vim: Finished.
Cannot retrieve cluster state due to: None of the configured nodes are available: [{#transport#-1}{eMbe1VJTRheZxoWGjHP2Dg}{0.0.0.0}{0.0.0.0:9300}]. This is not an error, will keep on trying ...
  Root cause: NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{eMbe1VJTRheZxoWGjHP2Dg}{0.0.0.0}{0.0.0.0:9300}]] (org.opensearch.client.transport.NoNodeAvailableException/org.opensearch.client.transport.NoNodeAvailableException)
   * Try running securityadmin.sh with -icl (but no -cl) and -nhnv (If that works you need to check your clustername as well as hostnames in your TLS certificates)
   * Make sure that your keystore or PEM certificate is a client certificate (not a node certificate) and configured properly in opensearch.yml
   * If this is not working, try running securityadmin.sh with --diagnose and see diagnose trace log file)
   * Add --accept-red-cluster to allow securityadmin to operate on a red cluster.
[vagrant@indexer2 ~]$ systeCannot retrieve cluster state due to: None of the configured nodes are available: [{#transport#-1}{eMbe1VJTRheZxoWGjHP2Dg}{0.0.0.0}{0.0.0.0:9300}]. This is not an error, will keep on trying ...
```

**Issue was so bad I had to close my VM. Will continue testing with a single node and circle around to this issue later.** 


### Issues

|Status|Item|Comments|
|---|---|---|
| :red_circle:  | Following documentation step by step did not connect nodes in the cluster. |Continued single node to complete tests. Will circle around to double check the issue|
| :red_circle: | Stopping the `indexer-security-init.sh` because status could not get green. Then doing `yum remove wazuh-indexer` and a `yum install wazuh-indexer` caused an unstoppable error loop.|I could not get the error notification to stop. Had to stop my VM|

### Suggestions

- Explanations on what should be filled for nodes are not enough:
```yml
 cluster.initial_master_nodes:
 - "node-1"
 #- "node-2"
 #- "node-3"
 cluster.name: "wazuh-cluster"
 #discovery.seed_hosts:
 #  - "node-1-ip"
 #  - "node-2-ip"
 #  - "node-3-ip"
```
- cluster.initial_master_nodes:
    > Should we add 1 node or all available nodes? Why? Why not?

- discovery.seed_hosts:
    > This options is not mentioned. Should we remove comments? When should we add the IP?

**Comment by mikykeane** [comment]
##  :green_circle: Test 3: Install wazuh dashboard using the installation guide step by step

|Component|Installation|Operating system|
|---|---|---|
|Indexer|Manual installation|CentOS 7.9|

###  Installation steps

1. Added repositories and dependencies.
2. Installed the Wazuh dashboard:    <code>yum install -y wazuh-dashboard</code>
3. Configured the correct hostname for the Wazuh API: 
<details>
    <summary><code>/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml</code></summary>

```
hosts:
  - default:
     url: https://192.168.88.165
     port: 55000
     username: wazuh-wui
     password: wazuh-wui
     run_as: false
```
</details>


4. Started the Wazuh-dashboard successfully 

![image](https://user-images.githubusercontent.com/4438081/162511372-2586d7ef-a0d9-4c55-9d89-1717ef80b238.png)
