### ISSUE TITLE
Symbolic Link are alerted as "World writable modified files" in Kibana

### ISSUE THREAD

**Issue by juergenc** [wazuh/wazuh#1316]
Hello,

in the _Overview / Integrity monitoring _ tab of Kibana, symbolic links are alerted as "World writable modified files". Symbolic links are always with the access pattern `777`, e.g.:
```
ls -l /usr/bin/rsh
lrwxrwxrwx 1 root root 21 Aug 10  2015 /usr/bin/rsh -> /etc/alternatives/rsh
```

Important is what permissions the destination file/ directory has where the symbolic link points to it. So for the FIM checks you should follow the symbolic link to its destination where it points to it and evaluate the inode meta information (`stat()`) and not the for the symbolic link itself.

Regards,
Jürgen

**Comment by JuanjiJG** [comment]
Hello @juergenc,

Thank you so much for your feedback. In fact, we're working on a new Wazuh app package which will include a redesigned _Overview / Integrity monitoring_ tab, with the main objective of providing better and more meaningful information about the overall status of your system's Integrity monitoring.

Take a look at the attached picture to see the new tab:

![192 168 56 101_5601_app_wazuh](https://user-images.githubusercontent.com/10928321/45556790-6103fd00-b83c-11e8-91d9-bd0f986be659.png)

This new tab will focus more on an overall view about your agents, instead of focusing on things that have more sense on individual agent basis.

Of course, everything on the Wazuh app is constantly evolving and will improve in future packages. This package will be available soon, but you can always head into our [Wazuh app repository](https://github.com/wazuh/wazuh-kibana-app) and create an issue with more suggestions for the app. Every feedback is really appreciated for us.

Also, we have a [mailing list](https://groups.google.com/forum/#!forum/wazuh) where the community can post threads about questions or problems when using Wazuh, so take a look at it.

Let us know if you have more problems or questions with this.

Regards,
Juanjo

**Comment by juergenc** [comment]
Hello @JuanjiJG ,

indeed, the FIM _overview_ tab looks much better focusing more on the big picture. :)

But a was maybe a little bit imprecise. To file this issue into the _wazuh/wazuh_ and not in the _wazuh/kibana-app_ queue, was on purpose. It does not make much sense to alert world-writable _sybolic links_ as they are always created a such and you cannot change it. More interesting is the destination file where the symbolic link points to it. It is the question how the agent deals with them. Obviously, the agent uses the `lstat()` instead of `stat()` system call for the FIM _syscheck_ processing . `lstat()` is identical to `stat()`, except that if path is a symbolic link, then the link itself is stat-ed, not the file that it refers to. In my eyes it always wrong in this context using `lstat()`, the agent should always use the `stat()` syscall, you are always interested in the destination where link points to it not in the link itself.

Regards and thanks for the hints.
Jürgen

**Comment by JuanjiJG** [comment]
Hello again @juergenc,

Thanks for your comment. I apologise for the misunderstanding, I thought that you were talking about the Wazuh app instead of the core component.

I'll ping the core team about this issue, and they will discuss your comments about symbolic links. We always appreciate the community feedback, and it's taken into account for future implementations, changes or bugfixes.

Regards,
Juanjo

**Comment by vikman90** [comment]
Hi @juergenc and @JuanjiJG,

Indeed, this seems to be an issue in the FIM engine. It's detecting and resolving symbolic links, but it reports the attributes of the link itself.

In other words, just as you said, the agent is using `lstat()` to detect if a file is a link, and then it uses `stat()` to detect whether the linked file is a regular file. However, it reports the data from `lstat()`.

I wonder if this behavior was designed on purpose. Let me discuss this issue with the team and will intent to fix it.

Thank you very much for your feedback.
Best regards.

**Comment by juan70** [comment]
Testing the fix
==
Preamble
--
In `ossec.conf`, on the agent:
```
<syscheck>
    <disabled>no</disabled>
    <scan_on_start>yes</scan_on_start>
    <frequency>120</frequency>
    <directories check_all="yes" realtime="yes" report_changes="yes">/home/vagrant/testdir</directories>
</syscheck>
```
- `frequency=2m`, the default is 12h...
- `realtime=yes`, so we can see the changes immediately.

Test
--
Within the monitored directory, and looking at the manager's `alerts.log`.
- `touch test1_file`
  ```
  Rule: 554 (level 5) -> 'File added to the system.'
  File '/home/vagrant/testdir/test1_file' was added.
  Attributes:
   - Size: 0
   - Permissions: 100644
   - Inode: 412407
   - User: vagrant (1000)
   - Group: vagrant (1000)
  ```

- `ln -s -i ./test1_file ./test1_link`
  ```
  Rule: 554 (level 5) -> 'File added to the system.'
  File '/home/vagrant/testdir/test1_link' was added.
  Attributes:
   - Size: 12
   - Permissions: 100644
   - Inode: 414360
   - User: vagrant (1000)
   - Group: vagrant (1000)
  ```

- `echo 'a' > test1_file `
  ```
  Rule: 550 (level 7) -> 'Integrity checksum changed.'
  File '/home/vagrant/testdir/test1_file' checksum changed.
  Size changed from '0' to '2'
  Attributes:
   - Size: 2
   - Permissions: 100644
   - Inode: 412407
   - User: vagrant (1000)
   - Group: vagrant (1000)
  ```

- `echo 'b' > test1_link `
    ```
  Rule: 550 (level 7) -> 'Integrity checksum changed.'
  File '/home/vagrant/testdir/test1_file' checksum changed.
  Attributes:
   - Size: 2
   - Permissions: 100644
   - Inode: 412407
   - User: vagrant (1000)
   - Group: vagrant (1000)
  ```

- `rm test1_file`
  ```
  Rule: 553 (level 7) -> 'File deleted.'
  File '/home/vagrant/testdir/test1_file' was deleted.
  ```
  No attributes, since the file does not exist now.
  And a bit later:
  ```
  Rule: 550 (level 7) -> 'Integrity checksum changed.'
  File '/home/vagrant/testdir/test1_link' checksum changed.
  Ownership was 'vagrant (1000)', now it is 'vagrant (0)'
  Group ownership was 'vagrant (1000)', now it is 'vagrant (0)'
  Attributes:
   - Size: 12
   - Inode: 414360
   - User: vagrant (0)
   - Group: vagrant (0)
  ```
  The symbolic link exists, but does not point to any real file anymore.

- `rm test1_link`
    ```
    Rule: 553 (level 7) -> 'File deleted.'
    File '/home/vagrant/testdir/test1_link' was deleted.
    ```


- `touch ../test2_file`
The file is out of the monitored directory, so nothing is reported in the manager's `alerts.log`.

- `chown user1:floppy ../test2_file`
Same thing here, the file is unknown to `syscheck`.

- `ln -s -i ../test2_file ./test2_link`
  ```
  Rule: 554 (level 5) -> 'File added to the system.'
  File '/home/vagrant/testdir/test2_link' was added.
  Attributes:
   - Size: 13
   - Permissions: 100644
   - Inode: 414360
   - User: root (1001)
   - Group: root (25)
  ```
  
  `uid=1001` and `gid=25` are correct on the agent.

  ```
  # getent passwd user1
  user1:x:1001:1001::/home/user1:
  # getent group floppy
  floppy:x:25:vagrant,user1
    ```

- `echo 'a' > ../test2_file `
  ```
  Rule: 550 (level 7) -> 'Integrity checksum changed.'
  File '/home/vagrant/testdir/test2_link' checksum changed.
  Attributes:
   - Size: 13
   - Permissions: 100644
   - Inode: 414360
   - User: root (1001)
   - Group: root (25)
  ```
  The change is detected through the symbolic link when the scanning starts.

- `echo 'b' > ./test2_link `
  ```
  Rule: 550 (level 7) -> 'Integrity checksum changed.'
  File '/home/vagrant/testdir/test2_link' checksum changed.
  Attributes:
   - Size: 13
   - Permissions: 100644
   - Inode: 414360
   - User: root (1001)
   - Group: root (25)
  ```

- `rm ../test2_file`
  ```
  Rule: 550 (level 7) -> 'Integrity checksum changed.'
  File '/home/vagrant/testdir/test2_link' checksum changed.
  Ownership was 'root (1001)', now it is 'root (0)'
  Group ownership was 'root (25)', now it is 'root (0)'
  Attributes:
   - Size: 13
   - Inode: 414360
   - User: root (0)
   - Group: root (0)
  ```

- `rm test2_link`
  ```
  Rule: 553 (level 7) -> 'File deleted.'
  File '/home/vagrant/testdir/test2_link' was deleted.
  ```
