### ISSUE TITLE
Analyze CPU consumption in syscheckd Centos agent

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh#13340]
In the tests carried out for RC7 we were able to verify a higher CPU consumption in the Centos agent with respect to 4.2.5, we were able to verify that this behavior does not occur in a sustained manner in the Ubuntu agent, now I share the evidence:

### Centos agent:
![image](https://user-images.githubusercontent.com/64099752/166483294-29c09dcf-71a8-4d1b-8806-152b929a5a26.png)

### Ubuntu agent:
![image](https://user-images.githubusercontent.com/64099752/166483336-04664b10-83c9-4226-96f3-4547df46f598.png)

### Centos agent:
![image](https://user-images.githubusercontent.com/64099752/166483446-89552d4e-7481-440a-beb2-241395ebe45d.png)

### Ubuntu agent:
![image](https://user-images.githubusercontent.com/64099752/166483463-70abbc50-b02f-460b-8ff7-297a0b4632fd.png)

Footprint Syscheck (2.5d): https://github.com/wazuh/wazuh/issues/13284

Regarding the changes in the configuration templates for both Centos and Ubuntu, the changes that were made between the versions are:
- The following files were removed from ignore:
```
    - '/sys/kernel/security'
    - '/sys/kernel/debug'
    - '/dev/core'
```
- Added these settings:
```
   skip_dev: 'yes'
    skip_proc: 'yes'
    skip_sys: 'yes'
    process_priority: '10'
    max_eps: '100'
    synchronization:
      enabled: 'yes'
      interval: '5m'
      max_interval: '10m'
      max_eps: '10'
```
