### ISSUE TITLE
Review failures in numbered branches in the `agent_PUT` API integration test

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#13804]
|Wazuh version|Component|
|---|---|
| 4.3.4 | API integration test |

The issue was discovered in 4.3, but it may be in every numbered branch.

The `Upgrade all agents with os version 18.04.5 LTS and query` test case of the `test_agent_PUT_endpoints.tavern.yaml` API integration test is failing in the **4.3** branch. This error is happening due to a bad test design and it is present in all the numbered branches including this stage.

That is the test stage failing, but the cause of the error is not in this test. The cause is in this previous test:

```yaml
  - name: Upgrade an agent to the latest version (task created but agent cannot be upgraded because the WPK does not exist)
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/agents/upgrade"
      method: PUT
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        agents_list: '006'
    response:
      status_code: 200
      json:
        data:
          affected_items:
            - agent: '006'
              task_id: !anyint
          total_affected_items: 1
          total_failed_items: 0
          failed_items: [ ]
        message: !anystr
```

As we can see in the test name, Upgrade an agent to the latest version (task created but agent cannot be upgraded because the WPK does not exist), the upgrade task is created, but the agent is not upgraded. This behavior is the expected one but in numbered branches, the WPK do exist, and the agent is therefore upgraded.

Due to this upgrade, the tests cases following the one mentioned will be likely (and they do) to fail.

We should review this test and change the design. Maybe using different agents for each test case involving an upgrade is the cleanest solution. The test name should also be updated because as we have seen, it is not true.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)
