### ISSUE TITLE
Analysisd thows two alerts when a new file is added

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#1390]
**Configuration:**

`<directories check_all="yes" whodata="yes">/tmp/e</directories>`

**To reproduce:**

`touch /tmp/e/ls`

**Output:**

```
** Alert 1537540905.77684: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,
2018 Sep 21 16:41:45 localhost->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/tmp/e/ls' was added.

Attributes:
 - Size: 0
 - Permissions: 100644
 - Date: Fri Sep 21 16:41:45 2018
 - Inode: 5229837
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1537540905.78193: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,
2018 Sep 21 16:41:45 localhost->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/tmp/e/ls' checksum changed.

Attributes:
 - Size: 0
 - Permissions: 100644
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

```
