### ISSUE TITLE
CIS benchmark for Ubuntu Linux 20.04 LTS Checks issues

### ISSUE THREAD

**Issue by scott-mackenzie** [wazuh/wazuh#14235]
Follow up from wazuh groups (google)
CIS benchmark for Ubuntu Linux 20.04 LTS (Does not work as expected)

Wazuh version:
- App version: 4.3.5
- App revision: 4306
- Install date: Jun 23, 2022 @ 15:49:57.085 

Component:
- CIS benchmark for Ubuntu Linux 20.04 LTS

Install type/method:
- clean install via AWS Marketplace

Platform/OS:
- Linux wazuh-server 4.14.281-212.502.amzn2.x86_64 #1 SMP Thu May 26 09:52:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Wazuh component:
- CIS benchmark for Ubuntu Linux 20.04 LTS + Agent Reporting Auditing

Wazuh Agent:
- clean install on clean AMI-Ubuntu-20.04

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

*fully updated and patched.

[This is a POC build with both wazuh-server and test server fully patched and up to date]

Problem:
CIS benchmark for Ubuntu Linux 20.04 LTS on AWS Marketplace wazuh install (server) with wazuh-agent installed based on guide on remote test server (below) does not report actual system state correctly upon audit.

Remote Test Server Information
Linux thinktank 5.4.0-1080-aws-fips #87+fips1-Ubuntu SMP Fri Jun 10 20:13:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux 

Distributor ID:    Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:    20.04
Codename:    focal

Wazuh Reports the Below Findings, which manually "pass" but wazuh shows "failed".  Examples provided below;

Wazuh reports
19093  Ensure iptables-persistent is not installed.  Command: dpkg -s iptables-persistent  failed

Rationale Running both ufw and the services included in the iptables-persistent package may lead to conflict

Manual check:
Is ufw installed?

Checks (Condition: all)
c:dpkg -s ufw -> r:Status: install ok installed
not c:dpkg -s iptables-persistent -> r:Status: install ok installed
thinktank:~$ sudo dpkg -s ufw
dpkg-query: package 'ufw' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.

thinktank:~$ sudo dpkg -s iptables-persistent
Package: iptables-persistent
Status: install ok installed
Priority: optional
Section: admin
Installed-Size: 49
Maintainer: Ubuntu Developers <[ubuntu-dev...@lists.ubuntu.com](https://groups.google.com/)>
Architecture: all
Version: 1.0.14ubuntu1
Depends: netfilter-persistent (= 1.0.14ubuntu1), debconf (>= 0.5) | debconf-2.0
Pre-Depends: iptables
Conffiles:
 /etc/systemd/system/netfilter-persistent.service.d/iptables.conf 6086e64821392da68277639fd6557f60
Description: boot-time loader for netfilter rules, iptables plugin
 netfilter-persistent is a loader for netfilter configuration using a
 plugin-based architecture.

This is happening on 15 rules (to be 100% clean).  Using this as an example does anyone have any ideas what "bug" or "issue" would be causing in correct reporting with a nearly default clean install of AWS Marketplace Wazuh + Clean Ubuntu Instance?

**Please note:**
The other question is about the CIS benchmark for Ubuntu Linux 20.04 LTS that is provided by wazuh.  

CIS provides 2 baselines for servers.  Level 1 and Level 2.  Which one is this one provided as default within wazuh and would it not be better to be clear which profile is provided?

Example, running # usg audit
The valid profiles are:
cis_level2_server, cis_level2_workstation, disa_stig, cis_level1_workstation, cis_level1_server

CIS Latest Copy;
https://edu.anarcho-copy.org/GNU%20Linux%20-%20Unix-Like/Debian/CIS_Ubuntu_Linux_20.04_LTS_Benchmark_v1.1.0.pdf

We are testing wazuh and this concerns the team that we cannot count on baseline reports or is this expected and anticipated as we should be doing something differently?  Or are thesee bugs that should be fixed?  If bugs, we are happy to report back detailed findings to help clean up the process and improve wazuh.

Thanks,  Scott

**Comment by alberpilot** [comment]
Tested with check 19137 and it fails:
```
  - id: 19137
    title: "Ensure cron daemon is enabled and running."
    description: "The cron daemon is used to execute batch jobs on the system."
    rationale: "While there may not be user jobs that need to be run on the system, the system does have maintenance jobs that may include security monitoring that have to run, and cron is used to execute them."
    remediation: "Run the following command to enable cron: systemctl --now enable cron"
    compliance:
      - cis: ["5.1.1"]
      - cis_csc: ["6"]
      - pci_dss: ["2.2.4"]
      - nist_800_53: ["CM.1"]
      - tsc: ["CC5.2"]
    condition: all
    rules:
      - 'c:systemctl is-enabled cron -> enabled'
      - 'c:systemctl status cron -> r:Active: active (running)'
```
The line:
```      
- 'c:systemctl status cron -> r:Active: active (running)'
```
should be changed by 
```      
- 'c:systemctl status cron -> r:Active: active \(running\)'
```
Other false fails looks similar.
