### ISSUE TITLE
FIM handling of logfile

### ISSUE THREAD

**Issue by hitman28594** [wazuh/wazuh#14449]
Hi,

Currently it is difficult to monitor the following two things with Wazuh’s syscheck module and FIM capabilities. 

1) logfile rotation, and the integrity of the rotated files. 
2) Logfiles which are currently changing. We can monitor other things like permissions etc instead. But overall, these files shouldn’t be ignored from FIM checks, but instead FIM should detect when these files reduce in size. 

Many APTs delete logfiles during/after an attack. The integrity of log files is very important, and changes are often an indicator of unusual behaviour. 

If syscheck can support the above two use cases better, we can more effectively use FIM to detect unexpected changes to growing and rotating logfiles. 

Thank you.

**Comment by hitman28594** [comment]
Might not be the best reference, but here is something similar in practice:

https://www.la-samhna.de/samhain/manual/filedef.html

**Comment by vikman90** [comment]
@hitman28594 you're right, log file monitoring is a use case that our FIM does not cover very well. However, we can easily extend the ruleset to detect log truncation and rotation. Let me show an example:

## Sample file

In this example, we will truncate `/root/test/demo.log` and also rotate it to `/root/test/demo.log`.

### Agent configuration

- Monitor the directory _/root/test_ in whodata mode.
- Do not ignore _.log_ files.

<details><summary>etc/ossec.conf</summary>

```xml
<ossec_conf>

  <!-- File integrity monitoring -->
  <syscheck>

    <!-- Directories to check  (perform all possible verifications) -->
    <directories whodata="yes">/root/test</directories>

    <!-- File types to ignore -->
    <ignore type="sregex">.swp$</ignore>

  </syscheck>
</ossec_conf>
```

</details>

### Ruleset

1. A file was created just after another event on a file with the same inode (child of rule `554`).
2. A file size has been reduced to zero (child of rule `550`).
3. Generic file change on a log file (ignore) (child of rule `550`).

<details><summary>etc/rules/local_rules.xml</summary>

```xml
<!-- Local rules -->

<group name="local,">

  <!-- A file was created just after another event on a file with the same inode. -->
  <rule id="100001" level="5" frequency="2" timeframe="10">
    <if_sid>554</if_sid>
    <if_matched_group>syscheck_file</if_matched_group>
    <same_field>inode</same_field>
    <same_field>uid</same_field>
    <same_field>sha1</same_field>
    <description>A file has been rotated.</description>
    <group>syscheck,syscheck_entry_modified,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>

  <!-- A file size has been reduced to zero. -->
  <rule id="100002" level="7">
    <if_sid>550</if_sid>
    <field name="size">^0$</field>
    <description>A file has been truncated.</description>
    <mitre>
      <id>T1565.001</id>
    </mitre>
    <group>syscheck,syscheck_entry_modified,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>

  <!-- Generic file change on a log file (ignore). -->
  <rule id="100003" level="0">
    <if_sid>550</if_sid>
    <field name="file">.log$</field>
    <field name="size" negate="yes">^0$</field>
    <description>A log file has changed.</description>
    <mitre>
      <id>T1565.001</id>
    </mitre>
    <group>syscheck,syscheck_entry_modified,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>
</group>
```

</details>

### Result

#### Rotate a file

```sh
mv demo.log demo.log.1
```

<details><summary>Alert</summary>

```
** Alert 1659341912.946054: - local,syscheck,syscheck_entry_modified,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2022 Aug 01 10:18:32 (centos7) any->syscheck
Rule: 100001 (level 5) -> 'A file has been rotated.'
File '/root/test/demo.log.1' added
Mode: whodata

Attributes:
 - Size: 3725805
 - Permissions: rw-------
 - Date: Mon Aug  1 10:15:21 2022
 - Inode: 33775067
 - User: root (0)
 - Group: root (0)
 - MD5: 726321d5446a7d9f13b7f66725cc76e3
 - SHA1: 108d830efd353ede1f546fc0fba6c680303d0e46
 - SHA256: cf7782b1f8305c59d2b9a3111fcae91c7384365007bfd3dbc26f81d66cd6bd78
 - (Audit) User name: root
 - (Audit) Audit name: vagrant
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 16262
 - (Audit) Process name: /usr/bin/mv
 - (Audit) Process cwd: /home/vagrant
 - (Audit) Parent process name: /usr/bin/sudo
 - (Audit) Parent process id: 16260
 - (Audit) Parent process cwd: /home/vagrant
File '/root/test/demo.log' deleted
Mode: whodata
```

</details>

#### Truncate a file

```sh
: > demo.log
```

<details><summary>Alert</summary>

```
** Alert 1659342075.950029: - local,syscheck,syscheck_entry_modified,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2022 Aug 01 10:21:15 (centos7) any->syscheck
Rule: 100002 (level 7) -> 'A file has been truncated.'
File '/root/test/demo.log' modified
Mode: whodata
Changed attributes: size,mtime,md5,sha1,sha256
Size changed from '3725805' to '0'
Old modification time was: '1659341928', now it is '1659342071'
Old md5sum was: '726321d5446a7d9f13b7f66725cc76e3'
New md5sum is : 'd41d8cd98f00b204e9800998ecf8427e'
Old sha1sum was: '108d830efd353ede1f546fc0fba6c680303d0e46'
New sha1sum is : 'da39a3ee5e6b4b0d3255bfef95601890afd80709'
Old sha256sum was: 'cf7782b1f8305c59d2b9a3111fcae91c7384365007bfd3dbc26f81d66cd6bd78'
New sha256sum is : 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'

Attributes:
 - Size: 0
 - Permissions: rw-------
 - Date: Mon Aug  1 10:21:11 2022
 - Inode: 33775069
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - (Audit) User name: root
 - (Audit) Audit name: vagrant
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 16305
 - (Audit) Process name: /usr/bin/bash
 - (Audit) Process cwd: /home/vagrant
 - (Audit) Parent process name: /usr/bin/sudo
 - (Audit) Parent process id: 16303
 - (Audit) Parent process cwd: /home/vagrant
```

</details>

#### Append data to a log

```sh
echo 'Aug  1 10:21:11 centos7 sudo: pam_unix(sudo:session): session closed for user root' >> demo.log
```

This action will trigger no alert as rule `100003` silences these types of events.

I'm sure the new engine we're developing (#11334) will make these rules easier to define. For instance, we will be able to compare the previous and the current file size, not only match the current size to `0`.

Hope this helps you.
Best regards.
