### ISSUE TITLE
Engine - Active response 

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#14737]
| Wazuh version | Component | Install type | Install method   | Platform   |
| ------------- | --------- | ------------ | ---------------- | ---------- |
| 5.0.0         | Engine    | Manager      | any | Linux |

We need to model the engine active response system:

 - Evaluate how active response is currently implemented
 - Evaluate whether we prefer a syntax block to describe active responses or a function helper

Our initial design stated that active responses are defined using a syntax stage like:

```
---
name: AR_remote_brute_forces_output

check:
  # https://attack.mitre.org/techniques/T1110/
  - rule.mitre.id: +match/T1110
  - event.srcip: +exist

active-response:
  exec_on: $.wazuh.agent
  script: ban_by_firewall.sh
  extra_args: $.event.srcip  

```

But following our recent development of WazuhDB integration, we might consider using a function helper approach. The flexibility of using a function helper to trigger an active response could open the possibility to launch multiple active responses from a single event.

Such a function helper could be using inside a conditional mapping block like:

```
  - check:
      - http.response.status_code: +gt/399
    map:
      wazuh.active_response.outcome: +active_response/...../
```

This will put a status of the active response within the event field `wazuh.active_response.outcome`.

It could also be used within a conditional expression. We might choose to implement all of the options, as the primitives to manage the active response API could be the same.

 - Implement the active response builder and tests
 - Evaluate the impact on performance for calling an external service 
 - Update the design document with the implemented design.
