### ISSUE TITLE
Engine - array & object direct mapping

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#15276]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | - | - | - |

We want to support object and array mapping with a more concise syntax. We want to go from:

```
- map:
    - key1.key2.key3. value
    - key1.key2.key4: value
    - key1.key2.key5: value
```

to:

```
- map:
  - key1:
    - key2:
      - key3: value
      - key4: value
      - key5. value
```

We will support both approaches, and the users will be able to use one or the other as they see fit.

## Tasks
- [x] Implement functionality
- [x] Update Design Document
- [x] Update script to generate a schema that supports new nested definitions
- [ ] QA validate
