### ISSUE TITLE
Release 4.4.0 - Alpha 1 - E2E UX tests - File Integrity Monitoring

### ISSUE THREAD

**Issue by hector222arroyo** [wazuh/wazuh#15553]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           | File Integrity Monitoring |
| **Category**            | File Integrity Monitoring |
| **Deployment option**   |[Quickstart](https://documentation.wazuh.com/current/quickstart.html)|
| **Main release issue**  |        https://github.com/wazuh/wazuh/issues/15505                                   |
| **Main E2E UX test issue** | https://github.com/wazuh/wazuh/issues/15519 |
| **Release candidate #** |                Alpha 1                           |

## Environment

| | | |
|-|-|-|
| **Component** | **OS** | **Installation** |
| Wazuh dashboard | Ubuntu 22.04 | [Quickstart](https://documentation.wazuh.com/current/quickstart.html)|
| Wazuh indexer | Ubuntu 22.04 | [Quickstart](https://documentation.wazuh.com/current/quickstart.html)|
| Wazuh server | Ubuntu 22.04 | [Quickstart](https://documentation.wazuh.com/current/quickstart.html)|
| Wazuh agent | Windows, Ubuntu 22.04, macOS | Wazuh WUI one-liner deploy |

## Test description
Test different FIM use cases for Windows, Linux and macOS:
- [x] whodata
- [x] report_changes
- [x] inventory of files

## Test report procedure

All test results must have one of the following statuses:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

## Conclusions

All tests have been executed and the results can be found in the issue updates.

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟡 | Installing the Wazuh manager, dashboard, and indexer | Known Issue | A toast appears for a few seconds saying there has been an error with the Wazuh cluster. [Issue ](https://github.com/wazuh/wazuh-kibana-app/issues/4938)|
| :green_circle: | Test  FIM use cases for Windows, Linux | - | - |
| :green_circle: | Test  FIM use cases for Linux| - | - |
| 🔴 | Test  FIM use cases macOS | No report | A directory for report_changes was configured, however the system did not detect the changes made to the files in that directory, the file inventory does detect it. |
| :green_circle: | [Proof of concept test](https://wazuh.com/blog/preventing-and-detecting-ransomware-with-wazuh/) | - | - |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @nicogp
- [x] @davidjiglesias

**Comment by hector222arroyo** [comment]
# Set up environment
<details><summary>Set up vm</summary>
To set up the environment, I have proceeded to deploy one EC2 type t3.medium, with SO Ubuntu 22.04, to install wazuh server, indexer y dashboard, it has used the [quickstart](https://documentation-dev.wazuh.com/v4.4.0-alpha1/quickstart.html) guide to install the components.
</Details>


# Installation Details
```yaml curl -sO https://packages-dev.wazuh.com/4.4/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
```
<Details><summary>Details</summary>

```yaml
ubuntu@ip-172-31-2-40:~$ curl -sO https://packages-dev.wazuh.com/4.4/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
01/12/2022 19:31:55 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
01/12/2022 19:31:55 INFO: Verbose logging redirected to /var/log/wazuh-install.log
01/12/2022 19:32:08 INFO: --- Dependencies ----
01/12/2022 19:32:08 INFO: Installing apt-transport-https.
01/12/2022 19:32:14 INFO: Wazuh development repository added.
01/12/2022 19:32:14 INFO: --- Configuration files ---
01/12/2022 19:32:14 INFO: Generating configuration files.
01/12/2022 19:32:16 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
01/12/2022 19:32:16 INFO: --- Wazuh indexer ---
01/12/2022 19:32:16 INFO: Starting Wazuh indexer installation.
01/12/2022 19:33:01 INFO: Wazuh indexer installation finished.
01/12/2022 19:33:01 INFO: Wazuh indexer post-install configuration finished.
01/12/2022 19:33:01 INFO: Starting service wazuh-indexer.
01/12/2022 19:33:19 INFO: wazuh-indexer service started.
01/12/2022 19:33:19 INFO: Initializing Wazuh indexer cluster security settings.
01/12/2022 19:33:29 INFO: Wazuh indexer cluster initialized.
01/12/2022 19:33:29 INFO: --- Wazuh server ---
01/12/2022 19:33:29 INFO: Starting the Wazuh manager installation.
01/12/2022 19:34:11 INFO: Wazuh manager installation finished.
01/12/2022 19:34:11 INFO: Starting service wazuh-manager.
01/12/2022 19:34:29 INFO: wazuh-manager service started.
01/12/2022 19:34:29 INFO: Starting Filebeat installation.
01/12/2022 19:34:37 INFO: Filebeat installation finished.
01/12/2022 19:34:37 INFO: Filebeat post-install configuration finished.
01/12/2022 19:34:37 INFO: Starting service filebeat.
01/12/2022 19:34:39 INFO: filebeat service started.
01/12/2022 19:34:39 INFO: --- Wazuh dashboard ---
01/12/2022 19:34:39 INFO: Starting Wazuh dashboard installation.
01/12/2022 19:35:24 INFO: Wazuh dashboard installation finished.
01/12/2022 19:35:24 INFO: Wazuh dashboard post-install configuration finished.
01/12/2022 19:35:24 INFO: Starting service wazuh-dashboard.
01/12/2022 19:35:24 INFO: wazuh-dashboard service started.
01/12/2022 19:35:54 INFO: Initializing Wazuh dashboard web application.
01/12/2022 19:35:55 INFO: Wazuh dashboard web application initialized.
01/12/2022 19:35:55 INFO: --- Summary ---
01/12/2022 19:35:55 INFO: You can access the web interface https://<wazuh-dashboard-ip>
    User: admin
    Password: <PASSWORD>
01/12/2022 19:35:55 INFO: Installation finished.

```
</Details>


When we access the option "Add agent", the following error appears repeatedly:

[Insertar imagen]

# Wazuh Agent Install
<Details><summary>Install and Enroll the agent: Windows 10 pro 64x V-21H2</summary>

In windows-powershell, execute for install:
```yaml
Invoke-WebRequest -Uri https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.4.0-1.msi -OutFile ${env:tmp}\wazuh-agent-4.4.0.msi; msiexec.exe /i ${env:tmp}\wazuh-agent-4.4.0.msi /q WAZUH_MANAGER='54.237.186.80' WAZUH_REGISTRATION_SERVER='54.237.186.80' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='windows-agent'
```

[Insertar imagen]

the agent starts automatically
[Insertar imagen]

[Insertar imagen_comprobe]
</Details>

<Details><summary>Install and Enroll the agent: Ubuntu 22.04</summary>

In windows-powershell, execute for install:
```yaml
curl -so wazuh-agent-4.4.0.deb https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_amd64.deb && sudo WAZUH_AGENT_GROUP='default' WAZUH_MANAGER='54.237.186.80' WAZUH_REGISTRATION_SERVER='54.237.186.80' WAZUH_AGENT_NAME='linux-agent' dpkg -i ./wazuh-agent-4.4.0.deb
```

Start the agent:
```yaml
sudo systemctl daemon-reload
sudo systemctl enable wazuh-agent
sudo systemctl start wazuh-agent
```

```yaml
ubuntu@ip-172-31-92-151:~$ curl -so wazuh-agent-4.4.0.deb https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.0-1_amd64.deb && sudo WAZUH_AGENT_GROUP='default' WAZUH_MANAGER='54.237.186.80' WAZUH_REGISTRATION_SERVER='54.237.186.80' WAZUH_AGENT_NAME='linux-agent' dpkg -i ./wazuh-agent-4.4.0.deb
(Reading database ... 111587 files and directories currently installed.)
Preparing to unpack ./wazuh-agent-4.4.0.deb ...
Unpacking wazuh-agent (4.4.0-1) over (4.4.0-1) ...
Setting up wazuh-agent (4.4.0-1) ...
ubuntu@ip-172-31-92-151:~$
ubuntu@ip-172-31-92-151:~$ sudo systemctl daemon-reload
ubuntu@ip-172-31-92-151:~$ sudo systemctl enable wazuh-agent
Synchronizing state of wazuh-agent.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable wazuh-agent
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-agent.service → /lib/systemd/system/wazuh-agent.service.
ubuntu@ip-172-31-92-151:~$ sudo systemctl start wazuh-agent
ubuntu@ip-172-31-92-151:~$ systemctl status wazuh-agent
● wazuh-agent.service - Wazuh agent
     Loaded: loaded (/lib/systemd/system/wazuh-agent.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-12-01 23:28:25 UTC; 33s ago
    Process: 1324884 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
      Tasks: 31 (limit: 1143)
     Memory: 383.5M
        CPU: 11.799s
     CGroup: /system.slice/wazuh-agent.service
             ├─1325630 /var/ossec/bin/wazuh-execd
             ├─1325647 /var/ossec/bin/wazuh-agentd
             ├─1325667 /var/ossec/bin/wazuh-syscheckd
             ├─1325685 /var/ossec/bin/wazuh-logcollector
             └─1325708 /var/ossec/bin/wazuh-modulesd

Dec 01 23:28:18 ip-172-31-92-151 systemd[1]: Starting Wazuh agent...
Dec 01 23:28:18 ip-172-31-92-151 env[1324884]: Starting Wazuh v4.4.0...
Dec 01 23:28:19 ip-172-31-92-151 env[1324884]: Started wazuh-execd...
Dec 01 23:28:20 ip-172-31-92-151 env[1324884]: Started wazuh-agentd...
Dec 01 23:28:21 ip-172-31-92-151 env[1324884]: Started wazuh-syscheckd...
Dec 01 23:28:22 ip-172-31-92-151 env[1324884]: Started wazuh-logcollector...
Dec 01 23:28:23 ip-172-31-92-151 env[1324884]: Started wazuh-modulesd...
Dec 01 23:28:25 ip-172-31-92-151 env[1324884]: Completed.
Dec 01 23:28:25 ip-172-31-92-151 systemd[1]: Started Wazuh agent.
ubuntu@ip-172-31-92-151:~$

```

</Details>


# TEST

## whodata
### WINDOWS
following the [guide](https://documentation.wazuh.com/current/user-manual/capabilities/auditing-whodata/who-windows.html)
whodata="yes" is declared within the directories statement in the ossec.conf file:

```yaml
 <syscheck>
  <directories check_all="yes" whodata="yes">C:\Windows\System32\drivers\etc</directories>
</syscheck>
```

Output
```yaml

```

### LINUX
following the [guide] (https://documentation.wazuh.com/current/user-manual/capabilities/auditing-whodata/who-linux.html)

### MAC OS

### report_changes
### WINDOWS
### LINUX
### MAC OS

### inventory of files
### WINDOWS
### LINUX
### MAC OS

**Comment by hector222arroyo** [comment]
## whodata

<Details><summary>Windows :green_circle: </summary>
following the [guide ]((https://documentation.wazuh.com/current/user-manual/capabilities/auditing-whodata/who-windows.html)
whodata="yes" is declared within the directories statement in the ossec.conf file:

```yaml
 <syscheck>
  <directories check_all="yes" whodata="yes">C:\temp\wazuh</directories>
</syscheck>
```
![image](https://user-images.githubusercontent.com/68483100/205327788-d39fb4ba-0820-4df6-aa4a-977d06f95351.png)

![image](https://user-images.githubusercontent.com/68483100/205327992-dd9c7404-cdee-4663-926b-99a9ae9e2f68.png)

![image](https://user-images.githubusercontent.com/68483100/205328237-9f65c53b-f473-4d49-84ec-27277f6c593e.png)

![image](https://user-images.githubusercontent.com/68483100/205328572-12f2d31b-7f5c-471c-8801-7fe59f56822b.png)



Modified | Integrity checksum changed
<Details><summary>Output Json</summary>

```yaml
{
  "syscheck": {
    "size_before": "0",
    "uname_after": "kensuke",
    "mtime_after": "2022-12-02T14:53:13",
    "size_after": "12",
    "md5_before": "d41d8cd98f00b204e9800998ecf8427e",
    "win_perm_after": [
      {
        "allowed": [
          "DELETE",
          "READ_CONTROL",
          "WRITE_DAC",
          "WRITE_OWNER",
          "SYNCHRONIZE",
          "READ_DATA",
          "WRITE_DATA",
          "APPEND_DATA",
          "READ_EA",
          "WRITE_EA",
          "EXECUTE",
          "READ_ATTRIBUTES",
          "WRITE_ATTRIBUTES"
        ],
        "name": "Administradores"
      },
      {
        "allowed": [
          "DELETE",
          "READ_CONTROL",
          "WRITE_DAC",
          "WRITE_OWNER",
          "SYNCHRONIZE",
          "READ_DATA",
          "WRITE_DATA",
          "APPEND_DATA",
          "READ_EA",
          "WRITE_EA",
          "EXECUTE",
          "READ_ATTRIBUTES",
          "WRITE_ATTRIBUTES"
        ],
        "name": "SYSTEM"
      },
      {
        "allowed": [
          "READ_CONTROL",
          "SYNCHRONIZE",
          "READ_DATA",
          "READ_EA",
          "EXECUTE",
          "READ_ATTRIBUTES"
        ],
        "name": "Usuarios"
      },
      {
        "allowed": [
          "DELETE",
          "READ_CONTROL",
          "SYNCHRONIZE",
          "READ_DATA",
          "WRITE_DATA",
          "APPEND_DATA",
          "READ_EA",
          "WRITE_EA",
          "EXECUTE",
          "READ_ATTRIBUTES",
          "WRITE_ATTRIBUTES"
        ],
        "name": "Usuarios autentificados"
      }
    ],
    "sha256_before": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "mtime_before": "2022-12-02T14:53:02",
    "mode": "whodata",
    "path": "c:\\temp\\wazuh\\prueba.txt",
    "sha1_after": "d9456a19de92a9d30f3159b4507605a4b8e06461",
    "changed_attributes": [
      "size",
      "mtime",
      "md5",
      "sha1",
      "sha256"
    ],
    "audit": {
      "process": {
        "name": "C:\\Windows\\System32\\notepad.exe",
        "id": "10972"
      },
      "user": {
        "name": "kensuke",
        "id": "S-1-5-21-3063451472-2378395904-3881120412-1001"
      }
    },
    "attrs_after": [
      "ARCHIVE"
    ],
    "uid_after": "S-1-5-21-3063451472-2378395904-3881120412-1001",
    "event": "modified",
    "md5_after": "bf9876c2fac4fdc7bd2c381ded1976d3",
    "sha1_before": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
    "sha256_after": "c389d0725ba3d45b78f96a3db45a28d869711b6d03321f0f104787567cbacdce"
  },
  "agent": {
    "ip": "169.254.147.84",
    "name": "ENVY-LAPTOP",
    "id": "001"
  },
  "manager": {
    "name": "ip-172-31-2-40"
  },
  "rule": {
    "mail": false,
    "level": 7,
    "pci_dss": [
      "11.5"
    ],
    "hipaa": [
      "164.312.c.1",
      "164.312.c.2"
    ],
    "tsc": [
      "PI1.4",
      "PI1.5",
      "CC6.1",
      "CC6.8",
      "CC7.2",
      "CC7.3"
    ],
    "description": "Integrity checksum changed.",
    "groups": [
      "ossec",
      "syscheck",
      "syscheck_entry_modified",
      "syscheck_file"
    ],
    "nist_800_53": [
      "SI.7"
    ],
    "gdpr": [
      "II_5.1.f"
    ],
    "firedtimes": 1,
    "mitre": {
      "technique": [
        "Stored Data Manipulation"
      ],
      "id": [
        "T1565.001"
      ],
      "tactic": [
        "Impact"
      ]
    },
    "id": "550",
    "gpg13": [
      "4.11"
    ]
  },
  "decoder": {
    "name": "syscheck_integrity_changed"
  },
  "full_log": "File 'c:\\temp\\wazuh\\prueba.txt' modified\nMode: whodata\nChanged attributes: size,mtime,md5,sha1,sha256\nSize changed from '0' to '12'\nOld modification time was: '1669992782', now it is '1669992793'\nOld md5sum was: 'd41d8cd98f00b204e9800998ecf8427e'\nNew md5sum is : 'bf9876c2fac4fdc7bd2c381ded1976d3'\nOld sha1sum was: 'da39a3ee5e6b4b0d3255bfef95601890afd80709'\nNew sha1sum is : 'd9456a19de92a9d30f3159b4507605a4b8e06461'\nOld sha256sum was: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'\nNew sha256sum is : 'c389d0725ba3d45b78f96a3db45a28d869711b6d03321f0f104787567cbacdce'\n",
  "input": {
    "type": "log"
  },
  "@timestamp": "2022-12-02T14:53:15.715Z",
  "location": "syscheck",
  "id": "1669992795.972425",
  "timestamp": "2022-12-02T14:53:15.715+0000",
  "_id": "9ehT04QB6CwxVSB61x-E"
}
```
</Details>

</Details>

<Details><summary>Linux :green_circle: </summary>
following the [guide](https://documentation.wazuh.com/current/user-manual/capabilities/auditing-whodata/who-linux.html)

whodata="yes" is declared within the directories statement in the ossec.conf file
```yaml
<syscheck>
  <directories check_all="yes" whodata="yes">/home/ubuntu/wazuh</directories>
</syscheck>
```

![image](https://user-images.githubusercontent.com/68483100/205392763-a5bab9be-0166-4a9f-9eac-3d2edb64316a.png)


```yaml
root@ip-172-31-92-151:/home/ubuntu# nano /var/ossec/etc/ossec.conf
root@ip-172-31-92-151:/home/ubuntu#
root@ip-172-31-92-151:/home/ubuntu# systemctl restart wazuh-agent
root@ip-172-31-92-151:/home/ubuntu# nano /home/ubuntu/wazuh/prueba.wazuh.txt
root@ip-172-31-92-151:/home/ubuntu#
root@ip-172-31-92-151:/home/ubuntu#
```
![image](https://user-images.githubusercontent.com/68483100/205393013-f2183a2d-1352-45b1-8f90-d74b73e328aa.png)

![image](https://user-images.githubusercontent.com/68483100/205393186-3a9af091-0fa4-4a15-be91-a441ce9b9b3c.png)


<Details><summary>Output Json</summary>

```yaml
{
  "syscheck": {
    "size_before": "0",
    "uname_after": "ubuntu",
    "mtime_after": "2022-12-02T20:58:45",
    "size_after": "8",
    "gid_after": "1000",
    "md5_before": "d41d8cd98f00b204e9800998ecf8427e",
    "sha256_before": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    "mtime_before": "2022-12-02T20:58:29",
    "mode": "whodata",
    "path": "/home/ubuntu/wazuh/prueba.wazuh.txt",
    "sha1_after": "cac7c63ab396f5a2204513a3c8a934f8ad07a3ff",
    "changed_attributes": [
      "size",
      "mtime",
      "md5",
      "sha1",
      "sha256"
    ],
    "gname_after": "ubuntu",
    "audit": {
      "process": {
        "parent_name": "/usr/bin/bash",
        "cwd": "/home/ubuntu",
        "parent_cwd": "/home/ubuntu",
        "name": "/usr/bin/nano",
        "id": "1404024",
        "ppid": "1401817"
      },
      "login_user": {
        "name": "ubuntu",
        "id": "1000"
      },
      "effective_user": {
        "name": "root",
        "id": "0"
      },
      "user": {
        "name": "root",
        "id": "0"
      },
      "group": {
        "name": "root",
        "id": "0"
      }
    },
    "uid_after": "1000",
    "perm_after": "rw-rw-r--",
    "event": "modified",
    "md5_after": "b25ac6f0dbc1b01b9b216d4f45de3063",
    "sha1_before": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
    "sha256_after": "13d431ba3491517efdae4dad248fb66dd742810f16fad1475586729d32329513",
    "inode_after": 533885
  },
  "agent": {
    "ip": "172.31.92.151",
    "name": "linux-agent",
    "id": "002"
  },
  "manager": {
    "name": "ip-172-31-2-40"
  },
  "rule": {
    "mail": false,
    "level": 7,
    "pci_dss": [
      "11.5"
    ],
    "hipaa": [
      "164.312.c.1",
      "164.312.c.2"
    ],
    "tsc": [
      "PI1.4",
      "PI1.5",
      "CC6.1",
      "CC6.8",
      "CC7.2",
      "CC7.3"
    ],
    "description": "Integrity checksum changed.",
    "groups": [
      "ossec",
      "syscheck",
      "syscheck_entry_modified",
      "syscheck_file"
    ],
    "nist_800_53": [
      "SI.7"
    ],
    "gdpr": [
      "II_5.1.f"
    ],
    "firedtimes": 1,
    "mitre": {
      "technique": [
        "Stored Data Manipulation"
      ],
      "id": [
        "T1565.001"
      ],
      "tactic": [
        "Impact"
      ]
    },
    "id": "550",
    "gpg13": [
      "4.11"
    ]
  },
  "decoder": {
    "name": "syscheck_integrity_changed"
  },
  "full_log": "File '/home/ubuntu/wazuh/prueba.wazuh.txt' modified\nMode: whodata\nChanged attributes: size,mtime,md5,sha1,sha256\nSize changed from '0' to '8'\nOld modification time was: '1670014709', now it is '1670014725'\nOld md5sum was: 'd41d8cd98f00b204e9800998ecf8427e'\nNew md5sum is : 'b25ac6f0dbc1b01b9b216d4f45de3063'\nOld sha1sum was: 'da39a3ee5e6b4b0d3255bfef95601890afd80709'\nNew sha1sum is : 'cac7c63ab396f5a2204513a3c8a934f8ad07a3ff'\nOld sha256sum was: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'\nNew sha256sum is : '13d431ba3491517efdae4dad248fb66dd742810f16fad1475586729d32329513'\n",
  "input": {
    "type": "log"
  },
  "@timestamp": "2022-12-02T20:58:45.157Z",
  "location": "syscheck",
  "id": "1670014725.1172914",
  "timestamp": "2022-12-02T20:58:45.157+0000",
  "_id": "0eii1IQB6CwxVSB6hSAX"
}
```
</Details>
</Details>

<Details><summary>Mac OS: green_circle: </summary>
</Details>
