### ISSUE TITLE
Release 4.4.0 - Alpha 1 - E2E UX tests -  Virustotal integration

### ISSUE THREAD

**Issue by camporeale** [wazuh/wazuh#15552]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           | Virustotal                                     |
| **Category**            | Integrations                                   |
| **Deployment option**   | [Installation assistant](https://documentation.wazuh.com/current/installation-guide/wazuh-server/installation-assistant.html)  |
| **Main release issue**  | https://github.com/wazuh/wazuh/issues/15505 |
| **Main E2E UX test issue** | https://github.com/wazuh/wazuh/issues/15519 |
| **Release candidate #** | Alpha 1 |

## Test description
Deploy Wazuh with the following design

| Component | Guide | Cluster / Single | OS |
|-------------|------|-----------------|----| 
| indexer | [ Installation Assistant ](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/installation-assistant.html)| Single | Ubuntu 18.04 |
| server | [ Installation Assistant ](https://documentation.wazuh.com/current/installation-guide/wazuh-server/installation-assistant.html)| Cluster | Ubuntu 18.04 |
| dashboard | [ Installation Assistant ](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/installation-assistant.html)| Single | Ubuntu 18.04 |
| agent | [ Dashboard command ](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/index.html) | Single | Alpine Linux |

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here]().

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|                |             |                     |                |

All tests have passed and the fails have been reported or justified. Therefore, I conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] MODULE OWNER
- [ ] EXTRA REVIEWER

**Comment by camporeale** [comment]
## :green_circle: Check 0. Test environment
### 1. Vagrant Setup
I used the following Vagrantfile to configure 3 boxes:

1. An Ubuntu  "server" box to deploy the master node, indexer and dashboard
2. An Alpine "agent" box to deploy the agent
3. An Ubuntu "worker" box to deploy worker manager

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
servers=[
  {
    :hostname => "server",
    :ip => "192.168.59.103",
    :box => "bento/ubuntu-18.04",
    :ram => 4192,
    :cpu => 2
  },
  {
    :hostname => "agent",
    :ip => "192.168.59.104",
    :box => "alpine-linux/alpine-x86_64",
    :ram => 1024,
    :cpu => 1 
  },
   {
    :hostname => "worker",
    :ip => "192.168.59.105",
    :box => "bento/ubuntu-18.04",
    :ram => 1024,
    :cpu => 1
  }
]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            if machine[:hostname] == "server"
                node.vm.network "forwarded_port", guest: 443, host: 4443
            end
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
            end
        end
    end
end

```

### 2. Installation

#### Indexer
The Indexer was installed using the [installation assistant](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/installation-assistant.html), but using [this installer](https://packages-dev.wazuh.com/4.4/wazuh-install.sh) for version 4.4.0

#### Server
The server was installed using the [installation assistant](https://documentation.wazuh.com/current/installation-guide/wazuh-server/installation-assistant.html),  but using [this installer](https://packages-dev.wazuh.com/4.4/wazuh-install.sh) for version 4.4.0

#### Dashboard
The dashboard was installed using the [installation assistant](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/installation-assistant.html)

#### Agent
The agent was installed using [this apk](https://packages-dev.wazuh.com/pre-release/alpine/v3.12/main/x86_64/wazuh-agent-4.4.0-r1.apk) for Alpine. And started manually, as explained in the not yet released [documentation for alpine](https://github.com/wazuh/wazuh-documentation/blob/1d44354536464aa077b9fce7e55446a4855bd398/source/_templates/installations/wazuh/common/enable_wazuh_agent_service.rst)

`agent:/var/ossec/bin# ./wazuh-control start`


### 3. Configuration

To test the VirustTotal integration, the agent was configured to do realtime FIM in the /root directory

**Comment by camporeale** [comment]
## :green_circle: Test 1 - Detecting and removing malware using VirusTotal integration POC
### 1. Setup

I followed the [POC documentation](https://documentation-dev.wazuh.com/current/proof-of-concept-guide/detect-remove-malware-virustotal.html#detecting-and-removing-malware-using-virustotal-integration)

**On the agent**
1. Configured realtime FIM on the /root directory of the agent box
2. Added the remove-threat.sh script on the agent box
3. Restarted the agent

**On the Server**
1. Updated local_rules.xml to add the rule for the /root directory
2. Added  integration section in ossec.conf with a newly created API key from VirusTotal site
3. Added the active response section in ossec.conf to delete the file 
4. Added the rule to notify about the active response in local_rules.xml
5. Restarted the managers

### 2. Test

1. Run the following commands on the Agent box to get a file that is in the VirusTotal database to be saved in the /root directory:

```bash
sudo cd /root
sudo curl -LO https://secure.eicar.org/eicar.com && ls -lah eicar.com
```


### 3. Result
We can see that the manager detects the creation of the new file, then calls the VirusTotal API, gets a match for the file, and proceeds to delete the file on the agent box: 

![image](https://user-images.githubusercontent.com/4818814/205357689-9bd3d5e7-7638-4cea-b07f-5f2238e5b0fe.png)

**Comment by camporeale** [comment]
## :green_circle: Test 2 - Test Using VirusTotal Integration to scan file hashes
### 1. Setup

We reused the setup from Test 0

### 2. Test

1. Downloaded sample file of trojan BPFDoor
2. Copied the file to /root directory on the agent box


### 3. Result
We can see that the manager detects the creation of the new file, then calls the VirusTotal API, gets a match for the file hash, and proceeds to delete the file on the agent box: 

![image](https://user-images.githubusercontent.com/4818814/205369138-800898c6-6551-473c-8c70-292891f85db7.png)

![image](https://user-images.githubusercontent.com/4818814/205369273-e33c2d20-258a-48b3-9d09-8db5d0244d7e.png)

**Comment by camporeale** [comment]
## :green_circle: Test 3 - Test VirusTotal integration alerts

To test the integration alerts described in the [documentation](https://documentation-dev.wazuh.com/v4.4.0-alpha1/user-manual/capabilities/virustotal-scan/integration.html#how-it-works)

### Setup
We used the same setup as the previous tests.

### Tests

#### 1. Test Invalid Credentials

After configuring VirusTotal integration, we changed the credentials in ossec.conf to an invalid string, restarted the manager, and created a file inside /root directory of the agent box.

After creation of the file, an alert is created, the error message is correct:

![image](https://user-images.githubusercontent.com/4818814/205906700-dbf85317-14b1-4147-aeea-c58d1fd62e82.png)


```
** Alert 1670327358.19157: - syscheck,pci_dss_11.5,nist_800_53_SI.7,
2022 Dec 06 11:49:18 (agent) any->syscheck
Rule: 100201 (level 7) -> 'File added to /root directory.'
File '/root/evil.bin' added
Mode: realtime

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Tue Dec  6 11:49:19 2022
 - Inode: 405
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1670327361.19674: - virustotal,gdpr_IV_35.7.d,gdpr_IV_32.2,
2022 Dec 06 11:49:21 server->virustotal
Rule: 87102 (level 3) -> 'VirusTotal: Error: Check credentials'
{"virustotal": {"error": 403, "description": "Error: Check credentials"}, "integration": "virustotal"}
virustotal.error: 403
virustotal.description: Error: Check credentials
integration: virustotal

```


#### 2. Test  API has reached the set rate limit

We ran a simple bash one liner to update the same file continuosly with a one second delay:

```bash
agent:~# while true; do touch evil.bin; sleep 1; done
```

After the first couple iterations we can see that the rate limit is reached (this is a free virustotal account, so it has a low limit):


![image](https://user-images.githubusercontent.com/4818814/205911422-a651a238-7ce2-4c6f-9b4a-110f0b7bf078.png)

<details>
  <summary>Coordinator logs</summary>

```
** Alert 1670328928.30723: - syscheck,pci_dss_11.5,nist_800_53_SI.7,
2022 Dec 06 12:15:28 (agent) any->syscheck
Rule: 100200 (level 7) -> 'File modified in /root directory.'
File '/root/evil.bin' modified
Mode: realtime
Changed attributes: mtime
Old modification time was: '1670328927', now it is '1670328928'

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Tue Dec  6 12:15:28 2022
 - Inode: 405
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1670328928.31336: - virustotal,
2022 Dec 06 12:15:28 (agent) 10.0.2.15->virustotal
Rule: 87104 (level 3) -> 'VirusTotal: Alert - /root/evil.bin - No positives found'
{"virustotal": {"found": 1, "malicious": 0, "source": {"alert_id": "1670328923.26964", "file": "/root/evil.bin", "md5": "d41d8cd98f00b204e9800998ecf8427e", "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709"}, "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "scan_date": "2022-12-06 12:13:18", "positives": 0, "total": 59, "permalink": "https://www.virustotal.com/gui/file/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/detection/f-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-1670328798"}, "integration": "virustotal"}
virustotal.found: 1
virustotal.malicious: 0
virustotal.source.alert_id: 1670328923.26964
virustotal.source.file: /root/evil.bin
virustotal.source.md5: d41d8cd98f00b204e9800998ecf8427e
virustotal.source.sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
virustotal.sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
virustotal.scan_date: 2022-12-06 12:13:18
virustotal.positives: 0
virustotal.total: 59
virustotal.permalink: https://www.virustotal.com/gui/file/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/detection/f-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-1670328798
integration: virustotal

** Alert 1670328929.32702: - syscheck,pci_dss_11.5,nist_800_53_SI.7,
2022 Dec 06 12:15:29 (agent) any->syscheck
Rule: 100200 (level 7) -> 'File modified in /root directory.'
File '/root/evil.bin' modified
Mode: realtime
Changed attributes: mtime
Old modification time was: '1670328928', now it is '1670328929'

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Tue Dec  6 12:15:29 2022
 - Inode: 405
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1670328930.33315: - syscheck,pci_dss_11.5,nist_800_53_SI.7,
2022 Dec 06 12:15:30 (agent) any->syscheck
Rule: 100200 (level 7) -> 'File modified in /root directory.'
File '/root/evil.bin' modified
Mode: realtime
Changed attributes: mtime
Old modification time was: '1670328929', now it is '1670328930'

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Tue Dec  6 12:15:30 2022
 - Inode: 405
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1670328930.33928: - virustotal,
2022 Dec 06 12:15:30 (agent) 10.0.2.15->virustotal
Rule: 87104 (level 3) -> 'VirusTotal: Alert - /root/evil.bin - No positives found'
{"virustotal": {"found": 1, "malicious": 0, "source": {"alert_id": "1670328924.27577", "file": "/root/evil.bin", "md5": "d41d8cd98f00b204e9800998ecf8427e", "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709"}, "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "scan_date": "2022-12-06 12:13:18", "positives": 0, "total": 59, "permalink": "https://www.virustotal.com/gui/file/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/detection/f-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-1670328798"}, "integration": "virustotal"}
virustotal.found: 1
virustotal.malicious: 0
virustotal.source.alert_id: 1670328924.27577
virustotal.source.file: /root/evil.bin
virustotal.source.md5: d41d8cd98f00b204e9800998ecf8427e
virustotal.source.sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
virustotal.sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
virustotal.scan_date: 2022-12-06 12:13:18
virustotal.positives: 0
virustotal.total: 59
virustotal.permalink: https://www.virustotal.com/gui/file/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/detection/f-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-1670328798
integration: virustotal

** Alert 1670328931.35294: - syscheck,pci_dss_11.5,nist_800_53_SI.7,
2022 Dec 06 12:15:31 (agent) any->syscheck
Rule: 100200 (level 7) -> 'File modified in /root directory.'
File '/root/evil.bin' modified
Mode: realtime
Changed attributes: mtime
Old modification time was: '1670328930', now it is '1670328931'

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Tue Dec  6 12:15:31 2022
 - Inode: 405
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1670328932.35907: - syscheck,pci_dss_11.5,nist_800_53_SI.7,
2022 Dec 06 12:15:32 (agent) any->syscheck
Rule: 100200 (level 7) -> 'File modified in /root directory.'
File '/root/evil.bin' modified
Mode: realtime
Changed attributes: mtime
Old modification time was: '1670328931', now it is '1670328932'

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Tue Dec  6 12:15:32 2022
 - Inode: 405
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1670328932.36520: - virustotal,
2022 Dec 06 12:15:32 (agent) 10.0.2.15->virustotal
Rule: 87104 (level 3) -> 'VirusTotal: Alert - /root/evil.bin - No positives found'
{"virustotal": {"found": 1, "malicious": 0, "source": {"alert_id": "1670328925.28190", "file": "/root/evil.bin", "md5": "d41d8cd98f00b204e9800998ecf8427e", "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709"}, "sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709", "scan_date": "2022-12-06 12:13:18", "positives": 0, "total": 59, "permalink": "https://www.virustotal.com/gui/file/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/detection/f-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-1670328798"}, "integration": "virustotal"}
virustotal.found: 1
virustotal.malicious: 0
virustotal.source.alert_id: 1670328925.28190
virustotal.source.file: /root/evil.bin
virustotal.source.md5: d41d8cd98f00b204e9800998ecf8427e
virustotal.source.sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
virustotal.sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
virustotal.scan_date: 2022-12-06 12:13:18
virustotal.positives: 0
virustotal.total: 59
virustotal.permalink: https://www.virustotal.com/gui/file/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855/detection/f-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-1670328798
integration: virustotal

** Alert 1670328933.37886: - syscheck,pci_dss_11.5,nist_800_53_SI.7,
2022 Dec 06 12:15:33 (agent) any->syscheck
Rule: 100200 (level 7) -> 'File modified in /root directory.'
File '/root/evil.bin' modified
Mode: realtime
Changed attributes: mtime
Old modification time was: '1670328932', now it is '1670328933'

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Tue Dec  6 12:15:33 2022
 - Inode: 405
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1670328934.38499: - syscheck,pci_dss_11.5,nist_800_53_SI.7,
2022 Dec 06 12:15:34 (agent) any->syscheck
Rule: 100200 (level 7) -> 'File modified in /root directory.'
File '/root/evil.bin' modified
Mode: realtime
Changed attributes: mtime
Old modification time was: '1670328933', now it is '1670328934'

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Tue Dec  6 12:15:34 2022
 - Inode: 405
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1670328934.39112: - virustotal,
2022 Dec 06 12:15:34 server->virustotal
Rule: 87101 (level 3) -> 'VirusTotal: Error: Public API request rate limit reached'
{"virustotal": {"error": 204, "description": "Error: Public API request rate limit reached"}, "integration": "virustotal"}
virustotal.error: 204
virustotal.description: Error: Public API request rate limit reached
integration: virustotal

** Alert 1670328935.39516: - syscheck,pci_dss_11.5,nist_800_53_SI.7,
2022 Dec 06 12:15:35 (agent) any->syscheck
Rule: 100200 (level 7) -> 'File modified in /root directory.'
File '/root/evil.bin' modified
Mode: realtime
Changed attributes: mtime
Old modification time was: '1670328934', now it is '1670328935'

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Tue Dec  6 12:15:35 2022
 - Inode: 405
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1670328936.40129: - syscheck,pci_dss_11.5,nist_800_53_SI.7,
2022 Dec 06 12:15:36 (agent) any->syscheck
Rule: 100200 (level 7) -> 'File modified in /root directory.'
File '/root/evil.bin' modified
Mode: realtime
Changed attributes: mtime
Old modification time was: '1670328935', now it is '1670328936'

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Tue Dec  6 12:15:36 2022
 - Inode: 405
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1670328936.40742: - virustotal,
2022 Dec 06 12:15:36 server->virustotal
Rule: 87101 (level 3) -> 'VirusTotal: Error: Public API request rate limit reached'
{"virustotal": {"error": 204, "description": "Error: Public API request rate limit reached"}, "integration": "virustotal"}
virustotal.error: 204
virustotal.description: Error: Public API request rate limit reached
integration: virustotal

** Alert 1670328937.41146: - syscheck,pci_dss_11.5,nist_800_53_SI.7,
2022 Dec 06 12:15:37 (agent) any->syscheck
Rule: 100200 (level 7) -> 'File modified in /root directory.'
File '/root/evil.bin' modified
Mode: realtime
Changed attributes: mtime
Old modification time was: '1670328936', now it is '1670328937'

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Tue Dec  6 12:15:37 2022
 - Inode: 405
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1670328938.41759: - virustotal,
2022 Dec 06 12:15:38 server->virustotal
Rule: 87101 (level 3) -> 'VirusTotal: Error: Public API request rate limit reached'
{"virustotal": {"error": 204, "description": "Error: Public API request rate limit reached"}, "integration": "virustotal"}
virustotal.error: 204
virustotal.description: Error: Public API request rate limit reached
integration: virustotal
```
</details>

### Results

For both tests, the integration alerts work as expected.
