### ISSUE TITLE
The escapping charater is not represented the same way for HLP and helpers

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#15880]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh-qa/issues/3735   |     https://github.com/wazuh/wazuh/issues/15421 |

# Description

During the function helpers' testing, was detected that escaped characters are not represented the same way for HLPs and function helpers.

<details><summary>Decoder's signatures</summary>

```
map:
    - ~outMap: +parse_csv/$~json.testing/¶/"/\\/out1/out2/outN

parse:
  logpar:
    - ~json.testing: <~outField/csv/¶/"/\\/out1/out2/outN>

```

</details>

<details><summary>Log input</summary>

```
{"type":"test","testing":"value1,value2,v,vv,vvv,src"}
```

</details>

```
OUTPUT:

{
    "wazuh": {
        "queue": 49,
        "origin": "/dev/stdin"
    },
    "event": {
        "original": "{\"type\":\"test\",\"testing\":\"value1,value2,v,vv,vvv,src\"}"
    },
    "~json": {
        "type": "test",
        "testing": "value1,value2,v,vv,vvv,src"
    },
    "~outField": {
        "\u00B6": "value1",
        "\"": "value2",
        "\\": "v",
        "out1": "vv",
        "out2": "vvv",
        "outN": "src"
    },
    "~outMap": {
        "\u00B6": "value1",
        "\"": "value2",
        "\\\\": "v",
        "out1": "vv",
        "out2": "vvv",
        "outN": "src"
    }
}
```

> The character `\` is not represented the same way using the HLP and the function helper

## Related cases

<details><summary>Check if sum operator can handle unicode characters when building as digits</summary>

1. Add the custom decoder with the following normalize section placed in `ruleset/decoders/custom.yml` 

    ```
    normalize:
    - check:
        - ~json.type: +s_eq/test
        map:
        - ~result: 0

    - check:
        - ~json.type: +s_eq/test
        map:
        - ~result: +i_calc/sum/100/\u0031/2147483648
    ```

    > \u0031 -> digit one: 1

2. Update the custom decoder
    
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main catalog update decoder/custom-json/0 < ruleset/decoders/custom.yml 
    An error occurred while trying to validate "decoder/custom-json/0": Stage block "map" building failed: An error occurred while building the helper function "i_calc": "helper.i_calc[/~0result, sum, 100, \u0031, 2147483648]" function: Could not convert parameter "\u0031" to int: stoi
    root@engine:/home/vagrant/engine/wazuh/src/engine#
    ```

    > Even if you use \u0031 or \\u0031 the output is the same

    > Seems related to https://github.com/wazuh/wazuh/issues/15880

</details>

<details><summary>Check if sub operator can handle unicode characters when building as digits</summary>

1. Add the custom decoder with the following normalize section placed in `ruleset/decoders/custom.yml` 

    ```
    normalize:
    - check:
        - ~json.type: +s_eq/test
        map:
        - ~result: 0

    - check:
        - ~json.type: +s_eq/test
        map:
        - ~result: +i_calc/sub/100/\u0031/2147483648
    ```

    > \u0031 -> digit one: 1

2. Update the custom decoder
    
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main catalog update decoder/custom-json/0 < ruleset/decoders/custom.yml 
    An error occurred while trying to validate "decoder/custom-json/0": Stage block "map" building failed: An error occurred while building the helper function "i_calc": "helper.i_calc[/~0result, sub, 100, \u0031, 2147483648]" function: Could not convert parameter "\u0031" to int: stoi
    root@engine:/home/vagrant/engine/wazuh/src/engine#
    ```

    > Even if you use \u0031 or \\u0031 the output is the same

    > Seems related to https://github.com/wazuh/wazuh/issues/15880

</details>

<details><summary>Check if mul operator can handle unicode characters when building as digits</summary>

1. Add the custom decoder with the following normalize section placed in `ruleset/decoders/custom.yml` 

    ```
    normalize:
    - check:
        - ~json.type: +s_eq/test
        map:
        - ~result: 0

    - check:
        - ~json.type: +s_eq/test
        map:
        - ~result: +i_calc/mul/100/\u0031/2147483648
    ```

    > \u0031 -> digit one: 1

2. Update the custom decoder
    
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main catalog update decoder/custom-json/0 < ruleset/decoders/custom.yml 
    An error occurred while trying to validate "decoder/custom-json/0": Stage block "map" building failed: An error occurred while building the helper function "i_calc": "helper.i_calc[/~0result, mul, 100, \u0031, 2147483648]" function: Could not convert parameter "\u0031" to int: stoi
    root@engine:/home/vagrant/engine/wazuh/src/engine#
    ```

    > Even if you use \u0031 or \\u0031 the output is the same

    > Seems related to https://github.com/wazuh/wazuh/issues/15880

</details>

<details><summary>Check if div operator can handle unicode characters when building as digits</summary>

1. Add the custom decoder with the following normalize section placed in `ruleset/decoders/custom.yml` 

    ```
    normalize:
    - check:
        - ~json.type: +s_eq/test
        map:
        - ~result: 0

    - check:
        - ~json.type: +s_eq/test
        map:
        - ~result: +i_calc/div/100/\u0031/2147483648
    ```

    > \u0031 -> digit one: 1

2. Update the custom decoder
    
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main catalog update decoder/custom-json/0 < ruleset/decoders/custom.yml 
    An error occurred while trying to validate "decoder/custom-json/0": Stage block "map" building failed: An error occurred while building the helper function "i_calc": "helper.i_calc[/~0result, div, 100, \u0031, 2147483648]" function: Could not convert parameter "\u0031" to int: stoi
    root@engine:/home/vagrant/engine/wazuh/src/engine# 
    ```

    > Even if you use \u0031 or \\u0031 the output is the same

    > Seems related to https://github.com/wazuh/wazuh/issues/15880

</details>

<details><summary>Check if sum operator can handle unicode characters as digits</summary>

1. Add the custom decoder with the following normalize section placed in `ruleset/decoders/custom.yml` 

    ```
    normalize:
        - check:
            - ~json.type: +s_eq/test
          map:
            - ~result: 100

        - check:
            - ~json.testing: +s_contains/i_calc
          map:
            - ~nums: +parse_csv/$~json.numbers/n1/n2/n3/n4

        - check:
            - ~json.type: +s_eq/test
          map:
            - ~result: +i_calc/sum/$~nums.n1/$~nums.n2/$~nums.n3/$~nums.n4
    ```

    > If we use this decoder, the parse_csv will transform the unicode in integer
    > "~nums": {
    >     "n1": 100,
    >     "n2": 1,
    >     "n3": 3,
    >     "n4": 66
    > }
    > So we will use the one below

    ```
    normalize:
       - check:
            - ~json.type: +s_eq/test
         map:
            - ~result: 100

       - check:
            - ~json.type: +s_eq/test
         map:
            - ~uninum: \u0031

       - check:
            - ~json.type: +s_eq/test
         map:
            - ~result: +i_calc/sum/100/$~uninum/3
    ```

    > \u0031 -> digit one: 1

2. Update the custom decoder
    
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main catalog update decoder/custom-json/0 < ruleset/decoders/custom.yml 
    OK
    root@engine:/home/vagrant/engine/wazuh/src/engine#
    ```

3. Obtain the result by using the test subcommand

    ```
    Enter a log in single line (Crtl+C to exit):

    root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main test -dd
    .
    .
    .

    {"type":"test","testing":"verify i_calc operation"}
    ```

4. Verify that the operation's result is the expected

    ```
    [decoder/custom-json/0] [helper.i_calc[/~0result, sum, 100, /~0uninum, 3]] -> Failure: Parameter is not integer: /~0uninum
    ```

    ```
    OUTPUT:

    {
        "wazuh": {
            "queue": 49,
            "origin": "/dev/stdin"
        },
        "event": {
            "original": "{\"type\":\"test\",\"testing\":\"verify i_calc operation\"}"
        },
        "~json": {
            "type": "test",
            "testing": "verify i_calc operation"
        },
        "~result": 100,
        "~uninum": "\\u0031"
    }
    ```

    > It seems related to https://github.com/wazuh/wazuh/issues/15880

</details>

<details><summary>Check if sub operator can handle unicode characters as digits</summary>

1. Add the custom decoder with the following normalize section placed in `ruleset/decoders/custom.yml` 

    ```
    normalize:
        - check:
            - ~json.type: +s_eq/test
          map:
            - ~result: 100

        - check:
            - ~json.testing: +s_contains/i_calc
          map:
            - ~nums: +parse_csv/$~json.numbers/n1/n2/n3/n4

        - check:
            - ~json.type: +s_eq/test
          map:
            - ~result: +i_calc/sub/$~nums.n1/$~nums.n2/$~nums.n3/$~nums.n4
    ```

    > If we use this decoder, the parse_csv will transform the unicode in integer
    > "~nums": {
    >     "n1": 100,
    >     "n2": 1,
    >     "n3": 3,
    >     "n4": 66
    > }
    > So we will use the one below

    ```
    normalize:
       - check:
            - ~json.type: +s_eq/test
         map:
            - ~result: 100

       - check:
            - ~json.type: +s_eq/test
         map:
            - ~uninum: \u0031

       - check:
            - ~json.type: +s_eq/test
         map:
            - ~result: +i_calc/sub/100/$~uninum/3
    ```

    > \u0031 -> digit one: 1

2. Update the custom decoder
    
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main catalog update decoder/custom-json/0 < ruleset/decoders/custom.yml 
    OK
    root@engine:/home/vagrant/engine/wazuh/src/engine#
    ```

3. Obtain the result by using the test subcommand

    ```
    Enter a log in single line (Crtl+C to exit):

    root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main test -dd
    .
    .
    .

    {"type":"test","testing":"verify i_calc operation"}
    ```

4. Verify that the operation's result is the expected

    ```
    [decoder/custom-json/0] [helper.i_calc[/~0result, sub, 100, /~0uninum, 3]] -> Failure: Parameter is not integer: /~0uninum
    ```

    ```
    OUTPUT:

    {
        "wazuh": {
            "queue": 49,
            "origin": "/dev/stdin"
        },
        "event": {
            "original": "{\"type\":\"test\",\"testing\":\"verify i_calc operation\"}"
        },
        "~json": {
            "type": "test",
            "testing": "verify i_calc operation"
        },
        "~result": 100,
        "~uninum": "\\u0031"
    }
    ```

    > It seems related to https://github.com/wazuh/wazuh/issues/15880

</details>

<details><summary>Check if mul operator can handle unicode characters as digits</summary>

1. Add the custom decoder with the following normalize section placed in `ruleset/decoders/custom.yml` 

    ```
    normalize:
        - check:
            - ~json.type: +s_eq/test
          map:
            - ~result: 100

        - check:
            - ~json.testing: +s_contains/i_calc
          map:
            - ~nums: +parse_csv/$~json.numbers/n1/n2/n3/n4

        - check:
            - ~json.type: +s_eq/test
          map:
            - ~result: +i_calc/mul/$~nums.n1/$~nums.n2/$~nums.n3/$~nums.n4
    ```

    > If we use this decoder, the parse_csv will transform the unicode in integer
    > "~nums": {
    >     "n1": 100,
    >     "n2": 1,
    >     "n3": 3,
    >     "n4": 66
    > }
    > So we will use the one below

    ```
    normalize:
       - check:
            - ~json.type: +s_eq/test
         map:
            - ~result: 100

       - check:
            - ~json.type: +s_eq/test
         map:
            - ~uninum: \u0031

       - check:
            - ~json.type: +s_eq/test
         map:
            - ~result: +i_calc/mul/100/$~uninum/3
    ```

    > \u0031 -> digit one: 1

2. Update the custom decoder
    
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main catalog update decoder/custom-json/0 < ruleset/decoders/custom.yml 
    OK
    root@engine:/home/vagrant/engine/wazuh/src/engine#
    ```

3. Obtain the result by using the test subcommand

    ```
    Enter a log in single line (Crtl+C to exit):

    root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main test -dd
    .
    .
    .

    {"type":"test","testing":"verify i_calc operation"}
    ```

4. Verify that the operation's result is the expected

    ```
    [decoder/custom-json/0] [helper.i_calc[/~0result, mul, 100, /~0uninum, 3]] -> Failure: Parameter is not integer: /~0uninum
    ```

    ```
    OUTPUT:

    {
        "wazuh": {
            "queue": 49,
            "origin": "/dev/stdin"
        },
        "event": {
            "original": "{\"type\":\"test\",\"testing\":\"verify i_calc operation\"}"
        },
        "~json": {
            "type": "test",
            "testing": "verify i_calc operation"
        },
        "~result": 100,
        "~uninum": "\\u0031"
    }
    ```

    > It seems related to https://github.com/wazuh/wazuh/issues/15880

</details>

<details><summary>Check if div operator can handle unicode characters as digits</summary>

1. Add the custom decoder with the following normalize section placed in `ruleset/decoders/custom.yml` 

    ```
    normalize:
        - check:
            - ~json.type: +s_eq/test
          map:
            - ~result: 100

        - check:
            - ~json.testing: +s_contains/i_calc
          map:
            - ~nums: +parse_csv/$~json.numbers/n1/n2/n3/n4

        - check:
            - ~json.type: +s_eq/test
          map:
            - ~result: +i_calc/div/$~nums.n1/$~nums.n2/$~nums.n3/$~nums.n4
    ```

    > If we use this decoder, the parse_csv will transform the unicode in integer
    > "~nums": {
    >     "n1": 100,
    >     "n2": 1,
    >     "n3": 3,
    >     "n4": 66
    > }
    > So we will use the one below

    ```
    normalize:
       - check:
            - ~json.type: +s_eq/test
         map:
            - ~result: 100

       - check:
            - ~json.type: +s_eq/test
         map:
            - ~uninum: \u0031

       - check:
            - ~json.type: +s_eq/test
         map:
            - ~result: +i_calc/div/100/$~uninum/3
    ```

    > \u0031 -> digit one: 1

2. Update the custom decoder
    
    ```
    root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main catalog update decoder/custom-json/0 < ruleset/decoders/custom.yml 
    OK
    root@engine:/home/vagrant/engine/wazuh/src/engine#
    ```

3. Obtain the result by using the test subcommand

    ```
    Enter a log in single line (Crtl+C to exit):

    root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main test -dd
    .
    .
    .

    {"type":"test","testing":"verify i_calc operation"}
    ```

4. Verify that the operation's result is the expected

    ```
    [decoder/custom-json/0] [helper.i_calc[/~0result, div, 100, /~0uninum, 3]] -> Failure: Parameter is not integer: /~0uninum
    ```

    ```
    OUTPUT:

    {
        "wazuh": {
            "queue": 49,
            "origin": "/dev/stdin"
        },
        "event": {
            "original": "{\"type\":\"test\",\"testing\":\"verify i_calc operation\"}"
        },
        "~json": {
            "type": "test",
            "testing": "verify i_calc operation"
        },
        "~result": 100,
        "~uninum": "\\u0031"
    }
    ```

    > It seems related to https://github.com/wazuh/wazuh/issues/15880

</details>

## Considerations

More details in the comment within the testing issue https://github.com/wazuh/wazuh-qa/issues/3735#issuecomment-1380754376 within the csv cases.

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp
