### ISSUE TITLE
API setting for global EPS `limits` block is not working

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#16419]
|Wazuh version|Component|
|---|---|
| 4.4.0 | Wazuh API |

## Description
The API configuration to prevent `global` ossec.conf section from including `limits` block, developed [here](https://github.com/wazuh/wazuh/issues/14140), is not working after the changes carried out here:
- https://github.com/wazuh/wazuh/pull/15311

Now the API allows uploading any `ossec.conf` containing `limits` even when it is disabled in the `api.yaml`:
```YAML
# Uploadable Wazuh configuration sections
 upload_configuration:
   remote_commands:
     localfile:
       allow: yes
       exceptions: []
     wodle_command:
       allow: yes
       exceptions: []
   limits:
     eps:
       allow: no
```
![image](https://user-images.githubusercontent.com/23361101/225859745-bb376950-2342-4f9f-8262-6cfe4f32aedc.png)

## To do
It is necessary to fix the API mechanism that prevents the upload of ossec.conf files containing the `limits` section. However, it should be done so that multiple <ossec_config> blocks are still allowed within the configuration file, as reported in:
- https://github.com/wazuh/wazuh/issues/15082  

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).
