### ISSUE TITLE
`i_calc` helper has issues with signs and float values

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#16474]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh-qa/issues/4010   |     https://github.com/wazuh/wazuh/pull/16094 |

# Description

During the helper function coverage extension testing, the `i_calc` operator has some not expected issues.

1. The signs seems to be not working at all.

    When using negative numbers the operations signs are not correct.

    For example, when we use the `+i_calc/mul/-2/5/-1` to obtain the operation result with an input's field, the result is not the expected:

    With this normalize section

    ```
    normalize:
        - check:
            - ~json.type: +s_eq/test
            map:
            - ~result: 3

        - check:
            - ~json.type: +s_eq/test
            map:
            - ~result: +i_calc/mul/-2/5/-1
    ```

    The operation throws an overflow

    ```
    [decoder/custom-json/0] [helper.i_calc[/~0result, mul, -2, 5, -1]] -> Failure: operation result in integer Overflown
    ```

    > Multiple samples can be checked in https://github.com/wazuh/wazuh-qa/issues/4010#issuecomment-1464094439, https://github.com/wazuh/wazuh-qa/issues/4010#issuecomment-1466593302 and https://github.com/wazuh/wazuh-qa/issues/4010#issuecomment-1466595738

2. When using float values, they are truncated. As the user manual says `If a reference is not a integer →Failure: Parameter is not integer.`, when using references it shows this error. But when the decimal value comes as a value within the decoder, it builds and truncates the values. It should also raise that error.

    > More details in https://github.com/wazuh/wazuh-qa/issues/4010#issuecomment-1468385478 and https://github.com/wazuh/wazuh-qa/issues/4010#issuecomment-1468386896

## Considerations

More details in https://github.com/wazuh/wazuh-qa/issues/4010

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
Fixed.

With this normalize section:
```yml
normalize:
    - check:
        - ~json.type: +s_eq/test
        map:
        - ~result: 3

    - check:
        - ~json.type: +s_eq/test
        map:
        - ~result: +i_calc/mul/-2/5/-1
```
Output:
```yml
[decoder/custom-json/0] [helper.i_calc[/~0result, mul, -2, 5, -1]] -> 10
```
