### ISSUE TITLE
Engine - KVDB module improvements

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#16614]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

## Description

The primary objective of KVDB is to function as a high-throughput interface for storing key-value pairs permanently.

While the existing implementation satisfies the requirements of the original design, there is room for improvement and the need to address technical debt.

Proposed improvements to the current system include the following:

Improve the DB Handlers to:

1. **Improve the DB Handlers** to:
   1. Count instances.
   2. Identify the Owners.
   3. Automatically unregister the unused handler to facilitate DB closure.
2. **Add resource tuning** at the Manager level, including memory and thread caps.  [Depends on #16702 results]
3. **Allow for raw-level DB operations** such as merging, appending, and replacing entire or partial contents of the DB 
   with raw representations of key-value pairs. Consider implementing patch application.

**Nice to have**:
  1. **Add optional triggers** to subscribe to specific keys and dispatch async handlers when values change. This would allow for triggering specific operations in one module after another module changes relevant information.
  2. ZSH breaks KVDB API when writing a value containing a null character. Might be related to CLI library.

Implementation considerations include:

1. Prioritize the use of `string_view` where possible.
2. Explore the usage of a common transport data type such as an array of bytes.
3. To improve logging in basic or primitive operations, minimize writing to the Wazuh log and return messages to the user for greater control. 
   Include a severity switch to adjust the level of detail in the log output as needed.
   
## Tasks
 - [x] #16702
 - [x] #16704
 - [x] #17056
 - [x] #17128

## DoD
 - [x] Complete all tasks. 
 - [x] Unit test.
 - [x] Update the design document.
 - [x] Update the user manual.
 - [x] Memory Leak analysis.

**Comment by soynof** [comment]
## Decoder to test helper functions

We have created a decoder to be able to test all the helper functions that use the KVDB module.

In order to perform the test, the following must be done:

1. Create an integration and upload the decoder to it:

```
---
name: decoder/test2/0

metadata:
  module: test2
  title: Test logs decoder
  description: Decoder for test
  author:
    name: Wazuh, Inc.
    url: https://wazuh.com
    date: 2023/01/30

sources:
  - decoder/integrations/0

parse:
  logpar:
    # KVDB 30 May 10:04:45 clients connected (0 slaves), 618932 bytes in use, 0 shared objects
    - event.original: <~tmp.id> <@timestamp/%d %b %Y %T>?<@timestamp/%d %b %T><message>

normalize:
  - map:
    # kvdb_set
    - ~tmp.value_1: value_1
    - ~tmp.value_2: value_2
    - ~tmp.json.key_1: value_1
    - ~tmp.json.key_2: value_2
    - ~tmp.set_key_1: +kvdb_set/test_db/key_1/$~tmp.value_1
    - ~tmp.set_key_2: +kvdb_set/test_db/key_2/$~tmp.value_2
    - ~tmp.set_key_3: +kvdb_set/test_db/key_3/$~tmp.json
    - ~tmp.set_key_4: +kvdb_set/test_db/key_4/$~tmp.value_1

    # kvdb_get
    - ~tmp.get_value_1: +kvdb_get/test_db/key_1
    - ~tmp.get_value_2: +kvdb_get/test_db/key_2
    - ~tmp.get_value_3: +kvdb_get/test_db/key_3

    # kvdb_get_merge
    - ~tmp.json_merged.key_3: value_3
    - ~tmp.json_merged.key_4: value_4
    - ~tmp.json_merged: +kvdb_get_merge/test_db/key_3

    - ~tmp.set_host: +kvdb_set/test_db/alfredo/value
    - ~tmp.set_user: +kvdb_set/test_db/pp/value
    - agent.name: alfredo

    # kvdb_delete
    #- ~tmp.delete_key_4: +kvdb_delete/test_db/key_4

  # kvdb_match
  - check:
    - agent.name: +kvdb_match/test_db
    map:
      - ~tmp.host_matched: true

  # kvdb_not_match
  - check:
    - user: +kvdb_not_match/test_db
    map:
      - ~tmp.user_not_matched: true

```

3. Run `/var/ossec/engine/wazuh-engine test`, with the following example event:
 
`KVDB 30 May 10:04:45 clients connected (0 slaves), 618932 bytes in use, 0 shared objects`

5. Validate the returned output, it should be equal to this:

```
OUTPUT:

{
    "wazuh": {
        queue: 49,
        "location": "/dev/stdin",
        "message": "KVDB 30 May 10:04:45 clients connected (0 slaves), 618932 bytes in use, 0 shared objects",
        "decoder": [
            "core-wazuh-message",
            "core-localfile",
            "integrations"
        ],
        "source": "logcollector"
    },
    "event": {
        "original": "KVDB 30 May 10:04:45 clients connected (0 slaves), 618932 bytes in use, 0 shared objects"
    },
    "~tmp": {
        "id": "KVDB",
        "value_1": "value_1",
        "value_2": "value_2",
        "json": {
            "key_1": "value_1",
            "key_2": "value_2"
        },
        "set_key_1": true,
        "set_key_2": true,
        "set_key_3": true,
        "set_key_4": true,
        "get_value_1": "value_1",
        "get_value_2": "value_2",
        "get_value_3": {
            "key_1": "value_1",
            "key_2": "value_2"
        },
        "json_merged": {
            "key_3": "value_3",
            "key_4": "value_4",
            "key_1": "value_1",
            "key_2": "value_2"
        },
        "set_host": true,
        "set_user": true,
        "host_matched": true,
        "user_not_matched": true
    },
    "@timestamp": "2023-05-30T10:04:45.000Z",
    "message": " clients connected (0 slaves), 618932 bytes in use, 0 shared objects",
    agent: {
        "name": "alfredo"
    }
}

```
