### ISSUE TITLE
Improve logical expression

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#16677]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

## Description

The new engine needs expand the logical expression capabilities, supporting varios data types, and comparators.

- [x]  Include all json data types.
        For `==` and ` !=` support all types of JSON data, numerical, string, array, object, boolean and null.
- [x]  For Operators `>` `<` `>=` `<=`
        Only support for numbers.
- [x]  Change in the build to make it support all operators. 
        `stageBuilderCheck` function.
- [x]  Identifies whether an operator is inside a helper function and takes it as a string.
- [x]  Improve the UT for stageBuilderCheck_test.cpp.
- [x]  Delete an extra file that is empty.

## DoD
 - [x] All tasks completed. 
 - [x] Unit test run and tested.
 - [x] Clang format checked.
 - [x] Documentation updated.

**Comment by NahuFigueroa97** [comment]
##   :green_circle: Logical expression functionality

#### :green_circle: < <= > >== != == for numbers and strings

- Int Helper Example

```
parse:
  logpar:
    - event.original: <message>

normalize:
  - map:
      - ~json: +parse_json/$message
  - check: ~json<3
    map:
      - event.action: "is less than 3"
  - check: ~json<=3
    map:
      - event.action: "is less equal than 3"
  - check: ~json>3
    map:
      - event.action: "is greate than 3"
  - check: ~json>=3
    map:
      - event.action: "is greate equal than 3"  
  - check: ~json==3
    map:
      - event.action: "is equal than 3"
  - check: ~json!=3
    map:
      - event.action: "is not equal than 3"
```

```
    decoder/test/0  ->  success
        [decoder/test/0] [condition.value[/wazuh/queue==103]] -> Success
        [decoder/test/0] [/event/original: <message>] -> Success
        [decoder/test/0] [condition]:success
        [decoder/test/0] [helper.parse_json[/~0json]] -> Success
        [decoder/test/0] [check: ~json<3] -> Success
        [decoder/test/0] [map.value[/event/action="is less than 3"]] -> Success
        [decoder/test/0] [check: ~json<=3] -> Success
        [decoder/test/0] [map.value[/event/action="is less equal than 3"]] -> Success
        [decoder/test/0] [check: ~json>3] -> Failure
        [decoder/test/0] [check: ~json>=3] -> Failure
        [decoder/test/0] [check: ~json==3] -> Failure
        [decoder/test/0] [check: ~json!=3] -> Success
        [decoder/test/0] [map.value[/event/action="is not equal than 3"]] -> Success

RULES:


OUTPUT:

{
    "wazuh": {
        "queue": 103,
        "location": "/dev/stdin",
        "message": "1",
        "decoders": [
            "core-ossec-message"
        ]
    },
    "event": {
        "original": "1",
        "action": "is not equal than 3"
    },
    "message": "1",
    "~json": 1
}


```
- String Helper Examples

```
parse:
  logpar:
    - event.original: <message>

normalize:
  - map:
      - ~json: +parse_json/$message
  - check: ~json<hello
    map:
      - event.action: "is less than hello"
  - check: ~json<=hello
    map:
      - event.action: "is less equal than hello"
  - check: ~json>3
    map:
      - event.action: "is greate than hello"
  - check: ~json>=hello
    map:
      - event.action: "is greate equal than hello"  
  - check: ~json==hello
    map:
      - event.action: "is equal than hello"
  - check: ~json!=hello
    map:
      - event.action: "is not equal than hello"
```
```
    decoder/test/0  ->  success
        [decoder/test/0] [condition.value[/wazuh/queue==103]] -> Success
        [decoder/test/0] [/event/original: <message>] -> Success
        [decoder/test/0] [condition]:success
        [decoder/test/0] [helper.parse_json[/~0json]] -> Success
        [decoder/test/0] [check: ~json<hello] -> Success
        [decoder/test/0] [map.value[/event/action="is less than hello"]] -> Success
        [decoder/test/0] [check: ~json<=hello] -> Success
        [decoder/test/0] [map.value[/event/action="is less equal than hello"]] -> Success
        [decoder/test/0] [check: ~json>3] -> Failure
        [decoder/test/0] [check: ~json>=hello] -> Failure
        [decoder/test/0] [check: ~json==hello] -> Failure
        [decoder/test/0] [check: ~json!=hello] -> Success
        [decoder/test/0] [map.value[/event/action="is not equal than hello"]] -> Success

RULES:


OUTPUT:

{
    "wazuh": {
        "queue": 103,
        "location": "/dev/stdin",
        "message": "\"arrow\"",
        "decoders": [
            "core-ossec-message"
        ]
    },
    "event": {
        "original": "\"arrow\"",
        "action": "is not equal than hello"
    },
    "message": "\"arrow\"",
    "~json": "arrow"
}

```
#### :green_circle: != == for objects (json, array, bool, nulll etc)

- Here it will be compared with a json that is in a different order but has the same content

```
parse:
  logpar:
    - event.original: <message>

normalize:
  - map:
      - ~json: +parse_json/$message
  - check: ~json=={"key":"value","key2":"value2"}
    map:
      - event.action: "is equal"
```

```
    decoder/test/0  ->  success
        [decoder/test/0] [condition.value[/wazuh/queue==103]] -> Success
        [decoder/test/0] [/event/original: <message>] -> Success
        [decoder/test/0] [condition]:success
        [decoder/test/0] [helper.parse_json[/~0json]] -> Success
        [decoder/test/0] [check: ~json=={"key":"value","key2":"value2"}] -> Success
        [decoder/test/0] [map.value[/event/action="is equal"]] -> Success

RULES:


OUTPUT:

{
    "wazuh": {
        "queue": 103,
        "location": "/dev/stdin",
        "message": "{\"key2\":\"value2\",\"key\":\"value\"}",
        "decoders": [
            "core-ossec-message"
        ]
    },
    "event": {
        "original": "{\"key2\":\"value2\",\"key\":\"value\"}",
        "action": "is equal"
    },
    "message": "{\"key2\":\"value2\",\"key\":\"value\"}",
    "~json": {
        "key2": "value2",
        "key": "value"
    }
}
```

```
