### ISSUE TITLE
[Windows SCA Policy] Problems with other OS languages except English

### ISSUE THREAD

**Issue by StefanSa** [wazuh/wazuh#16842]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.1 | Wazuh component | Agent | Packages | OS version Windows 10 + 11 |

Hi there,
Some windows cis guidelines fail because they are partly os locales specific.

Example with the `German OS`:
`c:net user guest -> r:Account active\s+No` fails, but `c:net user gast -> r:Konto aktiv\s+Nein` is successful.

The value `15` is correct here and also the spelling, but apparently regex has a problem with the umlauts.
`c:net.exe accounts -> n:Sperrüberprüfungsfenster \(Minuten\):\s+(\d+) compare >= 15`

```
C:\Tools>net.exe accounts
Abmelden erzwingen nach:                                  0
Minimales Kennwortalter (Tage):                           1
Maximales Kennwortalter (Tage):                           Unbegrenzt
Minimale Kennwortlänge:                                   8
Länge der Kennwortchronik:                                12
Sperrschwelle:                                            10
Sperrdauer (Minuten):                                     15
Sperrüberprüfungsfenster (Minuten):                       15
Rolle des Computers:                                      WORKSTATION
```
```
C:\Tools>net user gast
Benutzername                        Gast
Vollständiger Name
Beschreibung                        Vordefiniertes Konto für Gastzugriff auf den Computer bzw. die Domäne
Benutzerbeschreibung
Länder-/Regionscode                 000 (Standardsystemvorgabe)
Konto aktiv                         Nein
Konto abgelaufen                    Nie

Letztes Setzen des Kennworts        21.04.2023 15:22:30
Kennwort läuft ab                   Nie
Kennwort änderbar                   22.04.2023 15:22:30
Kennwort erforderlich               Nein
Benutzer kann Kennwort ändern       Nein

Erlaubte Arbeitsstationen           Alle
Anmeldeskript
Benutzerprofil
Basisverzeichnis
Letzte Anmeldung                    Nie

Erlaubte Anmeldezeiten              Alle

Lokale Gruppenmitgliedschaften      *Gäste
Globale Gruppenmitgliedschaften     *Kein
```

Is it possible to make such queries OS locales specific independent ?

**Comment by 72nomada** [comment]
Hi @StefanSa, 

We have the plan to try to use UUIDs in multiple checks to be able to solve some problems with language. Coming Windows SCA will come with those UUIDs, Hope we will reduce the impact on Windows Systems with no English language. 

Thanks

**Comment by StefanSa** [comment]
Possibly via method 2 mentioned in this article:
https://schneegans.de/windows/account-lockout/

**Comment by StefanSa** [comment]
@72nomada 
The same applies to `auditpol:`
```
auditpol.exe /list /subcategory:"*"
Kategorie/Unterkategorie
System
  Sicherheitsstatusänderung
  Sicherheitssystemerweiterung
  Systemintegrität
  IPSEC-Treiber
  Andere Systemereignisse
An-/Abmeldung
  Anmelden
  Abmelden
  Kontosperrung
  IPsec-Hauptmodus
  IPsec-Schnellmodus
  IPsec-Erweiterungsmodus
  Spezielle Anmeldung
  Andere Anmelde-/Abmeldeereignisse
  Netzwerkrichtlinienserver
  Benutzer-/Geräteansprüche
  Gruppenmitgliedschaft
Objektzugriff
  Dateisystem
  Registrierung
  Kernelobjekt
  SAM
  Zertifizierungsdienste
  Anwendung wurde generiert.
  Handleänderung
  Dateifreigabe
  Filterplattform: Verworfene Pakete
  Filterplattformverbindung
  Andere Objektzugriffsereignisse
  Detaillierte Dateifreigabe
  Wechselmedien
  Staging zentraler Richtlinien
Berechtigungen
  Sensible Verwendung von Rechten
  Nicht sensible Verwendung von Rechten
  Andere Rechteverwendungsereignisse
Detaillierte Nachverfolgung
  Prozesserstellung
  Prozessbeendigung
  DPAPI-Aktivität
  RPC-Ereignisse
  Plug &amp; Play-Ereignisse
  Ereignisse zu angepassten Tokenrechten
Richtlinienänderung
  Richtlinienänderungen überwachen
  Authentifizierungsrichtlinienänderung
  Autorisierungsrichtlinienänderung
  MPSSVC-Richtlinienänderung auf Regelebene
  Filterplattform-Richtlinienänderung
  Andere Richtlinienänderungsereignisse
Kontenverwaltung
  Benutzerkontenverwaltung
  Computerkontoverwaltung
  Sicherheitsgruppenverwaltung
  Verteilergruppenverwaltung
  Anwendungsgruppenverwaltung
  Andere Kontoverwaltungsereignisse
DS-Zugriff
  Verzeichnisdienstzugriff
  Verzeichnisdienständerungen
  Verzeichnisdienstreplikation
  Detaillierte Verzeichnisdienstreplikation
Kontoanmeldung
  Überprüfung der Anmeldeinformationen
  Ticketvorgänge des Kerberos-Diensts
  Andere Kontoanmeldungsereignisse
  Kerberos-Authentifizierungsdienst
```
Due to this dependence on the English OS language, there is at least a deviation of 20" - 25%, so the SCA rating /value is not valid.

**Comment by StefanSa** [comment]
@72nomada 
Hi Jose,
is there a time frame until this problem will be solved by UUID, because currently it is not usable except native english.

**Comment by marcinozga** [comment]
Gues account check also fails if guest account is renamed. Another that fails is machine account password age, net.exe accounts returns maximum user password age, not machine, perhaps registry check would work better.

**Comment by PiRomant** [comment]
Wouldn't it be easier to use `chcp 437` before `net`?

**Comment by ooniagbi** [comment]
See what I mean:

![image](https://github.com/wazuh/wazuh/assets/97736018/795ec04f-5b3a-4f60-a147-d6b0509ae3dd)

**Comment by kheldorn** [comment]
And an alternative for "net user" could maybe be this?

> wmic useraccount where "localaccount=true"

Gives a list of all local accounts and the following output on a German locale system:

```
AccountType=512
Description=
Disabled=TRUE
Domain=LocalComputerName
FullName=
InstallDate=
LocalAccount=TRUE
Lockout=FALSE
Name=Administrator
PasswordChangeable=TRUE
PasswordExpires=FALSE
PasswordRequired=TRUE
SID=S-1-5-21-290899589-3568597886-1793417347-500
SIDType=1
Status=Degraded


AccountType=512
Description=Ein vom System verwaltetes Benutzerkonto.
Disabled=TRUE
Domain=LocalComputerName
FullName=
InstallDate=
LocalAccount=TRUE
Lockout=FALSE
Name=DefaultAccount
PasswordChangeable=TRUE
PasswordExpires=FALSE
PasswordRequired=FALSE
SID=S-1-5-21-290899589-3568597886-1793417347-503
SIDType=1
Status=Degraded


AccountType=512
Description=Vordefiniertes Konto für Gastzugriff auf den Computer bzw. die Domäne
Disabled=TRUE
Domain=LocalComputerName
FullName=
InstallDate=
LocalAccount=TRUE
Lockout=FALSE
Name=Gast
PasswordChangeable=FALSE
PasswordExpires=FALSE
PasswordRequired=FALSE
SID=S-1-5-21-290899589-3568597886-1793417347-501
SIDType=1
Status=Degraded


AccountType=512
Description=Ein Benutzerkonto, das vom System für Windows Defender Application Guard-Szenarien verwaltet und verwendet wird
Disabled=TRUE
Domain=LocalComputerName
FullName=
InstallDate=
LocalAccount=TRUE
Lockout=FALSE
Name=WDAGUtilityAccount
PasswordChangeable=TRUE
PasswordExpires=TRUE
PasswordRequired=TRUE
SID=S-1-5-21-290899589-3568597886-1793417347-504
SIDType=1
Status=Degraded
```

**Comment by blackhawk1981** [comment]
Hi everyone, today I upgraded to Wazuh version 4.8. However, I see that this problem has not been solved yet. At what point is the development of the resolution?

**Comment by jmorda** [comment]
Hello, same problem here. A very low score due to numerous "fails" because of the bone language (French here). Hope this will be solved soon.

**Comment by peatsn00** [comment]
Same here for German. Has anyone translated sca files ?

**Comment by blackhawk1981** [comment]
Hello everyone,

at the moment I have Wazuh 4.8.1 in production but SCA always returns me extremely low scores because the rules I dispense via GPO are not recognized.

**Comment by lidstroem13** [comment]
Hi @peatsn00,

I have translated the SCA files for the "net accounts" commands to German. Additionally, I have replaced the English texts in the "auditpol" commands with the corresponding GUIDs, therefore they could be used for every language.

Feel free to check out the updated files and let me know if you have any questions or need further assistance!

Best,
[cis_win2022_german.txt](https://github.com/user-attachments/files/16522879/cis_win2022_german.txt)

**Comment by slhotellier** [comment]
Hello
I have the same problem on rhel and windows 2022.
For linux I think that somethink like export LANG="en_US.UTF-8" must be enough, in execution context of the agent. 

Best regards

**Comment by slhotellier** [comment]
Hello 
I have added 
`export LANG="en_US.UTF-8"` 
to /var/ossec/bin/wazuh-control and it works on RHEL 8 Wazuh 4.9.0.

now : how to do this with Windows agent ?

Best regards

**Comment by slhotellier** [comment]
Hello 

For Windows agent an idea may be to create a wazuh user on OS set with en-US language, and lanch service with this account ?

Best regards

**Comment by zbalkan** [comment]
This applies to the local Administrator as well.

**Comment by blackhawk1981** [comment]
Hello everyone,

I saw that version 4.10 is in the home stretch. I wanted to know if the SCA problem will be solved or will it be necessary to adjust the rules so that they recognize a language other than English (I am writing from Italy).

In case a solution has not been reached can you suggest some alternative software to the SCA analysis so that NIS2 compliance reports can be generated (the alternative software will have to live until the Wazuh DevTeam applies a final solution)?

Translated with DeepL.com (free version)

**Comment by zbalkan** [comment]
Hi @blackhawk1981,

I suggest using https://www.open-scap.org/

**Comment by ooniagbi** [comment]
> Hello everyone,
> 
> I saw that version 4.10 is in the home stretch. I wanted to know if the SCA problem will be solved or will it be necessary to adjust the rules so that they recognize a language other than English (I am writing from Italy).
> 
> In case a solution has not been reached can you suggest some alternative software to the SCA analysis so that NIS2 compliance reports can be generated (the alternative software will have to live until the Wazuh DevTeam applies a final solution)?

Hello @blackhawk1981, this issue will not be resolved in 4.10.0.

**Comment by PSOwned** [comment]
Have the same problems but found a Workaround: use \.+ for every ä,ü,ö,... like: 
`'c:net.exe accounts -> n:Sperr\.+berpr\.+fungsfenster \(Minuten\):\s+(\d+) compare >= 15'`

**Comment by Johnng007** [comment]
## Windows default account name (English).

## Affected SCAs and Checks

SCA | Check IDs 
-- | --
Windows 11 Enterprise | 26012, 26011, 26009
Windows 10 Enterprise | 15509, 15511, 15512
Windows Server 2012 non-R2 | 34509, 34511, 34512
Windows Server 2012 R2 | 15008, 15010, 15011
Windows Server 2016 | 16002
Windows Server 2019 | 16507, 16509, 16510
Windows Server 2022 | 27009, 27011, 27012

**Comment by Johnng007** [comment]
## SCA Check: `Configure 'Accounts: Rename administrator account'.`

Previous rule:

````
    condition: any
    rules:
      - 'c:net user administrator -> r:Account active\s+No'
      - "c:net user administrator -> r:The user name could not be found."
````

Proposed rule:

````
    condition: any
    rules:
      - 'c:wmic useraccount where (sid like "s-1-5-21-%-501") get status -> r:Degraded'
      - 'c:wmic useraccount where (sid like "s-1-5-21-%-501") get status -> r:No Instance\(s\) Available.'
````

The proposed rule take care of Language dependent issue.

![Image](https://github.com/user-attachments/assets/9bbef2b0-f69e-4b00-bfa1-8360f998c558)

![Image](https://github.com/user-attachments/assets/466f5ef5-6dd0-4022-bc23-6d36bd533804)

**Comment by tomkolp** [comment]
Polish language doesn't work either. Good thing I found this thread, because I thought it was my fault.![Image](https://github.com/user-attachments/assets/a65ab60f-1127-4767-bc72-a781bc20a56f)

**Comment by pano9000** [comment]
still having the same issue with Wazuh 4.12.0 and German localized OS with those checks that use `net.exe`

**Comment by Kobrasty** [comment]
As a temporary workaround, you can do the following:

1. Create a new (Windows, local) user, e.g., wazuh-monitor (the name doesn't matter).
2. Give them a really long password and prevent them from changing it.
3. Move them to a group with the appropriate permissions (e.g., Administrators).
4. Install the English (US) language pack for this user (if it wasn't already there) and set it as the default for this user.
5. In Services, change the default user running the service from SYSTEM to the newly created wazuh-monitor.
6. Restart the computer.

Magically, CSA starts returning the correct values. Tested on Polish-language Windows 11

Best regards

**Comment by Johnng007** [comment]
# Implementation Test

## Environment Setup

Operating system: Windows 11 Pro
Language: Traditional Chinese (Taiwan).

<img width="818" height="385" alt="Image" src="https://github.com/user-attachments/assets/1750f40b-4c42-4c58-8d19-d07e4607afe2" />

Connected to Wazuh Manager

<img width="1893" height="873" alt="Image" src="https://github.com/user-attachments/assets/0cc75dd2-44b5-4dfe-9d65-3640b27b3479" />

Reiterating issue with sample check below

<details><summary>SCA Check: Ensure 'Maximum password age' is set to '365 or fewer days, but not 0'. </summary>

````
  - id: 36001
    title: "Ensure 'Maximum password age' is set to '365 or fewer days, but not 0'."
    description: "This policy setting defines how long a user can use their password before it expires. Values for this policy setting range from 0 to 999 days. If you set the value to 0, the password will never expire. Because attackers can crack passwords, the more frequently you change the password the less opportunity an attacker has to use a cracked password. However, the lower this value is set, the higher the potential for an increase in calls to help desk support due to users having to change their password or forgetting which password is current. The recommended state for this setting is 365 or fewer days, but not 0. Note: Password Policy settings (section 1.1) and Account Lockout Policy settings (section 1.2) must be applied via the Default Domain Policy GPO in order to be globally in effect on domain user accounts as their default behavior. If these settings are configured in another GPO, they will only affect local user accounts on the computers that receive the GPO. However, custom exceptions to the default password policy and account lockout policy rules for specific domain users and/or groups can be defined using Password Settings Objects (PSOs), which are completely separate from Group Policy and most easily configured using Active Directory Administrative Center."
    rationale: "The longer a password exists the higher the likelihood that it will be compromised by a brute force attack, by an attacker gaining general knowledge about the user, or by the user sharing the password. Configuring the Maximum password age setting to 0 so that users are never required to change their passwords is a major security risk because that allows a compromised password to be used by the malicious user for as long as the valid user has authorized access."
    impact: "If the Maximum password age setting is too low, users are required to change their passwords very often. Such a configuration can reduce security in the organization, because users might write their passwords in an insecure location or lose them. If the value for this policy setting is too high, the level of security within an organization is reduced because it allows potential attackers more time in which to discover user passwords or to use compromised accounts."
    remediation: "To establish the recommended configuration via GP, set the following UI path to 365 or fewer days, but not 0: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Account Policies\\Password Policy\\Maximum password age."
    references:
      - 'https://www.cisecurity.org/white-papers/cis-password-policy-guide/'
      - 'https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-policy'
    compliance:
      - cis: ["1.1.2"]
      - cis_csc_v8: ["5.2"]
      - cis_csc_v7: ["16.10"]
      - cmmc_v2.0: ["IA.L2-3.5.7"]
      - pci_dss_v4.0: ["2.2.2", "8.3.5", "8.3.6", "8.6.3"]
      - soc_2: ["CC6.1"]
    condition: all
    rules:
      - 'c:net.exe accounts -> n:Maximum password age \(days\):\s+(\d+) compare <= 365'
      - 'c:net.exe accounts -> n:Maximum password age \(days\):\s+(\d+) compare > 0'

````
</details>

The test Environment has the correct configuration as seen below.

<img width="526" height="217" alt="Image" src="https://github.com/user-attachments/assets/64ece79c-f1a5-4606-8ca2-41cb19d8842b" />

But the SCA check fails due to language constraints.

<img width="1405" height="39" alt="Image" src="https://github.com/user-attachments/assets/5b4d45af-3530-4df7-9f87-06d1aec6076f" />

However the same account security policies can be retrieved in a language agnostic exported file.

<img width="739" height="159" alt="Image" src="https://github.com/user-attachments/assets/2081ccb4-2a90-4dfc-babf-4772362718e1" />

We will go ahead then to update the SCA check with a rule that exports, reads and deletes this file.

<details><summary>SCA Check: Ensure 'Maximum password age' is set to '365 or fewer days, but not 0'. </summary>

````
  - id: 36001
    title: "Ensure 'Maximum password age' is set to '365 or fewer days, but not 0'."
    description: "This policy setting defines how long a user can use their password before it expires. Values for this policy setting range from 0 to 999 days. If you set the value to 0, the password will never expire. Because attackers can crack passwords, the more frequently you change the password the less opportunity an attacker has to use a cracked password. However, the lower this value is set, the higher the potential for an increase in calls to help desk support due to users having to change their password or forgetting which password is current. The recommended state for this setting is 365 or fewer days, but not 0. Note: Password Policy settings (section 1.1) and Account Lockout Policy settings (section 1.2) must be applied via the Default Domain Policy GPO in order to be globally in effect on domain user accounts as their default behavior. If these settings are configured in another GPO, they will only affect local user accounts on the computers that receive the GPO. However, custom exceptions to the default password policy and account lockout policy rules for specific domain users and/or groups can be defined using Password Settings Objects (PSOs), which are completely separate from Group Policy and most easily configured using Active Directory Administrative Center."
    rationale: "The longer a password exists the higher the likelihood that it will be compromised by a brute force attack, by an attacker gaining general knowledge about the user, or by the user sharing the password. Configuring the Maximum password age setting to 0 so that users are never required to change their passwords is a major security risk because that allows a compromised password to be used by the malicious user for as long as the valid user has authorized access."
    impact: "If the Maximum password age setting is too low, users are required to change their passwords very often. Such a configuration can reduce security in the organization, because users might write their passwords in an insecure location or lose them. If the value for this policy setting is too high, the level of security within an organization is reduced because it allows potential attackers more time in which to discover user passwords or to use compromised accounts."
    remediation: "To establish the recommended configuration via GP, set the following UI path to 365 or fewer days, but not 0: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Account Policies\\Password Policy\\Maximum password age."
    references:
      - 'https://www.cisecurity.org/white-papers/cis-password-policy-guide/'
      - 'https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-policy'
    compliance:
      - cis: ["1.1.2"]
      - cis_csc_v8: ["5.2"]
      - cis_csc_v7: ["16.10"]
      - cmmc_v2.0: ["IA.L2-3.5.7"]
      - pci_dss_v4.0: ["2.2.2", "8.3.5", "8.3.6", "8.6.3"]
      - soc_2: ["CC6.1"]
    condition: all
    rules:
      - 'c:powershell secedit /export /cfg $env:TEMP\secpol.cfg; Get-Content $env:TEMP\secpol.cfg | Select-String "MaximumPasswordAge"; Remove-Item $env:TEMP\secpol.cfg -> n:MaximumPasswordAge = (\d+) compare <= 365'
      - 'c:powershell secedit /export /cfg $env:TEMP\secpol.cfg; Get-Content $env:TEMP\secpol.cfg | Select-String "MaximumPasswordAge"; Remove-Item $env:TEMP\secpol.cfg -> n:MaximumPasswordAge = (\d+) compare > 0'

````
</details>

We can see below that the SCA check is now passed.

<img width="1434" height="761" alt="Image" src="https://github.com/user-attachments/assets/bfcd839d-dda7-434d-9aaf-8cbce51b65eb" />

## TODO:
Update the affected checks in all Windows SCAs.
