### ISSUE TITLE
Limit syscollector github actions to run only on modifications in specific folders

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#16991]
## Description
Currently, GitHub Actions run on every push or pull request, even if there is no modification in some folders. This creates unnecessary overhead and increases the time required for the checks to complete. In order to optimize the workflow, we need to limit the GitHub Actions to only run on modifications in specific folders
## Proposed Solution
We can achieve this by using Git to identify the modified folders and passing them as parameters to the GitHub Actions workflow. The modified folders will then be checked while the rest of the folders will be skipped, reducing the time required for the checks.

## Tasks
- Modify https://github.com/wazuh/wazuh/actions/workflows/macos-syscollector-tests.yml
- Modify https://github.com/wazuh/wazuh/actions/workflows/ubuntu-syscollector-tests.yml
- Modify https://github.com/wazuh/wazuh/actions/workflows/windows-syscollector-tests.yml

## Expected Outcome
By limiting the GitHub Actions to only run on the modified folders, we can reduce the time required for the checks and optimize the workflow.

## Development notes

Expected change.
```
on:
  pull_request:
    paths:
      - "src/data_provider/**"
      - "src/shared_modules/**"
      - "src/wazuh_modules/syscollector/**"
      - "src/Makefile"
```
