### ISSUE TITLE
Release 4.4.2 - RC 1 - E2E UX tests - macOS log data collection

### ISSUE THREAD

**Issue by kujo-jotaro** [wazuh/wazuh#17014]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test Information

  |  
-- | --
Test name | macOS log data collection
Category | Log data analysis
Deployment option | Virtual Machine (OVA), Installing Wazuh agents
Main release issue | #16966
Main E2E UX test issue | #16965
Release candidate # | RC1

## Test Description

Deploy Wazuh with the following design:

| Component | Guide | Single/Cluster | OS |
| ----------------- | --------- | -------------------- | ---- |
| Indexer | [Virtual Machine (OVA)](https://documentation.wazuh.com/current/deployment-options/virtual-machine/virtual-machine.html) | Single | CentOS |
| Server | [Virtual Machine (OVA)](https://documentation.wazuh.com/current/deployment-options/virtual-machine/virtual-machine.html) | Single | CentOS |
| Dashboard | [Virtual Machine (OVA)](https://documentation.wazuh.com/current/deployment-options/virtual-machine/virtual-machine.html) | Single | CentOS |
| Agent | [Installing Wazuh agents](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/index.html) | - | macOS |

Create rule for macOS native logs and use wazuh-logtest command line tool in verbose mode and also try the WUI log test

## Test report procedure

All test results must have one of the following statuses:

|  | |
| -- | -- |
| 🟢 | All checks passed. |
| 🔴 | There is at least one failed result. |
| 🟡 | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause.

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

| Status | Test  | Failure type | Notes |
| -- | -- | -- | -- |
| | | | |

## Auditors validation

The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @wazuh/binary-beasts 
- [x] @davidjiglesias

**Comment by hector222arroyo** [comment]
# 🟢  Environment install

## 🟢 Manager

Manager was installed in a VMware® Workstation 17 Pro. After importing the OVA, all services were operational and the Dashboard was accessible via web browser.

<details><summary>Installation</summary>

![image](https://user-images.githubusercontent.com/68483100/236526604-42df6f08-380a-47a6-935c-4d7027a60803.png)

**Wazuh-indexer status**
![image](https://user-images.githubusercontent.com/68483100/236526818-c5207153-f92f-48b1-bb8a-6d25b9408b15.png)

**Wazuh-dashboard status**
![image](https://user-images.githubusercontent.com/68483100/236526912-82840307-8eda-45c4-9c86-2b3d1c0a8adc.png)

**Wazuh-manager status**
![image](https://user-images.githubusercontent.com/68483100/236527036-8aa7022c-27e0-4808-b20a-ba4fe4f9eb85.png)

**Wazuh Version**
![image](https://user-images.githubusercontent.com/68483100/236527231-2ef97612-6b24-4135-89aa-475f97c24880.png)


</details>

## 🟢 macOS agent

Agent installation package was downloaded from [the Wazuh website](https://packages-dev.wazuh.com/pre-release/macos/wazuh-agent-4.4.2-1.pkg). All commands detailed in the documentation ran successfully and the agent was connected to the manager.

<details><summary>Installation</summary>

![about](https://user-images.githubusercontent.com/68483100/236527665-7a056f4c-f141-48f2-92ce-85c3cddfb96e.png)

![download](https://user-images.githubusercontent.com/68483100/236527899-5112c87f-5c36-4827-adf2-1957706a2a98.png)

![Agent_Install](https://user-images.githubusercontent.com/68483100/236528288-d1ca0f6d-0dd1-4ef9-a4d3-cefaf26252ae.png)

![agent_connect](https://user-images.githubusercontent.com/68483100/236528483-f95a68bf-af45-46ce-b364-d31583604216.png)



</details>

**Comment by hector222arroyo** [comment]
# 🟢 macOS ULS alert generation in manager (rules and decoder added)

First of all, we use log stream command to see macOS logs. We will try to raise alerts for the following message:

```yaml
sh-3.2# log stream 
Timestamp                       Thread     Type        Activity             PID    TTL  
2023-05-05 17:56:07.398259-0400 0x22f5f    Error       0x0                  11428  0    BlueTool: [com.apple.bluetooth:BlueTool] Unable to open /dev/cu.BLTH: No such file or directory
```

## Example: BlueTool

### In Agent MacOS
As Wazuh does not monitor any logs by default, we need to add this config block to its ossec.conf file. The query used will filter all unrelated logs so the manager is not flooded:

`/Library/Ossec/etc/ossec.conf`

```xml
<!-- macOS ULS log collection -->
<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="activity,log" level="info">process == "BlueTool" AND composedMessage CONTAINS "Unable to open"</query>
</localfile>
```

### In Manager

After restarting the agent and enabling logall option in the manager.


`/var/ossec/etc/decoders/local_decoder.xml`

```xml
<decoder name="BlueTool">
    <program_name>^BlueTool</program_name>
</decoder>
  
<decoder name="BlueTool-alert">
    <parent>BlueTool</parent>
    <prematch>^[com.apple.bluetooth:BlueTool]</prematch>
    <regex offset="after_prematch">^(\.+)$</regex>
    <order>message</order>
</decoder>
```

`/var/ossec/etc/rules/local_rules.xml`

```xml
<group name="macos">
    <rule id="100005" level="0" noalert="1">
      <decoded_as>BlueTool</decoded_as>
      <description>BlueTool messages grouped.</description>
    </rule>
  
    <rule id="100010" level="3">
     <if_sid>100005</if_sid>
     <program_name>BlueTool</program_name>
     <match>Unable to open</match>
     <description>the device (bluetooth) is not available</description>
    </rule>
</group>
```

**Restart Wazuh agent**
![image](https://user-images.githubusercontent.com/68483100/236569208-4c8f40fb-4943-4da4-83d2-27697674a404.png)


### Expected behavior

Logs from macOS should be decoded and match the specified rule when using `wazuh-logtest` and Wazuh WUI log test. Wazuh dashboard should show the events.

<details><summary>:green_circle: Dashboard events</summary>

![image](https://user-images.githubusercontent.com/68483100/236579260-40725c9f-0690-41e4-873f-b741102a6fae.png)

</details>

<details><summary>:green_circle: /var/ossec/bin/wazuh-logtest -v output</summary>

```yml
[root@wazuh-server wazuh-user]# /var/ossec/bin/wazuh-logtest -v
Starting wazuh-logtest v4.4.2
Type one log per line

2023-05-05 17:56:07.398259-0400  localhost BlueTool[73]: [com.apple.bluetooth:BlueTool] Unable to open /dev/cu.BLTH: No such file or directory

**Phase 1: Completed pre-decoding.
        full event: '2023-05-05 17:56:07.398259-0400  localhost BlueTool[73]: [com.apple.bluetooth:BlueTool] Unable to open /dev/cu.BLTH: No such file or directory'
        timestamp: '2023-05-05 17:56:07.398259-0400'
        program_name: 'BlueTool'

**Phase 2: Completed decoding.
        name: 'BlueTool'
        parent: 'BlueTool'
        message: ' Unable to open /dev/cu.BLTH: No such file or directory'

**Rule debugging:
        Trying rule: 1 - Generic template for all syslog rules.
                *Rule 1 matched
                *Trying child rules
        Trying rule: 600 - Active Response Messages Grouped
        Trying rule: 650 - Active Response JSON Messages Grouped
        Trying rule: 200 - Grouping of wazuh rules.
        Trying rule: 400 - Rules for Wazuh API events.
        Trying rule: 420 - Rules for Wazuh API events.
        Trying rule: 2100 - NFS rules grouped.
        Trying rule: 2507 - OpenLDAP group.
        Trying rule: 2550 - rshd messages grouped.
        Trying rule: 2701 - Ignoring procmail messages.
        Trying rule: 2800 - Pre-match rule for smartd.
        Trying rule: 5100 - Pre-match rule for kernel messages.
        Trying rule: 5200 - Ignoring hpiod for producing useless logs.
        Trying rule: 2830 - Crontab rule group.
        Trying rule: 5300 - Initial grouping for su messages.
        Trying rule: 5905 - useradd failed.
        Trying rule: 5400 - Initial group for sudo messages.
        Trying rule: 9100 - PPTPD messages grouped.
        Trying rule: 9200 - Squid syslog messages grouped.
        Trying rule: 2900 - Dpkg (Debian Package) log.
        Trying rule: 2930 - Yum logs.
        Trying rule: 2931 - Yum logs.
        Trying rule: 2940 - NetworkManager grouping.
        Trying rule: 2943 - nouveau driver grouping.
        Trying rule: 2962 - Perdition custom app group.
        Trying rule: 3100 - Grouping of the sendmail rules.
        Trying rule: 3190 - Grouping of the smf-sav sendmail milter rules.
        Trying rule: 3300 - Grouping of the postfix reject rules.
        Trying rule: 3320 - Grouping of the postfix rules.
        Trying rule: 3390 - Grouping of the clamsmtpd rules.
        Trying rule: 3395 - Grouping of the postfix warning rules.
        Trying rule: 3500 - Grouping for the spamd rules
        Trying rule: 3600 - Grouping of the imapd rules.
        Trying rule: 3700 - Grouping of mailscanner rules.
        Trying rule: 3800 - Grouping of Exchange rules.
        Trying rule: 3900 - Grouping for the courier rules.
        Trying rule: 4500 - Grouping for the Netscreen Firewall rules
        Trying rule: 4700 - Grouping of Cisco IOS rules
        Trying rule: 4800 - SonicWall messages grouped.
        Trying rule: 5500 - Grouping of the pam_unix rules.
        Trying rule: 5556 - unix_chkpwd grouping.
        Trying rule: 5600 - Grouping for the telnetd rules
        Trying rule: 5700 - SSHD messages grouped.
        Trying rule: 6100 - Solaris BSM Auditing messages grouped.
        Trying rule: 6200 - Asterisk messages grouped.
        Trying rule: 6300 - Grouping for the MS-DHCP ipv4 rules.
        Trying rule: 6350 - Grouping for the MS-DHCP ipv6 rules.
        Trying rule: 7200 - Arpwatch messages grouped.
        Trying rule: 7300 - Grouping of Symantec AV rules.
        Trying rule: 7400 - Grouping of Symantec Web Security rules.
        Trying rule: 7600 - Grouping of Trend OSCE rules.
        Trying rule: 9300 - Grouping for the Horde imp rules.
        Trying rule: 9400 - Roundcube messages grouped.
        Trying rule: 9500 - Wordpress messages grouped.
        Trying rule: 9600 - cimserver messages grouped.
        Trying rule: 9700 - Dovecot Messages Grouped.
        Trying rule: 9770 - dovecot-info grouping.
        Trying rule: 9800 - Grouping for the vm-pop3d rules.
        Trying rule: 9900 - Grouping for the vpopmail rules.
        Trying rule: 11100 - Grouping for the ftpd rules.
        Trying rule: 11200 - Grouping for the proftpd rules.
        Trying rule: 11300 - Grouping for the pure-ftpd rules.
        Trying rule: 11310 - Rule grouping for pure ftpd transfers.
        Trying rule: 11400 - Grouping for the vsftpd rules.
        Trying rule: 11500 - Grouping for the Microsoft ftp rules.
        Trying rule: 12100 - Grouping of the named rules
        Trying rule: 13100 - Grouping for the smbd rules.
        Trying rule: 13106 - Grouping for the nmbd rules.
        Trying rule: 14100 - Grouping of racoon rules.
        Trying rule: 14200 - Grouping of Cisco VPN concentrator rules
        Trying rule: 19100 - VMWare messages grouped.
        Trying rule: 19101 - VMWare ESX syslog messages grouped.
        Trying rule: 30100 - Apache: Messages grouped.
        Trying rule: 31200 - Grouping of Zeus rules.
        Trying rule: 31300 - Nginx messages grouped.
        Trying rule: 31404 - PHP Warning message.
        Trying rule: 31405 - PHP Fatal error.
        Trying rule: 31406 - PHP Parse error.
        Trying rule: 40700 - Systemd rules
        Trying rule: 40900 - firewalld grouping
        Trying rule: 50100 - MySQL messages grouped.
        Trying rule: 50500 - PostgreSQL messages grouped.
        Trying rule: 51000 - Grouping for dropbear rules.
        Trying rule: 51500 - Grouping of bsd_kernel alerts
        Trying rule: 51521 - Grouping for groupdel rules.
        Trying rule: 51523 - No core dumps.
        Trying rule: 51525 - ftp-proxy cannot connect to a server.
        Trying rule: 51526 - Hard drive is dying.
        Trying rule: 51527 - CARP master to backup.
        Trying rule: 51528 - Duplicate IPv6 address.
        Trying rule: 51529 - Could not load a firmware.
        Trying rule: 51530 - hotplugd could not open a file.
        Trying rule: 51532 - Bad ntp peer.
        Trying rule: 51550 - doas grouping
        Trying rule: 52500 - Clamd messages grouped.
        Trying rule: 52501 - ClamAV: database update
        Trying rule: 53500 - OpenSMTPd grouping.
        Trying rule: 500000 - Unbound grouping.
        Trying rule: 80000 - Puppet Master messages grouped.
        Trying rule: 80001 - Puppet Agent messages grouped.
        Trying rule: 80100 - Netscaler messages grouped.
        Trying rule: 80200 - AWS alert.
        Trying rule: 80500 - Serv-u messages grouped.
        Trying rule: 80700 - Audit: Messages grouped.
        Trying rule: 81100 - USB messages grouped.
        Trying rule: 81300 - Redis messages grouped.
        Trying rule: 81400 - OpenSCAP messages grouped.
        Trying rule: 44400 - FortiNet Rules.
        Trying rule: 81600 - Fortigate v3 messages grouped.
        Trying rule: 81601 - Fortigate v4 messages grouped.
        Trying rule: 81602 - Fortigate v5 messages grouped.
        Trying rule: 81641 - Fortigate v6 messages grouped.
        Trying rule: 44640 - FortiMail Rules.
        Trying rule: 44698 - FortiMail: System Event System log messages.
        Trying rule: 44730 - Alert from Forti Authenticator.
        Trying rule: 81700 - HP 5500 EI messages grouped.
        Trying rule: 81800 - OpenVPN messages grouped.
        Trying rule: 81900 - RSA Authentication Manager messages grouped.
        Trying rule: 82000 - Imperva messages grouped.
        Trying rule: 82100 - Sophos alerts.
        Trying rule: 64270 - savscan category
        Trying rule: 64274 - Update category
        Trying rule: 82200 - FreeIPA syslog.
        Trying rule: 82400 - Cisco eStreamer messages grouped.
        Trying rule: 85000 - SQL Server messages.
        Trying rule: 85500 - Identity Guard Log.
        Trying rule: 85750 - MongoDB messages
        Trying rule: 86000 - Docker messages
        Trying rule: 86250 - Jenkins messages
        Trying rule: 86800 - VShell message grouped.
        Trying rule: 86600 - Suricata messages.
        Trying rule: 86900 - Qualysguard messages grouped.
        Trying rule: 87000 - Cylance events messages grouped.
        Trying rule: 87050 - Cylance threats messages grouped.
        Trying rule: 87100 - VirusTotal integration messages.
        Trying rule: 87200 - pvedaemon messages grouped.
        Trying rule: 87300 - ownCloud messages grouped.
        Trying rule: 87310 - ownCloud messages grouped.
        Trying rule: 22401 - Vuls integration event.
        Trying rule: 87402 - CIS-CAT events.
        Trying rule: 87403 - Old CIS-CAT events.
        Trying rule: 87500 - Exim: SMTP Messages Grouped.
        Trying rule: 87501 - dovecot messages grouped.
        Trying rule: 23501 - $(vulnerability.cve) affects $(vulnerability.package.name)
        Trying rule: 87600 - OpenVAS (gsad) messages grouped.
        Trying rule: 87608 - OpenVAS (openvasmd) messages grouped.
        Trying rule: 88000 - Percona Server audit events grouped.
        Trying rule: 89050 - McAfee AUDIT Plugin for MySQL events grouped.
        Trying rule: 88100 - MariaDB group messages.
        Trying rule: 87700 - pfSense firewall rules grouped.
        Trying rule: 87900 - Docker alerts: $(docker.Type)
        Trying rule: 64000 - Grouping of cisco-ASA rules
        Trying rule: 65500 - Mcafee EPO2
        Trying rule: 88200 - NextCloud messages grouped.
        Trying rule: 88201 - NextCloud messages grouped.
        Trying rule: 67100 - Junos IDS
        Trying rule: 67102 - Junos RT Flow
        Trying rule: 64200 - PANDA Antivirus event.
        Trying rule: 64220 - Checkpoint events.
        Trying rule: 65000 - GCP alert.
        Trying rule: 65260 - F5 Networks BigIP events
        Trying rule: 65293 - F5 BigIP CEF decoded grouped alerts
        Trying rule: 64500 - Palo Alto $(type) event.
        Trying rule: 70020 - Sophos XG210 Firewall event
        Trying rule: 70000 -  FreePBX parent
        Trying rule: 91100 - GitHub alert.
        Trying rule: 91531 - Office 365: $(office365.Workload) $(office365.Operation) operation.
        Trying rule: 88800 - Arbor
        Trying rule: 150100 - FireEye
        Trying rule: 89200 - Grouping of Huawei USG rules.
        Trying rule: 91500 - cisco-ftd rules
        Trying rule: 42001 - ESET console logs.
        Trying rule: 92501 - Cloudflare WAF rules
        Trying rule: 99000 - Amazon Security Lake rules grouped.
        Trying rule: 100005 - BlueTool messages grouped.
                *Rule 100005 matched
                *Trying child rules
        Trying rule: 100010 - the device (bluetooth) is not available
                *Rule 100010 matched

**Phase 3: Completed filtering (rules).
        id: '100010'
        level: '3'
        description: 'the device (bluetooth) is not available'
        groups: '['macos']'
        firedtimes: '1'
        mail: 'False'
**Alert to be generated.



```
</details>

<details><summary>:green_circle: Wazuh WUI log test</summary>

![image](https://user-images.githubusercontent.com/68483100/236579637-bcd22d59-4df8-44f2-a1c7-8b0e124565a9.png)

</details>

### 🟢 Result

All log tests decoded the macOS logs appropriately and matched them to the user-defined rules. Dashboard shows the event with the correct information.

**Comment by hector222arroyo** [comment]
# 🟢 Alerts

Alerts are generated correctly as shown here:

```yaml
[root@wazuh-server wazuh-user]# tail -f /var/ossec/logs/alerts/alerts.log
Previous output:
ossec: output: 'netstat listening ports':
tcp4 127.0.0.1.631 *.*
tcp6 ::1.631 *.*
udp4 *.137 *.*
udp4 *.138 *.*
udp4 *.5353 *.*
udp4 *.62024 *.*
udp6 *.5353 *.*

** Alert 1683326185.516352: - macos
2023 May 05 22:36:25 (MacBook-Pro-de-Hector.local) any->macos
Rule: 100010 (level 3) -> 'the device (bluetooth) is not available'
2023-05-05 18:36:19.655821-0400  localhost BlueTool[17001]: [com.apple.bluetooth:BlueTool] Unable to open /dev/cu.BLTH: No such file or directory
message:  Unable to open /dev/cu.BLTH: No such file or directory

** Alert 1683326190.516730: - macos
2023 May 05 22:36:30 (MacBook-Pro-de-Hector.local) any->macos
Rule: 100010 (level 3) -> 'the device (bluetooth) is not available'
2023-05-05 18:36:24.666470-0400  localhost BlueTool[17001]: [com.apple.bluetooth:BlueTool] Unable to open /dev/cu.BLTH: No such file or directory
message:  Unable to open /dev/cu.BLTH: No such file or directory

** Alert 1683326195.517108: - macos
2023 May 05 22:36:35 (MacBook-Pro-de-Hector.local) any->macos
Rule: 100010 (level 3) -> 'the device (bluetooth) is not available'
2023-05-05 18:36:29.677134-0400  localhost BlueTool[17001]: [com.apple.bluetooth:BlueTool] Unable to open /dev/cu.BLTH: No such file or directory
message:  Unable to open /dev/cu.BLTH: No such file or directory

** Alert 1683326200.517486: - macos
2023 May 05 22:36:40 (MacBook-Pro-de-Hector.local) any->macos
Rule: 100010 (level 3) -> 'the device (bluetooth) is not available'
2023-05-05 18:36:34.687753-0400  localhost BlueTool[17001]: [com.apple.bluetooth:BlueTool] Unable to open /dev/cu.BLTH: No such file or directory
message:  Unable to open /dev/cu.BLTH: No such file or directory

** Alert 1683326205.517864: - macos
2023 May 05 22:36:45 (MacBook-Pro-de-Hector.local) any->macos
Rule: 100010 (level 3) -> 'the device (bluetooth) is not available'
2023-05-05 18:36:39.698046-0400  localhost BlueTool[17001]: [com.apple.bluetooth:BlueTool] Unable to open /dev/cu.BLTH: No such file or directory
message:  Unable to open /dev/cu.BLTH: No such file or directory

** Alert 1683326207.518242: - macos
2023 May 05 22:36:47 (MacBook-Pro-de-Hector.local) any->macos
Rule: 100010 (level 3) -> 'the device (bluetooth) is not available'
2023-05-05 18:36:44.708720-0400  localhost BlueTool[17001]: [com.apple.bluetooth:BlueTool] Unable to open /dev/cu.BLTH: No such file or directory
message:  Unable to open /dev/cu.BLTH: No such file or directory

```

**Comment by hector222arroyo** [comment]
# 🟢 Support for localfile blocks deployment

This solves the need to deploy extra localfile configuration blocks for ossec.conf based on OS and OS Version.

Configuration

```yaml
 <!-- Log analysis -->
  <localfile>
    <log_format>full_command</log_format>
    <command>netstat -an | awk '{if ((/^(tcp|udp)/) && ($4 != "*.*") && ($5 == "*.*")) {print $1" "$4" "$5}}' | sort -u</command>
    <alias>netstat listening ports</alias>
    <frequency>360</frequency>
  </localfile>

  <localfile>
    <location>macos</location>
    <log_format>macos</log_format>
    <query type="trace,log,activity" level="info">(process == "sudo") or (process == "sessionlogoutd" and message contains "logout is complete.") or (process == "sshd") or (process == "tccd" and message contains "Update Access Record") or (message contains "SessionAgentNotificationCenter") or (process == "screensharingd" and message contains "Authentication") or (process == "securityd" and eventMessage contains "Session" and subsystem == "com.apple.securityd")</query>
  </localfile>
```

The local configuration block for the operating system is correctly included in the installed agent

**Comment by hector222arroyo** [comment]
# 🟢 Changes to the netstat command in macOS agents

The current netstat command on macOS agents is:
```yaml
<command>netstat -an | grep -e "tcp" -e "udp" | sed -E 's/([[:alnum:]]*)\ *[[:digit:]]*\ *[[:digit:]]*\ *(.*)\.([0-9\*]*)\ +([0-9\.\*]+).+/\1 \2 == \3 == \4/' | sort -k 4 -g | sed 's/ == \(.*\) ==/.\1/'| uniq</command>
```



This command does not provide the correct answer. We will modify that command with this one:
```yaml
<command>netstat -an | awk '{if ((/^(tcp|udp)/) && ($4 != "*.*") && ($5 == "*.*")) {print $1" "$4" "$5}}' | sort -u</command>
```

### Proposed command work as expected 🟢
```yaml
2023/05/09 14:06:33 wazuh-logcollector: INFO: Monitoring full output of command(360): netstat -an | awk '{if ((/^(tcp|udp)/) && ($4 != "*.*") && ($5 == "*.*")) {print $1" "$4" "$5}}' | sort -u
```


### Event In Dashboard 🟢

```yaml
{
  "_index": "wazuh-alerts-4.x-2023.05.09",
  "_id": "qDm8AYgB9ABkMO1xoO2Q",
  "_version": 1,
  "_score": null,
  "_source": {
    "previous_log": "ossec: output: 'netstat listening ports':\ntcp4 127.0.0.1.631 *.*\ntcp6 ::1.631 *.*\nudp4 *.137 *.*\nudp4 *.138 *.*\nudp4 *.5353 *.*\nudp4 *.57071 *.*\nudp4 127.0.0.1.32376 *.*\nudp6 *.5353 *.*",
    "input": {
      "type": "log"
    },
    "agent": {
      "ip": "192.168.145.128",
      "name": "MacBook-Pro-de-Hector.local",
      "id": "001"
    },
    "previous_output": "Previous output:\nossec: output: 'netstat listening ports':\ntcp4 127.0.0.1.631 *.*\ntcp6 ::1.631 *.*\nudp4 *.137 *.*\nudp4 *.138 *.*\nudp4 *.5353 *.*\nudp4 *.57071 *.*\nudp4 127.0.0.1.32376 *.*\nudp6 *.5353 *.*",
    "manager": {
      "name": "wazuh-server"
    },
    "rule": {
      "firedtimes": 3,
      "mail": false,
      "level": 7,
      "pci_dss": [
        "10.2.7",
        "10.6.1"
      ],
      "hipaa": [
        "164.312.b"
      ],
      "tsc": [
        "CC6.8",
        "CC7.2",
        "CC7.3"
      ],
      "description": "Listened ports status (netstat) changed (new port opened or closed).",
      "groups": [
        "ossec"
      ],
      "id": "533",
      "nist_800_53": [
        "AU.14",
        "AU.6"
      ],
      "gpg13": [
        "10.1"
      ],
      "gdpr": [
        "IV_35.7.d"
      ]
    },
    "location": "netstat listening ports",
    "decoder": {
      "name": "ossec"
    },
    "id": "1683656317.62185",
    "full_log": "ossec: output: 'netstat listening ports':\nudp4 *.137 *.*\nudp4 *.138 *.*\nudp4 *.5353 *.*\nudp4 *.57071 *.*\nudp4 127.0.0.1.32376 *.*\nudp6 *.5353 *.*",
    "timestamp": "2023-05-09T18:18:37.612+0000"
  },
  "fields": {
    "timestamp": [
      "2023-05-09T18:18:37.612Z"
    ]
  },
  "highlight": {
    "previous_log": [
      "ossec: output: 'netstat @opensearch-dashboards-highlighted-field@listening@/opensearch-dashboards-highlighted-field@ ports':\ntcp4 127.0.0.1.631 *.*\ntcp6 ::1.631 *.*\nudp4 *.137 *.*\nudp4 *.138 *.*\nudp4 *.5353 *.*\nudp4 *.57071 *.*\nudp4 127.0.0.1.32376 *.*\nudp6 *.5353 *.*"
    ],
    "agent.id": [
      "@opensearch-dashboards-highlighted-field@001@/opensearch-dashboards-highlighted-field@"
    ],
    "manager.name": [
      "@opensearch-dashboards-highlighted-field@wazuh-server@/opensearch-dashboards-highlighted-field@"
    ],
    "full_log": [
      "ossec: output: 'netstat @opensearch-dashboards-highlighted-field@listening@/opensearch-dashboards-highlighted-field@ ports':\nudp4 *.137 *.*\nudp4 *.138 *.*\nudp4 *.5353 *.*\nudp4 *.57071 *.*\nudp4 127.0.0.1.32376 *.*\nudp6 *.5353 *.*"
    ]
  },
  "sort": [
    1683656317612
  ]
}
```
