### ISSUE TITLE
Create and apply a standard for SCA metadata on current SCA files

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#17166]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.4.x | SCA |Improve |

Create and apply a standard for SCA metadata on current SCA files

Create a standard for content on top of including: 

- [ ] SCA file header information:
    - [ ] License and copyright
    - [ ] Description 
    - [ ] Based on

- [ ] Policy section:
    - [ ] id 
    - [ ] file
    - [ ] name
    - [ ] description 
    - [ ] references

- [ ] Requirements section:
    - [ ] title
    - [ ] description

## Current metadata section

```
# Security Configuration Assessment
# CIS Checks for Amazon Linux 1
# Copyright (C) 2015, Wazuh Inc.
#
# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation
#
# Based on:
# Center for Internet Security Benchmark for Amazon Linux v2.1.0 - 12-27-2017

policy:
  id: "cis_amazon_linux_1"
  file: "cis_amazon_linux_1.yml"
  name: "CIS Benchmark for Amazon Linux 1"
  description: "This document provides prescriptive guidance for establishing a secure configuration posture for Amazon Linux systems running on x86 and x64 platforms. This document was tested against CentOS 6."
  references:
    - https://www.cisecurity.org/cis-benchmarks/

requirements:
  title: "Check Amazon Linux version."
  description: "Requirements for running the policy against Amazon Linux 1."

```
