### ISSUE TITLE
Alert new files is always enabled

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#17694]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.4 | Syscheck | Manager/Agent | Packages | Ubuntu 22 |

### Description

The alert new files option is not working correctly. Even if we disable this option, it is generating alerts in case of new files are added to the system.

**Steps to reproduce**

- Disable `alert_new_files`
```
    <alert_new_files>no</alert_new_files>
    ...
    <directories>/tmp/testing</directories>
```
- Restart the manager
```
systemctl restart wazuh-manager
```
- Create a file in `/tmp/testing`. For example `/tmp/testing/file2`.
- Check that a `File added to the system` alert was generated
```
** Alert 1682006306.328849: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Apr 20 15:58:26 ubuntu->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/tmp/testing/file2' added
Mode: scheduled

Attributes:
 - Size: 8
 - Permissions: rw-r--r--
 - Date: Thu Apr 20 15:58:22 2023
 - Inode: 394441
 - User: root (0)
 - Group: root (0)
 - MD5: 20b860c600fae3e1017c6b4391cdb789
 - SHA1: 5e251be330db9ec722e23ead50eab367719abb86
 - SHA256: e1e3430e27bea590853543f542c935a0afa8a3a4c81ca27a5c9d6fad8f4da6ea
```

- Check active configuration through API: `curl -k -X GET "https://localhost:55000/manager/configuration/syscheck/syscheck" -H "Authorization: Bearer $TOKEN"`

```
{
   "data":{
      "affected_items":[
         {
            "syscheck":{
               "disabled":"no",
               "frequency":10,
               "skip_nfs":"yes",
               "skip_dev":"yes",
               "skip_sys":"yes",
               "skip_proc":"yes",
               "scan_on_start":"yes",
               "file_limit":{
                  "enabled":"yes",
                  "entries":100000
               },
               "diff":{
                  "disk_quota":{
                     "enabled":"yes",
                     "limit":1048576
                  },
                  "file_size":{
                     "enabled":"yes",
                     "limit":51200
                  }
               },
               "directories":[
                  {
                     "opts":[
                        "check_md5sum",
                        "check_sha1sum",
                        "check_perm",
                        "check_size",
                        "check_owner",
                        "check_group",
                        "check_mtime",
                        "check_inode",
                        "check_sha256sum"
                     ],
                     "dir":"/tmp/testing",
                     "recursion_level":256,
                     "diff_size_limit":51200
                  }
               ],
               "whodata":{
                  "restart_audit":"yes",
                  "startup_healthcheck":"yes"
               },
               "allow_remote_prefilter_cmd":"no",
               "synchronization":{
                  "enabled":"yes",
                  "max_interval":3600,
                  "interval":300,
                  "response_timeout":30,
                  "queue_size":16384,
                  "max_eps":10
               },
               "max_eps":100,
               "process_priority":10,
               "database":"disk"
            }
         }
      ],
      "total_affected_items":1,
      "total_failed_items":0,
      "failed_items":[
         
      ]
   },
   "message":"Active configuration was successfully read",
   "error":0
}
```

We can see that no `alert_new_files` configuration is returned.
