### ISSUE TITLE
Possible SCA rule identification error: 4557 - cis_rhel7_linux.yml.disabled

### ISSUE THREAD

**Issue by chzgustavo** [wazuh/wazuh#17707]
|Wazuh version| Component | Action type |
|---| --- | --- |
| - | Rules |/Error |

## Description

A community request has been received to correct a possible error in rule ID: 4557

Community request:

```console
I found an error in the SCA rule id: 4557 - cis_rhel7_linux.yml.disabled
Could someone tell the wazuh developers to correct this error in the repository, so that it works correctly?
The correct one is "package"
nano /var/ossec/ruleset/sca/cis_rhel7_linux.yml.disabled
```

```
  # 2.2.3 Ensure Avahi Server is not installed (Automated)
  - id: 4557
    title: " Ensure Avahi Server is not installed"
    description: "Avahi is a free zeroconf implementation, including a system for multicast DNS/DNS-SD service discovery. Avahi allows programs to publish and discover services and hosts running on a local network with no specific confi>
    rationale: "Automatic discovery of network services is not normally required for system functionality. It is recommended to remove this package to reduce the potential attack surface."
    remediation: "Run the following commands to stop, mask and remove avahi-autoipd and avahi: # systemctl stop avahi-daemon.socket avahi-daemon.service; # yum remove avahi-autoipd avahi"
    compliance:
      - cis: ["2.2.3"]
      - cis_csc: ["9.2"]
      - pci_dss: ["2.2.2"]
      - nist_800_53: ["CM.1"]
      - tsc: ["CC5.2"]
    condition: all
    rules:
      - "c:rpm -q avahi-autoipd -> r:package avahi-autoipd is not installed"
      - "c:rpm -q avahi -> r:pacakge avahi is not installed"
```

     
![image](https://github.com/wazuh/wazuh/assets/22420006/175bdf0d-ef48-42f5-a61f-d2c9b16e496f)

## Note
:information_source: [slack-community](https://wazuh.slack.com/archives/C0A933R8E/p1687574645291099)
