### ISSUE TITLE
Check Wazuh compatibility with new version Debian 12

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#17767]
# Description
Hello team, this issue is to check the full compatibility of Wazuh on the new found version of Debian 12 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/17387
Issue related with some problems found: https://github.com/wazuh/wazuh/issues/17458

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Agent and server (if possible) instalations.
- [x] WPK installation / upgrade / uninstall / upgrade.
- [x] Enrollment and connectivity with the manager.
- [x] SCA: Policy support.
- [x] FIM: Real-time and who-data engines (if available).
- [x] Vulnerability Detector: Vulnerability support.
- [x] Syscollector: Complete inventory.
- [x] Active Response: port blocking.
- [x] Log capture (Eventchannel for Windows and ULS for macOS).

**Comment by lesleyxyz** [comment]
+1 need vulnerability scanner.
oval url: `https://www.debian.org/security/oval/oval-definitions-bookworm.xml`

**Comment by Sysadminfromhell** [comment]
+1, when the support will be implemented?

**Comment by jotacarma90** [comment]
# Testing

###   :green_circle:  Agent and server, (enrollment and connectivity with the manager)
- Agent:
```
2023/09/22 09:29:33 wazuh-agentd: INFO: Version detected -> Linux |debian12 |6.1.0-9-amd64 |#1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) |x86_64 [Debian GNU/Linux|debian: 12 (bookworm)] - Wazuh v4.5.2
2023/09/22 09:29:33 wazuh-agentd: INFO: Started (pid: 3075).
2023/09/22 09:29:33 wazuh-agentd: INFO: Using AES as encryption method.
2023/09/22 09:29:33 wazuh-agentd: INFO: Trying to connect to server ([192.168.56.18]:1514/tcp).
2023/09/22 09:29:33 wazuh-agentd: INFO: (4102): Connected to the server ([192.168.56.18]:1514/tcp).
```
- Manager:
```
2023/09/22 09:29:07 wazuh-authd: INFO: New connection from 192.168.56.17
2023/09/22 09:29:07 wazuh-authd: INFO: Received request for a new agent (debian12) from: 192.168.56.17
2023/09/22 09:29:07 wazuh-authd: INFO: Agent key generated for 'debian12' (requested by any)
```


###  :green_circle: FIM: Real-time

<details><summary>Realtime alerts</summary>

```
** Alert 1695638159.4232: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Sep 25 07:35:59 (debian12) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/testrealtime/file1' added
Mode: realtime

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Mon Sep 25 07:35:59 2023
 - Inode: 524292
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1695638184.4913: - ossec,syscheck,syscheck_entry_modified,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Sep 25 07:36:24 (debian12) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/testrealtime/file1' modified
Mode: realtime
Changed attributes: mtime
Old modification time was: '1695638159', now it is '1695638184'

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Mon Sep 25 07:36:24 2023
 - Inode: 524292
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1695638188.5692: - ossec,syscheck,syscheck_entry_deleted,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Sep 25 07:36:28 (debian12) any->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File '/testrealtime/file1' deleted
Mode: realtime

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Mon Sep 25 07:36:24 2023
 - Inode: 524292
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

</details>

<details><summary>Whodata alerts</summary>

```
** Alert 1695638678.14964: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Sep 25 07:44:38 (debian12) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/testwhodata/file1' added
Mode: whodata

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Mon Sep 25 07:44:38 2023
 - Inode: 524292
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - (Audit) User name: root
 - (Audit) Audit name: vagrant
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 3039
 - (Audit) Process name: /usr/bin/touch
 - (Audit) Process cwd: /home/vagrant
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 2500
 - (Audit) Parent process cwd: /home/vagrant

** Alert 1695638683.15994: - ossec,syscheck,syscheck_entry_modified,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Sep 25 07:44:43 (debian12) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/testwhodata/file1' modified
Mode: whodata
Changed attributes: mtime
Old modification time was: '1695638678', now it is '1695638683'

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Mon Sep 25 07:44:43 2023
 - Inode: 524292
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - (Audit) User name: root
 - (Audit) Audit name: vagrant
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 3040
 - (Audit) Process name: /usr/bin/touch
 - (Audit) Process cwd: /home/vagrant
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 2500
 - (Audit) Parent process cwd: /home/vagrant

** Alert 1695638686.17122: - ossec,syscheck,syscheck_entry_deleted,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Sep 25 07:44:46 (debian12) any->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File '/testwhodata/file1' deleted
Mode: whodata

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Mon Sep 25 07:44:43 2023
 - Inode: 524292
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - (Audit) User name: root
 - (Audit) Audit name: vagrant
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 3042
 - (Audit) Process name: /usr/bin/rm
 - (Audit) Process cwd: /home/vagrant
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 2500
 - (Audit) Parent process cwd: /home/vagrant
```

</details>

### :green_circle: Syscollector
- Agent:
```
2023/09/25 07:44:14 wazuh-modulesd:syscollector: INFO: Module started.
2023/09/25 07:44:14 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2023/09/25 07:44:14 wazuh-modulesd:syscollector: INFO: Evaluation finished.
```
- Manager
```
2023/09/25 07:58:56 wazuh-modulesd:syscollector[5681] wm_syscollector.c:99 at wm_sys_log(): INFO: Starting evaluation.
2023/09/25 07:58:58 wazuh-modulesd:syscollector[5681] wm_syscollector.c:99 at wm_sys_log(): INFO: Evaluation finished.
```



###  :green_circle: Active response
```
2023/09/25 08:03:56 wazuh-execd[8571] execd.c:256 at ExecdRun(): DEBUG: Executing command 'active-response/bin/restart-wazuh {"version":1,"origin":{"name":"node01","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":[],"alert":{"timestamp":"2023-09-25T08:03:56.045-0300","rule":{"level":7,"description":"Host-based anomaly detection event (rootcheck).","id":"510","firedtimes":23,"mail":false,"groups":["ossec","rootcheck"],"pci_dss":["10.6.1"],"gdpr":["IV_35.7.d"]},"agent":{"id":"001","name":"debian12","ip":"10.0.2.15"},"manager":{"name":"debian12manager"},"id":"1695639836.92946","full_log":"Trojaned version of file '/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\\.h|proc\\.h|/dev/[^n]|^/bin/.*sh' (Generic).","decoder":{"name":"rootcheck"},"data":{"title":"Trojaned version of file detected.","file":"/bin/diff"},"location":"rootcheck"},"program":"active-response/bin/restart-wazuh"}}'
```

### :green_circle: Log capture (Eventchannel for Windows and ULS for macOS).
- Agent
```
2023/09/25 08:07:42 wazuh-logcollector[13603] read_syslog.c:104 at read_syslog(): DEBUG: Reading syslog message: 'Sep 10 22:12:41 example pvedaemon[6427]: authentication failure;'...
2023/09/25 08:07:42 wazuh-logcollector[13603] read_syslog.c:148 at read_syslog(): DEBUG: Read 1 lines from /test/test.log
```
- Manager
```
** Alert 1695640062.147309: - syslog,proxmox-ve,authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,gdpr_IV_35.7.d,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Sep 25 08:07:42 (debian12) any->/test/test.log
Rule: 87201 (level 6) -> 'Proxmox VE authentication failed.'
Src IP: 192.168.0.1
User: root
Sep 10 22:12:41 example pvedaemon[6427]: authentication failure; rhost=192.168.0.1 user=root@pam msg=Authentication failure
```


### :green_circle: Upgrade using WPK
```
root@debian12manager:/home/vagrant# /var/ossec/bin/agent_upgrade -a 002 -f /home/vagrant/wazuh_agent_v4.5.2_linux_x86_64.wpk 

Upgrading...

Upgraded agents:
	Agent 002 upgraded: Wazuh v4.4.0 -> Wazuh v4.5.2
```
