### ISSUE TITLE
Add an RTR workflow to the Vulnerability Scanner module

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#17952]
|Part of Epic| Branch |
|---|---|
|#14153|[dev-14153-vulndet-refactor](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor)|

## Description

As part of our efforts to improve the quality of our code delivery, we will add workflows (that will run on GitHub Actions), on every PR created that affects the modules related to this epic.

### Modules
The modules that must be tested are the following:
- [vulnerability_scanner](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor/src/wazuh_modules/vulnerability_scanner)
- [content_manager](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor/src/shared_modules/content_manager)
- [indexer_connector](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor/src/shared_modules/indexer_connector)
- [router](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor/src/shared_modules/router)

### Tests performed
The testing process will check for the following:
- Compilation must be successful
- Tests must pass (UTs, component, etc.)
- ~Coverage must be higher than a certain threshold~
- ~Address Sanitizer must pass~
- ~Must be compliant with Doxygen~

> **Note**
The last 3 bullets will be cover in a separated issue in order to facilitate the revision and development

All these tests will be run on two different Linux distributions, one Debian based and another one RHEL based.

> **Note**
This is only possible with [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners) (further investigation needed)

### 
If possible, this workflow will be as generic as possible to reuse them on future developments and to also facilitate the current implementation idea

## DoD

- [x] Create the baseline workflow file
- [x] Test for different scenarios
- [x] CI pass

**Comment by sebasfalcone** [comment]
## Detecting which project to compile
The following workflow will check, based on the strategy matrix which projects need to be compiled (based on file modifications) and run the compilation accordingly

I will improve this approach by generating a more complex matrix which takes into account dependencies between projects

```yaml
on: push
name: CI
jobs:
  diff:
    name: diff
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: # Filter , compilation path
          - ['src.*one.*cpp', /src/one]
          - ['src.*two.*cpp', /src/two]
    steps:
      # Prepare project repository.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # We need to fetch 2 commits to get the diff.
      
      - name: Check for compilation requirement
        run: |
          DIFFS=$(git diff --name-only HEAD HEAD~1)
          if echo $DIFFS | grep -q "${{ matrix.project[0] }}"; then
            echo "COMPILATION_FLAG=true" >> $GITHUB_ENV
          else
            echo "COMPILATION_FLAG=false" >> $GITHUB_ENV
          fi
          
      - name: Build Project
        if: ${{ env.COMPILATION_FLAG == 'true' }}
        run: |
          echo "cd ${{ matrix.project[1] }}"
          echo "mkdir build"
          echo "cd build"
          echo "cmake .."
          echo "make"
```
