### ISSUE TITLE
Wazuh installation script does not update internal users file

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#18021]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.5 | Installation | AIO | Packages | Ubuntu 22 |

### Description

Wazuh install script https://packages.wazuh.com/4.4/wazuh-install.sh for all in one installation does not update the internal_users regarding the new generated password.

### Steps to reproduce
- Install a AIO following the quickstart command: `curl -sO https://packages.wazuh.com/4.4/wazuh-install.sh && sudo bash ./wazuh-install.sh -a`
- Check the passwords for the environment users: `sudo tar -O -xvf wazuh-install-files.tar wazuh-install-files/wazuh-passwords.txt`
- Check that the `/etc/wazuh-indexer/opensearch-security/internal_users.yml` contains the default value:

```
config_file_indexer_roles_internal_users="---
# This is the internal user database
# The hash value is a bcrypt hash and can be generated with plugin/tools/hash.sh

_meta:
  type: \"internalusers\"
  config_version: 2

# Define your internal users here

## Demo users

admin:
  hash: \"\$2a\$12\$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG\"
  reserved: true
  backend_roles:
  - \"admin\"
  description: \"Demo admin user\"

kibanaserver:
  hash: \"\$2a\$12\$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H.\"
  reserved: true
  description: \"Demo kibanaserver user\"

kibanaro:
  hash: \"\$2a\$12\$JJSXNfTowz7Uu5ttXfeYpeYE0arACvcwlPBStB1F.MI7f0U9Z4DGC\"
  reserved: false
  backend_roles:
  - \"kibanauser\"
  - \"readall\"
  attributes:
    attribute1: \"value1\"
    attribute2: \"value2\"
    attribute3: \"value3\"
  description: \"Demo kibanaro user\"
```
