### ISSUE TITLE
Release 4.5.0 - Alpha 1 - E2E UX tests - Deployment on Kubernetes

### ISSUE THREAD

**Issue by hector222arroyo** [wazuh/wazuh#18084]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |      Deployment on Kubernetes                                      |
| **Category**            |        Installation                                    |
| **Deployment option**   |         Deployment on Kubernetes                                   |
| **Main release issue**  |               #18058                              |
| **Release candidate #** |           #18057                                  |

## Environment

| | | | |
|-|-|-|-|
| **Component** | **Type** | **OS** | **Installation** |
| Wazuh dashboard | Single node | Debian 12 | [Deployment on Kubernetes](https://documentation.wazuh.com/current/deployment-options/deploying-with-kubernetes/index.html) |
| Wazuh indexer | Single node | Debian 12 | [Deployment on Kubernetes](https://documentation.wazuh.com/current/deployment-options/deploying-with-kubernetes/index.html) |
| Wazuh server | Single node | Debian 12 | [Deployment on Kubernetes](https://documentation.wazuh.com/current/deployment-options/deploying-with-kubernetes/index.html) |
| Wazuh agent | | Debian 12 | [Wazuh WUI one-liner deploy](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/index.html) |

## Test description
- Test the installation guide in detail
- Test changing the default passwords

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

## Conclusions

All tests have been executed and the results can be found [here]().

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|🟡 | Test single node installation with wazuh indexer, wazuh manager and wazuh dashboard on kubernetes | versioning | the latest version of composer (2.x) uses `docker composer` instead of `docker-composer` as command. https://github.com/wazuh/wazuh-docker/issues/916 |
| 🟢  |      Test enrollment agent.     |           |                |
| 🔴 |      Test changing the default passwords       | No documentation to follow | [wazuh-documentation/issues/6279](https://github.com/wazuh/wazuh-documentation/issues/6279) |

All tests have passed and the fails have been reported or justified. Therefore, I conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @wazuh/cicd 
- [ ] @davidjiglesias

**Comment by hector222arroyo** [comment]
# Environment installation 🟢

<Details>
<summary>Hosts information</summary>

All the hosts used for this test are like this one:

```yaml
root@debian:/home/hector# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

</Details>



<Details>
<summary>Kubernetes information ([Using k3s](https://docs.k3s.io/installation/configuration))</summary>

All the hosts used for this test are like this one:

```yaml
root@debian:/home/hector# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
root@debian:/home/hector# kubectl config get-contexts
CURRENT   NAME      CLUSTER   AUTHINFO   NAMESPACE
root@debian:/home/hector# kubectl get nodes
NAME     STATUS   ROLES                  AGE     VERSION
debian   Ready    control-plane,master   6m39s   v1.27.3+k3s1
root@debian:/home/hector# kubectl get ns
NAME              STATUS   AGE
default           Active   6m44s
kube-system       Active   6m43s
kube-public       Active   6m43s
kube-node-lease   Active   6m43s
```

</Details>
