### ISSUE TITLE
Add an API option to set whether the user can enable allowing agents with higher version

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#18139]
|Parent issue|Source issue|Related PR|
|---|---|---|
|#18138|#11011|#15661|

The issue above asks for the agent version accepting filter to be optional. A new setting will enable or disable the capability to accept connections from agents with a higher version than the manager.

In turn, we need to be able to regulate whether this setting can be changed via the API.

## Setting

This is a suggestion:

```yaml
upload_configuration:
   agents:
      allow_higher_versions:
         allow: yes
         exceptions: []
```
