### ISSUE TITLE
Wazuh server breaks when changing admin password

### ISSUE THREAD

**Issue by RobertBrown3** [wazuh/wazuh#18320]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.4.5|            wazuh-manager(?)|      Single Node    |         Docker Compose        |            Ubuntu V22.04

I am running a wazuh single- node server in Docker. It was running without problems once I followed all the installation
instructions provided at

[Docker Install](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html)

The version of all the containers I am running is 4.4.5.

It is pretty clear that an application like this one shuld not depend on an easily guessed password like "SecretPassword", so I decided to set the admin password to a 30- character password that no one could possibly guess. To properly set this password, I shut down the server and followed the instructions provided at 

[Change Password](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#change-pwd-existing-usr)

I followed the instructions there to the letter.

Unfortunately, when I restarted Wazuh, two things happened: 

1. The single-node-wazuh.manager-1 container goes into a weird loop where it is starting processes, failing to find some file(s), then shuts down the processes it starts. A sample of this behavior is in the attached manager.txt file.
[manager.txt](https://github.com/wazuh/wazuh/files/12303890/manager.txt)

2. The second thing that happened is that failures occur when I log in. The Wazuh page accepts the new password, but then it has failures when it does its checks. The overall errors it displays are:

`    [API connection] Wazuh API is down
	[Alerts index pattern] No template found for the selected index-pattern title [wazuh-alerts-*]
	
`
Detailed info on the Wazuh API Connection failure is below:

` INFO: Current API id [1513629884013]

INFO: Checking current API id [1513629884013]...
ERROR: Wazuh API is down
`

Detailed info on the index pattern failure is below:

` 
INFO: Index pattern id in cookie: yes [wazuh-alerts-*]

INFO: Getting list of valid index patterns...
INFO: Valid index patterns found: 1
INFO: Found default index pattern with title [wazuh-alerts-*]: yes
    INFO: Checking the app default pattern exists: id [wazuh-alerts-*]...
    INFO: Default pattern with id [wazuh-alerts-*] exists: yes
    ACTION: Default pattern id [wazuh-alerts-*] set as default index pattern
    INFO: Checking the index pattern id [wazuh-alerts-*] exists...
    INFO: Index pattern id exists [wazuh-alerts-*]: yes
    INFO: Index pattern id in cookie: yes [wazuh-alerts-*]
    INFO: Checking if the index pattern id [wazuh-alerts-*] exists...
    INFO: Index pattern id [wazuh-alerts-*] found: yes title [wazuh-alerts-*]
    INFO: Checking if exists a template compatible with the index pattern title [wazuh-alerts-*]
    INFO: Template found for the selected index-pattern title [wazuh-alerts-*]: no
    ERROR: No template found for the selected index-pattern title [wazuh-alerts-*]
    INFO: Index pattern id in cookie: [wazuh-alerts-*]
    INFO: Getting index pattern data [wazuh-alerts-*]...
    INFO: Index pattern data found: [yes]
    INFO: Refreshing index pattern fields: title [wazuh-alerts-*], id [wazuh-alerts-*]...
    ACTION: Refreshed index pattern fields: title [wazuh-alerts-*], id [wazuh-alerts-*]
`
Apparently, changing the password for admin breaks the Wazuh server. Is this a bug?

Can someone fix this, or tell me how to fix it?

**Comment by datdamnzotz** [comment]
Ran into the same thing, full instructions here.
[Update ](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#change-pwd-existing-usr)
In a nushell
docker-compose down
docker run --rm -ti wazuh/wazuh-indexer:4.5.0 bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh
get your hash.
edit config/wazuh_indexer/internal_users.yml with the hash.
and update both wazuh.manager and wazuh.dashboard in your docker-compose file with the plain text password (not the hash)

**Comment by datdamnzotz** [comment]
> datdamnzotz:
> 
> As stated in my initial post: I followed the password change instructions to the letter. This included copying the hash to the internal_users.yml file and putting the _plain text password_ into the docker_compose.yml file. Doing so consistently broke Wazuh in the manner I previously described.
> 
> As it turns out, I determined what was causing the problem. It is definitely a bug in Wazuh, most likely somewhere in the interaction between the Manager and the Indexer. I believe that this bug deserves to be described in another issue, though I will refer to this one.

My issue was I didn't update the wazuh.manager AND wazuh.dashboard passwords in the docker-compose file.  Once I did that it worked just fine.

**Comment by Zalaxx** [comment]
So, I had this issue when trying Wazuh on my VM before using it.
I tried with multiple different password, and found that having a password with a `&` in it is probably the culprit.

More specifically, modifying the env var in the docker-compose.yml to have the plaintext password (with the & in it), will acuse the manager to start and throw this error:
```
wazuh.manager_1    | 2024/06/04 13:55:11 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_ubuntu20-04.yml'
wazuh.manager_1    | [services.d] done.
wazuh.manager_1    | Exiting: error loading config file: yaml: line 17: did not find expected key
```
I also do not think that passwords with `&` are invalid per se, it is just causing the manager to not be able to start, thus making the whole application unusable. I at some point launched with a password containing a & 


I initially tried with the password `vw73-md}Nj!&wtV`, it didn't work. Then with `whatever`, it worked. Because of https://github.com/wazuh/wazuh/issues/18435, I tried `frosty!obvious!boogeyman!widen!fretful!projector!easing!dreamboat`, it also worked. Then, `frosty!obvious!boogeyman!widen!fretful!projector!easing!dreamboat&` (notice the & at the end), which failed. 


I have no idea why this specific file has an issue, because it has apparently nothing to do with the root cause. I'm probably missing something here.
Start of the file: (line 17 is the description)
```yaml
root@wazuh:/# cat /var/ossec/ruleset/sca/cis_ubuntu20-04.yml
# Security Configuration Assessment
# CIS Checks for Ubuntu Linux 20.04 LTS
# Copyright (C) 2023, Wazuh Inc.
#
# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation
#
# Based on:
# Center for Internet Security Ubuntu Linux 20.04 LTS Benchmark v2.0.0 - 05-30-2023

policy:
  id: "cis_ubuntu20-04"
  file: "cis_ubuntu20-04.yml"
  name: "CIS Ubuntu Linux 20.04 LTS Benchmark v2.0.0"
  description: "This document provides prescriptive guidance for establishing a secure configuration posture for Ubuntu Linux 20.04 LTS."
  references:
    - https://www.cisecurity.org/cis-benchmarks/
```


Can someone try a password with and without `&` to confirm that this is the issue?
