### ISSUE TITLE
Issue running assistant installer in Raspberry pi 3B+ Ubuntu 64 Bit

### ISSUE THREAD

**Issue by wirytiox** [wazuh/wazuh#18644]
|Version 4.5|Component|in a single node|Assistant|Raspberry Pi 3B+|

Entire install | Ubuntu 23.04 64-bit arm |
I tried running the assistant script with this command  `sudo bash wazuh-install.sh --generate-config-files --ignore-check`
And this parameters:
```
nodes:
  indexer:
    - name: node-1
      ip: 127.0.0.1  # Use the Raspberry Pi's IP address or localhost
  server:
    - name: wazuh-1
      ip: 127.0.0.1  # Use the Raspberry Pi's IP address or localhost
  dashboard:
    - name: dashboard
      ip: 127.0.0.1  # Use the Raspberry Pi's IP address or localhost
```
And got this error:
```
27/08/2023 07:53:56 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.1
27/08/2023 07:53:56 INFO: Verbose logging redirected to /var/log/wazuh-install.log
27/08/2023 07:54:30 ERROR: Uncompatible system. This script must be run on a 64-bit system.
```
I am new to this, sorry for any mistake made in clarity.
