### ISSUE TITLE
Engine - Improve the engine parser stage

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#18806]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

The main goal of this enhancement is to provide a clearer and more intuitive syntax for the decoder parser stage in the Engine. This change aims to make the configuration more readable and consistent with other decoders.

## Description
The current decoder parser stage in the Engine uses a syntax that can be confusing. Specifically, the `logpar` parser uses the field on the left as the one to be parsed. This is contrary to other decoders stages where the field on the left is the target of the mapping.

**Current Syntax:**
```yaml
parse:
  logpar:
    - event.original: '[<timestamp/APACHE_ERROR>] [<_module>:<log.level>] [pid <process.pid>] <message>'
    - event.original: '[<timestamp/APACHE_ERROROR>] [<_module>:<log.level>] [pid <process.pid>:tid <process.thread.id>] [client <source.address>] <message>'
```

## Proposal:

To avoid confusion and simplify the syntax, we propose a change in the parser stage syntax. Since `logpar` is the only parser we have, the new syntax will directly specify the field to be parsed followed by the parsing patterns.

**Proposed Syntax:**
```yaml
parse|event.original:
  - '[<timestamp/APACHE_ERROR>] [<_module>:<log.level>] [pid <process.pid>] <message>'
  - '[<timestamp/APACHE_ERROR>] [<_module>:<log.level>] [pid <process.pid>:tid <process.thread.id>] [client <source.address>] <message>'
```

## Acceptance Criteria
- [x]  The proposed syntax change has been implemented.
- [x]  The asset decoder parser now follows the new syntax.
- [x]  Documentation has been updated to reflect the changes in syntax.
