### ISSUE TITLE
Release 4.6.0 - Alpha 1 - E2E UX tests - Wazuh Indexer ISM policies

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#18842]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.6.0-alpha1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documentation for the stage under test.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, or Docker) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Communicate these to QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/indexer team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Step by step](https://documentation-dev.wazuh.com/v4.6.0-alpha1/installation-guide/wazuh-indexer/step-by-step.html) | Multi node | Debian 10 x86_64 |
| Server | [Step by step](https://documentation-dev.wazuh.com/v4.6.0-alpha1/installation-guide/wazuh-server/step-by-step.html) | Single node | Debian 10 x86_64 |
| Dashboard | [Step by step](https://documentation-dev.wazuh.com/v4.6.0-alpha1/installation-guide/wazuh-dashboard/step-by-step.html) | - | Debian 10 x86_64 |
| Agent | [Installing Wazuh agents](https://documentation-dev.wazuh.com/v4.6.0-alpha1/installation-guide/wazuh-agent/index.html) | - | Debian 10 x86_64 |

## Test description

Test ISM policies in Wazuh Indexer (especifically related to retention policies, but rollover + alias are nice as well). https://opensearch.org/docs/latest/im-plugin/ism/index/

## Known issues

- https://github.com/wazuh/wazuh-packages/issues/1515

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below, removing current examples:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟢 | Install Indexer step by step (Multi node) | | https://github.com/wazuh/wazuh/issues/18842#issuecomment-1710760562|
| 🟢 | Install Server step by step (Single node) | | https://github.com/wazuh/wazuh/issues/18842#issuecomment-1713128171|
| 🟢 | Install Dashboard step by step  | | https://github.com/wazuh/wazuh/issues/18842#issuecomment-1713285846|
| 🟢 | Deploying Wazuh agent on Debian 10 end point  | | https://github.com/wazuh/wazuh/issues/18842#issuecomment-1714374480|
| 🟢 | Create ISM Policy (Retention Policy)  | | https://github.com/wazuh/wazuh/issues/18842#issuecomment-1714565885|

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
The testing guide is clear, although I see that it's the same guide that users have when interacting with Wazuh. I believe the experience could be improved by adding some key notes. For example, when I was installing the Dashboard, I had to modify the file /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml because it was a distributed deployment. However, I couldn't access the file. I thought it was a bad installation and reinstalled it, but I still encountered the same issue. It turned out that I needed to have all the Wazuh components active (I had turned off the indexer nodes because they were consuming too many machine resources and I wasn't using them). Therefore, a small note saying "all components must be active from this step onward" would be quite useful, in my opinion."

- Did you face any challenges not covered by the guideline?
No

- Suggestions for improvement:
In my particular case, ISM policies are something I had never worked with before. Based on the documentation, I was able to understand a bit about how they work, but it would be wonderful if there were training sessions for Wazuh members (could be in video format) covering many of the software's functionalities. A bit more focus on training new staff would make us more productive :)

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [x] @davidjiglesias
- [x] @wazuh/indexer

**Comment by Leoquicenoz** [comment]
# Environment installation 🟢 

Each component was installed using the `Step by step` guide.

## Wazuh indexer

<details>
<summary>Certificates creation :green_circle: </summary>

1. Download the `wazuh-certs-tool.sh` script and the `wazuh-config.yml` configuration file:

```shellsession
root@debian10:/home/vagrant# curl -sO https://packages-dev.wazuh.com/4.6/wazuh-certs-tool.sh
root@debian10:/home/vagrant# curl -sO https://packages-dev.wazuh.com/4.6/config.yml
```
2. Edit the `config.yml`:

```yml
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: 192.168.68.122
    - name: node-2
      ip: 192.168.68.121
    #- name: node-3
    #  ip: "<indexer-node-ip>"

  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  server:
    - name: wazuh-1
      ip: 192.168.68.123
    #  node_type: master
    #- name: wazuh-2
    #  ip: "<wazuh-manager-ip>"
    #  node_type: worker
    #- name: wazuh-3
    #  ip: "<wazuh-manager-ip>"
    #  node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: 192.168.68.124
```

3. Run the `wazuh-certs-tool.sh`:

```shellsession
root@debian10:/home/vagrant#  bash ./wazuh-certs-tool.sh -A
07/09/2023 16:20:19 INFO: Admin certificates created.
07/09/2023 16:20:19 INFO: Wazuh indexer certificates created.
07/09/2023 16:20:19 INFO: Wazuh server certificates created.
07/09/2023 16:20:19 INFO: Wazuh dashboard certificates created.
```

4. Compress the files:

```shellsession
root@debian10:/home/vagrant# tar -cvf ./wazuh-certificates.tar -C ./wazuh-certificates/ .
./
./node-2.pem
./wazuh-1.pem
./node-1-key.pem
./dashboard.pem
./wazuh-1-key.pem
./dashboard-key.pem
./node-2-key.pem
./root-ca.key
./root-ca.pem
./admin-key.pem
./admin.pem
./node-1.pem
root@debian10:/home/vagrant# rm -rf ./wazuh-certificates

```
5. Copy the files to Wazuh Indexer, Wazuh Server and Wazuh Dashboard nodes:

```shellsession
scp wazuh-certificates.tar node-1
scp wazuh-certificates.tar node-2
scp wazuh-certificates.tar server
scp wazuh-certificates.tar dashboard
```
</details>

<details>
<summary>Nodes installation :green_circle:</summary>

1. Install the packages if missing:

    Not missing

2. Add the Wazuh repository (as root)

```shellsession
root@debian10:/home/vagrant# curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
gpg: keyring '/usr/share/keyrings/wazuh.gpg' created
gpg: directory '/root/.gnupg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 96B3EE5F29111145: public key "Wazuh.com (Wazuh Signing Key) <support@wazuh.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

3. Add the repository:

```shellsession
root@debian10:/home/vagrant# echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main
 ```

4. Update the packages information and install the Indexer

```shellsession
root@debian10:/home/vagrant# apt-get update
Get:1 http://security.debian.org/debian-security buster/updates InRelease [34.8 kB]
Hit:2 http://deb.debian.org/debian buster InRelease                                                         
Get:3 https://packages.wazuh.com/4.x/apt stable InRelease [17.3 kB]                                         
Hit:4 http://deb.debian.org/debian buster-updates InRelease
Get:5 http://security.debian.org/debian-security buster/updates/main Sources [346 kB]
Get:6 https://packages.wazuh.com/4.x/apt stable/main amd64 Packages [32.1 kB]
Get:7 http://security.debian.org/debian-security buster/updates/main amd64 Packages [550 kB]
Fetched 980 kB in 1s (962 kB/s)
Reading package lists... Done

root@debian10:/home/vagrant# apt-get -y install wazuh-indexer
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  wazuh-indexer
0 upgraded, 1 newly installed, 0 to remove and 56 not upgraded.
Need to get 683 MB of archives.
After this operation, 971 MB of additional disk space will be used.
Get:1 https://packages.wazuh.com/4.x/apt stable/main amd64 wazuh-indexer amd64 4.5.2-1 [683 MB]
Fetched 683 MB in 18s (38.8 MB/s)                                                                                                                                                                          
apt-listchanges: Can't set locale; make sure $LC_* and $LANG are correct!
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_TIME = "es_CO.UTF-8",
	LC_MONETARY = "es_CO.UTF-8",
	LC_ADDRESS = "es_CO.UTF-8",
	LC_TELEPHONE = "es_CO.UTF-8",
	LC_NAME = "es_CO.UTF-8",
	LC_MEASUREMENT = "es_CO.UTF-8",
	LC_IDENTIFICATION = "es_CO.UTF-8",
	LC_NUMERIC = "es_CO.UTF-8",
	LC_PAPER = "es_CO.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
locale: Cannot set LC_ALL to default locale: No such file or directory
Selecting previously unselected package wazuh-indexer.
(Reading database ... 65397 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_4.5.2-1_amd64.deb ...
Creating wazuh-indexer group... OK
Creating wazuh-indexer user... OK
Unpacking wazuh-indexer (4.5.2-1) ...
Setting up wazuh-indexer (4.5.2-1) ...
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
Processing triggers for systemd (241-7~deb10u8) ...
```
</details>

<details>
<summary>Configuring the Wazuh Indexer :green_circle: </summary>

#### Node `node-1`

```yml
network.host: "192.168.68.122"
node.name: "node-1"
cluster.initial_master_nodes:
- "node-1"
- "node-2"
#- "node-3"
cluster.name: "wazuh-cluster"
discovery.seed_hosts:
  - 192.168.68.122
  - 192.168.68.121
#  - "node-3-ip"
node.max_local_storage_nodes: "3"
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer

plugins.security.ssl.http.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.http.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.transport.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.transport.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.http.enabled: true
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false

plugins.security.authcz.admin_dn:
- "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn:
- "CN=node-1,OU=Wazuh,O=Wazuh,L=California,C=US"
- "CN=node-2,OU=Wazuh,O=Wazuh,L=California,C=US"
#- "CN=node-3,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.restapi.roles_enabled:
- "all_access"
- "security_rest_api_access"

plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".plugins-ml-model", ".plugins-ml-task", ".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opensearch-notifications-*", ".opensearch-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]

### Option to allow Filebeat-oss 7.10.2 to work ###
compatibility.override_main_response_version: true

```

#### Node `indexer-02`

```yml
network.host: "192.168.68.121"
node.name: "node-2"
cluster.initial_master_nodes:
- "node-1"
- "node-2"
#- "node-3"
cluster.name: "wazuh-cluster"
discovery.seed_hosts:
  - 192.168.68.122
  - 192.168.68.121
#  - "node-3-ip"
node.max_local_storage_nodes: "3"
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer

plugins.security.ssl.http.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.http.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.transport.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.transport.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.http.enabled: true
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false

plugins.security.authcz.admin_dn:
- "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn:
- "CN=node-1,OU=Wazuh,O=Wazuh,L=California,C=US"
- "CN=node-2,OU=Wazuh,O=Wazuh,L=California,C=US"
#- "CN=node-3,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.restapi.roles_enabled:
- "all_access"
- "security_rest_api_access"

plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".plugins-ml-model", ".plugins-ml-task", ".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opensearch-notifications-*", ".opensearch-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]

### Option to allow Filebeat-oss 7.10.2 to work ###
compatibility.override_main_response_version: true
```

</details>











## Wazuh server

```shellsession
[root@ip-172-31-29-132 ec2-user]# bash wazuh-install.sh --wazuh-server wazuh-server
24/06/2022 12:44:53 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.5
24/06/2022 12:44:53 INFO: Verbose logging redirected to /var/log/wazuh-install.log
24/06/2022 12:44:58 INFO: Wazuh repository added.
24/06/2022 12:44:58 INFO: --- Wazuh server ---
24/06/2022 12:44:58 INFO: Starting the Wazuh manager installation.
24/06/2022 12:45:23 INFO: Wazuh manager installation finished.
24/06/2022 12:45:23 INFO: Starting service wazuh-manager.
24/06/2022 12:45:38 INFO: wazuh-manager service started.
24/06/2022 12:45:38 INFO: Starting Filebeat installation.
24/06/2022 12:45:51 INFO: Filebeat installation finished.
24/06/2022 12:45:51 INFO: Filebeat post-install configuration finished.
24/06/2022 12:45:55 INFO: Starting service filebeat.
24/06/2022 12:45:55 INFO: filebeat service started.
24/06/2022 12:45:55 INFO: Installation finished.
[root@ip-172-31-29-132 ec2-user]# 

[root@ip-172-31-29-132 ec2-user]# systemctl status wazuh-manager
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2022-06-24 12:45:38 UTC; 48s ago
   CGroup: /system.slice/wazuh-manager.service
           ├─1388 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─1431 /var/ossec/bin/wazuh-authd
           ├─1448 /var/ossec/bin/wazuh-db
           ├─1460 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─1463 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─1478 /var/ossec/bin/wazuh-execd
           ├─1493 /var/ossec/bin/wazuh-analysisd
           ├─1537 /var/ossec/bin/wazuh-syscheckd
           ├─1553 /var/ossec/bin/wazuh-remoted
           ├─1586 /var/ossec/bin/wazuh-logcollector
           ├─1608 /var/ossec/bin/wazuh-monitord
           └─1631 /var/ossec/bin/wazuh-modulesd

Jun 24 12:45:29 ip-172-31-29-132.ec2.internal env[1332]: Started wazuh-db...
Jun 24 12:45:30 ip-172-31-29-132.ec2.internal env[1332]: Started wazuh-execd...
Jun 24 12:45:31 ip-172-31-29-132.ec2.internal env[1332]: Started wazuh-analysisd...
Jun 24 12:45:32 ip-172-31-29-132.ec2.internal env[1332]: Started wazuh-syscheckd...
Jun 24 12:45:33 ip-172-31-29-132.ec2.internal env[1332]: Started wazuh-remoted...
Jun 24 12:45:34 ip-172-31-29-132.ec2.internal env[1332]: Started wazuh-logcollector...
Jun 24 12:45:35 ip-172-31-29-132.ec2.internal env[1332]: Started wazuh-monitord...
Jun 24 12:45:36 ip-172-31-29-132.ec2.internal env[1332]: Started wazuh-modulesd...
Jun 24 12:45:38 ip-172-31-29-132.ec2.internal env[1332]: Completed.
Jun 24 12:45:38 ip-172-31-29-132.ec2.internal systemd[1]: Started Wazuh manager.
[root@ip-172-31-29-132 ec2-user]# 
```

## Wazuh dashboard

```shellsession
[root@ip-172-31-25-239 ec2-user]# bash wazuh-install.sh --wazuh-dashboard wazuh-dashboard
27/06/2022 11:41:58 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.5
27/06/2022 11:41:58 INFO: Verbose logging redirected to /var/log/wazuh-install.log
27/06/2022 11:42:03 INFO: Wazuh repository added.
27/06/2022 11:42:03 INFO: --- Wazuh dashboard ----
27/06/2022 11:42:03 INFO: Starting Wazuh dashboard installation.
27/06/2022 11:42:52 INFO: Wazuh dashboard installation finished.
27/06/2022 11:42:52 INFO: Wazuh dashboard post-install configuration finished.
27/06/2022 11:42:56 INFO: Starting service wazuh-dashboard.
27/06/2022 11:42:56 INFO: wazuh-dashboard service started.
27/06/2022 11:42:56 INFO: Initializing Wazuh dashboard web application.
27/06/2022 11:43:07 INFO: Wazuh dashboard web application initialized.
27/06/2022 11:43:07 INFO: --- Summary ---
27/06/2022 11:43:07 INFO: You can access the web interface https://172.31.25.239
    User: admin
    Password: E?Q?T+tMocVfiEmu4U.bJP7O65KkCvjW
27/06/2022 11:43:07 INFO: Installation finished.
[root@ip-172-31-25-239 ec2-user]# 

```
