### ISSUE TITLE
Failure when attempting to create an SCA policy with Windows Server 2016

### ISSUE THREAD

**Issue by javiersanchz** [wazuh/wazuh#18981]
## Description 

As mentioned in issue [18833](https://github.com/wazuh/wazuh/issues/18833#issuecomment-1714394298) ,it seems that the policy of searching for the `custom_config` file in `C:\Users\Administrator\Desktop\custom_config` is failing, even though it is located in the mentioned path.
![image](https://github.com/wazuh/wazuh/assets/96108386/1b9ae9fe-9fb1-4eba-b7e2-b473b935a2f3)

Despite being on the route:

![image](https://github.com/wazuh/wazuh/assets/96108386/ae84aba3-2bbe-4e60-bee1-a2f48ec4be5d)

I created a new agent group through the UI called `windows_agents` and added the agent:

![image](https://github.com/wazuh/wazuh/assets/96108386/f62a3349-f6e3-4d6f-bccf-f8a4497800c6)

I created the following policy /`var/ossec/etc/shared/windows_agents/shared_custom_policy.yml` in the Wazuh manager:

```
policy:
  id: "shared_custom_win_policy"
  file: "shared_custom_win_policy.yml"
  name: "Shared custom policy for SCA test."
  description: "Review whether SCA is working as expected" 

checks:
  - id: 20021
    title: "File has the expected configuration"
    description: "Ensure the file contains the expected configuration"
    condition: all 
    rules:
      - 'f:C:\Users\Administrator\Desktop\custom_config'
```
I added the following configuration to the centralized configuration of the `windows_agents` group (`/var/ossec/etc/shared/windows_agents/agent.conf`)

```
<agent_config>
  <!-- Shared agent configuration here -->
    <sca>
      <policies>
        <policy>shared/shared_custom_policy.yml</policy>
      </policies>
    </sca>
</agent_config>
```
Everything seems to be in order, but the dashboard indicates that the Shared custom policy for SCA test has failed
