### ISSUE TITLE
Getting 401 Unauthorized when trying to Access Wazuh Dashboard via Authentik SAML SSO

### ISSUE THREAD

**Issue by Videothek** [wazuh/wazuh#19623]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.5.2-40505 | Wazuh Dashboard | Manager | apt-Package | Ubuntu 22.04 |

I have configured Wazuh for SSO use via SAML according to the offical [Wazuh Documentation](https://documentation.wazuh.com/current/user-manual/user-administration/single-sign-on/administrator/index.html) and with a little help from the following Github Issue   #16366 .

When I am trying to log into the Wazuh Dashboard it seems like that the Authentik Login is working but then it redirects me to the following page:

![grafik](https://github.com/wazuh/wazuh/assets/57219798/49adf306-aa4c-46bc-bbff-688d8e205c1a)

My `/etc/wazuh-indexer/opensearch-security/config.yml` config file has this section for the saml auth:

```
      saml_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_url: "Authentik Metadata File Download URL"
              entity_id: "Authentik URL"
            sp:
              entity_id: wazuh-saml
            kibana_url: https://wazuh_URL/app/wazuh
            roles_key: Roles
            exchange_key: 'x509 Certificate for signing the request'
        authentication_backend:
          type: noop
```

In Authentik I tested POST and REDIRECT as Service Provider Binding but both yielded the same result.

I configured `https://wazuh_URL/_opendistro/_security/saml/acs/idpinitiated` as ACS URL and `wazuh-saml` as Issuer in Authentik.

Does anyone had the same issue and know how to fix it?

Thank you in Advance.

**Comment by Videothek** [comment]
Does anyone had the same challenge as me?

And if not, i would be happy to know what i overlooked to use SSO with my Wazuh instace 😄.

**Comment by maikroservice** [comment]
did you add the backend role to your roles_mapping.yml? and add a role mapping inside of wazuh security (https://documentation.wazuh.com/current/_images/Wazuh-role-mapping7.png / https://documentation.wazuh.com/current/_images/Wazuh-role-mapping1.gif)

```
# roles_mapping.yml
all_access:
  reserved: false
  hidden: false
  backend_roles:
    #- "wazuh-admins"
  - "admin"
  hosts: []
  users: []
  and_backend_roles: []
  description: "Maps SAML admin to all_access"
```

**Comment by Videothek** [comment]
Running `journalctl -f -u wazuh-dashboard` when trying to login shows following:

`
Nov 07 15:24:58 wazuh opensearch-dashboards[740862]: {"type":"response","@timestamp":"2023-11-07T14:24:58Z","tags":[],"pid":740862,"method":"get","statusCode":401,"req":{"url":"/_opendistro/_security/saml/acs/idpinitiated?SAMLResponse=very_long_string_of_characters %3D%3D","method":"get","headers":{"host":"wazuh_dashboard_url","connection":"close","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8","accept-language":"de,en-US;q=0.7,en;q=0.3","accept-encoding":"gzip, deflate, br","upgrade-insecure-requests":"1","sec-fetch-dest":"document","sec-fetch-mode":"navigate","sec-fetch-site":"cross-site"},"remoteAddress":"127.0.0.1","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0"},"res":{"statusCode":401,"responseTime":2,"contentLength":9},"message":"GET /_opendistro/_security/saml/acs/idpinitiated?SAMLResponse=very_long_string_of_characters 401 2ms - 9.0B"}
`

My Wazuh installation was very new and i worked before thats why i think this shouldn´t be the problem, but you never know...

The remote address shows 127.0.0.1 because i am running Wazuh behind a Nginx proxy on the same system.

I also looked at https://documentation.wazuh.com/current/user-manual/user-administration/single-sign-on/administrator/keycloak.html and i added some extra steps that were mentioned.

I am also running the script after every update of the config files as shown in the offical Wazuh docs.

I am fully "invested" in Authentik since i am running all my SAML and OpenID requests with it.

Thats why it would be nice to get it working with Authentik.

Thank you for your response.

**Comment by maikroservice** [comment]
add me on discord @maikroservice and we can debug interactively

**Comment by Videothek** [comment]
@maikroservice and i got it figured out.

A detailed blog entry is going to be posted by @maikroservice.

I will link it here as soon as it is published.

In Authentik you have to configure your provider like this:
![grafik](https://github.com/wazuh/wazuh/assets/57219798/b173ec30-77c4-4fe2-a1ff-4344467f5e4a)

![grafik](https://github.com/wazuh/wazuh/assets/57219798/d6e51bc4-becc-4811-b334-4acc7588b998)

The Wazuh Admin Mapping looks like this:

![grafik](https://github.com/wazuh/wazuh/assets/57219798/e33c1da5-2374-4b2e-875d-7c05ffcc07d1)

The Authentik group i want to have access to wazuh is called Admin (change this group with the one that fits your configuration).

On Wazuh side i configured things like this:

Added the following to `/etc/wazuh-indexer/opensearch-security/config.yml`:

```
      saml_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_url: "https://your_authentik_metadata_download_url/"
              entity_id: "wazuh-saml"
            sp:
              entity_id: "wazuh-saml"
            kibana_url: "https://your_wazuh_url/"
            roles_key: Roles
            exchange_key: "X509_certificate_part_from_authentik_metadata_file"
        authentication_backend:
          type: noop
```


`/etc/wazuh-indexer/opensearch-security/roles_mapping.yml`:

```
all_access:
  reserved: true
  hidden: false
  backend_roles:
  - "admin"
  hosts: []
  users: []
  and_backend_roles: []
  description: "Maps admin to all_access"
```

Added the following to `/etc/wazuh-dashboard/opensearch_dashboards.yml`:

```
opensearch_security.auth.type: "saml"
server.xsrf.allowlist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout", "/_opendistro/_security/saml/acs/idpinitiated"]
opensearch_security.session.keepalive: false
```

And finally the following Role Mapping within Wazuh Dashbaord:
![grafik](https://github.com/wazuh/wazuh/assets/57219798/bcacf4b4-05a7-4329-ad2e-8c5d907db3d4)

This should be all you need to configure.

Dont forget to follow the wazuh saml documentation step by step and add the values from this issue according to your configuration.
