### ISSUE TITLE
Release 4.7.0 - Alpha 1 - E2E UX tests - Vulnerability Detection

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#19659]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.7.0-alpha1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing/publication` objective and `Very high` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/data-pirates team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Oct 18, 2023 and notify the @wazuh/data-pirates team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/data-pirates team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Oct 19, 2023 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Oct 20, 2023.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Step by step](https://documentation-dev.wazuh.com/v4.7.0-alpha1/installation-guide/wazuh-indexer/step-by-step.html) | Multi node | Debian 10 x86_64 |
| Server | [Step by step](https://documentation-dev.wazuh.com/v4.7.0-alpha1/installation-guide/wazuh-server/step-by-step.html) | Single node | Debian 10 x86_64 |
| Dashboard | [Step by step](https://documentation-dev.wazuh.com/v4.7.0-alpha1/installation-guide/wazuh-dashboard/step-by-step.html) | - | Debian 10 x86_64 |
| Agent | [Installing Wazuh agents](https://documentation-dev.wazuh.com/v4.7.0-alpha1/installation-guide/wazuh-agent/index.html) | - | Windows server 2012 x86_64, ubuntu 20.04 x86_64, RHEL 8 aarch64, macOS Ventura x86_64 |

## Test description

Use the new WUI for vulnerabilities. Install vulnerable package to force an alert. Patch or uninstall vulnerable package to force a "solved" alert.
Test POC for https://documentation-dev.wazuh.com/v4.7.0-alpha1/proof-of-concept-guide/poc-vulnerability-detection.html

## Known issues

- https://github.com/wazuh/wazuh/issues/15630
- https://github.com/wazuh/wazuh/issues/18447
- https://github.com/wazuh/wazuh/issues/18593

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below. **REMOVE CURRENT EXAMPLES**:

| **Status**     | **Endpoint**    | **Result**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟢 | Ubuntu 20.04  x86_64 |  Worked as expected   |       |
| 🟢 | RHEL 8 aarch64 |   Worked as expected   |       |
| 🟢 | macOS Ventura x86_64 |   Worked as expected   |       |
| 🟢 | Windows server 2012 x86_64 |  Worked as expected    |    |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
The guidelines were easy to follow
- Did you face any challenges not covered by the guideline?
  No issue encountered
- Suggestions for improvement:
  

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @davidjiglesias
- [x] @wazuh/data-pirates

**Comment by thony4uu** [comment]
## Debian 10 x86_64 Deployment Requirements 
<details>
<summary>Operating System Information</summary>

````console

wazuh@indexer1:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
wazuh@indexer1:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
wazuh@indexer1:~$ arch
x86_64
wazuh@indexer1:~$



<details>

**Comment by thony4uu** [comment]
# Installing the Wazuh Indexer step by step 🟢 

## Wazuh indexer

<details>
<summary>Certificates creation :green_circle: </summary>

1. Download the `wazuh-certs-tool.sh` script and the `wazuh-config.yml` configuration file:

```shellsession
root@indexer1:/home/wazuh# curl -sO https://packages-dev.wazuh.com/4.7/wazuh-certs-tool.sh
root@indexer1:/home/wazuh# curl -sO https://packages-dev.wazuh.com/4.7/config.yml
```
2. Edit the `config.yml`:

```yml
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: "192.168.71.192"
      name: node-2
      ip: "192.168.71.193"
    #- name: node-3
    #  ip: "<indexer-node-ip>"

  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  server:
    - name: wazuh-1
      ip: "192.168.71.189"
    #  node_type: master
    #- name: wazuh-2
    #  ip: "<wazuh-manager-ip>"
    #  node_type: worker
    #- name: wazuh-3
    #  ip: "<wazuh-manager-ip>"
    #  node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: "192.168.71.189"

```

3. Run the `wazuh-certs-tool.sh`:

```shellsession
root@indexer1:/home/wazuh# bash ./wazuh-certs-tool.sh -A
17/10/2023 07:47:35 INFO: Admin certificates created.
17/10/2023 07:47:35 INFO: Wazuh indexer certificates created.
17/10/2023 07:47:35 INFO: Wazuh server certificates created.
17/10/2023 07:47:35 INFO: Wazuh dashboard certificates created.
```

4. Compress the files:

```shellsession
root@indexer1:/home/wazuh# tar -cvf ./wazuh-certificates.tar -C ./wazuh-certificates/ .
./
./admin.pem
./admin-key.pem
./root-ca.pem
./wazuh-1.pem
./node-1-key.pem
./node-1.pem
./root-ca.key
./dashboard.pem
./dashboard-key.pem
./wazuh-1-key.pem
root@indexer1:/home/wazuh# rm -rf ./wazuh-certificates
```

</details>

<details>
<suetails>
<summary>Nodes installation :green_circle:</summary>

1. Install the packages if missing:

````console

root@indexer1:/home/wazuh# apt-get install debconf adduser procps
Reading package lists... Done
Building dependency tree
Reading state information... Done
adduser is already the newest version (3.118).
debconf is already the newest version (1.5.71+deb10u1).
procps is already the newest version (2:3.3.15-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@indexer1:/home/wazuh# apt-get install gnupg apt-transport-https
Reading package lists... Done
Building dependency tree
Reading state information... Done
gnupg is already the newest version (2.2.12-1+deb10u2).
gnupg set to manually installed.
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 149 kB of archives.
After this operation, 156 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.debian.org/debian buster/main amd64 apt-transport-https all 1.8.2.3 [149 kB]
Fetched 149 kB in 0s (699 kB/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 137307 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.8.2.3_all.deb ...
Unpacking apt-transport-https (1.8.2.3) ...
Setting up apt-transport-https (1.8.2.3) ...

````
   
2. Install the GPG key.

```shellsession
root@indexer1:/home/wazuh# curl -s https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
gpg: keyring '/usr/share/keyrings/wazuh.gpg' created
gpg: directory '/root/.gnupg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 96B3EE5F29111145: public key "Wazuh.com (Wazuh Signing Key) <support@wazuh.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1

```

3. Add the repository:

```shellsession
root@indexer1:/home/wazuh# echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages-dev.wazuh.com/pre-release/apt/ unstable main" | tee -a /etc/apt/sources.list.d/wazuh.list
deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages-dev.wazuh.com/pre-release/apt/ unstable main
 ```

4. Update the packages information and install the Indexer

```shellsession
root@indexer1:/home/wazuh# apt-get update
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://security.debian.org/debian-security buster/updates InRelease
Get:3 https://packages-dev.wazuh.com/pre-release/apt unstable InRelease [17.3 kB]
Get:4 https://packages-dev.wazuh.com/pre-release/apt unstable/main amd64 Packages [34.0 kB]
Fetched 51.3 kB in 1s (37.7 kB/s)
Reading package lists... Done

root@indexer1:/home/wazuh# apt-get -y install wazuh-indexer
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  wazuh-indexer
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 685 MB of archives.
After this operation, 969 MB of additional disk space will be used.
Get:1 https://packages-dev.wazuh.com/pre-release/apt unstable/main amd64 wazuh-indexer amd64 4.7.0-1 [685 MB]
Fetched 685 MB in 58s (11.8 MB/s)
Selecting previously unselected package wazuh-indexer.
(Reading database ... 137311 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_4.7.0-1_amd64.deb ...
Creating wazuh-indexer group... OK
Creating wazuh-indexer user... OK
Unpacking wazuh-indexer (4.7.0-1) ...
Setting up wazuh-indexer (4.7.0-1) ...
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
Processing triggers for systemd (241-7~deb10u10) ...
```
</details>

<details>
<summary>Configuring the Wazuh Indexer :green_circle: </summary>

#### Node `node-1`

```yml
network.host: "192.168.71.192"
node.name: "node-1"
cluster.initial_master_nodes:
- "node-1"
- "node-2"
#- "node-3"
cluster.name: "wazuh-cluster"
#discovery.seed_hosts:
 - "192.168.71.192"
 - "192.168.71.193"
 - "node-3-ip"
node.max_local_storage_nodes: "3"
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer

plugins.security.ssl.http.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.http.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.transport.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.transport.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.http.enabled: true
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false

plugins.security.authcz.admin_dn:
- "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn:
- "CN=node-1,OU=Wazuh,O=Wazuh,L=California,C=US"
- "CN=node-2,OU=Wazuh,O=Wazuh,L=California,C=US"
#- "CN=node-3,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.restapi.roles_enabled:
- "all_access"

plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".plugins-ml-model", ".plugins-ml-task", ".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendist$

### Option to allow Filebeat-oss 7.10.2 to work ###
compatibility.override_main_response_version: true
### Option to allow Filebeat-oss 7.10.2 to work ###

```

#### Node `node-2`

```yml
network.host: "192.168.71.193"
node.name: "node-2"
cluster.initial_master_nodes:
- "node-1"
- "node-2"
#- "node-3"
cluster.name: "wazuh-cluster"
#discovery.seed_hosts:
  - "192.168.71.192"
  - "192.168.71.193"
#  - "node-3-ip"
node.max_local_storage_nodes: "3"
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer

plugins.security.ssl.http.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.http.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.transport.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.transport.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.http.enabled: true
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.resolve_hostname: false

plugins.security.authcz.admin_dn:
- "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn:
- "CN=node-1,OU=Wazuh,O=Wazuh,L=California,C=US"
- "CN=node-2,OU=Wazuh,O=Wazuh,L=California,C=US"
#- "CN=node-3,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.restapi.roles_enabled:
- "all_access"

plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".plugins-ml-model", ".plugins-ml-task", ".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendist$

### Option to allow Filebeat-oss 7.10.2 to work ###
compatibility.override_main_response_version: true

```
</details>

<details>
<summary>Deploying certificates :green_circle: </summary>

```shellsession
root@indexer2:/home/wazuh# NODE_NAME=node-2
root@indexer2:/home/wazuh# mkdir /etc/wazuh-indexer/certs
root@indexer2:/home/wazuh# tar -xf ./wazuh-certificates.tar -C /etc/wazuh-indexer/certs/ ./$NODE_NAME.pem ./$NODE_NAME-key.pem ./admin.pem ./admin-key.pem ./root-ca.pem
root@indexer2:/home/wazuh# mv -n /etc/wazuh-indexer/certs/$NODE_NAME.pem /etc/wazuh-indexer/certs/indexer.pem
root@indexer2:/home/wazuh# mv -n /etc/wazuh-indexer/certs/$NODE_NAME-key.pem /etc/wazuh-indexer/certs/indexer-key.pem
root@indexer2:/home/wazuh#
root@indexer2:/home/wazuh# chmod 500 /etc/wazuh-indexer/certs
root@indexer2:/home/wazuh# chmod 400 /etc/wazuh-indexer/certs/*
root@indexer2:/home/wazuh# chown -R wazuh-indexer:wazuh-indexer /etc/wazuh-indexer/certs
```
</details>

<details>
<summary>Starting the service :green_circle: </summary>

```shellsession
root@indexer2:/home/wazuh# systemctl enable wazuh-indexer
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-indexer.service → /lib/systemd/system/wazuh-indexer.service.
root@indexer2:/home/wazuh# systemctl start wazuh-indexer
root@indexer2:/home/wazuh# systemctl status wazuh-indexer
● wazuh-indexer.service - Wazuh-indexer
   Loaded: loaded (/lib/systemd/system/wazuh-indexer.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2023-10-17 11:07:42 CDT; 13min ago
     Docs: https://documentation.wazuh.com
 Main PID: 2266 (java)
    Tasks: 50 (limit: 2315)
   Memory: 1.1G
   CGroup: /system.slice/wazuh-indexer.service
           └─2266 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl

Oct 17 11:06:35 indexer2 systemd[1]: Starting Wazuh-indexer...
Oct 17 11:06:54 indexer2 systemd-entrypoint[2266]: WARNING: A terminally deprecated method in java.lang.System has been called
Oct 17 11:06:54 indexer2 systemd-entrypoint[2266]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (file:/usr/sha
Oct 17 11:06:54 indexer2 systemd-entrypoint[2266]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSearch
Oct 17 11:06:54 indexer2 systemd-entrypoint[2266]: WARNING: System::setSecurityManager will be removed in a future release
Oct 17 11:07:11 indexer2 systemd-entrypoint[2266]: WARNING: A terminally deprecated method in java.lang.System has been called
Oct 17 11:07:11 indexer2 systemd-entrypoint[2266]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.Security (file:/usr/share
Oct 17 11:07:11 indexer2 systemd-entrypoint[2266]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Security
Oct 17 11:07:11 indexer2 systemd-entrypoint[2266]: WARNING: System::setSecurityManager will be removed in a future release
Oct 17 11:07:42 indexer2 systemd[1]: Started Wazuh-indexer.
```

</details>

<details>
<summary>Cluster initialization :green_circle: </summary>

1. Run the Wazuh indexer indexer-security-init.sh script on any Wazuh indexer node

```shellsession
root@indexer1:/home/wazuh# /usr/share/wazuh-indexer/bin/indexer-security-init.sh
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
Security Admin v7
Will connect to 192.168.71.192:9200 ... done
Connected as "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
OpenSearch Version: 2.8.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: GREEN
Number of nodes: 2
Number of data nodes: 2
.opendistro_security index does not exists, attempt to create it ... done (0-all replicas)
Populate config from /etc/wazuh-indexer/opensearch-security/
Will update '/config' with /etc/wazuh-indexer/opensearch-security/config.yml
   SUCC: Configuration for 'config' created or updated
Will update '/roles' with /etc/wazuh-indexer/opensearch-security/roles.yml
   SUCC: Configuration for 'roles' created or updated
Will update '/rolesmapping' with /etc/wazuh-indexer/opensearch-security/roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
Will update '/internalusers' with /etc/wazuh-indexer/opensearch-security/internal_users.yml
   SUCC: Configuration for 'internalusers' created or updated
Will update '/actiongroups' with /etc/wazuh-indexer/opensearch-security/action_groups.yml
   SUCC: Configuration for 'actiongroups' created or updated
Will update '/tenants' with /etc/wazuh-indexer/opensearch-security/tenants.yml
   SUCC: Configuration for 'tenants' created or updated
Will update '/nodesdn' with /etc/wazuh-indexer/opensearch-security/nodes_dn.yml
   SUCC: Configuration for 'nodesdn' created or updated
Will update '/whitelist' with /etc/wazuh-indexer/opensearch-security/whitelist.yml
   SUCC: Configuration for 'whitelist' created or updated
Will update '/audit' with /etc/wazuh-indexer/opensearch-security/audit.yml
   SUCC: Configuration for 'audit' created or updated
Will update '/allowlist' with /etc/wazuh-indexer/opensearch-security/allowlist.yml
   SUCC: Configuration for 'allowlist' created or updated
SUCC: Expected 10 config types for node {"updated_config_types":["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"],"updated_config_size":10,"message":null} is 10 (["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"]) due to: null
SUCC: Expected 10 config types for node {"updated_config_types":["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"],"updated_config_size":10,"message":null} is 10 (["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"]) due to: null
Done with success
```

2. Testing the cluster installation

```shellsession
root@indexer1:/home/wazuh# curl -k -u admin:admin https://192.168.71.192:9200
{
  "name" : "node-1",
  "cluster_name" : "wazuh-cluster",
  "cluster_uuid" : "BvmHnixJSACGOSvPPu5xcg",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "rpm",
    "build_hash" : "db90a415ff2fd428b4f7b3f800a51dc229287cb4",
    "build_date" : "2023-06-03T06:24:25.112415503Z",
    "build_snapshot" : false,
    "lucene_version" : "9.6.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```
</details>
