### ISSUE TITLE
Windows SCA check for guest account assumes guest account exists (false positive)

### ISSUE THREAD

**Issue by mynoc96** [wazuh/wazuh#19792]
|Wazuh version|Component|Install type|Install method|Platform|
| 4.5.3 | SCA Ruleset | Both | Both | Windows |

Current SCA rules for Windows 11 check whether the Guest account is disabled. If the account has been removed or renamed, the check fails. I'm recommending that rule 26011 be changed to the following to remove false positives when checking if guest account is disabled. If an admin deliberately removes or renames the guest account, it should be considered mitigated.

File: ruleset/sca/windows/cis_win11_enterprise.yml

```
  - id: 26011
    title: "Ensure 'Accounts: Guest account status' is set to 'Disabled'."
    description: "This policy setting determines whether the Guest account is enabled or disabled. The Guest account allows unauthenticated network users to gain access to the system. The recommended state for this setting is: Disabled. Note: This setting will have no impact when applied to the Domain Controllers organizational unit via group policy because Domain Controllers have no local account database. It can be configured at the domain level via group policy, similar to account lockout and password policy settings."
    rationale: "The default Guest account allows unauthenticated network users to log on as Guest with no password. These unauthorized users could access any resources that are accessible to the Guest account over the network. This capability means that any network shares with permissions that allow access to the Guest account, the Guests group, or the Everyone group will be accessible over the network, which could lead to the exposure or corruption of data."
    remediation: "To establish the recommended configuration via GP, set the following UI path to Disabled: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Local Policies\\Security Options\\Accounts: Guest account status"
    compliance:
      - cis: ["2.3.1.3"]
      - cis_csc: ["4.7"]
    condition: any
    rules:
      - 'c:net user guest -> r:The user name could not be found.'
      - 'c:net user guest -> r:Account active\s+No'
```

**Comment by JackW6809** [comment]
Agree with the above, still happens on 4.8.2

**Comment by zbalkan** [comment]
As I mentioned in another issue [some time ago](https://github.com/wazuh/wazuh/issues/21298#issuecomment-1908096665). the reliable way is using SID:

```shell
wmic useraccount where "sid like 's-1-5-21-%-500'" get name,status


Name      Status
<guest name> Degraded
```

Same with PowerShell:

```powershell
Get-LocalUser | Where-Object -Property SID -like "S-1-5-21-*-501"

Name     Enabled Description
----     ------- -----------
<localized name> False   Built-in account for guest access to the computer/domain

# or pnly get the status

(Get-LocalUser | Where-Object -Property SID -like "S-1-5-21-*-501").Enabled
False
```

This is the only reliable way.

So the SCA check must be:
```
'c:powershell "(Get-LocalUser | Where-Object -Property SID -like "S-1-5-21-*-501").Enabled" -> r:False'
```

**Comment by zbalkan** [comment]
This applies to the local Administrator as well.

**Comment by apitamy** [comment]
This is still an issue in 4.10. The CIS Microsoft Windows 11 Enterprise Benchmark v3.0.0 actually recommends renaming the guest account. So anyone correctly following the CIS Benchmark will get flagged with this false positive. (assuming renaming guest is the root cause)

2.3.1.5 	(L1) Configure 'Accounts: Rename guest account'

**Comment by df-an** [comment]
@AwwalQuan 

And in here from https://github.com/wazuh/wazuh/issues/19792#issuecomment-2450017709  @zbalkan use proper check for guest user check using powershell command using SID and without being limited to english locales...
Fix it as soon as possible, has been now forever an issue...


> So the SCA check must be:
> 
> 'c:powershell -noprofile "(Get-LocalUser | Where-Object -Property SID -like "S-1-5-21-*-501").Enabled" -> r:False'

For me it doe sonly the job fine, when running it manually in powershell, but not, when used in SCA file...

Just for crossreference: https://github.com/wazuh/wazuh/issues/16842

**Comment by df-an** [comment]
@AwwalQuan and @jk-olaoluwa  Is there any update on it?

All users have the issues, also the same in here: https://github.com/wazuh/wazuh/issues/28064

Thank you...

**Comment by Johnng007** [comment]
@mynoc96 
This has been fixed in the latest version of Wazuh. below is the updated check logic.

````
 # 2.3.1.2 (L1) Ensure 'Accounts: Guest account status' is set to 'Disabled'. (Automated)
  - id: 26009
    title: "Ensure 'Accounts: Guest account status' is set to 'Disabled'."
    description: "This policy setting determines whether the Guest account is enabled or disabled. The Guest account allows unauthenticated network users to gain access to the system. The recommended state for this setting is: Disabled. Note: This setting will have no impact when applied to the Domain Controllers organizational unit via group policy because Domain Controllers have no local account database. It can be configured at the domain level via group policy, similar to account lockout and password policy settings."
    rationale: "The default Guest account allows unauthenticated network users to log on as Guest with no password. These unauthorized users could access any resources that are accessible to the Guest account over the network. This capability means that any network shares with permissions that allow access to the Guest account, the Guests group, or the Everyone group will be accessible over the network, which could lead to the exposure or corruption of data."
    impact: "All network users will need to authenticate before they can access shared resources. If you disable the Guest account and the Network Access: Sharing and Security Model option is set to Guest Only, network logons, such as those performed by the Microsoft Network Server (SMB Service), will fail. This policy setting should have little impact on most organizations because it is the default setting in Microsoft Windows 2000, Windows XP, and Windows Server™ 2003."
    remediation: "To establish the recommended configuration via GP, set the following UI path to Disabled: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Local Policies\\Security Options\\Accounts: Guest account status."
    references:
      - 'https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/accounts-guest-account-status'
    compliance:
      - cis: ["2.3.1.2"]
      - cis_csc_v8: ["4.7"]
      - cis_csc_v7: ["16.8"]
      - iso_27001-2013: ["A.9.2.1"]
      - pci_dss_v3.2.1: ["2.1", "2.1.1"]
      - pci_dss_v4.0: ["2.2.2", "2.3.1"]
      - soc_2: ["CC6.3"]
    condition: any
    rules:
      - 'c:wmic useraccount where (sid like "s-1-5-21-%-501") get Disabled -> r:TRUE'
      - 'c:wmic useraccount where (sid like "s-1-5-21-%-501") get Disabled -> r:No Instance\(s\) Available.'
````

**Comment by df-an** [comment]
@Johnng007 You know that relying on wmic is not future proof as it won't do the job for fresh windows 11 builds anymore out of the box?

Read in here as one example:  [WMI command line (WMIC) utility deprecation: Next steps
https://techcommunity.microsoft.com/blog/windows-itpro-blog/wmi-command-line-wmic-utility-deprecation-next-steps/4039242

**Comment by Johnng007** [comment]
> [@Johnng007](https://github.com/Johnng007) You know that relying on wmic is not future proof as it won't do the job for fresh windows 11 builds anymore out of the box?
> 
> Read in here as one example: [WMI command line (WMIC) utility deprecation: Next steps https://techcommunity.microsoft.com/blog/windows-itpro-blog/wmi-command-line-wmic-utility-deprecation-next-steps/4039242

@df-an Thanks for the heads-up.
This is sad though but we will keep this in mind for future reworks.

**Comment by df-an** [comment]
@Johnng007 are you so kind to check how if will work with the proper powershell syntax, as i did not manage to get it working right now with powershell command... if you run in powershell cli, it works with output False

'c:powershell -noprofile "(Get-LocalUser | Where-Object -Property SID -like "S-1-5-21-*-501").Enabled" -> r:False'

**Comment by Johnng007** [comment]
@df-an The rule should look like.

````
 # 2.3.1.2 (L1) Ensure 'Accounts: Guest account status' is set to 'Disabled'. (Automated)
  - id: 26009
    title: "Ensure 'Accounts: Guest account status' is set to 'Disabled'."
    description: "This policy setting determines whether the Guest account is enabled or disabled. The Guest account allows unauthenticated network users to gain access to the system. The recommended state for this setting is: Disabled. Note: This setting will have no impact when applied to the Domain Controllers organizational unit via group policy because Domain Controllers have no local account database. It can be configured at the domain level via group policy, similar to account lockout and password policy settings."
    rationale: "The default Guest account allows unauthenticated network users to log on as Guest with no password. These unauthorized users could access any resources that are accessible to the Guest account over the network. This capability means that any network shares with permissions that allow access to the Guest account, the Guests group, or the Everyone group will be accessible over the network, which could lead to the exposure or corruption of data."
    impact: "All network users will need to authenticate before they can access shared resources. If you disable the Guest account and the Network Access: Sharing and Security Model option is set to Guest Only, network logons, such as those performed by the Microsoft Network Server (SMB Service), will fail. This policy setting should have little impact on most organizations because it is the default setting in Microsoft Windows 2000, Windows XP, and Windows Server™ 2003."
    remediation: "To establish the recommended configuration via GP, set the following UI path to Disabled: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Local Policies\\Security Options\\Accounts: Guest account status."
    references:
      - 'https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/accounts-guest-account-status'
    compliance:
      - cis: ["2.3.1.2"]
      - cis_csc_v8: ["4.7"]
      - cis_csc_v7: ["16.8"]
      - iso_27001-2013: ["A.9.2.1"]
      - pci_dss_v3.2.1: ["2.1", "2.1.1"]
      - pci_dss_v4.0: ["2.2.2", "2.3.1"]
      - soc_2: ["CC6.3"]
    condition: any
    rules:
      - 'c:powershell -noprofile "(Get-LocalUser | Where-Object -Property SID -like "S-1-5-21-*-501").Enabled" -> r:False'
      - 'c:powershell -noprofile "(Get-LocalUser | Where-Object -Property SID -like "S-1-5-21-*-501").Enabled" -> r:^\s*$'
````

**Comment by df-an** [comment]
@Johnng007 Thanks, have evaluted with it. But if have ENABLED the build in Guest account, it still resolved in a PASSED state (GREEN), which should be state FAILED (RED).  and yes, wazuh agent has been restarted after every guest account state change.

Do you have any idea?

**Comment by Johnng007** [comment]
> [@Johnng007](https://github.com/Johnng007) Thanks, have evaluted with it. But if have ENABLED the build in Guest account, it still resolved in a PASSED state (GREEN), which should be state FAILED (RED). and yes, wazuh agent has been restarted after every guest account state change.
> 
> Do you have any idea?

@df-an Implementing this outside WMIC is a bit tricky, we will figure it out over time before it gets fazed out by Microsoft.
you can mix your solution or remove the last rule.

````
 # 2.3.1.2 (L1) Ensure 'Accounts: Guest account status' is set to 'Disabled'. (Automated)
  - id: 26009
    title: "Ensure 'Accounts: Guest account status' is set to 'Disabled'."
    description: "This policy setting determines whether the Guest account is enabled or disabled. The Guest account allows unauthenticated network users to gain access to the system. The recommended state for this setting is: Disabled. Note: This setting will have no impact when applied to the Domain Controllers organizational unit via group policy because Domain Controllers have no local account database. It can be configured at the domain level via group policy, similar to account lockout and password policy settings."
    rationale: "The default Guest account allows unauthenticated network users to log on as Guest with no password. These unauthorized users could access any resources that are accessible to the Guest account over the network. This capability means that any network shares with permissions that allow access to the Guest account, the Guests group, or the Everyone group will be accessible over the network, which could lead to the exposure or corruption of data."
    impact: "All network users will need to authenticate before they can access shared resources. If you disable the Guest account and the Network Access: Sharing and Security Model option is set to Guest Only, network logons, such as those performed by the Microsoft Network Server (SMB Service), will fail. This policy setting should have little impact on most organizations because it is the default setting in Microsoft Windows 2000, Windows XP, and Windows Server™ 2003."
    remediation: "To establish the recommended configuration via GP, set the following UI path to Disabled: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Local Policies\\Security Options\\Accounts: Guest account status."
    references:
      - 'https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/accounts-guest-account-status'
    compliance:
      - cis: ["2.3.1.2"]
      - cis_csc_v8: ["4.7"]
      - cis_csc_v7: ["16.8"]
      - iso_27001-2013: ["A.9.2.1"]
      - pci_dss_v3.2.1: ["2.1", "2.1.1"]
      - pci_dss_v4.0: ["2.2.2", "2.3.1"]
      - soc_2: ["CC6.3"]
    condition: any
    rules:
      - 'c:powershell -noprofile "(Get-LocalUser | Where-Object -Property SID -like "S-1-5-21-*-501").Enabled" -> r:False'
      - 'c:wmic useraccount where (sid like "s-1-5-21-%-501") get Disabled -> r:No Instance\(s\) Available.'
````

you can outrightly remove the wmic rule and set the condition to all. (Note: This will not pass the check if the Guest account is removed/renamed.)


````
 # 2.3.1.2 (L1) Ensure 'Accounts: Guest account status' is set to 'Disabled'. (Automated)
  - id: 26009
    title: "Ensure 'Accounts: Guest account status' is set to 'Disabled'."
    description: "This policy setting determines whether the Guest account is enabled or disabled. The Guest account allows unauthenticated network users to gain access to the system. The recommended state for this setting is: Disabled. Note: This setting will have no impact when applied to the Domain Controllers organizational unit via group policy because Domain Controllers have no local account database. It can be configured at the domain level via group policy, similar to account lockout and password policy settings."
    rationale: "The default Guest account allows unauthenticated network users to log on as Guest with no password. These unauthorized users could access any resources that are accessible to the Guest account over the network. This capability means that any network shares with permissions that allow access to the Guest account, the Guests group, or the Everyone group will be accessible over the network, which could lead to the exposure or corruption of data."
    impact: "All network users will need to authenticate before they can access shared resources. If you disable the Guest account and the Network Access: Sharing and Security Model option is set to Guest Only, network logons, such as those performed by the Microsoft Network Server (SMB Service), will fail. This policy setting should have little impact on most organizations because it is the default setting in Microsoft Windows 2000, Windows XP, and Windows Server™ 2003."
    remediation: "To establish the recommended configuration via GP, set the following UI path to Disabled: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Local Policies\\Security Options\\Accounts: Guest account status."
    references:
      - 'https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/accounts-guest-account-status'
    compliance:
      - cis: ["2.3.1.2"]
      - cis_csc_v8: ["4.7"]
      - cis_csc_v7: ["16.8"]
      - iso_27001-2013: ["A.9.2.1"]
      - pci_dss_v3.2.1: ["2.1", "2.1.1"]
      - pci_dss_v4.0: ["2.2.2", "2.3.1"]
      - soc_2: ["CC6.3"]
    condition: all
    rules:
      - 'c:powershell -noprofile "(Get-LocalUser | Where-Object -Property SID -like "S-1-5-21-*-501").Enabled" -> r:False'
````

**Comment by zbalkan** [comment]
Well, to use wmic is the tricky bit. The PowerShell version is with SIDs is the best way.

**Comment by Johnng007** [comment]
> Well, to use wmic is the tricky bit. The PowerShell version is with SIDs is the best way.

But it has issues identifying a non existent SID.
For instance.
````
powershell -noprofile "(Get-LocalUser | Where-Object -Property SID -like "S-1-5-21-*-502").Enabled"
````
would just not return any value if the SID doesn't exist. I tried to read the null response but, wasn't handled properly.

If you try to handle it with an exception.
````
powershell -noprofile "try { (Get-LocalUser | Where-Object { $_.SID -like 'S-1-5-21-*-502' } | Select-Object -First 1).Name } catch { 'NotFound' }"
````
for some reason the line is not read properly also.

Anyway, this is not a priority issue and we will get to test it extensively before wmic blinks away.

**Comment by zbalkan** [comment]
The easiest way would be the one-liner below. If the user does not exist, it will return false as well.

```powershell
[bool](Get-LocalUser | Where-Object -Property  SID -like 'S-1-5-21-*-501' | Where-Object -Property Enabled)
```

**Comment by Johnng007** [comment]
> The easiest way would be the one-liner below. If the user does not exist, it will return false as well.
> 
> [bool](Get-LocalUser | Where-Object -Property  SID -like 'S-1-5-21-*-501' | Where-Object -Property Enabled)

Yes, i agree. This is simpler.

In that case @df-an can easily use the below.

````
 # 2.3.1.2 (L1) Ensure 'Accounts: Guest account status' is set to 'Disabled'. (Automated)
  - id: 26009
    title: "Ensure 'Accounts: Guest account status' is set to 'Disabled'."
    description: "This policy setting determines whether the Guest account is enabled or disabled. The Guest account allows unauthenticated network users to gain access to the system. The recommended state for this setting is: Disabled. Note: This setting will have no impact when applied to the Domain Controllers organizational unit via group policy because Domain Controllers have no local account database. It can be configured at the domain level via group policy, similar to account lockout and password policy settings."
    rationale: "The default Guest account allows unauthenticated network users to log on as Guest with no password. These unauthorized users could access any resources that are accessible to the Guest account over the network. This capability means that any network shares with permissions that allow access to the Guest account, the Guests group, or the Everyone group will be accessible over the network, which could lead to the exposure or corruption of data."
    impact: "All network users will need to authenticate before they can access shared resources. If you disable the Guest account and the Network Access: Sharing and Security Model option is set to Guest Only, network logons, such as those performed by the Microsoft Network Server (SMB Service), will fail. This policy setting should have little impact on most organizations because it is the default setting in Microsoft Windows 2000, Windows XP, and Windows Server™ 2003."
    remediation: "To establish the recommended configuration via GP, set the following UI path to Disabled: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Local Policies\\Security Options\\Accounts: Guest account status."
    references:
      - 'https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/accounts-guest-account-status'
    compliance:
      - cis: ["2.3.1.2"]
      - cis_csc_v8: ["4.7"]
      - cis_csc_v7: ["16.8"]
      - iso_27001-2013: ["A.9.2.1"]
      - pci_dss_v3.2.1: ["2.1", "2.1.1"]
      - pci_dss_v4.0: ["2.2.2", "2.3.1"]
      - soc_2: ["CC6.3"]
    condition: all
    rules:
      - 'c:powershell -noprofile "[bool](Get-LocalUser | Where-Object -Property  SID -like ''S-1-5-21-*-501'' | Where-Object -Property Enabled)" -> r:False'
````
