### ISSUE TITLE
SCA false positive for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by JackThird** [wazuh/wazuh#20231]
|Wazuh version|Component|Install type|Install method|Platform|
| --- | --- | --- | --- | --- |
|4.6.0|Manager/Agent|Manager|Packages|Ubuntu server 22.04 LTS|

I'm trying to resolve SCA 'Failed' checks on a server (Ubuntu server 22.04 LTS) where I installed Wazuh agent v4.6.0 but there are a lot of false positive, for example this check:

```
File: /var/ossec/ruleset/sca/cis_ubuntu22-04.yml
Rule id: 28528
Description: 1.4.2 Ensure permissions on bootloader config are configured (Automated)
rule: c:stat /boot/grub/grub.cfg -> r:Access: (0400/-r--------) && r:Uid:\s+\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s+\t*\(\s*\t*0/\s*\t*root\)
```

The file /boot/grub/grub.cfg has this stat result:
```
  File: /boot/grub/grub.cfg
  Size: 9724      	Blocks: 24         IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 1048589     Links: 1
Access: (0400/-r--------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-11-14 11:58:47.246387448 +0100
Modify: 2023-11-14 09:54:32.718403885 +0100
Change: 2023-11-14 10:45:56.124265278 +0100
 Birth: 2022-12-02 12:41:43.744000000 +0100
```

I have same issues on other checks like:
```
28529 | Ensure authentication required for single user mode.
f:/etc/shadow -> r:^root:\$\d+
```

```
28531 | Ensure Automatic Error Reporting is not enabled.
c:systemctl is-enabled apport.service -> r:disabled
not c:systemctl is-active apport.service -> r:active
not f:/etc/default/apport -> n:enabled=(\d+) compare != 0
```

etc.

Please could you check it? Is this module reliable?

Thanks.

**Comment by JackThird** [comment]
the fix:

before
`- 'c:stat /boot/grub/grub.cfg -> r:Access: (0400/-r--------) && r:Uid:\s+\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s+\t*\(\s*\t*0/\s*\t*root\)'`

after
`- 'c:stat /boot/grub/grub.cfg -> r:Access: \(0400/-r--------\) && r:Uid:\s+\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s+\t*\(\s*\t*0/\s*\t*root\)'`

**Comment by Grayfoox** [comment]
same issue here, bumping for visibility.

**Comment by Johnng007** [comment]
Errors confirmed for 
S/N | ID
-- | --
1 | 28528
2 | 28529
3 | 28531
4 | 28534
5 | 28653

**Comment by Johnng007** [comment]
**05-04-2024**

- checking linux based SCAs for similar issues - Ongoing

**Comment by Johnng007** [comment]
- [ ] Setup Debian 10, 11 and 12 testing labs labs

**Comment by Johnng007** [comment]
update: 19/04/2024
The debian SCAs are affected by the "Ensure permissions on bootloader config are configured." check.
The debian SCAs has the check as:
```
  # 1.5.1 Ensure permissions on bootloader config are configured (Automated)
  - id: 33030
    title: "Ensure permissions on bootloader config are configured."
    description: "The grub configuration file contains information on boot settings and passwords for unlocking boot options. Notes: - This recommendation is designed around the grub bootloader, if LILO or another bootloader is in use in your environment enact equivalent settings. - Replace /boot/grub/grub.cfg with the appropriate grub configuration file for your environment."
    rationale: "Setting the permissions to read and write for root only prevents non-root users from seeing the boot parameters or changing them. Non-root users who read the boot parameters may be able to identify weaknesses in security upon boot and be able to exploit them."
    remediation: "Run the following commands to set permissions on your grub configuration: # chown root:root /boot/grub/grub.cfg # chmod og-rwx /boot/grub/grub.cfg."
    compliance:
      - cis: ["1.5.1"]
      - cis_csc_v7: ["5.1"]
      - cmmc_v2.0: ["AC.1.002", "CM.2.061", "SC.3.180"]
      - iso_27001-2013: ["A.8.1.3", "A.14.2.5"]
      - mitre_techniques: ["T1110", "T1003", "T1081", "T1097", "T1178", "T1072", "T1067", "T1495", "T1019", "T1177", "T1485", "T1486", "T1491", "T1488", "T1487", "T1490", "T1146", "T1148", "T1015", "T1133", "T1200", "T1076", "T1051", "T1176", "T1501", "T1087", "T1098", "T1139", "T1197", "T1092", "T1136", "T1011", "T1147", "T1130", "T1174", "T1053", "T1166", "T1206", "T1503", "T1214", "T1187", "T1208", "T1142", "T1075", "T1201", "T1145", "T1184", "T1537", "T1078", "T1077", "T1134", "T1017", "T1088", "T1175", "T1190", "T1210", "T1525", "T1215", "T1086", "T1055", "T1505", "T1035", "T1218", "T1169", "T1100", "T1047", "T1084", "T1028", "T1156", "T1196", "T1530", "T1089", "T1073", "T1157", "T1054", "T1070", "T1037", "T1036", "T1096", "T1034", "T1150", "T1504", "T1494", "T1489", "T1198", "T1165", "T1492", "T1080", "T1209", "T1112", "T1058", "T1173", "T1137", "T1539", "T1535", "T1506", "T1138", "T1044", "T1199"]
      - nist_sp_800-53: ["AU-2", "CM-1", "CM-2", "CM-6", "CM-7", "IA-5", "IA-6", "SC-20", "SC-21"]
      - pci_dss_v3.2.1: ["2.2"]
    condition: all
    rules:
      - 'c:stat /boot/grub/grub.cfg -> r:Access:\s*\(0400/-r--------\)\s*Uid:\s*\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s*\(\s*\t*0/\s*\t*root\)'
```

The rule associated with it is wrong because the rationale explains that the permission should be set as read write for the root user. Also this is reflected in the remediation `chown root:root /boot/grub/grub.cfg` # `chmod og-rwx /boot/grub/grub.cfg`. 
applying the remediation the stats result will then differ from the rule checked.

![image](https://github.com/wazuh/wazuh/assets/30580457/79873f51-b4f3-445d-ad36-1233afe81442)

As expected the check fails for the debian agent.
![image](https://github.com/wazuh/wazuh/assets/30580457/8d271a7e-bf4b-4ab5-abe3-fe110f8b3dd8)

The check was fixed by modifying the rule to comply with the CIS rationale and recommendation.

```
    condition: all
    rules:
      - 'c:stat /boot/grub/grub.cfg -> r:Access: \(0600/-rw-------\) && r:Uid:\s+\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s+\t*\(\s*\t*0/\s*\t*root\)'
```
And as expected after the changes the rule passed.
![image](https://github.com/wazuh/wazuh/assets/30580457/b7a9ff39-8a75-4bba-8059-f47ec95e985b)

This issue applies to Debian 10 and 11 as well.
