### ISSUE TITLE
Check Wazuh Manager compatibility with new version Red Hat Enterprise Linux 9.3

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh#20430]
# Description
Hello team, this issue is to check the full compatibility of Wazuh Manager on the newfound version of Red Hat Enterprise Linux 9.3 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/20373

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Wazuh-manager installation.
- [x] Enrollment and connectivity with an agent.
- [x] Centralized configuration work correctly.
- [x] FIM: Decoding and filtering of correct alerts from FIM.
- [x] SCA: Policy support.
- [x] Syscollector: Complete inventory.
- [x] Vulnerability Detector: Vulnerability support.
- [x] Active Response.
- [x] Logcollector: Decoding and filtering of correct alerts from Logcollector.
- [x] csyslogd module. Testing forwards alerts via syslog.
- [ ] ~agentless functionality~, at the moment, is not possible to test it, wait until redesign: https://github.com/wazuh/wazuh/issues/14406
- [x] maild functionality, Check an email alerts.
- [x] clusterd functionality. Check two nodes cluster with master and worker, use nginx as load balancer to connect an agent.
- [x] integratord functionality. Check Virustotal integration alerts.

**Comment by jotacarma90** [comment]
## Update 7/12/2023
I have been preparing the environment and working on each of the necessary checks.
Nothing erroneous found so far, and no bugs related to any of the Wazuh modules.
Preparing full report of the whole report.

**Comment by jotacarma90** [comment]
# Testing

##   :green_circle: Wazuh-manager installation

Manager installed at the RHEL 9.3 machine by following [this guide](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html). Using vagrant box `generic/rhel9`.

<details><summary>Installation logs</summary>

```console
[root@rhel9 vagrant]# rpm --import https://packages.wazuh.com/key/GPG-KEY-WAZUH
[root@rhel9 vagrant]# echo -e '[wazuh]\ngpgcheck=1\ngpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH\nenabled=1\nname=EL-$releasever - Wazuh\nbaseurl=https://packages.wazuh.com/4.x/yum/\nprotect=1' | tee /etc/yum.repos.d/wazuh.repo
[wazuh]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-$releasever - Wazuh
baseurl=https://packages.wazuh.com/4.x/yum/
protect=1
[root@rhel9 vagrant]# yum -y install wazuh-manager
Extra Packages for Enterprise Linux 9 - x86_64                                                     13 MB/s |  20 MB     00:01    
EL-9 - Wazuh                                                                                       32 MB/s |  21 MB     00:00    
Last metadata expiration check: 0:00:04 ago on Tue 12 Dec 2023 11:10:34 AM UTC.
Dependencies resolved.
==================================================================================================================================
 Package                             Architecture                 Version                       Repository                   Size
==================================================================================================================================
Installing:
 wazuh-manager                       x86_64                       4.7.0-1                       wazuh                       165 M

Transaction Summary
==================================================================================================================================
Install  1 Package

Total download size: 165 M
Installed size: 600 M
Downloading Packages:
wazuh-manager-4.7.0-1.x86_64.rpm                                                                   59 MB/s | 165 MB     00:02    
----------------------------------------------------------------------------------------------------------------------------------
Total                                                                                              59 MB/s | 165 MB     00:02     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                          1/1 
  Running scriptlet: wazuh-manager-4.7.0-1.x86_64                                                                             1/1 
  Installing       : wazuh-manager-4.7.0-1.x86_64                                                                             1/1 
  Running scriptlet: wazuh-manager-4.7.0-1.x86_64                                                                             1/1 
  Verifying        : wazuh-manager-4.7.0-1.x86_64                                                                             1/1 
Installed products updated.

Installed:
  wazuh-manager-4.7.0-1.x86_64                                                                                                    

Complete!
[root@rhel9 vagrant]# /var/ossec/bin/wazuh-control restart
wazuh-clusterd not running...
wazuh-modulesd not running...
wazuh-monitord not running...
wazuh-logcollector not running...
wazuh-remoted not running...
wazuh-syscheckd not running...
wazuh-analysisd not running...
wazuh-maild not running...
wazuh-execd not running...
wazuh-db not running...
wazuh-authd not running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid not running...
Wazuh v4.7.0 Stopped
Starting Wazuh v4.7.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2023/12/12 11:14:01 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Completed.
[root@rhel9 vagrant]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.7.0"
WAZUH_REVISION="40704"
WAZUH_TYPE="server"
```

</details>

##   :green_circle: Enrollment and connectivity with an agent

It was neede to disable firewall to get agent connected:
`systemctl stop firewalld`

<details><summary>Connection logs</summary>

```
2023/12/12 11:28:06 wazuh-remoted[9450] secure.c:275 at handle_new_tcp_connection(): DEBUG: New TCP connection [12]
2023/12/12 11:28:06 wazuh-remoted[9450] secure.c:710 at HandleSecureMessage(): DEBUG: TCP socket 12 added to keystore.
2023/12/12 11:28:06 wazuh-remoted[9450] manager.c:300 at save_controlmsg(): DEBUG: Agent centos9 sent HC_STARTUP from '192.168.56.53'
2023/12/12 11:28:06 wazuh-remoted[9450] secure.c:707 at HandleSecureMessage(): DEBUG: TCP socket 12 already in keystore. Updating...
2023/12/12 11:28:06 wazuh-remoted[9450] manager.c:429 at save_controlmsg(): DEBUG: save_controlmsg(): inserting 'Linux |centos9 |5.14.0-378.el9.x86_64 |#1 SMP PREEMPT_DYNAMIC Thu Oct 19 18:39:36 UTC 2023 |x86_64 [CentOS Stream|centos: 9] - Wazuh v4.7.0
x merged.mg
#"_agent_ip":192.168.56.53
'
2023/12/12 11:28:06 wazuh-remoted[9450] manager.c:541 at assign_group_to_agent(): DEBUG: Agent '001' with file 'merged.mg' MD5 'x'
2023/12/12 11:28:06 wazuh-remoted[9450] manager.c:560 at assign_group_to_agent(): DEBUG: Group assigned: 'default'
2023/12/12 11:28:06 wazuh-remoted[9450] manager.c:1681 at wait_for_msgs(): DEBUG: Sending file 'default/merged.mg' to agent '001'.
2023/12/12 11:28:06 wazuh-remoted[9450] manager.c:1697 at wait_for_msgs(): DEBUG: End sending file 'default/merged.mg' to agent '001'.
```

</details>



##   :green_circle: Centralized configuration work correctly

Edit `/var/ossec/etc/shared/default/agent.conf`
<details><summary>agent.conf</summary>

```
<agent_config>
  <syscheck>
    <directories whodata="yes">/test</directories>
  </syscheck>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/file.log</location>
  </localfile>
</agent_config>
```

</details>



##   :green_circle: FIM: Decoding and filtering of correct alerts from FIM


<details><summary>Alert from FIM</summary>

```
** Alert 1702382243.568098: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2023 Dec 12 11:57:23 (centos9) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/test/file1' added
Mode: whodata

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Tue Dec 12 11:57:23 2023
 - Inode: 67275494
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - (Audit) User name: root
 - (Audit) Audit name: vagrant
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 6476
 - (Audit) Process name: /usr/bin/touch
 - (Audit) Process cwd: /home/vagrant
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 3246
 - (Audit) Parent process cwd: /home/vagrant

```

</details>





##   :green_circle: SCA: Policy support

SCA is officially supported on RHEL 9. Default configuration was used.

<details><summary>Connection logs</summary>

```
2023/12/12 11:29:49 sca: INFO: Module started.
2023/12/12 11:29:49 sca: INFO: Loaded policy '/var/ossec/ruleset/sca/cis_rhel9_linux.yml'
2023/12/12 11:29:49 sca: INFO: Starting Security Configuration Assessment scan.
2023/12/12 11:29:49 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_rhel9_linux.yml'
2023/12/12 11:29:54 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_rhel9_linux.yml'
2023/12/12 11:29:54 sca: INFO: Security Configuration Assessment scan finished. Duration: 5 seconds.
```

</details>
