### ISSUE TITLE
Stack use after return at database module unit tests

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#20733]
|Version|Test|Platform|
|---|---|---|
|4.4.1|`test_wm_database`|Ubuntu 23.04|

## Bug log

```yml
[ RUN      ] test_sync_keys_with_wdb_insert
=================================================================
==1267612==ERROR: AddressSanitizer: stack-use-after-return on address 0x7f070b200020 at pc 0x55666c0e52c6 bp 0x7ffd9f241ce0 sp 0x7ffd9f241cd0
READ of size 128 at 0x7f070b200020 thread T0
    #0 0x55666c0e52c5 in test_sync_keys_with_wdb_insert /root/wazuh-v4.7.1-rc2/src/unit_tests/wazuh_modules/database/test_wm_database.c:366
    #1 0x7f070db5caab  (/lib/x86_64-linux-gnu/libcmocka.so.0+0x5aab) (BuildId: 611dbb07b6f1c189c91c3f2b694a6708efe2987d)
    #2 0x7f070db5d192 in _cmocka_run_group_tests (/lib/x86_64-linux-gnu/libcmocka.so.0+0x6192) (BuildId: 611dbb07b6f1c189c91c3f2b694a6708efe2987d)
    #3 0x55666c0e8651 in main /root/wazuh-v4.7.1-rc2/src/unit_tests/wazuh_modules/database/test_wm_database.c:548
    #4 0x7f070d366a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #5 0x7f070d366b48 in __libc_start_main_impl ../csu/libc-start.c:360
    #6 0x55666c0e0874 in _start (/root/wazuh-v4.7.1-rc2/src/unit_tests/build/wazuh_modules/database/test_wm_database+0x26b874) (BuildId: c6e3b406c5c76dc7b725e38b27a347169690cf66)

Address 0x7f070b200020 is located in stack of thread T0 at offset 32 in frame
    #0 0x55666c0e0f86 in setup_keys_to_db /root/wazuh-v4.7.1-rc2/src/unit_tests/wazuh_modules/database/test_wm_database.c:50

  This frame has 1 object(s):
    [32, 160) 'keys' (line 51) <== Memory access at offset 32 is inside this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-return /root/wazuh-v4.7.1-rc2/src/unit_tests/wazuh_modules/database/test_wm_database.c:366 in test_sync_keys_with_wdb_insert
Shadow bytes around the buggy address:
  0x7f070b1ffd80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f070b1ffe00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f070b1ffe80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f070b1fff00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f070b1fff80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x7f070b200000: f5 f5 f5 f5[f5]f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x7f070b200080: f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00 00 00 00 00
  0x7f070b200100: f1 f1 f1 f1 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f070b200180: 00 00 00 00 f3 f3 f3 f3 00 00 00 00 00 00 00 00
  0x7f070b200200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x7f070b200280: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1267612==ABORTING
```

## Rationale

The unit test setup function is allocating `keys` in the stack but it's assigning it to the global `state`.

## Proposed fix

```diff
--- a/src/unit_tests/wazuh_modules/database/test_wm_database.c
+++ b/src/unit_tests/wazuh_modules/database/test_wm_database.c
@@ -63,20 +63,22 @@ int setup_keys_to_db(void **state) {
     key->ip = (os_ip *)1;
     key->raw_key = strdup("1234567890abcdef");

-    *state = &keys;
+    os_calloc(1, sizeof(keystore), *state);
+    memcpy(*state, &keys, sizeof(keystore));

     test_mode = 1;
     return OS_SUCCESS;
 }

 int teardown_keys_to_db(void **state) {
-    keystore keys = *((keystore *)*state);
-
-    os_free(keys.keyentries[0]->id);
-    os_free(keys.keyentries[0]->name);
-    os_free(keys.keyentries[0]->raw_key);
-    os_free(keys.keyentries[0]);
-    os_free(keys.keyentries);
+    keystore * keys = *(keystore **)state;
+
+    os_free(keys->keyentries[0]->id);
+    os_free(keys->keyentries[0]->name);
+    os_free(keys->keyentries[0]->raw_key);
+    os_free(keys->keyentries[0]);
+    os_free(keys->keyentries);
+    os_free(keys);

     test_mode = 0;
     return OS_SUCCESS;
```
