### ISSUE TITLE
Implement pre-commit hook for python files

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#20753]
|Wazuh version|Component|
|---|---|
| 4.9.0 | Framework, API, Wodles, Integrations |

## Description

In #18802 we decided to include a pre-commit hook, with linter and formatter capabilities, to validate some conventions before opening a PR.

In this issue, we'll track all the refactors needed to work correctly with the [pre-commit](https://pre-commit.com/) hook.

We decided to use the [Ruff](https://docs.astral.sh/ruff/) tool, which provides linter and formatter capabilities all in one tool.
The proposed `.ruff.toml` configuration to include is:

```toml
# Include the Framework Team-owned directories.
include = [
    "framework/**/*.py",
    "api/**/*.py",
    "wodles/**/*.py",
    "integrations/**/*.py",
]

# Same as Black.
line-length = 120
indent-width = 4

# Assume Python 3.7
target-version = "py37"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F", "I001", "C901", "D212"]
ignore = ["F405"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[per-file-ignores]
"wodles/**/*.py" = ["E402"]
"api/test/integration/env/configurations/**/*.py" = ["E402"]
"__init__.py" = ["F401"]

[format]
# Like Black, use double quotes for strings.
quote-style = "single"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
```

Also, is needed to write some documentation explaining how to get running the pre-commit hook and how to integrate this with the code editors.

## Related Issues:

- [x] #20755 
- [x] #20756
- [x] #20757
- [x] #20758
- [x] #20759
- [x] #21034 

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
Given that the pre-commit hook is local, I think we should also create a github action workflow to validate that the changes submitted in pull requests are correctly linted and formatted. We could use something like:

```yml
name: Lint
on: 
  pull_request:
    paths:
      - '.github/workflows/python-lint.yml'
      - 'api/**'
      - 'framework/**'
      - 'integrations/**'
      - 'wodles/**'

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: '.ruff.toml'
```
