### ISSUE TITLE
Unexpected errors in Vulnerability Detector Refactor

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#20785]
| Wazuh version                      | Commit | 
| ---------------------------------- | ------ |
| 4.8.0 - `dev-14153-vulndet-refactor` |  https://github.com/wazuh/wazuh/commit/2fd595e541e2d9437f1963f977c1e03da92d7cce      |

## Description

A comprehensive testing effort has been conducted for the [Vulnerability Detector refactor](https://github.com/wazuh/wazuh/issues/14153). In the specified commit, numerous issues have been identified, addressing unexpected errors not only concerns related to the vulnerability detector module but also uncovering issues pertaining to the overall behavior of the environment.

### Infrastructure

The environment was deployed using the QA internal `Wazuh QA Envionment` pipeline.

The environment can be described as the following yaml but it consist on:
- Manager cluster: 2 nodes
- Indexer: Single node in the master manager
- Filebeat in both managers
- Agents: Six agents of different OS and architectures

<details>

<summary> Environment YAML description </summary>

```yaml
manager1:
    roles: [manager, filebeat, indexer]
    os: ubuntu_22
    type: master

manager2:
    roles: [manager, filebeat]
    os: ubuntu_22
    type: worker

agent1:
    roles: [agent]
    os: centos_7
    manager: manager1

agent2:
    roles: [agent]
    os: windows_11
    manager: manager2

agent3:
    roles: [agent]
    os: ubuntu_22
    manager: manager1

agent4:
    roles: [agent]
    os: centos_7
    manager: manager1
    architecture: arm64v8

agent5:
    roles: [agent]
    os: ubuntu_22
    manager: manager2
    architecture: arm64v8

agent6:
    roles: [agent]
    os: macos_1400
    manager: manager2
    architecture: arm64v8
```

</details>

### Packages

The used packages were created in the packages builder tier pipeline

- **Build**: https://ci.wazuh.info/job/Packages_builder_tier/3291/console

### Packages creation

- https://github.com/wazuh/wazuh-jenkins/issues/6066 

### QA Deploy and Provision tools
- https://github.com/wazuh/wazuh-jenkins/issues/6067

### Development

- https://github.com/wazuh/wazuh/issues/20786
- https://github.com/wazuh/wazuh/issues/20789
- https://github.com/wazuh/wazuh/issues/20790
- https://github.com/wazuh/wazuh/issues/20791
- https://github.com/wazuh/wazuh/issues/20793
- https://github.com/wazuh/wazuh/issues/20794
- https://github.com/wazuh/wazuh/issues/20912
- https://github.com/wazuh/wazuh/issues/20914
- https://github.com/wazuh/wazuh/issues/20915

## Evidences

- [Managers Logs](https://github.com/wazuh/wazuh/files/13662359/ManagerLogs.zip)
- [Wazuh QA Environment pipeline](https://ci.wazuh.info/job/Wazuh_QA_environment/776/console)

## Conclusion

- No Vulnerability alerts were triggered in the environment
- Multiple errors in the environment appears
- Minor Issues detected in packages creation and  QA provision tools
