### ISSUE TITLE
Create lint github action

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#21034]
## Description

In https://github.com/wazuh/wazuh/issues/20753, we are introducing a pre-commit hook to validate some conventions before opening a PR. 

Since the pre-commit hook is local and could be misconfigured or not present at all in the developer's development environment, this issue aims to create a github action that validates that the changes submitted in pull requests are correctly linted and formatted.

We could use something like

```yml
# framework-lint.yml
name: Lint
on: 
  pull_request:
    paths:
      - '.github/workflows/framework-lint.yml'
      - 'api/**'
      - 'framework/**'
      - 'integrations/**'
      - 'wodles/**'

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          src: '.ruff.toml'
```

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).
