### ISSUE TITLE
Dashboard does not displays alerts while `alert.log` file does in Docker deployments

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#21806]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta1 | Server | Docker deployment | Docker deployment  | Docker deployment |

|Related Issue|
|---|
| https://github.com/wazuh/wazuh/issues/21760 |

While performing the Deployment on Docker E2E test it has been found that the alerts reported by the agent, at least regarding to FIM, since this kind of alert was the tested one, are not shown in the dashboard while they are present in the `alert.log` file. 

If the mentioned file is checked by accessing the manager docker, alerts are recorded, but they are not present in the dashboard. The [deploy agent section](https://github.com/wazuh/wazuh/issues/21760#issuecomment-1931818261) details this scenario. This behavior has been found under single and multi-node docker deployment.

No events are displayed in the dashboard, but alerts are present in `alerts.log`.

``` console
root@agent3-ubu22:/home/vagrant/wazuh-docker/single-node# docker exec -it single-node-wazuh.manager-1 /bin/bash
root@agent3-ubu22:/home/vagrant/wazuh-docker/single-node# docker exec -it single-node-wazuh.manager-1 /bin/bash
root@wazuh:/# cat /var/ossec/logs/alerts/alerts.log | grep syscheck
** Alert 1707315611.1222916: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2024 Feb 07 14:20:11 (opensuse15) any->syscheck
** Alert 1707315692.1223599: - ossec,syscheck,syscheck_entry_deleted,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2024 Feb 07 14:21:32 (opensuse15) any->syscheck
```

![image](https://github.com/wazuh/wazuh/assets/119335479/a37b297c-eca8-4925-9a1a-9c6c28ae9480)

**Comment by vcerenu** [comment]
The injection of the `wazuh-template.yml` file was added within the execution of the ISM script, and the wazuh template parameters were removed from the `filebeat.yml `file, since it caused delays in injecting the template within the Wazuh indexer and the execution failed from the ISM script.

``` yaml
# Wazuh - Filebeat configuration file
filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.overwrite: true
setup.ilm.enabled: false
output.elasticsearch:
  hosts: ['https://wazuh.indexer:9200']
  #username:
  #password:
  #ssl.verification_mode:
  #ssl.certificate_authorities:
  #ssl.certificate:
  #ssl.key:

logging.metrics.enabled: false

seccomp:
  default_action: allow
  syscalls:
  - action: allow
    names:
    - rseq
```

This change caused Filebeat to not know the structure of `wazuh-template.yml` and not be able to send the Wazuh manger logs to the Wazuh indexer.

It is necessary to add the following parameters again:

``` yaml
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
```
