### ISSUE TITLE
Check Wazuh agent compatibility with the new version of Oracle-Linux-9.3 version 2024.01.26-0 

### ISSUE THREAD

**Issue by lchico** [wazuh/wazuh#22135]
# Description
Hello team, this issue is to check the full compatibility of Wazuh on the newfound version of Oracle-Linux-9.3-2024.01.26-0 operating system.

OSs checks issue: #22132

- Release notes: https://docs.oracle.com/en/operating-systems/oracle-linux/9/relnotes9.3/#Oracle-Linux-9

For this, it is necessary to perform the following tests to check that everything works as expected:

- [ ] Agent and server (if possible) installations.
- [ ] O.S. reporting in the interface.
- [ ] WPK  upgrade.
- [ ] Enrollment and connectivity with the manager.
- [ ] FIM: Real-time and who-data engines (if available).
- [ ] SCA: Policy support.
- [ ] Vulnerability Detector: Vulnerability support.
- [ ] Syscollector: Complete inventory.
- [ ] Active Response: port blocking.
- [ ] Log capture.

**Comment by lchico** [comment]
The new changes introduced between the last tested Oracle Linux 9.2 version and the new version could have an impact on the Wazuh agent. Therefore, I recommend checking this new OS.

**Comment by lchico** [comment]
# Update 

I have been preparing the environment and working on each of the necessary checks.

**Comment by lchico** [comment]
# Testing

## :green_circle: Agent and server, (enrollment and connectivity with the manager)

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/c95c55e5-7201-4d4f-8411-8a87edd5d739" >
</details>

<details>
<summary>Agent Log</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/dcea6fb5-5227-40be-95d4-e32fbbbdb177">
</details>

### :green_circle: FIM scheduled

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/90c02774-ba07-4e28-82c0-ce581f2f76c9">
</details>

## :green_circle: FIM Real-time
<details>
<summary>Configuration on the agent</summary>

  ```
    <frequency>4</frequency>
    <directories realtime="yes">/var/log/testrealtime</directories>
  ```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/9faed740-f957-49af-b72c-d651d2b1231b">
</details>

## :green_circle:  FIM Whodata

<details>
<summary>Configuration on the agent</summary>

  ```
    <directories check_all="yes" whodata="yes">/testwhodata</directories>
  ```
</details>

<details>
<summary>Alerts</summary>

  ```
    mkdir -p /var/log/testwhodata
    touch /var/log/testwhodata/file1
    rm /var/log/testwhodata/file1
  ```
 <img src="https://github.com/wazuh/wazuh/assets/21695385/6914724b-977a-4a3f-9eef-d7eb9fdf8ccc">
</details>


## :green_circle: Upgrade using WPK
From the manager run:
  ```
     /var/ossec/bin/agent_upgrade -a 001
  ```

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/773f669f-5e24-4ebb-abc8-208ad97af02c">
</details>


## :yellow_circle: SCA support
No official SCA policies are available ( [check](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/available-sca-policies.html) this list).

Since it is not listed at [CIS Benchmarks](https://downloads.cisecurity.org/#/), no issue will be created.

SCA module is tested anyway, with a custom policy.

Configuration

[This usecase](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/use-cases.html#detecting-keyword-in-a-file) is used to test SCA module.

<details>
<summary>Manager log:</summary>

```
** Alert 1712761114.643632: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2024 Apr 10 14:58:34 (66b4e4242b15) any->sca
Rule: 19007 (level 7) -> 'SCA use case: Keyword check: Ensure password is disabled in the test configuration file'
{"type":"check","id":506129585,"policy":"SCA use case: Keyword check","policy_id":"keyword_check","check":{"id":10000,"title":"Ensure password is disabled in the test configuration file","description":"Password is enabled in the test configuration file.","rationale":"Password is considered weak for the custom test application. Threat actors can brute-force your password.","remediation":"Disable password by setting the value of the password_enabled option to no.","rules":["f:/usr/share/testfile.txt -> r:^password_enabled: yes$"],"condition":"none","file":"/usr/share/testfile.txt","result":"failed"}}
sca.type: check
sca.scan_id: 506129585
sca.policy: SCA use case: Keyword check
sca.check.id: 10000
sca.check.title: Ensure password is disabled in the test configuration file
sca.check.description: Password is enabled in the test configuration file.
sca.check.rationale: Password is considered weak for the custom test application. Threat actors can brute-force your password.
sca.check.remediation: Disable password by setting the value of the password_enabled option to no.
sca.check.file: ["/usr/share/testfile.txt"]
sca.check.result: failed

** Alert 1712761118.645043: - ossec,syscheck,syscheck_entry_modified,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2024 Apr 10 14:58:38 (66b4e4242b15) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/var/log/testing' modified
Mode: scheduled
Changed attributes: inode,mtime
Old modification time was: '1712761099', now it is '1712761116'
Old inode was: '29240349', now it is '29240348'

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Wed Apr 10 14:58:36 2024
 - Inode: 29240348
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1712761121.646571: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2024 Apr 10 14:58:41 (66b4e4242b15) any->sca
Rule: 19005 (level 9) -> 'SCA summary: SCA use case: Keyword check: Score less than 30% (0)'
{"type":"summary","scan_id":506129585,"name":"SCA use case: Keyword check","policy_id":"keyword_check","file":"keywordcheck.yml","description":"Guidance for checking for a keyword or phrase in files on Ubuntu endpoints.","references":"https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/index.html,https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html","passed":0,"failed":1,"invalid":0,"total_checks":1,"score":0,"start_time":1712761109,"end_time":1712761109,"hash":"5d28a90f4498a81461efbaf6f628a19d9778390bb5c81a393dd936181cc3d826","hash_file":"a33741eefba60ba75052477564b607cc97bdf36c773194c7ead40f30e356ec4d","force_alert":"1"}
sca.type: summary
sca.scan_id: 506129585
sca.policy: SCA use case: Keyword check
sca.description: Guidance for checking for a keyword or phrase in files on Ubuntu endpoints.
sca.policy_id: keyword_check
sca.passed: 0
sca.failed: 1
sca.invalid: 0
sca.total_checks: 1
sca.score: 0
sca.file: keywordcheck.yml

```

</details>
<details>
<summary>Agent log:</summary>

```
2024/04/10 18:09:40 sca[8797] wm_sca.c:152 at wm_sca_main(): INFO: Module started.
2024/04/10 18:09:40 sca[8797] wm_sca.c:191 at wm_sca_main(): INFO: Loaded policy '/var/ossec/ruleset/sca/sca_unix_audit.yml'
2024/04/10 18:09:40 sca[8797] wm_sca.c:191 at wm_sca_main(): INFO: Loaded policy '/var/ossec/etc/custom-sca-files/keywordcheck.yml'
```

</details>

<details>
<summary>Inventory:</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/72868d31-2afe-4117-93b6-5614d746da5a">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/1b378263-1872-4a19-98c1-59dd8b62d168">
</details>

## :green_circle: Vulnerability detector
<details>
<summary>Manager Config</summary>

  ```
    <!-- RedHat OS vulnerabilities -->
    <provider name="redhat">
      <enabled>yes</enabled>
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os>8</os>
      <os>9</os>
      <update_interval>1m</update_interval>
      <os allow="Oracle Linux Server-9">9</os>
    </provider>
  ```
</details>

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/ed8aeee6-2fb5-4dab-b485-6033e730a06c">
</details>


## :green_circle: Active response

<details>
<summary>Manager configuration:</summary>

```
<ossec_config>
  <active-response>
    <disabled>no</disabled>
    <command>restart-wazuh</command>
    <location>defined-agent</location>
    <agent_id>001</agent_id>
    <level>7</level>
  </active-response>
</ossec_config>
```
</details>

<details>
<summary>Result:</summary>
<img src="https://github.com/wazuh/wazuh/assets/21695385/ce77258c-b01b-4d6a-80ec-9293b49aca0a">
</details>


## :green_circle: Log Capture

<details>
<summary>Agent configuration:</summary>

```
  <localfile>
    <location>/var/log/log_capture.log</location>
    <log_format>syslog</log_format>
  </localfile>
```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/d65b38c4-8e66-4cf7-8914-67b5106a0d34">
</details>


## :green_circle:  Syscollector


<details>
<summary>Inventory</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/df7599b2-4968-45a6-86dc-a0048d7e7226">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/e0bc6e64-722a-4b9d-bf7d-f4cde7d696e8">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/9a62ee6b-040b-4fd3-8ff4-9491d8321d93">
</details>
