### ISSUE TITLE
Delete `cache` API configuration

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#22372]
|Wazuh version|Component|
|---|---|
| 4.9 | API |

## Description
In the analysis of https://github.com/wazuh/wazuh/issues/20245 it was decided that we will delete the `cache` option in the API configuration. This issue aims to delete this configuration option and to delete all unit test, integration test and code related to it. We should also check other repositories of Wazuh to check if this configuration option is used and make the appropriate changes.

Documentation: [Link](https://documentation.wazuh.com/current/user-manual/api/configuration.html#cache).

**Comment by RamosFe** [comment]
## Update

Deleted all functionality related to the `cache` API configuration in PR https://github.com/wazuh/wazuh/pull/22416.

### Some comments for the reviewer
There are some instances where code related to the `cache` API configuration wasn't removed. The following special cases are:
- The deprecated `configuration_model.py` has a `CacheModel` representing the API configuration option. It wasn´t removed due to not being maintained and not used in any part of the code since `v4.0.4` as shown in the comment:
https://github.com/wazuh/wazuh/blob/3e8b3c9e721f46368b929db62057428c530a59a4/api/api/models/configuration_model.py#L239-L251
- The schema in `validator.py` continues to have the `cache` API option because we want to display a warning whenever this option is used. Deleting this from the schema will result in an error and it isn´t the expected behavior:
https://github.com/wazuh/wazuh/blob/3e8b3c9e721f46368b929db62057428c530a59a4/api/api/validator.py#L136-L143

  The warning was suggested in https://github.com/wazuh/wazuh/pull/22387#discussion_r1516085939:
https://github.com/wazuh/wazuh/blob/0e652e67053c3b06e54d9fae58de4ee8016eb43f/api/scripts/wazuh-apid.py#L14-L16
https://github.com/wazuh/wazuh/blob/14b96d88586a5857e29616f613222528e16d8c53/api/scripts/wazuh-apid.py#L215-L217

**Comment by RamosFe** [comment]
## Update

After searching through the other Wazuh repositories, no other reference to the `cache` API configuration option was found.

**Comment by RamosFe** [comment]
## Update

I continue debugging the following error in the IT:

```
test_manager_endpoints.tavern.yaml::PUT /manager/restart - Failed: Timeout on API callback. Could not find 'Listening on'
```

**Comment by RamosFe** [comment]
## Update
### Manager IT

Run the IT for the manager. All the errors are related to the following issue:  https://github.com/wazuh/wazuh/issues/22742
[test_manager_endpoints_results.txt](https://github.com/wazuh/wazuh/files/14937124/test_manager_endpoints_results.txt)

## Cluster IT
All test passed without any errors.
[test_cluster_endpoints_results.txt](https://github.com/wazuh/wazuh/files/14937148/test_cluster_endpoints_results.txt)

**Comment by RamosFe** [comment]
## Message test
Configuration:
```yaml
root@wazuh-master:/var/ossec/api/configuration# cat api.yaml 
host: 0.0.0.0
port: 55000

# Advanced configuration

https:
 enabled: yes
 key: "server.key"
 cert: "server.crt"
 use_ca: False
 ca: "ca.crt"

# Logging configuration
# Values for API log level: disabled, info, warning, error, debug, debug2 (each level includes the previous level).
logs:
 level: "info"
 format: "plain"

# Cross-origin resource sharing: https://github.com/aio-libs/aiohttp-cors#usage
cors:
 enabled: no
 source_route: "*"
 expose_headers: "*"
 allow_headers: "*"
 allow_credentials: no

# Access parameters
access:
  max_login_attempts: 10000
  max_request_per_minute: 10000

# Drop privileges (Run as wazuh user)
drop_privileges: yes

# Enable features under development
experimental_features: yes
root@wazuh-master:/var/ossec/api/configuration# vi api.yaml 
root@wazuh-master:/var/ossec/api/configuration# cd ..
root@wazuh-master:/var/ossec/api# cd configuration/
root@wazuh-master:/var/ossec/api/configuration# cat api.yaml 
host: 0.0.0.0
port: 55000

# Advanced configuration

cache:
 enabled: yes

https:
 enabled: yes
 key: "server.key"
 cert: "server.crt"
 use_ca: False
 ca: "ca.crt"

# Logging configuration
# Values for API log level: disabled, info, warning, error, debug, debug2 (each level includes the previous level).
logs:
 level: "info"
 format: "plain"

# Cross-origin resource sharing: https://github.com/aio-libs/aiohttp-cors#usage
cors:
 enabled: no
 source_route: "*"
 expose_headers: "*"
 allow_headers: "*"
 allow_credentials: no

# Access parameters
access:
  max_login_attempts: 10000
  max_request_per_minute: 10000

# Drop privileges (Run as wazuh user)
drop_privileges: yes

# Enable features under development
experimental_features: yes

```

Result after restart:
```
root@wazuh-master:/var/ossec/bin# ./wazuh-apid -f
wazuh-apid: Orphan child process 27156 was terminated.
wazuh-apid: Orphan child process 27157 was terminated.
wazuh-apid: Orphan child process 27160 was terminated.
wazuh-apid: Orphan child process 27163 was terminated.
2024/04/10 19:59:57 INFO: Starting API in foreground
2024/04/10 19:59:57 INFO: Checking RBAC database integrity...
2024/04/10 19:59:57 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
2024/04/10 19:59:57 INFO: RBAC database integrity check finished successfully
2024/04/10 20:00:01 WARNING: The `cache` API configuration option no longer take effect since 4.9.0 and will be completely removed in the next major release.
2024/04/10 20:00:01 INFO: Listening on 0.0.0.0:55000.
2024/04/10 20:00:01 INFO: Getting installation UID...
2024/04/10 20:00:01 INFO: Getting updates information...

```
