### ISSUE TITLE
Engine - correlation rules

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#22399]
### Description
We propose the implementation of a new job-based processing engine in our product to complement the existing event-based model. The goal is to provide users with the flexibility to define sets of rules that periodically execute queries in the indexer, generating new events based on specified conditions.

We want to integrate the new jobs system into our current event-based engine. This will allow users to define custom jobs that encapsulate a set of rules, queries, and conditions for event generation with the same syntax as the other decoders and rules. The jobs will be scheduled to run at specified intervals, and the rule engine will evaluate the conditions to generate new events.

### Overall design

```mermaid
flowchart TD

subgraph "indexer"
    ingest["ingest pipeline"] -- sec_events --> security_events_index
end

subgraph "engine"
    policy --> builder 
    builder -- creates --> execution_graph
    subgraph "execution_graph"

        decoders --> outputs
        decoders --> rules --> outputs
    end

    builder -- creates --> correlation_jobs
    uv["socket"] -- events --> queue -- events --> router -- events --> decoders 
    outputs -- sec_events --> ingest["ingest pipeline"]
    correlation_jobs --> scheduler --> execution --> correlation_queue
    correlation_queue --> outputs
end

execution -- request--> security_events_index -- response --> execution

```

### Proposed syntax

```yaml
name: correlation/brute_force_login/0
# module: wazuh

metadata:
  title: Login brute force detection
  description: >
    Checks for multiple failed login attempts from the same source IP address.
  compatibility: Wazuh Schema version 1.0
  versions:
    - Wazuh 5.*
  author:
    name: Wazuh, Inc.
    date: 07/03/2023
  references:
    - https://documentation.wazuh.com/...
    - https://documentation.wazuh.com/...
    - https://cti.wazuh.com/...

correlate:
    - period: 60
    - index: "wazuh-security-events-*"
    - query_type: sql
    - query: >
        SELECT count(*) AS count WHERE event.type = 'login' AND event.outcome = 'failure' AND timestamp >= NOW() - INTERVAL 10 MINUTES GROUP BY source.ip;

normalize:
  - map:
      - threat:
            enrichments:
            - indicator: 
            ...

```

### Functional requirements

- Correlation rules must use the same syntax as decoders and rules. We might want to add a new configuration section to show the query to be executed and the action to be taken.
- The scheduler must be able to run jobs at the specified intervals, planning job execution based on the rules requirements.
- We want to use a language plugin so the syntax of the query language is as easy as possible. We might want to add support for multiple plugins. Support for PPL and SQL seems to be a good start.

### Non-functional requirements

- We want to run multiple jobs concurrently.
- We want to limit how many concurrent jobs we can run.
- We want to detect indexer saturation and stop running jobs if the indexer cannot keep up with the load.
- We want to detect when the correlation jobs cannot keep up with the load and stop/skip running jobs.

### Implementation restrictions

- We want this implemented as part of the engine, and not in a separate program.
- We want to use the same syntax as the decoders and rules.

### Plan

- [ ] Design spike
- [ ] Implementation
- [ ] Testing
