### ISSUE TITLE
API cache option deprecation warning always appears even if it is not explicitly enabled

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#22567]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.8.0-beta4 | API | Manager | Packages | centOS7 |

### Description

During https://github.com/wazuh/wazuh/issues/22547 it has been detected that warning messages concerning the deprecation of the [cache option](https://github.com/wazuh/wazuh/pull/22387) always appear even if the cache option is not enabled by the user

```
2024/03/15 14:00:01 WARNING: The `cache` API configuration option was deprecated in 4.8.0 and will be removed in the next minor release.
```

We should consider avoiding showing this message if the user does not enable it explicitly

**Comment by RamosFe** [comment]
## Update

Added warning for only the cases where the user added the `cache` API option.

https://github.com/wazuh/wazuh/blob/be2f1aafd28465c8581dcddfeca75cd8c54a8085/api/api/configuration.py#L314-L316

And created a new unit test for testing this specific case:
https://github.com/wazuh/wazuh/blob/be2f1aafd28465c8581dcddfeca75cd8c54a8085/api/api/test/test_configuration.py#L159-L174

Results:
```
python3 -m pytest api/api/test/test_configuration.py 
========================================================================================================== test session starts ==========================================================================================================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.4.0
rootdir: /home/federamos/Documents/Wazuh/Repositories/wazuh/api/api
configfile: pytest.ini
plugins: asyncio-0.18.1, html-2.1.1, metadata-3.1.1, tavern-1.23.5, anyio-4.3.0, trio-0.8.0
asyncio: mode=auto
collected 49 items                                                                                                                                                                                                                      

api/api/test/test_configuration.py .................................................                                                                                                                                              [100%]

=========================================================================================================== warnings summary ============================================================================================================
api/api/validator.py:11
api/api/validator.py:11
  /home/federamos/Documents/Wazuh/Repositories/wazuh/api/api/validator.py:11: DeprecationWarning: Accessing jsonschema.draft4_format_checker is deprecated and will be removed in a future release. Instead, use the FORMAT_CHECKER attribute on the corresponding Validator.
    from jsonschema import draft4_format_checker

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
==================================================================================================== 49 passed, 2 warnings in 1.52s =====================================================================================================
``

**Comment by RamosFe** [comment]
## Option enabled
```
root@wazuh-master:/var/ossec/api/configuration# cat api.yaml 
# USE THIS FILE AS A TEMPLATE. UNCOMMENT LINES TO APPLY CUSTOM CONFIGURATION

# host: 0.0.0.0
# port: 55000

# Advanced configuration

# https:
#  enabled: yes
#  key: "server.key"
#  cert: "server.crt"
#  use_ca: False
#  ca: "ca.crt"
#  ssl_protocol: "auto"
#  ssl_ciphers: ""

# Modify API's intervals (time in seconds)
# intervals:
#   request_timeout: 10

# Logging configuration
# Values for API log level: disabled, info, warning, error, debug, debug2 (each level includes the previous level).
# Values for API log max_size: <value><unit>. Valid units: K (kilobytes), M (megabytes)
# Enabling the API log max_size will disable the time based rotation (on midnight)
# logs:
#  level: "info"
#  format: "plain"
#  max_size:
#    enabled: False
#    size: "1M"

# Cross-origin resource sharing: https://github.com/aio-libs/aiohttp-cors#usage
# cors:
#  enabled: no
#  source_route: "*"
#  expose_headers: "*"
#  allow_headers: "*"
#  allow_credentials: no

# Cache (time in seconds)
cache:
  enabled: yes
  time: 0.750

# Access parameters
access:
#  max_login_attempts: 50
#  block_time: 300
  max_request_per_minute: 99999

# Drop privileges (Run as wazuh user)
# drop_privileges: yes

# Enable features under development
# experimental_features: no

# Maximum body size that the API can accept, in bytes (0 -> limitless)
# max_upload_size: 10485760

# Uploadable Wazuh configuration sections
# upload_configuration:
#   remote_commands:
#     localfile:
#       allow: yes
#       exceptions: []
#     wodle_command:
#       allow: yes
#       exceptions: []
#   limits:
#     eps:
#       allow: yes
#   agents:
#     allow_higher_versions:
#       allow: yes
```
### Results
```
root@wazuh-master:/var/ossec/bin# ./wazuh-control restart
The `cache` API configuration option was deprecated in 4.8.0 and will be removed in the next minor release.
2024/03/18 17:59:58 wazuh-db[7965] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2024/03/18 17:59:58 wazuh-db[7965] main.c:125 at main(): DEBUG: Wazuh home directory: /var/ossec
2024/03/18 17:59:59 wazuh-remoted[7970] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2024/03/18 17:59:59 wazuh-remoted[7970] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2024/03/18 17:59:59 wazuh-remoted[7970] main.c:148 at main(): DEBUG: This is not a worker
2024/03/18 17:59:59 wazuh-modulesd:router: INFO: Loaded router module.
2024/03/18 17:59:59 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
The `cache` API configuration option was deprecated in 4.8.0 and will be removed in the next minor release.
Killing wazuh-clusterd...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.8.0 Stopped
Starting Wazuh v4.8.0...
The `cache` API configuration option was deprecated in 4.8.0 and will be removed in the next minor release.
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2024/03/18 18:00:06 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
2024/03/18 18:00:06 wazuh-authd[8254] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2024/03/18 18:00:06 wazuh-authd[8254] config.c:24 at authd_read_config(): DEBUG: Reading configuration 'etc/ossec.conf'
2024/03/18 18:00:06 wazuh-authd[8254] authd-config.c:276 at Read_Authd(): DEBUG: The tag <force><after_registration_time> is not defined. Applied default value: '3600'
2024/03/18 18:00:06 wazuh-authd[8254] authd-config.c:278 at Read_Authd(): DEBUG: The tag <force><key_mismatch> is not defined. Applied default value: 'true'
2024/03/18 18:00:06 wazuh-authd[8254] main-server.c:465 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-authd...
2024/03/18 18:00:06 wazuh-db[8263] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2024/03/18 18:00:06 wazuh-db[8263] main.c:125 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
2024/03/18 18:00:07 wazuh-remoted[8328] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2024/03/18 18:00:07 wazuh-remoted[8328] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2024/03/18 18:00:07 wazuh-remoted[8328] main.c:148 at main(): DEBUG: This is not a worker
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
2024/03/18 18:00:08 wazuh-modulesd:router: INFO: Loaded router module.
2024/03/18 18:00:08 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
Started wazuh-modulesd...
Started wazuh-clusterd...
Completed.
``
