### ISSUE TITLE
S3 permissions to Wazuh via service account

### ISSUE THREAD

**Issue by anjanaradhakrishnan** [wazuh/wazuh#22604]
We need to achieve the Wazuh Integration with S3 using [Kubernetes Service account](https://kubernetes.io/docs/concepts/security/service-accounts/).
I'm trying to annotate a k8s service account with an IAM role. For that I have created a role with trust relationship(Which Authenticates the AWS services with Cluster Pods) and necessary permissions and created a service account with the created role ARN.

```
apiVersion: v1
kind: ServiceAccount
metadata:
    name: wazuh-service-account
    namespace: wazuh
    annotations:
        eks.amazonaws.com/role-arn: "arn:aws-us-gov:iam::xxx:role/wazuh-ph-sa-role" 
```
In the deployment file of wazuh-Manager added the service account.

```
spec:
    serviceAccountName: wazuh-service-account
```
This is working and I'm able to access the s3 bucket from the Wazuh Manager pod while doing aws s3 ls.
But Not sure why the wazuh is not able access the bucket, We are getting the below error in integration.log file
```
2024/03/11 10:26:14 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.
```
This is the integration added in the ossec.conf

```
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>1m</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>yes</skip_on_error>
  <bucket type="cloudtrail">
    <name>cloudtrail</name>
  </bucket>
  <bucket type="guardduty">
    <name>guardduty</name>
  </bucket>  
</wodle>
```
