### ISSUE TITLE
Update OpenScap content

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2299]
There exist new Scap Security Policies which we should include into the content for the OpenScap module. [Here](https://github.com/ComplianceAsCode/content/releases) we can find policies for OS like Fedora (currently we only support Fedora 24) or Ubuntu 18.

**Comment by juan70** [comment]
# Status
2019-02-05
----------
- There are updates for all the existing oscap XML files. The new files are bigger than the older ones: centos6, centos7, debian8, rhel6, rhel7, ubuntu1404, ubuntu1604.
- Some new files: fedora (no version, generic?), centos8, rhel8, ubuntu1804
- File for `cve-ubuntu-xenial-oval.xml` is not part of the scap archives. Found the most recent one: https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.xenial.cve.oval.xml. Updated 05-Feb-2019 11:23  44M. The old one currently in Wazuh sources is 31M.
- The errors described in issue https://github.com/wazuh/wazuh/issues/2272 are not reproduced in v3.8 nor in 3.9 using the current file `cve-ubuntu-xenial-oval.xml`.
- Tried scanning with the recent file from Canonical `com.ubuntu.xenial.cve.oval.xml` (it takes a very long time). The alerts finally show up.

**Comment by asucrews** [comment]
oval for ubuntu 18.04 https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.bionic.cve.oval.xml

**Comment by ruslantum** [comment]
> oval for ubuntu 18.04 https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.bionic.cve.oval.xml

Hey @asucrews unfortunately the oval file you provided also results in an error:
wazuh-modulesd:oscap: ERROR: Internal error. Exiting...

Here is my shared agent config:
```
<agent_config profile="ubuntu18">
  <wodle name="open-scap">
    <disabled>no</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>
  
    <content type="oval" path="cve-ubuntu-bionic-oval.xml">
    </content>
  </wodle>
</agent_config>
```

And my ansible task to get the oval:
```
        - name: Download Ubuntu 18 (bionic) oval definitions
          get_url:
            url: https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.bionic.cve.oval.xml
            dest: /var/ossec/wodles/oscap/content/cve-ubuntu-bionic-oval.xml
            mode: 0640
            owner: root
            group: ossec
```
