### ISSUE TITLE
Wazuh packages redesign tier 1 - Use secret for AWS region

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23085]
| Related Issue|
|---|
| https://github.com/wazuh/internal-devel-requests/issues/1073 |

# Description

Iit is needed for all repositories involved in the Packages redesign objective to add an authentication step to AWS, so the workflows do not use a hardcoded region

The secret name is: `CI_AWS_REGION`

```
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CI_INTERNAL_DEVELOPMENT_BUCKET_USER_SECRET_KEY }}
          aws-region: ${{ secrets.CI_AWS_REGION }}
```

We have included these changes directly in a commit in the PR to migrate the workflows to the new private repository:
https://github.com/wazuh/wazuh-agent-packages/pull/2/commits/c7087dad95bb89bd898568f503c1b5ceb8015bd2
