### ISSUE TITLE
Missing Nodejs CVE-2022-0778 vulnerability for Windows agent 

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#23192]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta6 | Vulnerability Detection | Manager | Packages | Ubuntu 22 |

During [Additional E2E Tests for Vulnerability Detector](https://github.com/wazuh/wazuh-qa/issues/4914) it has been detected that `CVE-2022-0778` vulnerability is not triggered in the Windows Server host

Related: https://github.com/wazuh/wazuh/issues/22906

### Environment

```yaml
manager1:
    roles: [manager, filebeat, indexer]
    os: ubuntu_22
    type: master

manager2:
    roles: [manager, filebeat]
    os: ubuntu_22
    type: worker

agent1:
    roles: [agent]
    os: centos_7
    manager: manager1

agent2:
    roles: [agent]
    os: windows_11
    manager: manager2

agent3:
    roles: [agent]
    os: ubuntu_22
    manager: manager1

agent4:
    roles: [agent]
    os: centos_7
    manager: manager1
    architecture: arm64v8

agent5:
    roles: [agent]
    os: ubuntu_22
    manager: manager2
    architecture: arm64v8

agent6:
    roles: [agent]
    os: macos_1400
    manager: manager1
    architecture: arm64v8

```

### Evidences

**Node.js Package**: https://nodejs.org/dist/v17.0.1/node-v17.0.1-x64.msi
**Windows Logs**: [WindowsAgentLogs.zip](https://github.com/wazuh/wazuh/files/15162235/e4a5789c-9763-46f3-8ab1-8455d5fded95.zip)
**Manager logs**: [WorkerLogs.zip](https://github.com/wazuh/wazuh/files/15161975/bfa234dd-46d8-4a8b-ac9f-06df8a7a52b6.zip)
**Triggered Node.js vulnerabilities**:

<details>

```
    "agent2": [
        [
            "CVE-2021-4044",
            "Node.js",
            "17.0.1",
            "x86_64"
        ],
        [
            "CVE-2021-44531",
            "Node.js",
            "17.0.1",
            "x86_64"
        ],
        [
            "CVE-2021-44532",
            "Node.js",
            "17.0.1",
            "x86_64"
        ],
        [
            "CVE-2021-44533",
            "Node.js",
            "17.0.1",
            "x86_64"
        ],
        [
            "CVE-2022-21824",
            "Node.js",
            "17.0.1",
            "x86_64"
        ]
    ]
```

</details>
