### ISSUE TITLE
Add API option to set whether users can use the `virustotal` public api key in the `ossec.conf`

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#23741]
|Component|
|---|
| Wazuh API |

## Description

We need a new development, similar to what was done for the `<limits>` and `<indexer>` blocks, to prevent users from using Public VirustTotal API keys in the `<integration><name>virustotal</name>` block ([link](https://documentation.wazuh.com/current/user-manual/manager/manual-integration.html#virustotal))
```XML
<integration>
  <name>virustotal</name>
  <api_key><API_KEY></api_key>
  <group>syscheck</group>
  <alert_format>json</alert_format>
</integration>
```

Using or not the Public API key shown above should only be allowed when explicitly permitted in the `api.yaml` (it will be allowed by default). Therefore, a new configuration must be added:
```YAML
# Uploadable Wazuh configuration sections
 upload_configuration:
   integrations:
     virustotal:
       public_key:
         allow: yes
         minimum_quota: 240
```

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (**unit tests**, API integration tests, [**API configuration IT**](https://github.com/wazuh/wazuh/tree/master/tests/integration/test_api/test_config)).
- [x] **Changelog**.
- [x] **Documentation**.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

> [!NOTE]
> Related issues:
> - https://github.com/wazuh/wazuh/issues/16520
> - https://github.com/wazuh/wazuh/issues/22656
