### ISSUE TITLE
Support new OSs - RHEL 8.10 - Test agent package

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23886]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23879 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 1 | Yes | Minor |

Requested testing code:
:white_circle: Requested.
:black_circle: Not requested.

Result code:
:green_circle: Completed: Test finished with success. 
:red_circle: Completed with failures.
:yellow_circle: Completed with known issues.

**Requested checks by tier:**
|| Tier 1 | Tier 2 | Tier 3 | Result |
|-|-|-|-|-| 
| **Log collection - System events** | :white_circle: | :white_circle: | :white_circle: | :green_circle: |
| **Log collection - Log files** | :white_circle: | :white_circle: | :white_circle: | :green_circle: |
| **Log collection -Command execution** | :white_circle: | :white_circle: | :white_circle: | :green_circle: | 
| **FIM - Scheduled** | :white_circle: | :white_circle: | :white_circle: | :green_circle: |
| **FIM - Realtime** | :white_circle: | :black_circle: | :black_circle: | :green_circle: |
| **FIM - Whodata** | :white_circle: | :black_circle: | :black_circle: | :green_circle: |
| **SCA** | :white_circle: | :white_circle: | :black_circle: | :green_circle: |
| **Inventory** | :white_circle: | :white_circle: | :white_circle: | :green_circle: |
| **Active response** | :white_circle: | :white_circle: | :black_circle: | :green_circle: |
| **Remote upgrade** | :white_circle: | :black_circle: | :black_circle: | :green_circle: |
| **Command monitoring** | :white_circle: | :white_circle: | :black_circle: | :green_circle: |
| **Wodles** | :white_circle: | :black_circle: | :black_circle: | :green_circle: |

**Comment by mjcr99** [comment]
## Update
**(05/06/2024)** I have not managed to find a valid box to deploy RHEL 8.10, I have tried using 8.9 and updating it using the Rocky Linux 8.10 repositories, but the version is not fully updated although I was able to download successfully packages.

**Comment by jotacarma90** [comment]
# Testing

## :green_circle: Install wazuh-agent
<details>
<summary>Os information</summary>

```
[ec2-user@ip-172-31-82-59 ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.10 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.10 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.10
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"

```
</details>

<details>
<summary>Install wazuh-agent</summary>

```
[root@ip-172-31-82-59 ec2-user]# rpm --import https://packages.wazuh.com/key/GPG-KEY-WAZUH
[root@ip-172-31-82-59 ec2-user]# cat > /etc/yum.repos.d/wazuh.repo << EOF
> [wazuh]
> gpgcheck=1
> gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
> enabled=1
> name=EL-\$releasever - Wazuh
> baseurl=https://packages.wazuh.com/4.x/yum/
> protect=1
> EOF
[root@ip-172-31-82-59 ec2-user]# WAZUH_MANAGER="xxx.xxx.xxx.xxx" yum install wazuh-agent
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

EL-8 - Wazuh                                                                  63 MB/s |  28 MB     00:00
Last metadata expiration check: 0:00:12 ago on Mon 10 Jun 2024 03:21:39 PM UTC.
Dependencies resolved.
============================================================================================================= Package                      Architecture            Version                   Repository              Size =============================================================================================================Installing:
 wazuh-agent                  x86_64                  4.7.5-1                   wazuh                  9.0 M

Transaction Summary
=============================================================================================================Install  1 Package

Total download size: 9.0 M
Installed size: 26 M
Is this ok [y/N]: y
Downloading Packages:
wazuh-agent-4.7.5-1.x86_64.rpm                                                53 MB/s | 9.0 MB     00:00
-------------------------------------------------------------------------------------------------------------Total                                                                         52 MB/s | 9.0 MB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                     1/1
  Running scriptlet: wazuh-agent-4.7.5-1.x86_64                                                          1/1
  Installing       : wazuh-agent-4.7.5-1.x86_64                                                          1/1
  Running scriptlet: wazuh-agent-4.7.5-1.x86_64                                                          1/1
  Verifying        : wazuh-agent-4.7.5-1.x86_64                                                          1/1 Installed products updated.

Installed:
  wazuh-agent-4.7.5-1.x86_64

Complete!
```

[I followed this documentation](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html)

</details>

## :green_circle: Agent and server, (enrollment and connectivity with the manager)

<details>
<summary>Dashboard</summary>

![image](https://github.com/wazuh/wazuh/assets/60003131/99e86740-4143-4a49-a0da-95b2299fa953)

</details>

<details>
<summary>Agent Log</summary>

```
2024/06/10 15:29:33 wazuh-agentd: INFO: Trying to connect to server ([xxx.xxx.xxx.xxx]:1514/tcp).
2024/06/10 15:29:33 wazuh-agentd: INFO: (4102): Connected to the server ([xxx.xxx.xxx.xxx]:1514/tcp).
```

</details>

## :green_circle: Log files

<details>
<summary>Configuration</summary>

The following default configuration is tested:

```xml
  <localfile>
    <log_format>audit</log_format>
    <location>/var/log/audit/audit.log</location>
  </localfile>
```
</details>

<details>
<summary>Test</summary>
```xml
/var/ossec/bin/wazuh-control restart
```
In the ossec.log from the agent we can see:
```log
2024/06/10 15:29:35 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/log/audit/audit.log'
```
</details>

<details>
<summary>Result</summary>

Alert comes when we set whodata as a monitoring method.

```log
** Alert 1718033877.1246914: - audit,audit_configuration,gdpr_IV_30.1.g,gpg13_10.1,
2024 Jun 10 15:37:57 (ip-172-31-82-59.ec2.internal) any->/var/log/audit/audit.log
Rule: 80705 (level 3) -> 'Auditd: Configuration changed.'
type=CONFIG_CHANGE msg=audit(1718033876.425:475): op=set audit_backlog_wait_time=60000 old=60000 auid=4294967295 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 res=1AUID="unset" type=SYSCALL msg=audit(1718033876.425:475): arch=c000003e syscall=44 success=yes exit=60 a0=3 a1=7ffeb1d15310 a2=3c a3=0 items=0 ppid=12165 pid=12181 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="auditctl" exe="/usr/sbin/auditctl" subj=system_u:system_r:unconfined_service_t:s0 key=(null)ARCH=x86_64 SYSCALL=sendto AUID="unset" UID="root" GID="root" EUID="root" SUID="root" FSUID="root" EGID="root" SGID="root" FSGID="root" type=PROCTITLE msg=audit(1718033876.425:475): proctitle=2F7362696E2F617564697463746C002D52002F6574632F61756469742F61756469742E72756C6573
audit.type: CONFIG_CHANGE
audit.id: 475
audit.key: null
```
</details>

## :green_circle: System events
<details>
<summary>Configuration</summary>

From the agent, we have to install `rsyslog` and add the following code to the `ossec.conf` file:

```xml
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/secure</location>
  </localfile>
```
</details>

<details>
<summary>Test</summary>

An `ssh` connection is tried with a non-existing user with the following command:

```
# User: test does not exist.
ssh xxx.xxx.xxx.xxx -l test
```
</details>

<details>
<summary>Result</summary>

The following alert is generated in the server:

```
** Alert 1718034098.1257907: - syslog,sshd,authentication_failed,gdpr_IV_35.7.d,gdpr_IV_32.2,gpg13_7.1,hipaa_164.312.b,invalid_login,nist_800_53_AU.14,nist_800_53_AC.7,nist_800_53_AU.6,pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_10.6.1,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2024 Jun 10 15:41:38 (ip-172-31-82-59.ec2.internal) any->/var/log/secure
Rule: 5710 (level 5) -> 'sshd: Attempt to login using a non-existent user'
Src IP: 79.117.201.10
Src Port: 54757
User: test
Jun 10 15:41:37 ip-172-31-82-59 sshd[14321]: Connection reset by invalid user test 79.117.201.10 port 54757 [preauth]

```

</details>

## :green_circle: Command execution
<details>
<summary>Configuration</summary>

From the agent, we have to install `rsyslog` and add the following code to the `ossec.conf` file:

```xml
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/secure</location>
  </localfile>
```
</details>


<details>
<summary>Test</summary>

The user is changed to the root one:
```
[root@ip-172-31-82-59 ec2-user]# sudo su
```
</details>
<details>
<summary>Result</summary>

The following alert is generated in the server:
```
** Alert 1718034203.1271904: - syslog,sudo,
2024 Jun 10 15:43:23 (ip-172-31-82-59.ec2.internal) any->/var/log/secure
Rule: 5403 (level 4) -> 'First time user executed sudo.'
User: root
Jun 10 15:43:22 ip-172-31-82-59 sudo[15514]:    root : TTY=pts/1 ; PWD=/home/ec2-user ; USER=root ; COMMAND=/bin/su
tty: pts/1
pwd: /home/ec2-user
command: /bin/su
```
</details>




### :green_circle: FIM scheduled
<details>
<summary>Result</summary>

  ```
2024/06/10 15:44:40 wazuh-syscheckd[15653] create_db.c:499 at fim_scan(): INFO: (6008): File integrity monitoring scan started.
2024/06/10 15:44:40 wazuh-syscheckd[15653] run_check.c:124 at send_syscheck_msg(): DEBUG: (6321): Sending FIM event: {"type":"scan_start","data":{"timestamp":1718034280}}
2024/06/10 15:44:40 wazuh-syscheckd[15653] create_db.c:511 at fim_scan(): DEBUG: (6348): Size of 'queue/diff' folder: 0.00000 KB.
2024/06/10 15:44:40 wazuh-syscheckd[15653] run_realtime.c:109 at fim_add_inotify_watch(): DEBUG: (6227): Directory added for real time monitoring: '/testwhodata'
2024/06/10 15:44:40 wazuh-syscheckd[15653] run_realtime.c:109 at fim_add_inotify_watch(): DEBUG: (6227): Directory added for real time monitoring: '/var/log/testrealtime'
2024/06/10 15:44:40 wazuh-syscheckd[15653] create_db.c:614 at fim_scan(): INFO: (6009): File integrity monitoring scan ended.
2024/06/10 15:44:40 wazuh-syscheckd[15653] run_check.c:124 at send_syscheck_msg(): DEBUG: (6321): Sending FIM event: {"type":"scan_end","data":{"timestamp":1718034280}}
2024/06/10 15:44:40 wazuh-syscheckd[15653] create_db.c:1822 at fim_print_info(): DEBUG: (6330): The scan has been running during: 0.007 sec (0.002 clock sec)
2024/06/10 15:44:40 wazuh-syscheckd[15653] create_db.c:1837 at fim_print_info(): DEBUG: (6336): Fim inode entries: '0', path count: '0'
  ```

</details>

## :green_circle: FIM Real-time
<details>
<summary>Configuration on the agent</summary>

```
    <frequency>4</frequency>
    <directories realtime="yes">/var/log/testrealtime</directories>
```
</details>

<details>
<summary>Result</summary>

```
** Alert 1718034436.1280012: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2024 Jun 10 15:47:16 (ip-172-31-82-59.ec2.internal) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/var/log/testrealtime/file1' added
Mode: realtime

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Mon Jun 10 15:47:16 2024
 - Inode: 8916881
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

</details>

## :green_circle:  FIM Whodata
<details>
<summary>I had to install audispd-plugins</summary>

```
[root@ip-172-31-82-59 ec2-user]# yum install audispd-plugins
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Last metadata expiration check: 0:30:13 ago on Mon 10 Jun 2024 03:21:39 PM UTC.
Dependencies resolved.
============================================================================================================= Package                   Architecture     Version                  Repository                         Size =============================================================================================================Installing:
 audispd-plugins           x86_64           3.1.2-1.el8              rhel-8-baseos-rhui-rpms            54 k

Transaction Summary
=============================================================================================================Install  1 Package

Total download size: 54 k
Installed size: 90 k
Is this ok [y/N]: y
Downloading Packages:
audispd-plugins-3.1.2-1.el8.x86_64.rpm                                       1.3 MB/s |  54 kB     00:00
-------------------------------------------------------------------------------------------------------------Total                                                                        760 kB/s |  54 kB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                     1/1
  Installing       : audispd-plugins-3.1.2-1.el8.x86_64                                                  1/1
  Running scriptlet: audispd-plugins-3.1.2-1.el8.x86_64                                                  1/1
  Verifying        : audispd-plugins-3.1.2-1.el8.x86_64                                                  1/1 Installed products updated.

Installed:
  audispd-plugins-3.1.2-1.el8.x86_64

Complete!
```

</details>

<details>
<summary>Configuration on the agent</summary>

  ```
    <directories check_all="yes" whodata="yes">/testwhodata</directories>
  ```
</details>

<details>
<summary>Alerts</summary>

```
** Alert 1718034759.1303776: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2024 Jun 10 15:52:39 (ip-172-31-82-59.ec2.internal) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/testwhodata/filetest' added
Mode: whodata

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Mon Jun 10 15:52:39 2024
 - Inode: 501731
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - (Audit) User name: root
 - (Audit) Audit name: ec2-user
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 18033
 - (Audit) Process name: /usr/bin/touch
 - (Audit) Process cwd: /home/ec2-user
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 15517
 - (Audit) Parent process cwd: /home/ec2-user
```

</details>
