### ISSUE TITLE
Support new OSs - SUSE Linux Enterprise 15 SP6 - Test agent package

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24139]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/24128 | https://github.com/wazuh/wazuh/issues/24134 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Minor |

# Plan

**Agent**
Requested testing code:
:white_circle: Requested.
:black_circle: Not requested.

Result code:
:green_circle: Completed: Test finished with success.
:red_circle: Completed with failures.
:yellow_circle: Completed with known issues.

- **Requested checks by tier:**

|| Tier 1 | Tier 2 | Tier 3 | Result |
|-|-|-|-|-|
| **Log collection - System events** | :white_circle: | :white_circle: | :white_circle: |:green_circle: |
| **Log collection - Log files** | :white_circle: | :white_circle: | :white_circle: |:green_circle: |
| **Log collection -Command execution** | :white_circle: | :white_circle: | :white_circle: |:green_circle: |
| **FIM - Scheduled** | :white_circle: | :white_circle: | :white_circle: |:green_circle: |
| **FIM - Realtime** | :white_circle: | :black_circle: | :black_circle: |:green_circle: |
| **FIM - Whodata** | :white_circle: | :black_circle: | :black_circle: |:green_circle: |
| **SCA** | :white_circle: | :white_circle: | :black_circle: |:green_circle: |
| **Inventory** | :white_circle: | :white_circle: | :white_circle: |:green_circle: |
| **Active response** | :white_circle: | :white_circle: | :black_circle: |:green_circle: |
| **Remote upgrade** | :white_circle: | :black_circle: | :black_circle: |:green_circle: |
| **Command monitoring** | :white_circle: | :white_circle: | :black_circle: |:green_circle: |
| **Wodles** | :white_circle: | :black_circle: | :black_circle: |:green_circle: |

**Comment by lchico** [comment]
# Testing

## :green_circle: Agent package install (enrollment and connectivity with the manager)

<details>
<summary>OS information</summary>

```console
ec2-user@ip-172-31-33-170:~> cat /etc/os-release
NAME="SLES"
VERSION="15-SP6"
VERSION_ID="15.6"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP6"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp6"
DOCUMENTATION_URL="https://documentation.suse.com/"
```

</details>

<details>
<summary>Package install</summary>

```console
rpm --import https://packages.wazuh.com/key/GPG-KEY-WAZUH
cat > /etc/zypp/repos.d/wazuh.repo <<\EOF
[wazuh]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-$releasever - Wazuh
baseurl=https://packages.wazuh.com/4.x/yum/
protect=1
EOF
zypper refresh

WAZUH_MANAGER="xx.xxx.xx.xx" zypper install wazuh-agent-4.7.2-1
```
</details>

<details>
<summary>Agent enrollment and connection</summary>

```bash
2024/06/19 18:25:20 wazuh-agentd: INFO: Version detected -> Linux |ip-172-31-33-170 |6.4.0-150600.21-default |#1 SMP PREEMPT_DYNAMIC Thu May 16 11:09:22 UTC 2024 (36c1e09) |x86_64 [SLES|sles: 15-SP6] - Wazuh v4.7.2
2024/06/19 18:25:20 wazuh-agentd: INFO: Started (pid: 8655).
2024/06/19 18:25:20 wazuh-agentd: INFO: Using AES as encryption method.
2024/06/19 18:25:20 wazuh-agentd: INFO: Trying to connect to server ([xx.xxx.xx.xx]:1514/tcp).
2024/06/19 18:25:20 wazuh-agentd: INFO: (4102): Connected to the server ([xx.xxx.xx.xx]:1514/tcp).
```
</details>

## :green_circle: Log files

<details>
<summary>Configuration</summary>

The following default configuration is tested:

```xml
  <localfile>
    <log_format>audit</log_format>
    <location>/var/log/audit/audit.log</location>
  </localfile>
```
</details>

<details>
<summary>Test</summary>

```xml
/var/ossec/bin/wazuh-control restart
```
In the ossec.log from the agent we can see:
```log
2024/06/19 18:36:58 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/log/audit/audit.log'.
```
</details>

<details>
<summary>Result</summary>

After restarting, enable whodata:


```log
** Alert 1718828216.649019: - audit,audit_configuration,gdpr_IV_30.1.g,gpg13_10.1,
2024 Jun 19 20:16:56 (ip-172-31-33-170) any->/var/log/audit/audit.log
Rule: 80705 (level 3) -> 'Auditd: Configuration changed.'
type=CONFIG_CHANGE msg=audit(1718828215.282:2424): auid=4294967295 ses=4294967295 subj=unconfined op=add_rule key="docker" list=4 res=1 type=SYSCALL msg=audit(1718828215.282:2424): arch=c000003e syscall=44 success=yes exit=1084 a0=3 a1=7ffe6c550540 a2=43c a3=0 items=1 ppid=25792 pid=25816 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="auditctl" exe="/usr/sbin/auditctl" subj=unconfined key=(null) type=SOCKADDR msg=audit(1718828215.282:2424): saddr=100000000000000000000000 type=CWD msg=audit(1718828215.282:2424): cwd="/" type=PATH msg=audit(1718828215.282:2424): item=0 name="/etc/default/" inode=25165971 dev=ca:03 mode=040755 ouid=0 ogid=0 rdev=00:00 nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0 type=PROCTITLE msg=audit(1718828215.282:2424): proctitle=2F7362696E2F617564697463746C002D52002F6574632F61756469742F61756469742E72756C6573
audit.type: CONFIG_CHANGE
audit.id: 2424
audit.key: null
```
</details>

## :green_circle: System events
<details>
<summary>Test</summary>

An **ssh** connection is tried with a non-existing user with the following command:

```
# User: non_exist_user does not exist.
ssh -p 2200 non_exist_user@XXXXX
```

</details>

<details>
<summary>Result</summary>

The following alert is generated in the server:

```
** Alert 1718823066.550930: - syslog,sshd,authentication_failed,gdpr_IV_35.7.d,gdpr_IV_32.2,gpg13_7.1,hipaa_164.312.b,invalid_login,nist_800_53_AU.14,nist_800_53_AC.7,nist_800_53_AU.6,pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_10.6.1,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2024 Jun 19 18:51:06 (ip-172-31-33-170) any->/var/log/messages
Rule: 5710 (level 5) -> 'sshd: Attempt to login using a non-existent user'
Src IP: ::1
Src Port: 57916
2024-06-19T18:51:05.461341+00:00 ip-172-31-33-170 sshd[14067]: Invalid user non_exist_user from ::1 port 57916

```

</details>

## :green_circle: Command execution

<details>
<summary>Test</summary>

The user is changed to the root one:
```
root@fedora:~# sudo su
```
</details>
<details>
<summary>Result</summary>

The following alert is generated in the server:
```
** Alert 1718822905.545675: - syslog,sudo,
2024 Jun 19 18:48:25 (ip-172-31-33-170) any->/var/log/messages
Rule: 5403 (level 4) -> 'First time user executed sudo.'
User: root
2024-06-19T18:48:25.638736+00:00 ip-172-31-33-170 sudo:     root : TTY=pts/1 ; PWD=/var/ossec/etc ; USER=root ; COMMAND=/usr/bin/su
tty: pts/1
pwd: /var/ossec/etc
command: /usr/bin/su
```
</details>

## :green_circle: Command monitoring

<details>
<summary>Configuration</summary>

The following configuration block is added to the agent:

```xml
<localfile>
  <log_format>full_command</log_format>
  <command>free -m | awk 'NR==2{printf "%.2f\t\t\n", $3*100/$2 }'</command>
  <alias>memory_utilization</alias>
  <frequency>120</frequency>
</localfile>
```

The following custom rule is added in the manager's `/var/ossec/etc/rules/local_rules.xml` file:

```xml
<group name="memory_utilization,">
  <rule id="100012" level="6">
    <if_sid>530</if_sid>
    <match>^ossec: output: 'memory_utilization'</match>
    <description>Memory utilization metric.</description>
  </rule>
</group>
```
</details>
<details>
<summary>Result</summary>

The server and agent are restarted. After this, the following alert is generated in the server:
```
** Alert 1718824367.565534: - memory_utilization,
2024 Jun 19 19:12:47 (ip-172-31-33-170) any->memory_utilization
Rule: 100012 (level 6) -> 'Memory utilization metric.'
ossec: output: 'memory_utilization':
19.60
```

</details>




## :green_circle: SCA support

<details>
<summary>Manager log:</summary>

```
** Alert 1718821406.517511: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2024 Jun 19 18:23:26 (ip-172-31-33-170) any->sca
Rule: 19004 (level 7) -> 'SCA summary: CIS SUSE Linux Enterprise 15 Benchmark v1.1.0: Score less than 50% (40)'
{"type":"summary","scan_id":1792207277,"name":"CIS SUSE Linux Enterprise 15 Benchmark v1.1.0","policy_id":"cis_sles15_linux","file":"cis_sles15_linux.yml","description":"This document provides prescriptive guidance for establishing a secure configuration posture for SUSE Linux Enterprise 12 systems running on x86 and x64 platforms. This document was tested against SUSE Linux Enterprise Server 15 SP1.","references":"https://www.cisecurity.org/cis-benchmarks/","passed":52,"failed":78,"invalid":7,"total_checks":137,"score":40,"start_time":1718821379,"end_time":1718821382,"hash":"744ed7d25dd3f0f2b9573c9775a450accb53d3c8036d6bc528407cff0d92f81f","hash_file":"cc26c1801f1c5fd4e61951b2cf6bd001415e9e1c4fb9a199e1fddb4868d62067","force_alert":"1","force_alert":"1"}
sca.type: summary
sca.scan_id: 1792207277
sca.policy: CIS SUSE Linux Enterprise 15 Benchmark v1.1.0
sca.description: This document provides prescriptive guidance for establishing a secure configuration posture for SUSE Linux Enterprise 12 systems running on x86 and x64 platforms. This document was tested against SUSE Linux Enterprise Server 15 SP1.
sca.policy_id: cis_sles15_linux
sca.passed: 52
sca.failed: 78
sca.invalid: 7
sca.total_checks: 137
sca.score: 40
sca.file: cis_sles15_linux.yml
```
</details>


### :green_circle: FIM scheduled

<details>
<summary>Agent configuration</summary>
The following configuration line is added in the syscheck block into the 'ossec.conf':

```
    <directories>/var/log</directories>
```
Then restart wazuh-agent.
</details>

<details>
<summary>Test</summary>

```
# Adds test_scheduled file
touch /var/log/test_scheduled
```
</details>

<details>
<summary>Result</summary>

```
** Alert 1718827705.621728: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2024 Jun 19 20:08:25 (ip-172-31-33-170) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/var/log/test_scheduled' added
Mode: scheduled

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Wed Jun 19 20:08:14 2024
 - Inode: 9135091
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

```
</details>




## :green_circle: FIM Real-time
<details>
<summary>Configuration on the agent</summary>

  ```
  # ossec.conf add
    <frequency>4</frequency>
    <directories realtime="yes">/var/log/testrealtime</directories>

  # To generate the alert run:
  touch /var/log/testrealtime/test_file
  ```
</details>

<details>
<summary>Result</summary>

 ```
** Alert 1718827974.629488: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2024 Jun 19 20:12:54 (ip-172-31-33-170) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/var/log/testrealtime/test_file' added
Mode: realtime

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Wed Jun 19 20:12:54 2024
 - Inode: 92275078
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```
</details>

## :green_circle:  FIM Whodata
<details>
<summary>I had to remove the rule "never, task"</summary>

```
vi /etc/audit/rules.d/audit.rules # Remove the line "-a never,task"
service auditd restart
service wazuh-agent restart
touch /var/log/whodata/test_file
```

</details>

<details>
<summary>Configuration on the agent</summary>

  ```
    <directories check_all="yes" whodata="yes">/var/log/whodata</directories>
  ```
</details>

<details>
<summary>Alerts</summary>

```
** Alert 1718830137.791033: - ossec,syscheck,syscheck_entry_modified,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2024 Jun 19 20:48:57 (ip-172-31-33-170) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/var/log/whodata/test_file' modified
Mode: whodata
Changed attributes: mtime
Old modification time was: '1718828850', now it is '1718830137'

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Wed Jun 19 20:48:57 2024
 - Inode: 133690
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - (Audit) User name: root
 - (Audit) Audit name: ec2-user
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 28721
 - (Audit) Process name: /usr/bin/touch
 - (Audit) Process cwd: /var/ossec
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 26549
 - (Audit) Parent process cwd: /var/ossec
```

</details>














## :green_circle: Active response

<details>
<summary>Manager configuration:</summary>

```
<ossec_config>
  <active-response>
    <disabled>no</disabled>
    <command>restart-wazuh</command>
    <location>defined-agent</location>
    <agent_id>007</agent_id>
    <level>7</level>
  </active-response>
</ossec_config>
```
</details>

<details>
<summary>Result:</summary>

```
2024/06/19 21:40:17 active-response/bin/restart-wazuh: Starting
2024/06/19 21:40:17 active-response/bin/restart-wazuh: {"version":1,"origin":{"name":"node01","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":[],"alert":{"timestamp":"2024-06-19T21:40:17.426+0000","rule":{"level":7,"description":"Host-based anomaly detection event (rootcheck).","id":"510","firedtimes":6,"mail":false,"groups":["ossec","rootcheck"],"pci_dss":["10.6.1"],"gdpr":["IV_35.7.d"]},"agent":{"id":"007","name":"ip-172-31-33-170","ip":"172.31.33.170"},"manager":{"name":"wazuh-server"},"id":"1718833217.1000636","full_log":"Rootkit 'ZK' detected by the presence of file '/etc/sysconfig/console/load.zk'.","decoder":{"name":"rootcheck"},"data":{"title":"Rootkit 'ZK' detected by the presence of file '/etc/sysconfig/console/load.zk'."},"location":"rootcheck"},"program":"active-response/bin/restart-wazuh"}}

2024/06/19 21:40:21 active-response/bin/restart-wazuh: Ended

```

</details>




## :green_circle:  Inventory

<details>
<summary>Script to get the first 5 rows of each table</summary>

```bash
#!/bin/bash

db_path="/var/ossec/queue/syscollector/db/local.db"

for table in $(sqlite3 $db_path ".tables"); do

  echo
  echo "Local agent db: $table"
  echo
  TMP_FILE=$(mktemp)

  # Execute the query and store output in temporary file
  sqlite3 $db_path ".headers on" "select * from $table"|head -n5 > $TMP_FILE

  # Check if query execution was successful
  if [[ $? -ne 0 ]]; then
    echo "Error executing query!"
    exit 1
  fi

  # Build markdown table header
  HEADER_ROW=$(head -n 1 "$TMP_FILE" | tr ',' '\t')
  echo "| ${HEADER_ROW// /|} |"
  max_col=$(tr -cd '|' <<< "$HEADER_ROW" | wc -c)
  for i in $(seq 0 $max_col); do  echo -n "|---"; done ; echo "|"

  # Build markdown table body with separators
  tail -n +2 "$TMP_FILE" | tr ',' '\t' | while IFS= read -r line; do
    echo "| $line |"
  done

  # Clean up temporary file
  rm "$TMP_FILE"


done
```
</details>


<details>
<summary>Inventory</summary>
Local agent db: dbsync_network_iface

| name|adapter|type|state|mtu|mac|tx_packets|rx_packets|tx_bytes|rx_bytes|tx_errors|rx_errors|tx_dropped|rx_dropped|checksum|item_id|db_status_field_dm |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| eth0||ethernet|up|9001|0e:56:26:06:06:03|62533|67106|13138630|18873787|0|0|0|0|a582608dd37f942d0f9f39be6f3ee3cb9ace82cb|d4aa8b01955e438235d586585492f3f5edceec1b|1 |

Local agent db: dbsync_packages

| name|version|vendor|install_time|location|architecture|groups|description|size|priority|multiarch|source|format|checksum|item_id|db_status_field_dm |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| Babel|2.8.0| | |/usr/lib/python3.6/site-packages/Babel-2.8.0-py3.6.egg-info/PKG-INFO| | | |0| || |pypi|8ce537453bf884e88286e95678aeb8827b1d66e0|b322f4c078b3713d8f31a9a7e2d6d4bdf90346c7|1 |
| Brotli|1.1.0| | |/usr/lib64/python3.11/site-packages/Brotli-1.1.0-py3.11.egg-info/PKG-INFO| | | |0| || |pypi|348e51f8f3d8e62a22d784ca181531aec9094eb1|06abd75d89b66475ffe4931f28683791028cd6b7|1 |
| Jinja2|2.10.1| | |/usr/lib/python3.6/site-packages/Jinja2-2.10.1-py3.6.egg-info/PKG-INFO| | | |0| || |pypi|8f7136b599ee1c93a8f49cad81f0a3d018068837|57189229a2df61e0d9400245bfc5bb80b619217a|1 |
| M2Crypto|0.38.0| | |/usr/lib64/python3.6/site-packages/M2Crypto-0.38.0-py3.6.egg-info/PKG-INFO| | | |0| || |pypi|4d758f632ebb5fb5c5ba0b94b34ddb76b4c4c8ce|e0cb9fc31534863c5d14cafded67acc0cea6e7e1|1 |

Local agent db: dbsync_hwinfo

| board_serial|cpu_name|cpu_cores|cpu_mhz|ram_total|ram_free|ram_usage|checksum|db_status_field_dm |
|---|---|---|---|---|---|---|---|---|
|  |Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz|1|2401.0|2011884|1627864|20|30a2f9c26daea6b847e3d4a6b9613550b72ab42b|1 |

Local agent db: dbsync_network_protocol

| iface|type|gateway|dhcp|metric|checksum|item_id|db_status_field_dm |
|---|---|---|---|---|---|---|---|
| eth0|ipv4|172.31.32.1|enabled|0|89237147dafa5048d7a5ba96db1de0bda8b186c2|f19629d858393054b7075ec6db3d778db7f18f30|1 |
| eth0|ipv6|172.31.32.1|unknown||6d33b3693d14ea8201e1405cec2cd9629cfe64d7|fbcf407d1580022a542a97e16a094c6eadd7ee67|1 |

Local agent db: dbsync_ports

| protocol|local_ip|local_port|remote_ip|remote_port|tx_queue|rx_queue|inode|state|pid|process|checksum|item_id|db_status_field_dm |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| udp|0.0.0.0|68|0.0.0.0|0|0|4992|19736||875|wickedd-dhcp4|52284d629ed1ff57cdb903c89e3b6cf1d6e43d7a|c89b5ff51bfb214f8ce1dc1093d3fd070c0bdd60|1 |
| udp|127.0.0.1|323|0.0.0.0|0|0|0|20213||1284|chronyd|06e49bc23d50a56deb3c4c6cb947d381e35709bb|e23e49f76062de1be4113d064a7025eaa0972133|1 |
| udp6|::1|323|::|0|0|0|20214||1284|chronyd|47ba0af38963724c776271b83a5f18943de964db|b615033cdd5c36cd61161d2133b37cfb5da0a104|1 |
| tcp|127.0.0.1|25|0.0.0.0|0|0|0|20817|listening|1424|master|18dce957ac860894a2ec0ec8d5b9ec2666526fb9|850bfda4a1fdef946d3b52f5fcf4cd397d32907f|1 |

Local agent db: dbsync_network_address

| iface|proto|address|netmask|broadcast|checksum|item_id|db_status_field_dm |
|---|---|---|---|---|---|---|---|
| eth0|0|172.31.33.170|255.255.240.0|172.31.47.255|682c1dbf56b89ab9a86c6285743996c3d4258474|f10f1f81fc180f4e2c50b1f9ed5ee97eb3c3e94b|1 |
| eth0|1|fe80::c56:26ff:fe06:603|ffff:ffff:ffff:ffff::||52ef4a41c7230cef4a38985238f930b9c9cd4869|b42531190376ccb0fe11d54e414a116a922ced21|1 |

Local agent db: dbsync_osinfo

| hostname|architecture|os_name|os_version|os_codename|os_major|os_minor|os_patch|os_build|os_platform|sysname|release|version|os_release|os_display_version|checksum|db_status_field_dm |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| ip-172-31-33-170|x86_64|SLES|15-SP6||15||||sles|Linux|6.4.0-150600.21-default|#1 SMP PREEMPT_DYNAMIC Thu May 16 11:09:22 UTC 2024 (36c1e09)|||1718834184823827373|1 |

Local agent db: dbsync_processes

| pid|name|state|ppid|utime|stime|cmd|argvs|euser|ruser|suser|egroup|rgroup|sgroup|fgroup|priority|nice|size|vm_size|resident|share|start_time|pgrp|session|nlwp|tgid|tty|processor|checksum|db_status_field_dm |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| 1|systemd|S|0|1621|270|/usr/lib/systemd/systemd|--switched-root --system --deserialize=31 dis_ucode_ldr|root|root|root|root|root|root|root|20|0|8685|34740|14716|2642|1718794237|1|1|1|1|0|0|1208cde5a651279ddf8fab9c4b506d6a4528b48a|1 |
| 10|kworker/u30:0-e|I|2|0|41|||root|root|root|root|root|root|root|20|0|0|0|0|0|1718794237|0|0|1|10|0|0|43c785fd35dab077ab14a8f644443ee3ef138f2f|1 |
| 11|mm_percpu_wq|I|2|0|0|||root|root|root|root|root|root|root|0|-20|0|0|0|0|1718794237|0|0|1|11|0|0|9e6521e66f3ef22609d2ff48fff0f75b9591a829|1 |
| 12|rcu_tasks_kthre|I|2|0|0|||root|root|root|root|root|root|root|20|0|0|0|0|0|1718794237|0|0|1|12|0|0|744e80979d9dc1fd9ec178780f8a7bccc22fedcf|1 |


</details>
