### ISSUE TITLE
Vulnerability Scanner - Content generation workflow is failing

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#24150]
## Description
The Vulnerability Scanner Database generation workflow is failing to checkout to the corresponding tag ([example](https://github.com/wazuh/wazuh/actions/runs/9556866095/job/26342972579))

The problem is related to the checkout step, now that the 4.8.0 branch doesn't exist it exits with an error:
```yml
      - name: Checkout to branch
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          ref: ${{ matrix.wazuh_version }}
```

## DoD
- [x] Issue has been fixed
