### ISSUE TITLE
Support new OSs - macOS Sequoia 15 - Add support in QA procedures

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24157]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/25665 | https://github.com/wazuh/wazuh/issues/24146 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Major |

# Plan

**QA**
## Considerations

- Testing environment: Deploy the new OS taking into account the following notes:
  - If the Wazuh central components are supported: 1 VM
  - If the Wazuh agent is supported: 1 VM for each architecture supported.
  - If the Wazuh central components or the Wazuh agent is not supported, deploy a Debian 12 VM for the non-supported component.
- All testing tasks must be completed for each OS architecture supported.
- The following tasks should be completed in order.

## Tasks

- [x] Test the Wazuh dashboard one-liner deployment. https://github.com/wazuh/wazuh/issues/24157#issuecomment-2377159156
  - [x] Deploy a Wazuh agent using the Wazuh dashboard one-liner feature provided in the Wazuh user interface with the following cases.
    - [x] Only IP address.
    - [x] Only FQDN.
    - [x] IP address, agent name, and group.
- [x] Add/Update/Check CI https://github.com/wazuh/wazuh/issues/24157#issuecomment-2378630850
  - [x] Test the JobFlow testing tool for that specific system.
  - [x] Add the OS and each architecture to the JobFlow testing tool.
  - [x] Add the OS and each architecture to the GitHub Deployability and Upgrade release templates.
- [x] Add the OS and its supported architectures to the E2E UX Tests spreadsheet (OS sheet).
- [x] Add the OS as supported in the compatibility system spreadsheet.
- [x] ~We need to add proper documentation, including adding the new OS version if it belongs to an OS family already added to these tables:~ All the documentation is related to Wazuh Central Components while macOs support is only for the Wazuh-Agent
  - [x]  ~https://documentation.wazuh.com/current/quickstart.html#operating-system~
  - [x]  ~https://documentation.wazuh.com/current/installation-guide/wazuh-server/index.html#recommended-operating-systems~
  - [x]  ~https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/index.html#recommended-operating-systems~
  - [x]  ~https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/index.html#recommended-operating-systems~

I have checked the macOS Agents section to see if there is any reference to versions but I have not found anything [here](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html).

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this issue as not planned because it is a pre-release version.

**Comment by jotacarma90** [comment]
Reopened due to release date for macOS 15 Sequoia is here:
https://9to5mac.com/2024/09/09/macos-sequoia-release-date/

**Comment by pro-akim** [comment]
## ## Test the Wazuh dashboard one-liner deployment :construction:

**Comment by pro-akim** [comment]
## Add/Update/Check CI :construction: 
### Test the JobFlow testing tool for that specific system.
<details><summary>YAML</summary>

```
version: 0.1
description: This workflow is used to test agents deployment for DDT
variables:

  macos-agent-os:
    - macos-sequoia-15-amd64
    - macos-sequoia-15-arm64

  manager-os: linux-ubuntu-22.04-amd64
  infra-provider: aws
  macos-infra-provider: vagrant
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique manager allocate task
  - task: "allocate-manager-{manager-os}"
    description: "Allocate resources for the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{manager-os}"
          - inventory-output: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh/issues/24157"
    on-error: "abort-all"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"

  # Unique manager provision task
  - task: "provision-manager-{manager-os}"
    description: "Provision the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/provision/main.py
          - inventory: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - install:
            - component: wazuh-manager
              type: assistant
              version: <major.minor.patch>
              live: False
    depends-on:
      - "allocate-manager-{manager-os}"
    on-error: "abort-all"

  # Unique agent allocate task
  - task: "allocate-macos-agent-{agent}"
    description: "Allocate resources for the agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{macos-infra-provider}"
          - size: small
          - composite-name: "{agent}"
          - inventory-output: "{working-dir}/agent-{agent}/inventory.yaml"
          - track-output: "{working-dir}/agent-{agent}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh/issues/24157"
    on-error: "abort-all"
    foreach:
      - variable: macos-agent-os
        as: agent
    depends-on:
      - "provision-manager-{manager-os}"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/agent-{agent}/track.yaml"

  # Generic agent test task
  - task: "run-macos-agent-{agent}-tests"
    description: "Run tests install for the agent {agent}."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/manager-{manager-os}/inventory.yaml"
            - agent: "{working-dir}/agent-{agent}/inventory.yaml"
          - tests: "install,registration,connection,basic_info,restart,stop,uninstall"
          - component: "agent"
          - wazuh-version: "4.9.0"
          - wazuh-revision: ""
          - live: True
    foreach:
      - variable: macos-agent-os
        as: agent
    depends-on:
      - "allocate-macos-agent-{agent}"

```
</details>
