### ISSUE TITLE
Incorrect checks in Ubuntu 22.04 SCA

### ISSUE THREAD

**Issue by jk-olaoluwa** [wazuh/wazuh#24298]
| Component | Action type           | Main Issue 
| --- | --- | ---
| SCA       | Rule Correction |  #21930

## Description

A community user identified a discrepancy in CIS check results where some checks passed in AWS Inspector and failed in Wazuh SCA - as mentioned [here](https://github.com/wazuh/community/issues/28162)

### Wrong CIS Checks
![Screenshot 2024-06-19 103555](https://github.com/wazuh/wazuh/assets/69200476/7d177e97-bbd1-45c4-850e-136274c6d22e)
![Screenshot 2024-06-19 105410](https://github.com/wazuh/wazuh/assets/69200476/9fbf4f06-ff95-481a-af3f-5bb3728f28cb)

### Current
``` 
# 5.2.22 Ensure SSH Idle Timeout Interval is configured (Automated)                                                                            
- id: 28653
   title: "Ensure SSH Idle Timeout Interval is configured."
   description: "NOTE: To clarify, the two settings described below is only meant for idle connections from a protocol perspective and not mea>   rationale: "In order to prevent resource exhaustion, appropriate values should be set for both ClientAliveInterval and ClientAliveCountMax.>   remediation: "Edit the /etc/ssh/sshd_config file to set the parameters according to site policy. Example: ClientAliveInterval 15 ClientAliv>   references:
     - https://man.openbsd.org/sshd_config
   compliance:
     - cis: ["5.2.22"]
     - mitre_techniques: ["T1078", "T1078.001", "T1078.002", "T1078.003"]
     - mitre_tactics: ["TA0001"]
     - mitre_mitigations: ["M1026"]
   condition: all
   rules:
     - "c:sshd -T -> -> n:^clientaliveinterval\\s*\\t*(\\d+) compare > 0"
     - "c:sshd -T -> -> n:^clientalivecountmax\\s*\\t*(\\d+) compare > 0"
```
### Expected
```
# 5.2.22 Ensure SSH Idle Timeout Interval is configured (Automated)                                                                            
- id: 28653
   title: "Ensure SSH Idle Timeout Interval is configured."
   description: "NOTE: To clarify, the two settings described below is only meant for idle connections from a protocol perspective and not mea>   rationale: "In order to prevent resource exhaustion, appropriate values should be set for both ClientAliveInterval and ClientAliveCountMax.>   remediation: "Edit the /etc/ssh/sshd_config file to set the parameters according to site policy. Example: ClientAliveInterval 15 ClientAliv>   references:
     - https://man.openbsd.org/sshd_config
   compliance:
     - cis: ["5.2.22"]
     - mitre_techniques: ["T1078", "T1078.001", "T1078.002", "T1078.003"]
     - mitre_tactics: ["TA0001"]
     - mitre_mitigations: ["M1026"]
   condition: all
   rules:
     - "c:sshd -T -> n:^clientaliveinterval\\s*\\t*(\\d+) compare > 0"
     - "c:sshd -T -> n:^clientalivecountmax\\s*\\t*(\\d+) compare > 0"
```

### Current
```
# 4.1.4.9 Ensure audit tools are owned by root (Automated)                                                                                    
- id: 28611
  title: "Ensure audit tools are owned by root."
  description: "Audit tools include, but are not limited to, vendor-provided and open source audit tools needed to successfully view and mani>  rationale: "Protecting audit information includes identifying and protecting the tools used to view and manipulate log data. Protecting aud>  remediation: "Run the following command to change the owner of the audit tools to the root user: # chown root /sbin/auditctl /sbin/aureport>  compliance:
    - cis: ["4.1.4.9"]
    - cis_csc_v7: ["14.6"]
    - cis_csc_v8: ["3.3"]
    - mitre_techniques: ["T1070", "T1070.002", "T1083"]
    - mitre_tactics: ["TA0007"]
    - cmmc_v2.0: ["AC.L1-3.1.1", "AC.L1-3.1.2", "AC.L2-3.1.5", "AC.L2-3.1.3", "MP.L2-3.8.2"]
    - hipaa: ["164.308(a)(3)(i)", "164.308(a)(3)(ii)(A)", "164.312(a)(1)"]
    - pci_dss_3.2.1: ["7.1", "7.1.1", "7.1.2", "7.1.3"]
    - pci_dss_4.0: ["1.3.1", "7.1"]
    - nist_sp_800-53: ["AC-5", "AC-6"]
    - soc_2: ["CC5.2", "CC6.1"]
  condition: none
  rules:
    - 'c:stat -c "%n %U" /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace /sbin/auditd /sbin/augenrules -> !r:root|\\s*'
```

### Expected
```
# 4.1.4.9 Ensure audit tools are owned by root (Automated)                                                                                    
- id: 28611
  title: "Ensure audit tools are owned by root."
  description: "Audit tools include, but are not limited to, vendor-provided and open source audit tools needed to successfully view and mani>  rationale: "Protecting audit information includes identifying and protecting the tools used to view and manipulate log data. Protecting aud>  remediation: "Run the following command to change the owner of the audit tools to the root user: # chown root /sbin/auditctl /sbin/aureport>  compliance:
    - cis: ["4.1.4.9"]
    - cis_csc_v7: ["14.6"]
    - cis_csc_v8: ["3.3"]
    - mitre_techniques: ["T1070", "T1070.002", "T1083"]
    - mitre_tactics: ["TA0007"]
    - cmmc_v2.0: ["AC.L1-3.1.1", "AC.L1-3.1.2", "AC.L2-3.1.5", "AC.L2-3.1.3", "MP.L2-3.8.2"]
    - hipaa: ["164.308(a)(3)(i)", "164.308(a)(3)(ii)(A)", "164.312(a)(1)"]
    - pci_dss_3.2.1: ["7.1", "7.1.1", "7.1.2", "7.1.3"]
    - pci_dss_4.0: ["1.3.1", "7.1"]
    - nist_sp_800-53: ["AC-5", "AC-6"]
    - soc_2: ["CC5.2", "CC6.1"]
  condition: all
  rules:
    - 'c:stat -c "%n %U" /sbin/auditctl /sbin/aureport /sbin/ausearch /sbin/autrace /sbin/auditd /sbin/augenrules -> r:root$'
```
