### ISSUE TITLE
Validate Multi-CA File Support in OpenSearch via Indexer Connector

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#24551]
### Description
The recent enhancement proposal #24295, which involves the Indexer Connector supporting multiple CA files, requires validation in the OpenSearch environment. This proposal hinges on the ability of OpenSearch to handle connections where each node may have certificates signed by different CAs. The indexer team has indicated uncertainty regarding this capability in OpenSearch, suggesting the need for practical tests and comprehensive documentation of the findings.

### Background
During discussions with the indexer team, it was brought up that OpenSearch might need to be tested to confirm whether it can support certificates signed by different CAs for each node.

### Task
Conduct tests to determine if OpenSearch supports using multiple CA files via the Indexer Connector, where each node might have its certificate signed by a different CA.

### Additional Information
- **Related Issues:** Enhancement proposal #24295.
- **References:** Include links to any relevant documentation or issues that might help in understanding the background and technical details.

------------------

**Comment by f-galland** [comment]
I was able to get a 2 node Wazuh Indexer cluster running using two separate CAs by concatenating the `root-ca.pem` file from each of them and setting the concatenated file up as the value for the following options in `/etc/wazuh-indexer/opensearch.yml`:

```yaml
plugins.security.ssl.http.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/conc-ca.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/conc-ca.pem
```

The concatenated root CA file looks like this:
```
root@indexer1:/etc/wazuh-indexer/certs# cat conc-ca.pem 
-----BEGIN CERTIFICATE-----
MIIDSzCCAjOgAwIBAgIUBpx8YLPH/Omdu1y6fxdKUkj60YUwDQYJKoZIhvcNAQEL
BQAwNTEOMAwGA1UECwwFV2F6dWgxDjAMBgNVBAoMBVdhenVoMRMwEQYDVQQHDApD
YWxpZm9ybmlhMB4XDTI0MDcxMjIwMDQxN1oXDTM0MDcxMDIwMDQxN1owNTEOMAwG
A1UECwwFV2F6dWgxDjAMBgNVBAoMBVdhenVoMRMwEQYDVQQHDApDYWxpZm9ybmlh
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlHnS5Frw4okdP/bA435z
zAl/Cksy/6n8Q710tE87ZoQSDQGLzvfFWnRAnb1nBEfoUXmMEgca6GbBbeNb9U0/
z/wLnUs4XNDttqb8oLiaL8/VwNkexV+QOVFH2AGRIS2mb03dW6v64vfBmSQq7vGA
in8vhlvrNDopHaksYQuSh+1+nVxXfeSfz8g4J6kiimR8iwJTWwLsvcPEz3q8rW3u
sRvwacC1h4TwxY35d13UBUhPaS4ohpBCiSjslclUSB/zyjFnYcxz+kUki/uxKJZ3
1vAc8RHRNnmXmys/bDWWT25gjbgprgvuTwXb72TZUssc8ro7Y8yQKbvyxL7Vx8EF
BwIDAQABo1MwUTAdBgNVHQ4EFgQUoFZEje6sfs0zoqzuXkyih5+bgaQwHwYDVR0j
BBgwFoAUoFZEje6sfs0zoqzuXkyih5+bgaQwDwYDVR0TAQH/BAUwAwEB/zANBgkq
hkiG9w0BAQsFAAOCAQEAkKjoZ+kxuDqYPgPy0QPOX05aaj0iBtdAzcLSuuQy1AqJ
pJaHJkQMxH976dSo4t0BitIEK2khY/sWzgz+nNTdSFf77YqXGLF+UIEDLIeg7aIy
Jq/MTgZTv9P2J7QCwf8/syTYFDFmpONX6kjkmCgOuCIyRypnYaNfaq59WJNE/jgR
WSgefEoGijiRSmcUPtYd3wXfYgSJNmA4IOUdo0KbB5iPqc85/C/ugveczk7aGkYl
CVP+7oEsdbBkbMamMUGVDBBokO6omSMzepRJzDr0twr7ATscJHVkTf5cbEQ9Cw61
KlTLCjjZ6vareSlvtNnlga/71/+LX0FT3rEEQorW6Q==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIDSzCCAjOgAwIBAgIUBfPY8Z3v7dkczwBIEOcFAKWgwB4wDQYJKoZIhvcNAQEL
BQAwNTEOMAwGA1UECwwFV2F6dWgxDjAMBgNVBAoMBVdhenVoMRMwEQYDVQQHDApD
YWxpZm9ybmlhMB4XDTI0MDcxMjE5NDkzM1oXDTM0MDcxMDE5NDkzM1owNTEOMAwG
A1UECwwFV2F6dWgxDjAMBgNVBAoMBVdhenVoMRMwEQYDVQQHDApDYWxpZm9ybmlh
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyj6DFdL+eysfu4Cu7C3I
uTUCSGFyAW5ndoG87LPeLFyhO50IZK+OSVZZ9qzLG/aqQDthFPsGuAcwXuXRq7j5
bH/AxGrBvs9Dj2SK92EFUxu9SfAKJJrfbP+BwWq6OUmudZTAjFE3td0eCazLKWtu
qrCt6fvZawLBnRcVzHqVmsCW5Gc9BCzqIAzLl9dxsEANnyMbKqL6V31LJdU4/7HD
LwKdmRaEUOV9cnKDpgMm1STUJ+8Vd7MccK7t2Z1gn8yWPo0gysf3IJxHUBZkBu9r
qm80eaUlLtFYSN5CAEUDNxNgzP8hSTnUDYCdljFC2XHzc8/B1Y4Bo7Cw7p31uPKs
5QIDAQABo1MwUTAdBgNVHQ4EFgQUNVVeVvOcKIHQhSs1iBfvnD2MQgowHwYDVR0j
BBgwFoAUNVVeVvOcKIHQhSs1iBfvnD2MQgowDwYDVR0TAQH/BAUwAwEB/zANBgkq
hkiG9w0BAQsFAAOCAQEAMcNBCEI0MGmsco1oHyQIYuRaumyzD8gpZWasPZByfIcK
hUIth7vyFNE5pnyulyGunS1+mha0NeLd1MUMz2zWz0xJ5RGLwzent9lpwjU4+3gI
CbVLpJPkFFwLVrPigpC+XQvWorJ5affsDBqWm/Gdnvbt5JpJ1JnJiZuHUFJFF+Gb
l5MzHx+dxk+ZDTZUeuRDvcNw84FZysuAXQBHBVoEDliS9uyc8+UwazXWu37ZNMzW
0lgs1kl6qi1yanpD8cyQ2W7qu3+S7wiTBzb/KRmVtjuNfxIaEUtpqCNFw+fTLd1L
Cq/D9MKErFka+Y5Qn3cVjgcvy3gdTHnIHtNUrp6JHg==
-----END CERTIFICATE-----
```

The `opensearch.yml` configuration files for each node look as follows:

<details>
<summary>node-1</summary>

```yaml
network.host: "0.0.0.0"
node.name: "node-1"
cluster.initial_master_nodes:
- "node-1"
- "node-2"
#- "node-3"
cluster.name: "wazuh-cluster"
discovery.seed_hosts:
  - "192.168.58.4"
  - "192.168.58.227"
#  - "node-3-ip"
node.max_local_storage_nodes: "2"
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer

plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.http.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/conc-ca.pem

plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.transport.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.transport.resolve_hostname: false
plugins.security.ssl.transport.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/conc-ca.pem

plugins.security.authcz.admin_dn:
- "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn:
- "CN=node-1,OU=Wazuh,O=Wazuh,L=California,C=US"
- "CN=node-2,OU=Wazuh,O=Wazuh,L=California,C=US"
#- "CN=node-2,OU=Wazuh,O=Wazuh,L=California,C=US"
#- "CN=node-3,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.restapi.roles_enabled:
- "all_access"
- "security_rest_api_access"

plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".plugins-ml-model", ".plugins-ml-task", ".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opensearch-notifications-*", ".opensearch-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]

### Option to allow Filebeat-oss 7.10.2 to work ###
compatibility.override_main_response_version: true
```

</details>


<details>
<summary>node-2</summary>

```yaml
network.host: "192.168.58.227"
node.name: "node-2"
cluster.initial_master_nodes:
- "node-1"
- "node-2"
#- "node-3"
cluster.name: "wazuh-cluster"
discovery.seed_hosts:
  - "192.168.58.4"
  - "192.168.58.227"
#  - "node-3-ip"
node.max_local_storage_nodes: "2"
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer

plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.http.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/conc-ca.pem
    #  - certs/root-ca.pem

plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.pemcert_filepath: /etc/wazuh-indexer/certs/indexer.pem
plugins.security.ssl.transport.pemkey_filepath: /etc/wazuh-indexer/certs/indexer-key.pem
plugins.security.ssl.transport.resolve_hostname: false
plugins.security.ssl.transport.pemtrustedcas_filepath: /etc/wazuh-indexer/certs/conc-ca.pem
    #  - certs/root-ca.pem

plugins.security.authcz.admin_dn:
- "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn:
- "CN=node-1,OU=Wazuh,O=Wazuh,L=California,C=US"
- "CN=node-2,OU=Wazuh,O=Wazuh,L=California,C=US"
#- "CN=node-3,OU=Wazuh,O=Wazuh,L=California,C=US"
plugins.security.restapi.roles_enabled:
- "all_access"
- "security_rest_api_access"

plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".plugins-ml-model", ".plugins-ml-task", ".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opensearch-notifications-*", ".opensearch-notebooks", ".opensearch-observability", ".opendistro-asynchronous-search-response*", ".replication-metadata-store"]

### Option to allow Filebeat-oss 7.10.2 to work ###
compatibility.override_main_response_version: true
```

</details>

I had to make sure the files had the right `400` permissions and `wazuh-indexer:wazuh-indexer` ownership:

```shell
root@indexer2:/etc/wazuh-indexer/certs# stat /etc/wazuh-indexer/certs/conc-ca.pem
  File: /etc/wazuh-indexer/certs/conc-ca.pem
  Size: 2408      	Blocks: 8          IO Block: 4096   regular file
Device: 10302h/66306d	Inode: 3978543     Links: 1
Access: (0400/-r--------)  Uid: (  106/wazuh-indexer)   Gid: (  113/wazuh-indexer)
Access: 2024-07-12 20:22:52.342943775 +0000
Modify: 2024-07-12 20:21:44.346646691 +0000
Change: 2024-07-12 20:22:46.622914417 +0000
 Birth: 2024-07-12 20:21:33.694603592 +0000
```
