### ISSUE TITLE
Policy Monitoring Module

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#2457]
This issue continues the development of https://github.com/wazuh/wazuh/issues/1983. 

#### Main tasks

 - Monday
    - [x] Script for transforming current benchmarks to YAML
    - [ ] Enrich benchmark data
    - [x] Prepare the base code (configuration reading and loading) for Policy Monitoring
    - [x] Read the YAML benchmarks and transform then to JSON

 - Tuesday
    - [x] Investigate rootcheck algorithm and behavior
    - [x] Do the scan for every benchmark test (Phase 1)
    - [x] Do the summary for each benchmark (Phase 1)

 - Wednesday
    - [ ] Do the scan for every benchmark test (Phase 2)
    - [ ] Do the summary for each benchmark (Phase 2)

 - Thursday
    - [x] Send every scan to the manager in JSON format
    - [x] Send every summary to the manager in JSON format
    - [ ] Decode the event on the manager side and throw an alert

 - Friday
    - [ ] Implement a basic version of the hash table to check differences
    - [ ] Send only the differences to the manager

The YAML file actually has the format as shown in the example:
```yaml

# Copyright (C) 2015-2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation
#
# OSSEC Linux Audit - (C) 2017
#
# Released under the same license as OSSEC.
# More details at the LICENSE file included with OSSEC or online
# at: https://github.com/ossec/ossec-hids/blob/master/LICENSE
#
# [Application name] [any or all] [reference]
# type:<entry name>;
#
# Type can be:
#             - f (for file or directory)
#             - p (process running)
#             - d (any file inside the directory)
#
# Additional values:
# For the registry , use "->" to look for a specific entry and another
# "->" to look for the value.
# For files, use "->" to look for a specific value in the file.
#
# Values can be preceeded by: =: (for equal) - default
#                             r: (for ossec regexes)
#                             >: (for strcmp greater)
#                             <: (for strcmp  lower)
# Multiple patterns can be specified by using " && " between them.
# (All of them must match for it to return true).
# CIS Checks for Apache Https Server
# Based on Center for Internet Security Benchmark for Apache HttpSserver 2.4 v1.3.1 and Apache HttpsServer 2.2 v3.4.1 (https://workbench.cisecurity.org/benchmarks/307, https://workbench.cisecurity.org/benchmarks/308)
#
#
description:
 name: "CIS Checks for Apache Https Server"
 
variables:
 $main-conf: /etc/apache2/apache2.conf,/etc/httpd/conf/httpd.conf;
 $conf-dirs: /etc/apache2/conf-enabled,/etc/apache2/mods-enabled,/etc/apache2/sites-enabled,/etc/httpd/conf.d,/etc/httpd/modsecurity.d;
 $ssl-confs: /etc/apache2/mods-enabled/ssl.conf,/etc/httpd/conf.d/ssl.conf;
 $mods-en: /etc/apache2/mods-enabled;
 $request-confs: /etc/httpd/conf/httpd.conf,/etc/apache2/mods-enabled/reqtimeout.conf;
 $traceen: /etc/apache2/apache2.conf,/etc/httpd/conf/httpd.conf,/etc/apache2/conf-enabled/security.conf;
#
#
#2.3 Disable WebDAV Modules
check:
 title: "WebDAV Modules are enabled"
 cis: "Apache Configuration - 2.3"
 condition: any
 references:
  - https://workbench.cisecurity.org/benchmarks/307
  - https://workbench.cisecurity.org/benchmarks/308
 id: 1
 rules:
  - d:$conf-dirs -> conf -> !r:^# && r:loadmodule\sdav;
  - d:$conf-dirs -> load -> !r:^# && r:loadmodule\sdav;
  - f:/etc/httpd/conf.d -> !r:^# && r:loadmodule\sdav;
  - d:$mods-en -> dav.load;
#
#
#2.4 Disable Status Module
check:
 title: "Status Module is enabled"
 cis: "Apache Configuration - 2.4"
 condition: any
 references:
  - https://workbench.cisecurity.org/benchmarks/307
  - https://workbench.cisecurity.org/benchmarks/308
 id: 2
 rules:
  - d:$conf-dirs -> conf -> !r:^# && r:loadmodule\sstatus;
  - d:$conf-dirs -> load -> !r:^# && r:loadmodule\sstatus;
  - f:/etc/httpd/conf.d -> !r:^# && r:loadmodule\sstatus;
  - d:$mods-en -> status.load;

```
Working on branch https://github.com/wazuh/wazuh/tree/3.9-sql-rootcheck
