### ISSUE TITLE
App loading logo and wazuh dashboard home logo in Wazuh 4.9.0 - Beta 1 - E2E UX tests - Change custom logos

### ISSUE THREAD

**Issue by dupuju** [wazuh/wazuh#25084]
### Describe the bug

During `4.9.0-beta1` UX testing issue https://github.com/wazuh/wazuh/issues/25020, the following issues were noticed again this is relating to previous issue found in 4.8.0 Alpha 2 test https://github.com/wazuh/wazuh/issues/21469:  

1. The dashboard GUI customization.logo.app doesn't change the app loading logo as expected.
2. Modifying the OpenseacrhDashboards.branding in opensearch_dashboards.yml changes the logo of the loading and Wazuh dashboard home logo together and with the same image

### To reproduce

1. Launch the 4.9.0 Beta 1 dashboard
2. Log in
3. dashboard management > App Settings
4. Custom branding > App main logo
5. Upload an image that fits the specification under customization.logo.app
6. App logo remains unchanged

### Evidence

![image](https://github.com/user-attachments/assets/faac5db4-9119-4da6-bb18-173934fc8079)

### The App loading logo remains unchanged

![image](https://github.com/user-attachments/assets/0e9ef28c-c60f-40bd-8c7a-e1b4e52a9f1f)

### To Reproduce

1. Install and config Wazuh dashboard
2. Edit the /etc/wazuh-dashboard/opensearch_dashboards.yml file
3. Specify the source of the image opensearchDashboards.branding:
4. Restart the Wazuh dashboard service
5. App loading logo and wazuh dashboard home logo changes instead of just the wazuh dashboard home logo from the documentation 

### Editing the opensearch_dashboards.yml changes both the App loading logo and the Wazuh dashboard home logo

```

[root@ip-172-31-40-29 ~]# nano /etc/wazuh-dashboard/opensearch_dashboards.yml
[root@ip-172-31-40-29 ~]# cat /etc/wazuh-dashboard/opensearch_dashboards.yml
server.host: 0.0.0.0
server.port: 443
opensearch.hosts: https://172.31.37.73:9200
opensearch.ssl.verificationMode: certificate
opensearch.requestHeadersAllowlist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
server.ssl.enabled: true
server.ssl.key: "/etc/wazuh-dashboard/certs/dashboard-key.pem"
server.ssl.certificate: "/etc/wazuh-dashboard/certs/dashboard.pem"
opensearch.ssl.certificateAuthorities: ["/etc/wazuh-dashboard/certs/root-ca.pem"]
uiSettings.overrides.defaultRoute: /app/wz-home

opensearchDashboards.branding:
   mark:
      defaultUrl: "https://www.xxxx.com/show/305xxx/zigbxx.svg"
      darkModeUrl: "https://www.xxxx.com/show/305xxx/zigbxx.svg"

[root@ip-172-31-40-29 ~]# ls /usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom/images/
customization.logo.app.png  customization.logo.healthcheck.png  customization.logo.reports.png
[root@ip-172-31-40-29 ~]#
[root@ip-172-31-40-29 ~]# systemctl restart wazuh-dashboard
```
### 🟢 Dashboard home logo changed
![image](https://github.com/user-attachments/assets/c130c81a-25f7-4655-bf0d-7b24542566d1)

🟡 After changing the home log, that is when the app loading changes with the icon for the home logo. This issue has been reported in v4.8.0 and closed https://github.com/wazuh/wazuh/issues/21469 It needs to be reopened.

![image](https://github.com/user-attachments/assets/b4f9aa84-9d1b-4864-80f3-96c24ca706ff)
