### ISSUE TITLE
Release 4.9.0 - RC 2 - Deployability

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#25497]
### Packages tests metrics information

|||
| :--                              | :--                                                             |
| **Main release stage issue**     | #25475                                         |
| **Main packages metrics issue**  | #25489                                                   |
| **Version**                      | 4.9.0                                                   |
| **Release stage**                | RC 2                                                   |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.9.0-rc2          |

---

### Wazuh agent tests
- Log: [agent_dtt_log](https://github.com/user-attachments/files/16848387/log_agent_2.log)

<details> 

<summary> YAML </summary>

```yaml
version: 0.1
description: This workflow is used to test agents deployment for DDT1 PoC
variables:
  agent-os:
    - linux-redhat-7-amd64
    - linux-redhat-7-arm64
    - linux-redhat-8-amd64
    - linux-redhat-8-arm64
    - linux-redhat-9-amd64
    - linux-redhat-9-arm64
    - linux-centos-7-amd64
    - linux-centos-7-arm64
    - linux-centos-8-amd64
    - linux-centos-8-arm64
    - linux-debian-10-amd64
    - linux-debian-10-arm64
    - linux-debian-11-amd64
    - linux-debian-11-arm64
    - linux-debian-12-amd64
    - linux-debian-12-arm64
    - linux-ubuntu-22.04-amd64
    - linux-ubuntu-22.04-arm64
    - linux-ubuntu-18.04-amd64
    - linux-ubuntu-18.04-arm64
    - linux-ubuntu-20.04-amd64
    - linux-ubuntu-20.04-arm64
    - linux-oracle-9-amd64
    - linux-amazon-2-amd64
    - linux-amazon-2-arm64
    - linux-amazon-2023-amd64
    - linux-amazon-2023-arm64

  windows-agent-os:
    - windows-desktop-10-amd64
    - windows-server-2012r2-amd64
    - windows-server-2016-amd64
    - windows-server-2019-amd64
    - windows-server-2022-amd64

  macos-agent-os:
    - macos-ventura-13-amd64
    - macos-sonoma-14-amd64

  manager-os: linux-ubuntu-22.04-amd64
  infra-provider: aws
  macos-infra-provider: vagrant
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique manager allocate task
  - task: "allocate-manager-{manager-os}"
    description: "Allocate resources for the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{manager-os}"
          - inventory-output: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh/issues/25497"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"

  # Unique manager provision task
  - task: "provision-manager-{manager-os}"
    description: "Provision the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/provision/main.py
          - inventory: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - install:
            - component: wazuh-manager
              type: assistant
              version: 4.9.0
              live: False
    depends-on:
      - "allocate-manager-{manager-os}"
    on-error: "abort-all"

  # Unique agent allocate task
  - task: "allocate-agent-{agent}"
    description: "Allocate resources for the agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: small
          - composite-name: "{agent}"
          - inventory-output: "{working-dir}/agent-{agent}/inventory.yaml"
          - track-output: "{working-dir}/agent-{agent}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh/issues/25497"
    foreach:
      - variable: agent-os
        as: agent
    depends-on:
      - "provision-manager-{manager-os}"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/agent-{agent}/track.yaml"

  # Generic agent test task
  - task: "run-agent-{agent}-tests"
    description: "Run tests install for the agent {agent}."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/manager-{manager-os}/inventory.yaml"
            - agent: "{working-dir}/agent-{agent}/inventory.yaml"
          - tests: "install,registration,connection,basic_info,restart,stop,uninstall"
          - component: "agent"
          - wazuh-version: "4.9.0"
          - wazuh-revision: "40907"
          - live: False
    foreach:
      - variable: agent-os
        as: agent
    depends-on:
      - "allocate-agent-{agent}"

  # Unique agent allocate task
  - task: "allocate-macos-agent-{agent}"
    description: "Allocate resources for the agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{macos-infra-provider}"
          - size: small
          - composite-name: "{agent}"
          - inventory-output: "{working-dir}/agent-{agent}/inventory.yaml"
          - track-output: "{working-dir}/agent-{agent}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh/issues/25497"
    foreach:
      - variable: macos-agent-os
        as: agent
    depends-on:
      - "provision-manager-{manager-os}"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/agent-{agent}/track.yaml"

  # Generic agent test task
  - task: "run-macos-agent-{agent}-tests"
    description: "Run tests install for the agent {agent}."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/manager-{manager-os}/inventory.yaml"
            - agent: "{working-dir}/agent-{agent}/inventory.yaml"
          - tests: "install,registration,connection,basic_info,restart,stop,uninstall"
          - component: "agent"
          - wazuh-version: "4.9.0"
          - wazuh-revision: "40907"
          - live: False
    foreach:
      - variable: macos-agent-os
        as: agent
    depends-on:
      - "allocate-macos-agent-{agent}"

  # Unique agent allocate task
  - task: "allocate-windows-agent-{agent}"
    description: "Allocate resources for the agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{agent}"
          - inventory-output: "{working-dir}/agent-{agent}/inventory.yaml"
          - track-output: "{working-dir}/agent-{agent}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh/issues/25497"
    foreach:
      - variable: windows-agent-os
        as: agent
    depends-on:
      - "provision-manager-{manager-os}"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/agent-{agent}/track.yaml"

  # Generic agent test task
  - task: "run-windows-agent-{agent}-tests"
    description: "Run tests install for the agent {agent}."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/manager-{manager-os}/inventory.yaml"
            - agent: "{working-dir}/agent-{agent}/inventory.yaml"
          - tests: "install,registration,connection,basic_info,restart,stop,uninstall"
          - component: "agent"
          - wazuh-version: "4.9.0"
          - wazuh-revision: "40907"
          - live: False
    foreach:
      - variable: windows-agent-os
        as: agent
    depends-on:
      - "allocate-windows-agent-{agent}"
```

</details>

Failed macOS Ventura. Rerunning the tests
```
[31m[2024-09-03 11:53:27] [ERROR] [368765] [ThreadPoolExecutor-0_1] [jobflow]: [run-macos-agent-macos-ventura-13-amd64-tests] Task failed with error: Error executing process task /home/rebits/Wazuh/wazuh-qa/4.9.0-rc2/lib/python3.10/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/home/rebits/Wazuh/wazuh-qa/4.9.0-rc2/lib/python3.10/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
Traceback (most recent call last):
  File "/home/rebits/Wazuh/wazuh-qa/deployability/modules/testing/main.py", line 30, in <module>
    Tester.run(InputPayload(**vars(parse_arguments())))
  File "/home/rebits/Wazuh/wazuh-qa/deployability/modules/testing/testing.py", line 61, in run
    cls._run_tests(payload.tests, ansible, extra_vars)
  File "/home/rebits/Wazuh/wazuh-qa/deployability/modules/testing/testing.py", line 104, in _run_tests
    raise Exception(f"Test {test} failed with error")
Exception: Test connection failed with error
```

- Reported in: https://github.com/wazuh/wazuh-qa/issues/5718

macOS seems to work properly in the second iteration

**Log**: [log_agent_macos.log](https://github.com/user-attachments/files/16849944/log_agent_macos.log)

Further research is required
  
|System Agent|Deploy instance|Connection instance|Install|Registration|Connection|Basic info|Restart|Stop|Uninstall|
|:--|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:
|Red Hat 7 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Red Hat 7 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Red Hat 8 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Red Hat 8 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Red Hat 9 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Red Hat 9 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|CentOS 7 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|CentOS 7 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|CentOS 8 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|CentOS 8 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 10 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 10 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 11 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 11 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 12 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 12 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 22.04 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 22.04 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 20.04 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 20.04 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 18.04 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 18.04 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Oracle Linux 9 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Amazon Linux 2 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Amazon Linux 2 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Amazon Linux 2023 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Amazon Linux 2023 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Windows Desktop 10 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Windows Server 2012-r2 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Windows Server 2016 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Windows Server 2019 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Windows Server 2022 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|macOS Ventura 13 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|macOS Sonoma 14 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |

### Wazuh manager tests
- Log: [log_manager.log](https://github.com/user-attachments/files/16846006/log_manager.log)

<details>

<summary> YAML </summary>

```yaml
version: 0.1
description: This workflow is used to test manager deployment for DDT1 PoC
variables:
  manager-os:
    - linux-ubuntu-20.04-amd64
    - linux-ubuntu-22.04-amd64
    - linux-amazon-2-amd64
    - linux-redhat-7-amd64
    - linux-redhat-8-amd64
    - linux-redhat-9-amd64
    - linux-centos-7-amd64
    - linux-centos-8-amd64
    - linux-debian-10-amd64
    - linux-debian-11-amd64
    - linux-debian-12-amd64
  infra-provider: aws
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique manager allocate task
  - task: "allocate-manager-{manager}"
    description: "Allocate resources for the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - deployability/modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{manager}"
          - inventory-output: "{working-dir}/manager-{manager}/inventory.yaml"
          - track-output: "{working-dir}/manager-{manager}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh/issues/25497"
    foreach:
      - variable: manager-os
        as: manager
    cleanup:
      this: process
      with:
        path: python3
        args:
          - deployability/modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/manager-{manager}/track.yaml"

  # Generic manager test task
  - task: "run-manager-tests"
    description: "Run tests install for the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - deployability/modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/manager-linux-centos-7-amd64/inventory.yaml"
            - wazuh-2: "{working-dir}/manager-linux-ubuntu-20.04-amd64/inventory.yaml"
            - wazuh-3: "{working-dir}/manager-linux-ubuntu-22.04-amd64/inventory.yaml"
            - wazuh-4: "{working-dir}/manager-linux-redhat-7-amd64/inventory.yaml"
            - wazuh-5: "{working-dir}/manager-linux-redhat-8-amd64/inventory.yaml"
            - wazuh-6: "{working-dir}/manager-linux-redhat-9-amd64/inventory.yaml"
            - wazuh-7: "{working-dir}/manager-linux-centos-8-amd64/inventory.yaml"
            - wazuh-8: "{working-dir}/manager-linux-debian-10-amd64/inventory.yaml"
            - wazuh-9: "{working-dir}/manager-linux-debian-11-amd64/inventory.yaml"
            - wazuh-10: "{working-dir}/manager-linux-debian-12-amd64/inventory.yaml"
            - wazuh-11: "{working-dir}/manager-linux-amazon-2-amd64/inventory.yaml"
          - tests: "install,restart,stop,uninstall"
          - component: "manager"
          - wazuh-version: "4.9.0"
          - wazuh-revision: "40907"
          - live: False
    depends-on:
      - "allocate-manager-linux-ubuntu-20.04-amd64"
      - "allocate-manager-linux-ubuntu-22.04-amd64"
      - "allocate-manager-linux-amazon-2-amd64"
      - "allocate-manager-linux-redhat-7-amd64"
      - "allocate-manager-linux-redhat-8-amd64"
      - "allocate-manager-linux-redhat-9-amd64"
      - "allocate-manager-linux-centos-7-amd64"
      - "allocate-manager-linux-centos-8-amd64"
      - "allocate-manager-linux-debian-10-amd64"
      - "allocate-manager-linux-debian-11-amd64"
      - "allocate-manager-linux-debian-12-amd64"
```

</details>

|System|Deploy instance|Connection instance|Install|Restart|Stop|Uninstall|
|:--|:--:|:--:|:--:|:--:|:--:|:--:|
|Red Hat 7 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Red Hat 8 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Red Hat 9 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|CentOS 7 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|CentOS 8 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 10 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 11 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 12 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 22.04 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 20.04 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Amazon Linux 2 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |

### Wazuh central components tests

- Log: [log_central_component.log](https://github.com/user-attachments/files/16845998/log_central_component.log)

<details>

<summary> YAML </summary>

```yaml
version: 0.1
description: This workflow is used to test the Wazuh manager deployment for DDT1 PoC
variables:
  central_components-os:
    - linux-ubuntu-20.04-amd64
    - linux-ubuntu-22.04-amd64
    - linux-amazon-2-amd64
    - linux-redhat-7-amd64
    - linux-redhat-8-amd64
    - linux-redhat-9-amd64
    - linux-centos-7-amd64
    - linux-centos-8-amd64
    - linux-debian-10-amd64
    - linux-debian-11-amd64
    - linux-debian-12-amd64
  infra-provider: aws
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique central components allocate task
  - task: "allocate-central_components-{central_components}"
    description: "Allocate resources for the central_components."
    do:
      this: process
      with:
        path: python3
        args:
          - deployability/modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{central_components}"
          - inventory-output: "{working-dir}/central_components-{central_components}/inventory.yaml"
          - track-output: "{working-dir}/central_components-{central_components}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh/issues/25497"
    foreach:
      - variable: central_components-os
        as: central_components
    cleanup:
      this: process
      with:
        path: python3
        args:
          - deployability/modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/central_components-{central_components}/track.yaml"

  # Generic manager test task
  - task: "run-central_components-{central_components}-tests"
    description: "Run tests install for the central_components."
    do:
      this: process
      with:
        path: python3
        args:
          - deployability/modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/central_components-{central_components}/inventory.yaml"
          - tests: "install,restart,stop,uninstall"
          - component: "central_components"
          - wazuh-version: "4.9.0"
          - wazuh-revision: "40907"
          - live: False
    foreach:
      - variable: central_components-os
        as: central_components
    depends-on:
      - "allocate-central_components-linux-ubuntu-20.04-amd64"
      - "allocate-central_components-linux-ubuntu-22.04-amd64"
      - "allocate-central_components-linux-amazon-2-amd64"
      - "allocate-central_components-linux-redhat-7-amd64"
      - "allocate-central_components-linux-redhat-8-amd64"
      - "allocate-central_components-linux-redhat-8-amd64"
      - "allocate-central_components-linux-redhat-9-amd64"
      - "allocate-central_components-linux-centos-7-amd64"
      - "allocate-central_components-linux-centos-8-amd64"
      - "allocate-central_components-linux-debian-10-amd64"
      - "allocate-central_components-linux-debian-11-amd64"
      - "allocate-central_components-linux-debian-12-amd64"
```

</details>

|System|Deploy instance|Connection instance|Install|Restart|Stop|Uninstall|
|:--|:--:|:--:|:--:|:--:|:--:|:--:|
|Red Hat 7 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Red Hat 8 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Red Hat 9 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|CentOS 7 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|CentOS 8 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 10 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 11 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 12 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 22.04 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 20.04 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Amazon Linux 2 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |

---

Status legend:

:black_circle: - Not started/In progress
:white_circle: - Skipped
:red_circle: - Found new errors/bugs/failures
:yellow_circle: - Found known errors/bugs/failures
:green_circle: - All tests passed

---

## Conclusion :green_circle:

- No abnormalities were found

---

## Auditor's validation
In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.
- [x] @wazuh/devel-qa-release

**Comment by Rebits** [comment]
Currently running DTT tests

**Comment by fcaffieri** [comment]
LGTM

**Comment by rauldpm** [comment]
There is some failed tasks in the log provided, like

```
TASK [Gathering Facts] *********************************************************
[0;31mfatal: [localhost]: FAILED! => changed=false [0m
[0;31m  ansible_facts: {}[0m
[0;31m  failed_modules:[0m
[0;31m    ansible.legacy.setup:[0m
[0;31m      failed: true[0m
[0;31m      module_stderr: |-[0m
[0;31m        sudo: a password is required[0m
[0;31m      module_stdout: ''[0m
[0;31m      msg: |-[0m
[0;31m        MODULE FAILURE[0m
[0;31m        See stdout/stderr for the exact error[0m
[0;31m      rc: 1[0m
[0;31m  msg: |-[0m
[0;31m    The following modules failed to execute: ansible.legacy.setup[0m

PLAY RECAP *********************************************************************
[0;31mlocalhost[0m                  : ok=0    changed=0    unreachable=0    [0;31mfailed=1   [0m skipped=0    rescued=0    ignored=0  
```

Please review the log and ensure there is no other failed tasks

**Comment by fcaffieri** [comment]
All errors are about `cleanup.yaml`, it is not an error that affects the test itself. The [issue](https://github.com/wazuh/wazuh-qa/issues/5641) is reopened to analyze the reason for the failure.
At first, it would seem to be an error in the environment where it was executed since a replay of the test was performed in my local environment and it worked without errors:

Test:

<details> 
<summary> YAML </summary>

```
version: 0.1
description: This workflow is used to test agents deployment for DDT1 PoC
variables:
  macos-agent-os:
    - macos-ventura-13-amd64

  manager-os: linux-ubuntu-22.04-amd64
  infra-provider: aws
  macos-infra-provider: vagrant
  working-dir: /tmp/dtt1-poc

tasks:
  # Unique manager allocate task
  - task: "allocate-manager-{manager-os}"
    description: "Allocate resources for the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{infra-provider}"
          - size: large
          - composite-name: "{manager-os}"
          - inventory-output: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh/issues/25497"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/manager-{manager-os}/track.yaml"

  # Unique manager provision task
  - task: "provision-manager-{manager-os}"
    description: "Provision the manager."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/provision/main.py
          - inventory: "{working-dir}/manager-{manager-os}/inventory.yaml"
          - install:
            - component: wazuh-manager
              type: assistant
              version: 4.9.0
              live: False
    depends-on:
      - "allocate-manager-{manager-os}"
    on-error: "abort-all"

  # Unique agent allocate task
  - task: "allocate-macos-agent-{agent}"
    description: "Allocate resources for the agent."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: create
          - provider: "{macos-infra-provider}"
          - size: small
          - composite-name: "{agent}"
          - inventory-output: "{working-dir}/agent-{agent}/inventory.yaml"
          - track-output: "{working-dir}/agent-{agent}/track.yaml"
          - label-termination-date: "1d"
          - label-team: "qa"
          - label-issue: "https://github.com/wazuh/wazuh/issues/25497"
    foreach:
      - variable: macos-agent-os
        as: agent
    depends-on:
      - "provision-manager-{manager-os}"
    cleanup:
      this: process
      with:
        path: python3
        args:
          - modules/allocation/main.py
          - action: delete
          - track-output: "{working-dir}/agent-{agent}/track.yaml"

  # Generic agent test task
  - task: "run-macos-agent-{agent}-tests"
    description: "Run tests install for the agent {agent}."
    do:
      this: process
      with:
        path: python3
        args:
          - modules/testing/main.py
          - targets:
            - wazuh-1: "{working-dir}/manager-{manager-os}/inventory.yaml"
            - agent: "{working-dir}/agent-{agent}/inventory.yaml"
          - tests: "install,registration,connection,basic_info,restart,stop,uninstall"
          - component: "agent"
          - wazuh-version: "4.9.0"
          - wazuh-revision: "40907"
          - live: False
    foreach:
      - variable: macos-agent-os
        as: agent
    depends-on:
      - "allocate-macos-agent-{agent}"

```

</details> 

Logs:
[Test-agents-cleanup.log](https://github.com/user-attachments/files/16854751/Test-agents-cleanup.log)
