### ISSUE TITLE
Integration tests for FIM on Windows - Tier 2 fail

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#25563]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.9.0-rc2 | Integration test | Manager/Agent | Packages/Sources | Windows |

### Description
During test [Release 4.9.0 - RC 2- Agent integration test](https://github.com/wazuh/wazuh/issues/25538#top), it was found that the test case for FIM Tier 2 for Windows fails constantly, the test was run 5 times with the same result.

- Test [link](https://github.com/wazuh/wazuh/actions/workflows/integration-tests-fim-tier-2-win.yml)
  - Run workflow options: 
    - Use workflow from: v4.9.0-rc2
    - Base branch: v4.9.0-rc2
- Result [link](https://github.com/wazuh/wazuh/actions/runs/10689024409/job/29630373398)

### Error Log

```log
        wazuh_log_monitor = FileMonitor(WAZUH_LOG_PATH)
        wazuh_log_monitor.start(callback=generate_callback(test_metadata['regex']))
    
>       assert wazuh_log_monitor.callback_result
E       assert None
E        +  where None = <wazuh_testing.tools.monitors.file_monitor.FileMonitor object at 0x00000270E1C8A550>.callback_result

test_fim\test_files\test_ambiguous_confs\test_ignore_works_over_restrict.py:169: AssertionError

```

**Comment by cborla** [comment]
### Analysis

The test that fails is the only one of all the test cases in the file. 

``` log
test_fim\test_files\test_ambiguous_confs\test_ignore_works_over_restrict.py F........

================================== FAILURES ===================================
_ test_ignore_works_over_restrict[ignore_file_pattern_over_restrict_regex_scheduled] _
```

Test case file
```
#wazuh/tests/integration/test_fim/test_files/test_ambiguous_confs/data/test_cases/cases_ignore_works_over_restrict.yaml
```

Test case description:

```yaml
- name: ignore_file_pattern_over_restrict_regex_scheduled
  description: Check ignore pattern is applied over restrict regex
  configuration_parameters:
    REALTIME: 'no'
    WHODATA: 'no'
    RESTRICT: testfile$
    TEST_DIR: !!python/object/apply:os.path.join [/test_dir_1]
  metadata:
    folder_to_monitor: !!python/object/apply:os.path.join [/test_dir_1]
    file_to_monitor: !!python/object/apply:os.path.join [/test_dir_1/testfile]
    is_pattern: true
    regex: .*?Ignoring path '(.*)' due to pattern '(.*)'.*
    fim_mode: scheduled

```

Test case description for success case, it's a similar case but in `REALTIME: 'yes'`.

```yaml

- name: ignore_file_pattern_over_restrict_regex_realtime
  description: Check ignore pattern is applied over restrict regex
  configuration_parameters:
    REALTIME: 'yes'
    WHODATA: 'no'
    RESTRICT: testfile$
    TEST_DIR: !!python/object/apply:os.path.join [/test_dir_1]
  metadata:
    folder_to_monitor: !!python/object/apply:os.path.join [/test_dir_1]
    file_to_monitor: !!python/object/apply:os.path.join [/test_dir_1/testfile]
    is_pattern: true
    regex: .*?Ignoring path '(.*)' due to pattern '(.*)'.*
    fim_mode: realtime

```
The test fails every time it is launched, it appears to be a flaky test, because similar tests but in realtime yes does not fail.


### Changing the behaviour of the test.
Assuming it is a timing problem, a test is performed by adding a 20 second sleep time between the time the monitor is turned off and the assert is validated.

Branch: `test/25563-fix-fim-tier2-win-test`
Test link: https://github.com/wazuh/wazuh/actions/runs/10693064255/job/29642688800
Result: Fail 🔴
