### ISSUE TITLE
Failing test - Integration tests for Agentd on Windows - Tier 0 and 1

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#25603]
## Description
While performing the [post release tasks for 4.9.0](https://github.com/wazuh/wazuh/issues/25590), we found that the ["Integration tests for Agentd on Windows - Tier 0 and 1"](https://github.com/wazuh/wazuh/actions/runs/10725471692/job/29743644399?pr=25601) are failing. 
```
FAILED test_agentd/test_state/test_agentd_state.py::test_agentd_state[Successful_connection_with_remoted]
FAILED test_agentd/test_state/test_agentd_state.py::test_agentd_state[Only_remote_request_available]
=========== 2 failed, 35 passed, 26 warnings in 2540.24s (0:42:20) ============
```

> [!NOTE]
> It may be related to:
> - https://github.com/wazuh/wazuh/issues/23995

## DoD
- [ ] Root cause found
- [ ] Issue fixed

**Comment by LucioDonda** [comment]
This is a flaky test, [rerun](https://github.com/wazuh/wazuh/actions/runs/10725471692/job/29895090558) under the same conditions and results were OK.

### Successful_connection_with_remoted
`FAILED test_agentd/test_state/test_agentd_state.py::test_agentd_state[Successful_connection_with_remoted]`

When starting the log monitor called from _check_msg_count_ inside of _check_fields_ tries to convert current_value to int but the type doesn't match.
```
wazuh_log_monitor.start(only_new_events = True, callback=callbacks.generate_callback AGENTD_SENDING_AGENT_NOTIFICATION), accumulations = int(current_value))
E TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
test_agentd\utils.py:70: TypeError
```
Inside the test config for this case:

```
- name: "Successful_connection_with_remoted"
  description:
  configuration_parameters:
  metadata:
    remoted: true
    output:
    - type: "file"
      fields:
        status: "connected"
        last_keepalive: true
        last_ack: true
        msg_count: true
```


### Only_remote_request_available - WIP
`FAILED test_agentd/test_state/test_agentd_state.py::test_agentd_state[Only_remote_request_available]`

```
assert (wazuh_log_monitor.callback_result != None), f'Sending keep alive not found'
E AssertionError: Sending keep alive not found
test_agentd\utils.py:17: AssertionError
```
