### ISSUE TITLE
Define minimum configuration for Wazuh Server Node

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#25697]
| Related task |
|---|
| https://github.com/wazuh/wazuh/issues/25193 |

## Description

This issue aims to define the minimum required configuration for the deployment of a Wazuh Server node. This includes the configuration related to the Cluster, Managment API, Communication API, and the Server node itself.  This also includes the definition of configuration related to services used by the component described above, like the Indexer configuration.

The definitions not only include the configuration options themselves it also include the definition of the default values for each configuration option.

## Requirements
- [x] Define the minimum required configuration for the Cluster.
- [x] Define the minimum required configuration for the Managment API.
- [x] Define the minimum required configuration for the Communication API.
- [x] Define the minimum required configuration for the Server node.
- [x] Example of the configuration with their default values.

**Comment by RamosFe** [comment]
## Update

I continue checking the new configuration options added in `comms_api` and documenting the minimum configuration found on the other issues.

**Comment by RamosFe** [comment]
## Update -  Cluster configurations

After the analysis in https://github.com/wazuh/wazuh/issues/25702#issuecomment-2383981401, I passed the configuration options to a `yaml` format and changed how the configuration is divided for better name consistency (Example: joining the intervals in one section and the retries in other). The default values are the ones we are already using in the cluster configuration.

Finally the `shared_files` now includes a list of directories instead of using keys (For example "etc/shared/") to identify were we should search this files. Nowadays the code already does the logic of a list of files but without using a list, as shown in the following code:

<details>
<summary>Cluster code</summary>

```python
def get_files_status(previous_status=None, get_hash=True):
    """Get all files and metadata inside the directories listed in cluster.json['files'].

    Parameters
    ----------
    previous_status : dict
        Information collected in the previous integration process.
    get_hash : bool
        Whether to calculate and save the BLAKE2b hash of the found file.

    Returns
    -------
    final_items : dict
        Paths (keys) and metadata (values) of all the files requested in cluster.json['files'].
    result_logs: dict
        Dict containing debug or any error messages emitted in the process.
    """
    if previous_status is None:
        previous_status = {}

    cluster_items = get_cluster_items()

    final_items = {}
    result_logs = {'debug': defaultdict(dict), 'warning': defaultdict(list), 'error': defaultdict(dict)}
    for file_path, item in cluster_items['files'].items():
        if file_path == "excluded_files" or file_path == "excluded_extensions":
            continue
        try:
            items, logs = walk_dir(file_path, item['recursive'], item['files'],
                                   cluster_items['files']['excluded_files'],
                                   cluster_items['files']['excluded_extensions'],
                                   file_path, previous_status, get_hash)
            if 'debug' in logs and logs['debug']:
                result_logs['debug'][file_path].update(dict(logs['debug']))
            if 'error' in logs and logs['error']:
                result_logs['error'][file_path].update(dict(logs['error']))
            final_items.update(items)
        except Exception as e:
            result_logs['warning'][file_path].append(f"Error getting file status: {e}.")

    return final_items, result_logs
```

</details>

The cluster configuration in `yaml` format:

```yaml
cluster:
  shared_files:
    files:
      - path: "etc/shared/"
        description: "group files"
        permissions: "0o660"
        source: "master"
        files:
          - "all"
        recursive: false
        restart: false
        remove_subdirs_if_empty: true
        extra_valid: false

    excluded_files:
      - "ar.conf"

    excluded_extensions:
      - "~",
      - ".tmp",
      - ".lock",
      - ".swp"

  worker:
    intervals:
      sync_integrity: 9,
      keep_alive: 60,
      connection_retry: 10,
    retries:
      max_failed_keepalive_attempts: 2
  master:
    intervals:
      timeout_extra_valid: 40,
      recalculate_integrity: 8,
      check_worker_lastkeepalive: 60,
      max_allowed_time_without_keepalive: 120,
      max_locked_integrity_time: 1000
    processes:
      process_pool_size: 2

  communications:
    zip:
      max_zip_size: 1073741824,
      min_zip_size: 31457280,
      compress_level: 1,
      zip_limit_tolerance: 0.2
    timeouts:
      timeout_cluster_request: 20,
      timeout_dapi_request: 200,
      timeout_receiving_file: 120,
```

**Comment by RamosFe** [comment]
## Update - Management API configurations

After the analysis made in https://github.com/wazuh/wazuh/issues/25595#issuecomment-2341122581, the Management API will contain the following format with this values as default values. The only configuration options missions are the ones related to `upload_configuration`, which they will be analyzed after defining the complete configuration.

```yaml
management_api:
  host: 0.0.0.0
  port: 55000
  drop_privileges: true
  max_upload_size: 10485760

  intervals:
    request_timeout: 10

  https:
    key: "server.key"
    cert: "server.crt"
    use_ca: False
    ca: "ca.crt"
    ssl_protocol: "auto"
    ssl_ciphers: ""

  logs:
    level: "info"
    format: "plain"
    max_size:
      enabled: false

  cors:
    enabled: no
    source_route: "*"
    expose_headers: "*"
    allow_headers: "*"
    allow_credentials: no

  access:
    max_login_attempts: 50
    block_time: 300
    max_request_per_minute: 300
```

**Comment by RamosFe** [comment]
## Update - Communications API

Here are the communications API configuration options. The Indexer configurations are missing and should be reviewed in the `Server node configuration` section. Each configuration option has a comment with the file where it is used.

```yaml
communications_api:
  batcher: # framework/wazuh/core/batcher/config.py
    batcher_max_elements: 5
    batcher_max_size: 30000
    batcher_wait_time: 0.15
  https: # apis/comms_api/scripts/wazuh_comms_apid.py
    key: "server.key"
    cert: "server.crt"
  files:
    path: "/file" # apis/comms_api/core/files.py
```

**Comment by RamosFe** [comment]
## Update - Server node

There are multiple configuration options we must take into account with the server node:
- `Cluster`: Configuration related to the cluster itself. These configuration options are migrated from `ossec.conf` as mentioned in https://github.com/wazuh/wazuh/issues/25595#issuecomment-2344674974.
- `Integrations`: Configuration related to the integrations. These configuration options are migrated from `ossec.conf` as mentioned in https://github.com/wazuh/wazuh/issues/25595#issuecomment-2344674974.
- `Debug`: Configuration options migrated from `internal_options.conf`. Documentation: https://github.com/wazuh/wazuh/issues/25595#issuecomment-2344692423.
- `Engine`: Configuration options needed by the Engine. Details in  https://github.com/wazuh/wazuh/issues/25472#issuecomment-2341233505.
- `Index`: Configuration options for the Indexer. These configuration options are used by the Engine as well as the Communications API. Details in  https://github.com/wazuh/wazuh/issues/25472#issuecomment-2345119633.

The configuration options for the server node will have the following structure with these default values:
> The Index names are placeholder and will be changed depending on future definitions

```yaml
cluster:
  # Configuration options migrated from ossec.conf
  # Details in https://github.com/wazuh/wazuh/issues/25595#issuecomment-2344674974
  node_config:
    name: wazuh
    node_name: manager_01
    node_type: master
    key: ugdtAnd7Pi9myP7CVts4qZaZQEQcRYZa
    port: 1516
    bind_addr: 0.0.0.0
    nodes:
      - master
    hidden: no
    disabled: no
  haproxy_helper:
    haproxy_disabled: no
    haproxy_address: wazuh-proxy
    haproxy_user: haproxy
    haproxy_password: haproxy
    haproxy_port: 5555
    haproxy_protocol: http
    haproxy_backend: wazuh_cluster
    frequency: 60
    agent_chunk_size: 100
    agent_reconnection_time: 10
    agent_reconnection_stability_time: 60
    imbalance_tolerance: 0.1
    remove_disconnected_node_after: 10

# Integrations configuration migrated from ossec.conf
# Details in https://github.com/wazuh/wazuh/issues/25595#issuecomment-2344674974
integrations:
  - name: slack
    hook_url: https://hooks.slack.com/services/...
    level: 10
    group: multiple_drops,authentication_failures
    alert_format: json
    options:
      pretext: Custom Title

  - name: pagerduty
    api_key: API_KEY
    options:
      pretext: Custom title
    alert_format: json

  - name: virustotal
    api_key: API_KEY
    group: syscheck
    alert_format: json
    timeout: 30
    retries: 5

# Configuration options migrated from internal_options.conf
# Details in https://github.com/wazuh/wazuh/issues/25595#issuecomment-2344692423
debug:
  integrator: 0
  wazuh_clusterd: 0

# Configuration required by Cppserver team documented in https://github.com/wazuh/wazuh/issues/25472#issuecomment-2345119633
# And required by the Communications API for the communication with the API
index:
  host:
    - localhost:9200
  user: admin
  password: admin
  ssl:
    certificate_authorities: /etc/ssl/certs/ca.pem
    certificate: /etc/ssl/certs/cert.pem
    key: /etc/ssl/certs/key.pem
  indexes:
    alert: wazuh-alerts-5.x
    agents: agents-index # To define value
    commands: commands-index # To define value
    events: events-index # To define value

# Configuration required by the Engine documented in https://github.com/wazuh/wazuh/issues/25472#issuecomment-2341233505
engine:
  log_level: debug
  tzdv_automatic_update: false
```

**Comment by RamosFe** [comment]
## Update - Complete configuration

Here is the complete configuration with each extract showed in the comments above:

```yaml
cluster:
  # Configuration options migrated from ossec.conf
  # Details in https://github.com/wazuh/wazuh/issues/25595#issuecomment-2344674974
  node_config:
    name: wazuh
    node_name: manager_01
    node_type: master
    key: ugdtAnd7Pi9myP7CVts4qZaZQEQcRYZa
    port: 1516
    bind_addr: 0.0.0.0
    nodes:
      - master
    hidden: no
    disabled: no
  haproxy_helper:
    haproxy_disabled: no
    haproxy_address: wazuh-proxy
    haproxy_user: haproxy
    haproxy_password: haproxy
    haproxy_port: 5555
    haproxy_protocol: http
    haproxy_backend: wazuh_cluster
    frequency: 60
    agent_chunk_size: 100
    agent_reconnection_time: 10
    agent_reconnection_stability_time: 60
    imbalance_tolerance: 0.1
    remove_disconnected_node_after: 10

  # Configuration options migrated from `cluster.json`
  shared_files:
    files:
      - path: "etc/shared/"
        description: "group files"
        permissions: "0o660"
        source: "master"
        files:
          - "all"
        recursive: false
        restart: false
        remove_subdirs_if_empty: true
        extra_valid: false

    excluded_files:
      - "ar.conf"

    excluded_extensions:
      - "~",
      - ".tmp",
      - ".lock",
      - ".swp"

  worker:
    intervals:
      sync_integrity: 9,
      keep_alive: 60,
      connection_retry: 10,
    retries:
      max_failed_keepalive_attempts: 2
  master:
    intervals:
      timeout_extra_valid: 40
      recalculate_integrity: 8
      check_worker_lastkeepalive: 60
      max_allowed_time_without_keepalive: 120
      max_locked_integrity_time: 1000
    processes:
      process_pool_size: 2

  communications:
    zip:
      max_zip_size: 1073741824,
      min_zip_size: 31457280,
      compress_level: 1,
      zip_limit_tolerance: 0.2
    timeouts:
      timeout_cluster_request: 20
      timeout_dapi_request: 200
      timeout_receiving_file: 120

# Integrations configuration migrated from ossec.conf
# Details in https://github.com/wazuh/wazuh/issues/25595#issuecomment-2344674974
integrations:
  - name: slack
    hook_url: https://hooks.slack.com/services/...
    level: 10
    group: multiple_drops,authentication_failures
    alert_format: json
    options:
      pretext: Custom Title

  - name: pagerduty
    api_key: API_KEY
    options:
      pretext: Custom title
    alert_format: json

  - name: virustotal
    api_key: API_KEY
    group: syscheck
    alert_format: json
    timeout: 30
    retries: 5

# Configuration options migrated from internal_options.conf
# Details in https://github.com/wazuh/wazuh/issues/25595#issuecomment-2344692423
debug:
  integrator: 0
  wazuh_clusterd: 0

# Configuration required by Cppserver team documented in https://github.com/wazuh/wazuh/issues/25472#issuecomment-2345119633
# And required by the Communications API for the communication with the API
indexer:
  host:
    - localhost:9200
  user: admin
  password: admin
  ssl:
    certificate_authorities: /etc/ssl/certs/ca.pem
    certificate: /etc/ssl/certs/cert.pem
    key: /etc/ssl/certs/key.pem
  indexes:
    alert: wazuh-alerts-5.x
    agents: agents-index # To define value
    commands: commands-index # To define value
    events: events-index # To define value

# Configuration required by the Engine documented in https://github.com/wazuh/wazuh/issues/25472#issuecomment-2341233505
engine:
  log_level: debug
  tzdv_automatic_update: false

# Managment API configuration
management_api:
  host: 0.0.0.0
  port: 55000
  drop_privileges: true
  max_upload_size: 10485760

  intervals:
    request_timeout: 10

  https:
    key: "server.key"
    cert: "server.crt"
    use_ca: False
    ca: "ca.crt"
    ssl_protocol: "auto"
    ssl_ciphers: ""

  logs:
    level: "info"
    format: "plain"
    max_size:
      enabled: false

  cors:
    enabled: no
    source_route: "*"
    expose_headers: "*"
    allow_headers: "*"
    allow_credentials: no

  access:
    max_login_attempts: 50
    block_time: 300
    max_request_per_minute: 300

# Communication API
communications_api:
  batcher: # framework/wazuh/core/batcher/config.py
    batcher_max_elements: 5
    batcher_max_size: 30000
    batcher_wait_time: 0.15
  https: # apis/comms_api/scripts/wazuh_comms_apid.py
    key: "server.key"
    cert: "server.crt"
  files:
    path: "/file" # apis/comms_api/core/files.py
```

**Comment by GGP1** [comment]
## Review

After reviewing the configurations of the different components, here are the changes I would apply:

1. Rename `cluster` to `server`.
2. I would remove `cluster.node_config` and leave its fields in the first level (i.e. `server.node_type`, `server.bind_addr`, etc).
3. `name`, `disabled` and `key` were removed to make a cluster by default, so they shouldn't be included in `cluster.node_config`.
4. We should add `cafile`, `certfile`, `keyfile` and `keyfile_password` inside `cluster.node_config`.
5. `cluster.node_config.bind_addr` should bind to `localhost`.
6. The HAProxy helper won't be part of 5.0, so it should be removed.
7. I would rename `timeouts.timeout_cluster_request` to `timeout.cluster_request`.
8. `debug` should be removed, the logging level should be set on a per-module basis instead of a global config.
9. SSL configurations should be the same on all components (server, indexer, management API, communications API).
10. `engine` options seem limited, I see a lot more in their [tests](https://github.com/wazuh/wazuh/blob/master/src/engine/test/health_test/configuration_files/general.conf). Let's ask the Cpp Server team for the full list.
11. We need to add a section for the [engine client configurations](https://github.com/wazuh/wazuh/blob/64db62a9ab2c537a87ea2fa4f424cb181eb23f82/framework/wazuh/core/engine/__init__.py#L13-L15) (perhaps within `engine`, like we do in `indexer`)
12. `management_api.host` should have a default value of `localhost`.
13. We should discuss whether to include `management_api.https.enabled` or not. Even though it's unsafe, it may help for debugging purposes to have it on hand.
14. We should add `communications_api.workers` so users can specify the number of workers spawned by gunicorn.
15. We should add `communications_api.https.cafile` to specify the path to the root CA file.
16. I would rename `communications_api.batcher.batcher_max_elements` to `batcher.max_elements`, same with the others.
17. I would rename `communications_api.files.path` to `communications_api.files.dir`. Although I'm not sure if this is going to be a configuration option or not.

**Comment by GGP1** [comment]
## Review

After reviewing the configurations of the different components, here are the changes I would apply:

1. Rename `cluster` to `server`.
2. I would remove `cluster.node_config` and leave its fields in the first level (i.e. `server.node_type`, `server.bind_addr`, etc).
3. `name`, `disabled` and `key` were removed to make a cluster by default, so they shouldn't be included in `cluster.node_config`.
4. We should add `cafile`, `certfile`, `keyfile` and `keyfile_password` inside `cluster.node_config`.
5. `cluster.node_config.bind_addr` should bind to `localhost`.
6. The HAProxy helper won't be part of 5.0, so it should be removed.
7. I would rename `timeouts.timeout_cluster_request` to `timeout.cluster_request`.
8. `debug` should be removed, the logging level should be set on a per-module basis instead of a global config.
9. SSL configurations should be the same on all components (server, indexer, management API, communications API).
10. `engine` options seem limited, I see a lot more in their [tests](https://github.com/wazuh/wazuh/blob/master/src/engine/test/health_test/configuration_files/general.conf). Let's ask the Cpp Server team for the full list.
11. We need to add a section for the [engine client configurations](https://github.com/wazuh/wazuh/blob/64db62a9ab2c537a87ea2fa4f424cb181eb23f82/framework/wazuh/core/engine/__init__.py#L13-L15) (perhaps within `engine`, like we do in `indexer`)
12. `management_api.host` should have a default value of `localhost`.
13. We should discuss whether to include `management_api.https.enabled` or not. Even though it's unsafe, it may help for debugging purposes to have it on hand.
14. We should add `communications_api.workers` so users can specify the number of workers spawned by gunicorn.
15. We should add `communications_api.https.cafile` to specify the path to the root CA file.
16. I would rename `communications_api.batcher.batcher_max_elements` to `batcher.max_elements`, same with the others.
17. I would rename `communications_api.files.path` to `communications_api.files.dir`. Although I'm not sure if this is going to be a configuration option or not.

**Comment by RamosFe** [comment]
## Update - Changes and corrections

I added the following changes:
- [ ] 1. Rename `cluster` to `server`.
- [ ] 2. I would remove `cluster.node_config` and leave its fields in the first level (i.e. `server.node_type`, `server.bind_addr`, etc).
- [ ] 3. `name`, `disabled` and `key` were removed to make a cluster by default, so they shouldn't be included in `cluster.node_config`.
- [ ] 4. We should add `cafile`, `certfile`, `keyfile` and `keyfile_password` inside `cluster.node_config`.
- [ ] 5. `cluster.node_config.bind_addr` should bind to `localhost`.
- [ ] 6. The HAProxy helper won't be part of 5.0, so it should be removed.
- [ ] 7. I would rename `timeouts.timeout_cluster_request` to `timeout.cluster_request`.
- [ ] 8. `debug` should be removed, the logging level should be set on a per-module basis instead of a global config.
- [ ] 9. SSL configurations should be the same on all components (server, indexer, management API, communications API).
- [ ] 10. `engine` options seem limited, I see a lot more in their [tests](https://github.com/wazuh/wazuh/blob/master/src/engine/test/health_test/configuration_files/general.conf). Let's ask the Cpp Server team for the full list.
- [ ] 11. We need to add a section for the [engine client configurations](https://github.com/wazuh/wazuh/blob/64db62a9ab2c537a87ea2fa4f424cb181eb23f82/framework/wazuh/core/engine/__init__.py#L13-L15) (perhaps within `engine`, like we do in `indexer`)
- [ ] 12. `management_api.host` should have a default value of `localhost`.
- [ ] 13. We should discuss whether to include `management_api.https.enabled` or not. Even though it's unsafe, it may help for debugging purposes to have it on hand.
- [ ] 14. We should add `communications_api.workers` so users can specify the number of workers spawned by gunicorn.
- [ ] 15. We should add `communications_api.https.cafile` to specify the path to the root CA file.
- [ ] 16. I would rename `communications_api.batcher.batcher_max_elements` to `batcher.max_elements`, same with the others.
- [ ] 17. I would rename `communications_api.files.path` to `communications_api.files.dir`. Although I'm not sure if this is going to be a configuration option or not.

**Comment by RamosFe** [comment]
## Update

Completed the missing points and updated each of the comments.

**Comment by GGP1** [comment]
## Review

1. We shouldn't use `config` as part of a key, since that is implicit. I would replace `server.node_config.ssl` with `server.node.ssl`
2. Related to the change above, include `node_name` and `node_type` inside `server.node` as `server.node.name` and `server.node.type`
3. We have `shared_files.files[].files[]`, which is a bit weird, we could probably use `integrity_sync.files[].names[]` instead
4. I would try to avoid repeating the same name in a configuration chain. For example in `communications.zip.max_zip_size` we are using `zip twice`. I would personally prefer

```yaml
communications:
    zip:
      max_size: 1073741824
      min_size: 31457280
      compress_level: 1
      limit_tolerance: 0.2
```

5. We should use `indexer` instead of `index`
6. The `communications_api` section should include the fields `host` and `port`

**Comment by RamosFe** [comment]
## Update

Made all the changes suggested in https://github.com/wazuh/wazuh/issues/25697#issuecomment-2419213986.

**Comment by fdalmaup** [comment]
# Review

GJ. Points to take into account:
- Please, attach which would be the minimum default content of the configuration when installing the Wazuh server, leaving only what the user must review/modify.
- I would not leave the `communications_api.files.dir` as a configuration option.
- The timeout value of the Comms API endpoints is not being taken into account as parameters to set in the configuration.

**Comment by RamosFe** [comment]
## Update

The minimum required configuration is the following:

```yaml
server:
  node:
    name: manager_01
    type: master

indexer:
  host:
    - 'localhost:9200'
  user: admin
  password: admin
```

The node `name` can't be defaulted due to the cluster not allowing duplicate nodes in the same name, and the `type` is needed to know the type of the node, different node types require different actions when initializing, including how the configuration pulling mechanism works.

Finally, the fields related to the indexer connection and credentials are needed to initialize the server processes.

I will discuss with the team if there are more configuration options we should consider.

**Comment by RamosFe** [comment]
## Complete configuration

After the changes made in https://github.com/wazuh/wazuh/issues/26356, the following configuration is the final one:


```yaml
server:
  port: 1516
  bind_addr: "0.0.0.0"
  nodes: 
    - 'master' 
  hidden: false
  update_check: false
  node:
    name: ""
    type: "master"
    ssl:
      key: ""
      cert: ""
      ca: ""
      keyfile_password: ""
  worker:
    intervals:
      sync_integrity: 9
      keep_alive: 60
      connection_retry: 10
    retries:
      max_failed_keepalive_attempts: 2
  master:
    intervals:
      timeout_extra_valid: 40
      recalculate_integrity: 8
      check_worker_last_keep_alive: 60
      max_allowed_time_without_keep_alive: 120
      max_locked_integrity_time: 1000
    processes:
      process_pool_size: 2
  communications:
    zip:
      max_size: 1073741824
      min_size: 31457280
      compress_level: 1
      limit_tolerance: 0.2
    timeouts:
      cluster_request: 20
      dapi_request: 200
      receiving_file: 120
  logging:
    level: "debug2"
  cti:
    update_check: true
    url: "https://cti.wazuh.com"
indexer:
  host: ""
  port: 0
  user: ""
  password: ""
  ssl:
    use_ssl: false
    key: ""
    cert: ""
    ca: ""
engine:
  tzdv_automatic_update: false
  client:
    api_socket_path: "/var/wazuh/queue/engine.sock"
    retries: 3
    timeout: 10.0
  logging:
    level: "info"
management:
  host: "0.0.0.0"
  port: 55000
  drop_privileges: true
  max_upload_size: 10485760
  jwt_expiration_timeout: 900
  rbac_mode: "white"
  intervals:
    request_timeout: 10
  ssl:
    key: "/var/ossec/api/configuration/ssl/server.key"
    cert: "/var/ossec/api/configuration/ssl/server.crt"
    use_ca: false
    ca: ""
    ssl_protocol: "auto"
    ssl_ciphers: ""
  logging:
    level: "debug"
  cors:
    enabled: false
    source_route: "*"
    expose_headers: "*"
    allow_headers: "*"
    allow_credentials: false
  access:
    max_login_attempts: 50
    block_time: 300
    max_request_per_minute: 300
communications_api:
  host: "localhost"
  port: 27000
  workers: 4
  logging:
    level: "debug"
    format:
      - "plain"
  batcher:
    max_elements: 5
    max_size: 3000
    wait_time: 0.15
  intervals:
    request_timeout: 10
  ssl:
    key: "/var/ossec/api/configuration/ssl/server.key"
    cert: "/var/ossec/api/configuration/ssl/server.crt"
    use_ca: false
    ca: ""
    ssl_protocol: "auto"
    ssl_ciphers: ""
```
