### ISSUE TITLE
Active response not triggered for Windows endpoint

### ISSUE THREAD

**Issue by thecotilking** [wazuh/wazuh#25950]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.1 - RC 1 | Active Response | Agent | Packages | Windows 10 |

During https://github.com/wazuh/wazuh/issues/25826#issuecomment-2371428340, following this [documentation](https://documentation-dev.wazuh.com/v4.9.1-rc1/user-manual/capabilities/malware-detection/fim-yara.html#use-case-detecting-malware-on-windows-endpoints-using-yara) it was found that the active response yara.bat for Windows endpoints is not activating even after the FIM rule was triggered as seen ![image](https://github.com/user-attachments/assets/07e610c6-3619-43c0-933f-139481d56e15)

<details><summary>Agents ossec.log</summary>

[ossec.log](https://github.com/user-attachments/files/17134108/ossec.log)

</details>

Also no logs on the active-responses.log concerning this

**Comment by MarcelKemp** [comment]
## Testing

After performing the tests according to the steps that appear in the documentation for a manager and agent 4.9.1, I have observed that there is no problem, since both the alerts and AR are generated and executed correctly. 

These are the results I have obtained:

<details><summary>Syscheck Alert</summary>

```
** Alert 1727351357.2349630: - syscheck,
2024 Sep 26 11:49:17 (win11) any->syscheck
Rule: 100304 (level 7) -> 'File added to C:\Users\vagrant\Downloads  directory.'
File 'c:\users\vagrant\downloads\eicar.com' added
Mode: realtime

Attributes:
 - Size: 68
 - Permissions: SYSTEM (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES, Administrators (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES, vagrant (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES
 - Date: Wed May 24 19:07:00 2000
 - Inode: 0
 - User: Administrators (S-1-5-32-544)
 - MD5: 44d88612fea8a8f36de82e1278abb02f
 - SHA1: 3395856ce81f2b7382dee72602f798b642f14140
 - SHA256: 275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f
 - File attributes: ARCHIVE
 ```

</details>

<details><summary>active-responses.log</summary>

```
c:\users\vagrant\downloads\eicar.com 
wazuh-yara: INFO - Scan result: SUSP_Just_EICAR_RID2C24 c:\users\vagrant\downloads\eicar.com 
```

</details>

<details open><summary>AR Alert</summary>

```
** Alert 1727351361.2350682: mail  - yara,
2024 Sep 26 11:49:21 (win11) any->active-response\active-responses.log
Rule: 108001 (level 12) -> 'File "c:\users\vagrant\downloads\eicar.com" is a positive match. Yara rule: SUSP_Just_EICAR_RID2C24'
wazuh-yara: INFO - Scan result: SUSP_Just_EICAR_RID2C24 c:\users\vagrant\downloads\eicar.com
log_type: INFO
yara_rule: SUSP_Just_EICAR_RID2C24
yara_scanned_file: c:\users\vagrant\downloads\eicar.com
```

</details>

So I conclude that the bug must be in the configuration process.

Please, @thecotilking check the steps again and verify if it works for you or if there is a problem with your OS. In that case I would need more information about the Windows you are using for testing.
