### ISSUE TITLE
Upload wazuh-server packages artifacts to GitHub

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#26863]
## Description

The [workflow](https://github.com/wazuh/wazuh/blob/master/.github/workflows/packages-build-server.yml) we use to create the server packages is currently uploading the artifacts to AWS S3 in a location that many of us can't access.

It would be ideal if we could upload the packages to GitHub using the [upload-artifact](https://github.com/actions/upload-artifact) action to have them available in the build itself. We would need something like this:

```yaml
 - name: Upload artifact
   uses: actions/upload-artifact@v4
   with:
     name: ${{ env.PACKAGE_NAME }}
     path: /tmp/${{ env.PACKAGE_NAME }}
     if-no-files-found: error
```

This issue aims at investigating how to upload the packages to both places and implement the changes necessary to do so.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).
