### ISSUE TITLE
Getting 401 Unauthorized when trying to Access Wazuh Dashboard via SAML SSO with Onelogin Integration

### ISSUE THREAD

**Issue by rbenabdelaziz** [wazuh/wazuh#26875]
I have configured Wazuh (**version 4.8.1, installed using Docker**) for SSO via **SAML 2.0** following the official Wazuh documentation : ([https://documentation.wazuh.com/current/user-manual/user-administration/single-sign-on/administrator/onelogin.html])

 Additionally, I referred to a related GitHub issue for guidance. However, when attempting to log into the Wazuh Dashboard, I encounter a 401 Unauthorized error after being redirected back from the OneLogin IdP.

1. Here’s the relevant configuration section from my /usr/share/wazuh-indexer/opensearch-security/config.yml file:

```
basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: "basic"
          challenge: false
        authentication_backend:
          type: "intern"
      saml_auth_domain2:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: "saml"
          challenge: true
          config:
            idp:
              metadata_file: '/usr/share/wazuh-indexer/opensearch-security/metadata_onelogin.xml'
              entity_id: 'https://app.onelogin.com/saml/metadata/be43xxxxxxxxxxxxxxxxxxxxxxxxxxxx' 
            sp:
              entity_id: wazuh-saml
            kibana_url: https://x.x.x.x 
            roles_key: Roles
            exchange_key: 'x509 Certificate for signing the request'
        authentication_backend:
          type: noop
```

2. Also /usr/share/wazuh-indexer/opensearch-security/roles_mapping.yml file : 

```
## Default roles mapping

all_access:
  reserved: true
  hidden: false
  backend_roles:
  - "admin"
  - "wazuh-admin"
  hosts: []
  users: []
  and_backend_roles: []
  description: "Maps admin to all_access"
```
3. On Wazuh dashboard configuration side, here's opensearch_dashboards.yml file configurations :

```
server.host: x.x.x.x
server.port: 5601
opensearch.hosts: https://wazuh.indexer:9200
opensearch.ssl.verificationMode: certificate
opensearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
server.ssl.enabled: true
server.ssl.key: "/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem"
server.ssl.certificate: "/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem"
opensearch.ssl.certificateAuthorities: ["/usr/share/wazuh-dashboard/certs/root-ca.pem"]
uiSettings.overrides.defaultRoute: /app/wz-home
opensearch_security.auth.type: ["basicauth","saml"]
server.xsrf.allowlist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout", "/_opendistro/_security/saml/acs/idpinitiated"]
opensearch_security.session.keepalive: false
opensearch_security.auth.multiple_auth_enabled: true

```
I've added  a role mapping on the Wazuh dashboard: 

![44](https://github.com/user-attachments/assets/c5315aea-b777-466b-af62-6b6f783e9495)

Here is the configuration on the OneLogin side : 
![Image chargée (2)](https://github.com/user-attachments/assets/38a0a259-c224-4f57-8564-1767d0aed40c)
![Image chargée (1)](https://github.com/user-attachments/assets/0dffed85-800a-431b-85c2-a964df03f81b)
![Image chargée](https://github.com/user-attachments/assets/d92e5c8e-849a-4389-a321-78ac250e7048)
![Image chargée par l’utilisateur](https://github.com/user-attachments/assets/3bc0c6a9-0f8b-463c-9a84-189f9642fcd4)

When I tried to access the Wazuh Dashboard, I encountered the following errors in the wazuh.indexer logs:

**`[wazuh.indexer] No 'Authorization' header, send 401 and 'WWW-Authenticate Basic`**

Here are the Wazuh.dashboard logs : 

```
wazuh.dashboard-1  | {"type":"response","@timestamp":"2024-11-15T15:59:21Z","tags":[],"pid":54,"method":"get","statusCode":302,"req":{"url":"/auth/saml/login?nextUrl=%2F&redirectHash=false","method":"get","headers":{"host":"<wazuh_dashboard_url>","x-real-ip":"x.x.x","x-forwarded-for":"x.x.x.x","x-forwarded-proto":"https","connection":"close","sec-ch-ua":"\"Brave\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8","sec-gpc":"1","accept-language":"fr-FR,fr","sec-fetch-site":"same-origin","sec-fetch-mode":"navigate","sec-fetch-dest":"document","referer":"https://<wazuh_dashboard_url>/auth/saml/captureUrlFragment?nextUrl=%2F","accept-encoding":"gzip, deflate, br, zstd"},"remoteAddress":"x.x.x.x","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","referer":"https://<wazuh_dashboard_url>/auth/saml/captureUrlFragment?nextUrl=%2F"},"res":{"statusCode":302,"responseTime":37,"contentLength":9},"message":"GET /auth/saml/login?nextUrl=%2F&redirectHash=false 302 37ms - 9.0B"}
wazuh.dashboard-1  | {"type":"log","@timestamp":"2024-11-15T16:00:03Z","tags":["error","opensearch","data"],"pid":54,"message":"[ResponseError]: Response Error"}

```

As soon as I enter the credentials of the user with the appropriate rights to access the  wazuh dashboard via SSO, I encounter this error message
![4](https://github.com/user-attachments/assets/41d33957-3a75-473e-b986-92c55de5095e)

Thank you in advance, and if you need any additional information, please let me know. I've been struggling with this issue for three months now.
