### ISSUE TITLE
Modify default configuration for Wazuh Server

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#26904]
# Description

Currently, the minimal `wazuh-server.yml` configuration has the following default values when installing the Wazuh Server:
```yaml
server:
  nodes:
    - 'wazuh-master'
  node:
    name: manager_01
    type: "master"
    ssl:
      key: /etc/wazuh-server/server.key
      cert: /etc/wazuh-server/server.cert
      ca: /etc/wazuh-server/server.ca
indexer:
  host: wazuh-indexer
  port: 9200
  user: ""
  password: ""
```

Since the SSL configurations are required both for the `server` and `indexer` sections, we need to modify these and the `manager_01` mention:

```yaml
---
server:
  nodes:
    - master
  node:
    name: server_01
    type: master
    ssl:
      key: /etc/wazuh-server/server.key
      cert: /etc/wazuh-server/server.crt
      ca: /etc/wazuh-server/server.ca
indexer:
  host: localhost
  port: 9200
  user: admin
  password: admin
  ssl:
    use_ssl: true
    key: <PATH_TO_KEY_FILE>
    cert: <PATH_TO_CERT_FILE>
    ca: <PATH_TO_CA_FILE>

```
