### ISSUE TITLE
Minor BUG in SCA Rocky Linux 9: Command searches for /tmp but should use /var instead.

### ISSUE THREAD

**Issue by SirStephanikus** [wazuh/wazuh#26914]
Wazuh Version 4.9.1

Wazuh checks a wrong partition in its SCA for a Rocky Linux 9 system.

The check command searches for `/tmp`, but should use `/var` instead. **_The fix should be easily done!_**

```
# 1.1.3.3 Ensure nosuid option set on /var partition. (Automated)
    - id: 31508
      title: "Ensure nosuid option set on /var partition."
      description: "The nosuid mount option specifies that the filesystem cannot contain setuid files."
      rationale: "Since the /var filesystem is only intended for variable files such as logs, set this option to ensure that users cannot create setuid files in /var."
      remediation: "Edit the /etc/fstab file and add nosuid to the fourth field (mounting options) for the /var partition. Example: <device> /var <fstype> defaults,rw,nosuid,nodev,noexec,relatime 0 0 Run the following command to remount /var with the configured options: # mount -o remount /var."
      rules:
        - "c:findmnt --kernel /tmp -> r:nosuid"
```
