### ISSUE TITLE
SCA rule Improvement | MacOS 15 SCA

### ISSUE THREAD

**Issue by Johnng007** [wazuh/wazuh#26982]
A [community](https://discord.com/channels/1049711339578331186/1308797116293976156) user reported a MacOS rule as incorrect, based on the fact that after remediation the rule kept failing.

<details>
<summary>SCA Check</summary>

```
  # 2.2.2 Ensure Firewall Stealth Mode Is Enabled. (Automated)
  - id: 35007
    title: "Ensure Firewall Stealth Mode Is Enabled."
    description: "While in Stealth mode, the computer will not respond to unsolicited probes, dropping that traffic."
    rationale: "Stealth mode on the firewall minimizes the threat of system discovery tools while connected to a network or the Internet."
    impact: "Traditional network discovery tools like ping will not succeed. Other network tools that measure activity and approved applications will work as expected. This control aligns with the primary macOS use case of a laptop that is often connected to untrusted networks where host segregation may be non-existent. In that use case, hiding from the other inmates is likely more than desirable. In use cases where use is only on trusted LANs with static IP addresses, stealth mode may not be desirable."
    remediation: "Graphical Method: Perform the following steps to enable firewall stealth mode: 1. Open System Settings 2. Select Network 3. Select Firewall 4. Select Options... 5. Set Enabled stealth mode to enabled Terminal Method: Run the following command to enable stealth mode: $ /usr/bin/sudo /usr/libexec/ApplicationFirewall/socketfilterfw -- setstealthmode on Stealth mode enabled Profile Method: Create or edit a configuration profile with the following information: 1. The PayloadType string is com.apple.security.firewall 2. The key to include is EnableStealthMode 3. The key must be set to <true/> Note: This key must be set in the same configuration profile with EnableFirewall set to <true/>. If it is set in its own configuration profile, it will fail."
    references:
      - "http://support.apple.com/en-us/HT201642"
    compliance:
      - cis: ["2.2.2"]
      - cis_csc_v8: ["4.1", "4.5", "4.8"]
      - cis_csc_v7: ["5.1", "9.4"]
      - cmmc_v2.0: ["AC.L1-3.1.1", "AC.L1-3.1.2", "AC.L1-3.1.20", "CM.L2-3.4.1", "CM.L2-3.4.2", "CM.L2-3.4.6", "CM.L2-3.4.7", "CM.L2-3.4.8", "SC.L1-3.13.1", "SC.L2-3.13.6"]
      - iso_27001-2013: ["A.13.1.1", "A.14.2.5", "A.8.1.3"]
      - nist_sp_800-53: ["CM-7(1)", "CM-9", "SA-10", "SC-7(5)"]
      - pci_dss_v3.2.1: ["1.1.4", "1.1.6", "1.2.1", "1.4", "11.5", "2.2", "2.2.2", "2.2.5"]
      - pci_dss_v4.0: ["1.1.1", "1.2.1", "1.2.5", "1.2.6", "1.2.7", "1.5.1", "2.1.1", "2.2.1", "2.2.4", "6.4.1"]
      - soc_2: ["CC6.3", "CC6.6", "CC7.1", "CC8.1"]
    condition: any
    rules:
      - "c:defaults read /Library/Preferences/com.apple.alf stealthenabled -> r:^1$|^2$"
      - "c:defaults read /Library/Preferences/com.apple.security.firewall EnableStealthMode -> r:^1$|^2$|^true$"
```

</details>

**Observation**
I observed that the rule is correct, however, it is very narrow in scope as it only covers when the remediation is done manually by creating a configuration profile and setting the needed key values.

**Fix**
To cover for when firewall configuration stealthmode is enabled via both the GUI, Terminal, and configuration profile the below rule suffices.

`/usr/libexec/ApplicationFirewall/socketfilterfw --getstealthmode | grep -q "enabled"` should return `Stealth Mode is enabled`

The corrected SCA check below should be used instead.

<details>
<summary>Fixed SCA Check</summary>

```
  # 2.2.2 Ensure Firewall Stealth Mode Is Enabled. (Automated)
  - id: 35007
    title: "Ensure Firewall Stealth Mode Is Enabled."
    description: "While in Stealth mode, the computer will not respond to unsolicited probes, dropping that traffic."
    rationale: "Stealth mode on the firewall minimizes the threat of system discovery tools while connected to a network or the Internet."
    impact: "Traditional network discovery tools like ping will not succeed. Other network tools that measure activity and approved applications will work as expected. This control aligns with the primary macOS use case of a laptop that is often connected to untrusted networks where host segregation may be non-existent. In that use case, hiding from the other inmates is likely more than desirable. In use cases where use is only on trusted LANs with static IP addresses, stealth mode may not be desirable."
    remediation: "Graphical Method: Perform the following steps to enable firewall stealth mode: 1. Open System Settings 2. Select Network 3. Select Firewall 4. Select Options... 5. Set Enabled stealth mode to enabled Terminal Method: Run the following command to enable stealth mode: $ /usr/bin/sudo /usr/libexec/ApplicationFirewall/socketfilterfw -- setstealthmode on Stealth mode enabled Profile Method: Create or edit a configuration profile with the following information: 1. The PayloadType string is com.apple.security.firewall 2. The key to include is EnableStealthMode 3. The key must be set to <true/> Note: This key must be set in the same configuration profile with EnableFirewall set to <true/>. If it is set in its own configuration profile, it will fail."
    references:
      - "http://support.apple.com/en-us/HT201642"
    compliance:
      - cis: ["2.2.2"]
      - cis_csc_v8: ["4.1", "4.5", "4.8"]
      - cis_csc_v7: ["5.1", "9.4"]
      - cmmc_v2.0: ["AC.L1-3.1.1", "AC.L1-3.1.2", "AC.L1-3.1.20", "CM.L2-3.4.1", "CM.L2-3.4.2", "CM.L2-3.4.6", "CM.L2-3.4.7", "CM.L2-3.4.8", "SC.L1-3.13.1", "SC.L2-3.13.6"]
      - iso_27001-2013: ["A.13.1.1", "A.14.2.5", "A.8.1.3"]
      - nist_sp_800-53: ["CM-7(1)", "CM-9", "SA-10", "SC-7(5)"]
      - pci_dss_v3.2.1: ["1.1.4", "1.1.6", "1.2.1", "1.4", "11.5", "2.2", "2.2.2", "2.2.5"]
      - pci_dss_v4.0: ["1.1.1", "1.2.1", "1.2.5", "1.2.6", "1.2.7", "1.5.1", "2.1.1", "2.2.1", "2.2.4", "6.4.1"]
      - soc_2: ["CC6.3", "CC6.6", "CC7.1", "CC8.1"]
    condition: all
    rules:
      - "c:/usr/libexec/ApplicationFirewall/socketfilterfw --getstealthmode -> r:(?i)Stealth\s+Mode\s+is\s+enabled"
```

</details>

**Comment by cyntony0** [comment]
SCA ID 35004, 35006, 35024, 35025, 35028, 35032, 35058, 35060 are also similarly affected by narrow rules check causing false fails.

**Comment by IsExec** [comment]
# Issue update

- Waiting for the provisioned environment to test the identified checks.

**Comment by IsExec** [comment]
## Issue Update - 02/12/2024

<details>
<summary>Check ID 35007</summary>

```yaml
  # 2.2.2 Ensure Firewall Stealth Mode Is Enabled. (Automated)
  - id: 35007
    title: "Ensure Firewall Stealth Mode Is Enabled."
    
    condition: any
    rules:
      - "c:/usr/libexec/ApplicationFirewall/socketfilterfw --getstealthmode -> r:^Firewall\s*\t*stealth\s*\t*mode\s*\t*is\s*\t*on"
      - "c:defaults read /Library/Preferences/com.apple.alf stealthenabled -> r:^1$|^2$"
      - "c:defaults read /Library/Preferences/com.apple.security.firewall EnableStealthMode -> r:^1$|^2$|^true$"
```

</details>

**Comment by Johnng007** [comment]
## Issue Update - 05/12/2024

<details>
<summary>Check ID 35025</summary>

```
  # 2.6.8 Ensure an Administrator Password Is Required to Access System-Wide Preferences. (Automated)
  - id: 35025
    title: "Ensure an Administrator Password Is Required to Access System-Wide Preferences."
    
    condition: all
    rules:
      - "c:security authorizationdb read system.preferences | grep -A1 shared -> r:<false"
```

</details>
