### ISSUE TITLE
SCA rule Improvement | Debian 11 SCA

### ISSUE THREAD

**Issue by Johnng007** [wazuh/wazuh#27067]
A [community](https://www.reddit.com/r/Wazuh/comments/1grz2nw/wazuh_sca_regex_issue_nonescaped_characters_in/) user reported a Debian 11 SCA rule as incorrect based on the fact that after remediation, the rule kept failing.

<details>
<summary>SCA Check </summary>

```
  # 1.7.5 Ensure permissions on /etc/issue are configured (Automated)
  - id: 29542
    title: "Ensure permissions on /etc/issue are configured."
    description: "The contents of the /etc/issue file are displayed to users prior to login for local terminals."
    rationale: "If the /etc/issue file does not have the correct ownership it could be modified by unauthorized users with incorrect or misleading information."
    remediation: "Run the following commands to set permissions on /etc/issue : # chown root:root $(readlink -e /etc/issue) # chmod u-x,go-wx $(readlink -e /etc/issue)."
    compliance:
      - cis: ["1.7.5"]
      - cis_csc_v8: ["3.3"]
      - cis_csc_v7: ["14.6"]
      - cmmc_v2.0: ["AC.L1-3.1.1", "AC.L1-3.1.2", "AC.L2-3.1.5", "AC.L2-3.1.3", "MP.L2-3.8.2"]
      - hipaa: ["164.308(a)(3)(i)", "164.308(a)(3)(ii)(A)", "164.312(a)(1)"]
      - pci_dss_3.2.1: ["7.1", "7.1.1", "7.1.2", "7.1.3"]
      - pci_dss_4.0: ["1.3.1", "7.1"]
      - nist_sp_800-53: ["AC-5", "AC-6"]
      - soc_2: ["CC5.2", "CC6.1"]
      - iso_27001-2013: ["A.9.1.1"]
      - mitre_techniques: ["T1222", "T1222.002"]
      - mitre_tactics: ["TA0005"]
      - mitre_mitigations: ["M1022"]
    condition: all
    rules:
      - 'c:stat -L /etc/issue -> r:Access:\s*\(0644/-rw-r--r--\)\s*Uid:\s*\(\s*\t*0/\s*\t*root\)\s*\t*Gid:\s*\(\s*\t*0/\s*\t*root\)'
```
</details>

Observation
I observed that the rule logic is correct, and works as expected.

![WhatsApp Image 2024-11-27 at 02 15 24_a456611a](https://github.com/user-attachments/assets/14012f4c-a058-44bf-8ed6-88ca529eff54)

```
root@TestDeb:/home/stockholm/wazuh# stat -L /etc/issue
  File: /etc/issue
  Size: 27              Blocks: 8          IO Block: 4096   regular file
Device: 801h/2049d      Inode: 1703959     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-11-26 23:53:30.426767900 +0000
Modify: 2024-08-14 16:05:00.000000000 +0000
Change: 2024-11-11 04:23:34.913471856 +0000
 Birth: 2024-11-11 04:23:34.913471856 +0000
```
