### ISSUE TITLE
Wazuh server configuration refinement

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#27158]
# Description

Following up on the initial configuration carried out in https://github.com/wazuh/wazuh/issues/26356, we need to refine the several configuration options currently available in the `wazuh-server.yml` file and their use throughout the Wazuh Server lifecycle. 

The configuration is required in the following stages:
- **Deployment**. Every Wazuh server manager instance must contain the following default values:
  <details><summary>wazuh-server.yml</summary>

  ```yaml
    node: 
        name: "wazuh-server-1"
        type: manager
        host: https://localhost:1516/ 
        ssl: 
            certificate:
            key:
            certificate_authorities: []
    management_api:
        host: https://localhost:55000/
        ssl: 
            certificate:
            key:
            certificate_authorities: []
    communications_api:
        host: https://localhost:27000/ 
        ssl: 
            certificate:
            key:
            certificate_authorities: []
    indexer_connector:
        hosts: [https://localhost:9200/]
        ssl: 
            certificate:
            key:
            certificate_authorities: []
    cluster:
        name: cluster-1
  ```

  </details>

  The complete set of options to be configured would be:
  <details><summary>wazuh-server.yml</summary>
  
  ```yaml
  node: 
      name: ""
      type: manager | worker
      host: https://localhost:1516/ 
      logging: info | warning | error | debug | trace
      ssl: 
          enabled:
          certificate:
          key:
          certificate_authorities: []
          verification_mode: full | strict | certificate | none # JUST CLIENT
          cipher_suites:
          supported_protocols:
      keep_alive: 60
      connection_retry: 10
      failed_keepalive_retries: 2
      process_pool_size: 2
  management_api:
      host: https://localhost:55000/
      ssl: 
          enabled:
          certificate:
          key:
          certificate_authorities: []
          cipher_suites:
          supported_protocols:
  communications_api:
      host: https://localhost:27000/
      ssl: 
          enabled: true | false
          certificate:
          key:
          certificate_authorities: []
          cipher_suites:
          supported_protocols:
  indexer_connector:
      hosts: [https://localhost:9200/]
      ssl: 
          enabled:
          certificate:
          key:
          certificate_authorities: []
          verification_mode: full | strict | certificate | none # JUST CLIENT
          cipher_suites:
          supported_protocols:
  ```
  
  </details>

  It is important to notice the following:
    - The Wazuh Server logging will be unified.
    - The SSL configurations will be separate having by default the most secure protocol available but not removing support for other alternatives that may be required by the users.

- **Initialization**
- **Parameter change during operation**: related to point 5 of https://github.com/wazuh/wazuh/issues/25193

**WIP**
