### ISSUE TITLE
Add Comms and Management API sections by default in the configuration

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#27170]
# Description

Currently, we are delivering the following content by default in the `wazuh-server.yml` file:
```yaml
server:
  nodes:
    - master
  node:
    name: server_01
    type: master
    ssl:
      key: /etc/wazuh-server/server.key
      cert: /etc/wazuh-server/server.crt
      ca: /etc/wazuh-server/server.ca
indexer:
  hosts:
    - host: localhost
      port: 9200
  username: admin
  password: admin
  ssl:
    use_ssl: true
    key: <PATH_TO_KEY_FILE>
    certificate: <PATH_TO_CERT_FILE>
    certificate_authorities:
      - <PATH_TO_CA_FILE>
```

We need the `management_api` and `communications_api` sections to come by default since these are part of the deployment of the server.
