### ISSUE TITLE
Fix Doxygen coverage for shared_modules/utils

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#27590]
# Description 

As part of this issue https://github.com/wazuh/wazuh/issues/27503 where we included the `shared_modules/utils` code in the vulnerability scanner test workflow, several errors arise in the Doxygen action due to lack of documentation for different helpers and its tests. 

[doxygen_errors.txt](https://github.com/user-attachments/files/18399202/doxygen_errors.txt)

To enable Doxygen check we added. 

```yml
      - name: Utils - Doxygen
        if: env.UTILS
        uses: ./.github/actions/doxygen
        with:
          path: src/shared_modules/utils
          id: utils
```

## DoD 

- [ ] Evaluate if we can ignore some of those warnings
- [ ] Add required documentation 
- [ ] Add step in vulnerability scanner workflow
- [ ] Test must pass
