### ISSUE TITLE
Add default values for certificates in the Wazuh Server configuration

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#27778]
## Description

Currently, the `/etc/wazuh-server/wazuh-server.yml` configuration file contains the following default values:
<details><summary>wazuh-server.yml</summary>

```yaml
server:
  nodes:
    - master
  node:
    name: server_01
    type: master
    ssl:
      key: /etc/wazuh-server/certs/server.key
      cert: /etc/wazuh-server/certs/server.crt
      ca: /etc/wazuh-server/certs/server.ca
  jwt:
      private_key: /etc/wazuh-server/certs/private-key.pem
      public_key: /etc/wazuh-server/certs/public-key.pem
indexer:
  hosts:
    - host: localhost
      port: 9200
  username: admin
  password: admin
  ssl:
    use_ssl: true
    key: <KEY_FILE_PATH>
    certificate: <CERT_FILE_PATH>
    certificate_authorities:
      - <CA_FILE_PATH>
communications_api:
  host: localhost
  port: 27000
  ssl:
    key: /etc/wazuh-server/certs/api.key
    cert: /etc/wazuh-server/certs/api.crt
    use_ca: false
    ca: <CA_FILE_PATH>
management_api:
  host:
    - localhost
    - ::1
  port: 55000
  ssl:
    key: /etc/wazuh-server/certs/api.key
    cert: /etc/wazuh-server/certs/api.crt
    use_ca: false
    ca: <CA_FILE_PATH>
```

</details>

This issue aims to remove placeholders and set default values in the configuration for the CA, CERT, and key files, similar to what the indexer has currently for its [certificates](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html#deploying-certificates). The values should be something like `/etc/wazuh-server/certs/server-key.pem`,  `/etc/wazuh-server/certs/server.pem` and  `/etc/wazuh-server/certs/root-ca.pem` to have a unified nomenclature.

## Tasks

- [x] Perform the necessary changes to the `wazuh-server.yml` configuration file default values.
- [x] Document the necessary steps to generate the certificates and key files.
- [x] Perform manual tests of the package's installation.
