### ISSUE TITLE
Unify Server certificates for default deployment

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#27905]
## Description

As part of a new iteration related to the enhancement of the user experience when deploying the Wazuh Server, we need to change the current `wazuh-server.yml` configuration file to make use of a single set of certificates for the `server`, `indexer` and APIs configuration section. Until #27776 is completed, the default configuration should be:

<details><summary>wazuh-server.yml</summary>

```
server:
  nodes:
    - master
  node:
    name: server_01
    type: master
    ssl:
      key: /etc/wazuh-server/certs/server-key.pem
      cert: /etc/wazuh-server/certs/server.pem
      ca: /etc/wazuh-server/certs/root-ca.pem
  jwt:
      private_key: /etc/wazuh-server/certs/private-key.pem
      public_key: /etc/wazuh-server/certs/public-key.pem
indexer:
  hosts:
    - host: localhost
      port: 9200
  username: admin
  password: admin
  ssl:
    use_ssl: true
    key: /etc/wazuh-server/certs/server-key.pem
    certificate: /etc/wazuh-server/certs/server.pem
    certificate_authorities:
      - /etc/wazuh-server/certs/root-ca.pem
communications_api:
  host: localhost
  port: 27000
  ssl:
    key: /etc/wazuh-server/certs/server-key.pem
    cert: /etc/wazuh-server/certs/server.pem
    use_ca: false
    ca: /etc/wazuh-server/certs/root-ca.pem
management_api:
  host:
    - localhost
    - ::1
  port: 55000
  ssl:
    key: /etc/wazuh-server/certs/server-key.pem
    cert: /etc/wazuh-server/certs/server.pem
    use_ca: false
    ca: /etc/wazuh-server/certs/root-ca.pem
```

</details>

This requires for the user to execute as few commands as possible when generating the keys and certificate files. In case it is required to use different certificates, the user will have the configuration option available to modify them.

## Tasks

- [ ] Modify the default configuration.
- [ ] Manual tests and required steps to deploy the Wazuh Server.
