### ISSUE TITLE
Add a new trigger in package generation workflow for each PR

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#27948]
## Description

After the merge of this issue
- https://github.com/wazuh/wazuh/issues/27154

It was found that the package generation was broken. This process isn't run for each PR, so any  issue is found after the merge.

We need to add another trigger condition in the workflow to catch any potential bug early
https://github.com/wazuh/wazuh/blob/master/.github/workflows/packages-build-manager.yml

## DoD

- [x] Add the new trigger
- [x] Confirm the behavior with manual tests

**Comment by GabrielEValenzuela** [comment]
# Update

- I made a change to the current workflow, but the actions only executed that workflow and no others, so I decided to create a new one similar but without the 

```yaml
- name: Cancel previous runs
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_after_successful_duplicate: 'false'
```

If this step prevents me from executing all other actions, I will still get the same result. I'll ask the team tomorrow about it.
