### ISSUE TITLE
Vulnerabilities template wrong type for package size

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#27979]
## Description
While investigating:
- https://github.com/wazuh/wazuh/issues/27745

It was found that there is an issue with the type used to express the package size for vulnerability events:
https://github.com/wazuh/wazuh/blob/29263a6aaa8c5482db2a39bcf98e91bdf75ea859/src/wazuh_modules/vulnerability_scanner/indexer/template/index-template.json#L141

The type used is **long (int 64)**, when in reality it should be an **unsigned long (unit 64)**

## DoD
- [x] Template updated

**Comment by QU3B1M** [comment]
The field `package.size` comes from the default ECS fields, we need to override it in order to modify its type, something like this should to the trick:
```yaml
- name: package
  title: Package
  group: 2
  short: Fields to describe the package relevant to an event.
  description: >
    The package fields describe information about a package that is
    relevant to an event.
  type: group
  fields:
    - name: size
      type: uint
      level: custom
      description: >
        Size of the package.

```
