### ISSUE TITLE
Fix RTR Winagent test after upward merge

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#28032]
## Description

After the upward merge at:
- https://github.com/wazuh/wazuh/issues/28014

There is a failing test:
- https://github.com/wazuh/wazuh/actions/runs/13140971139/job/36667839446?pr=28024

It's required to analyze it and fix it.

## DoD

- [x] Identify the cause
- [x] Fix the failing test

**Comment by cborla** [comment]
On the second attempt the test passed without problems:
- https://github.com/wazuh/wazuh/actions/runs/13140971139?pr=28024
Appears to be a flaky test.

**Comment by cborla** [comment]
This Flaky test fails in install dependencies step, when cmocka is about to be decompressed.

![Image](https://github.com/user-attachments/assets/55595c59-5152-439a-902b-7b09261bd7be)

The [workflow](https://github.com/wazuh/wazuh/actions/runs/13140971139/workflow?pr=28024) in charge of install dependencies is

`name: Running RTR. Module syscollector and its dependencies for agent/winagent targets`

In section

``` yml
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: "Install dependencies"
        uses: ./.github/actions/install_build_deps
        with:
          target: ${{ matrix.target }}
```

The action [install_build_deps](https://github.com/wazuh/wazuh/blob/f877982656ec8d2e72524894f556e5341dfc30be/.github/actions/install_build_deps/action.yml
)
.github/actions/install_build_deps/action.yml

`name: "Install Wazuh build dependencies"`

in section:

``` yml
        if [[ "${{ inputs.target }}" == "winagent" ]]; then
          echo "Installing CMocka by sources with 'winagent' required flags"
          cd /tmp
          curl -L https://git.cryptomilk.org/projects/cmocka.git/snapshot/stable-1.1.tar.gz | \
          tar zvx -C /tmp/ && \
          sed -i "s|ON|OFF|g" /tmp/stable-1.1/DefineOptions.cmake && \
          mkdir /tmp/stable-1.1/build && \
          cd /tmp/stable-1.1/build && \
          cmake -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc -DCMAKE_C_LINK_EXECUTABLE=i686-w64-mingw32-ld -DCMAKE_INSTALL_PREFIX=/usr/i686-w64-mingw32/ -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_BUILD_TYPE=Release .. && \
          make && \
          sudo make install && \
          cd $GITHUB_WORKSPACE
```

Decompression error occurs 
Possible causes: 
- Download error
- Corrupted file.
