### ISSUE TITLE
Cluster removal - Server configuration enhancement

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#28415]
## Description

Currently, in version 5.0, after the developments made in https://github.com/wazuh/wazuh/issues/27776, the SSL key generates the JWT private key if it is not specified.  Given that the `ssl` section of the APIs configuration will be initially mandatory and the use of a certificate creation tool a required step for the deployment, this issue aims to propose and implement the default configuration of a server instance. The objective is also to update the JWT key mechanism to ensure that the JWT generated by each API is done with the `api.ssl.key`.

## Functional requirements

- By default, the APIs SSL private keys will be used to generate the JWT signing keys.

## Implementation restrictions

- The Server certificate private keys must be generated with the RSA algorithm using a 2048-bit key size (RSA-2048).
- The Server APIs SSL configurations will be mandatory for every Server instance since the use of the certificate creation tool will be part of the required steps in the deployment of the Wazuh components.

## Minimal configuration proposal

> [!NOTE]
> The issue takes into consideration the required removal of cluster configuration of #27434 and the default use of IPv4 https://github.com/wazuh/wazuh/issues/28798.

```yaml
communications_api:
  host: 
    - "0.0.0.0"
  port: 27000
  ssl:
    use_ssl: true
    key: /etc/wazuh-server/certs/server-1-key.pem
    certificate: /etc/wazuh-server/certs/server-1.pem
    certificate_authorities:
      - /etc/wazuh-server/certs/root-ca.pem
management_api:
  host:
    - "0.0.0.0"
  port: 55000
  ssl:
    use_ssl: true
    key: /etc/wazuh-server/certs/server-1-key.pem
    certificate: /etc/wazuh-server/certs/server-1.pem
    certificate_authorities:
      - /etc/wazuh-server/certs/root-ca.pem
indexer:
  hosts: ["https://127.0.0.1:9200"]
  username: admin
  password: admin
  ssl:
    use_ssl: true
    key: /etc/wazuh-server/certs/server-1-key.pem
    certificate: /etc/wazuh-server/certs/server-1.pem
    certificate_authorities:
      - /etc/wazuh-server/certs/root-ca.pem
```

**Comment by RamosFe** [comment]
## Update

Passed to `on-hold` due to issues with higher priority related to `4.x`.

**Comment by GGP1** [comment]
## Server deployment simplification proposal

The current [certificates deployment](https://documentation.wazuh.com/current/user-manual/wazuh-server-cluster/certificates-deployment.html) consists of generating a ser of key/certificate pairs for each node.

The typical set of certificates the user ends up with is the following:

```
wazuh-certificates/
├── admin-key.pem
├── admin.pem
├── root-ca.key
├── root-ca.pem
├── server-key.pem
└── server.pem
```

This is in addition to the API certificates, which are generated by the server on startup if the don't exist.

These certificates are all self-signed, if the user were to have certificates signed by a third party CA, it wouldn't have to generate them, just share and use them in each node. So, the default configuration (and probably the most used one) is with self-signed certificates.

Taking this into consideration, and if we want to continue with this approach, I think we could greatly simplify the deployment process by instructing the user to generate **a single key**, which would be used to:

- Sign JWT tokens
- Create APIs certificates

Having the same key on all servers, which must be the same on all nodes anyway to handle requests from any node, we can generate the certificates for the APIs connections. This will leave us with the following default configuration.

```yaml
server:
  private_key: /etc/wazuh-server/private-key.pem
indexer:
  hosts:
    - host: 127.0.0.1
      port: 9200
  username: admin
  password: admin
  ssl:
    use_ssl: true
    key: /etc/wazuh-server/certs/node-1-key.pem
    certificate: /etc/wazuh-server/certs/node-1.pem
    certificate_authorities:
      - /etc/wazuh-server/certs/root-ca.pem
communications_api:
  host: 0.0.0.0
  port: 27000
management_api:
  host: 0.0.0.0
  port: 55000
```

Because all SSL keys and certificates will be handled internally by the server, the user won't be required to generate any of them, just the `server.private_key`.

This being said, it is important to clarify that the configuration options will still be available and the user can at any time choose to use custom certificates signed by a certificate authority and specify them in the APIs configuration to avoid use self-signed ones.

> [!Note]
> The indexer SSL configuration is still required because the key used to generate the certificate should (ideally) be different than the one in the server.
