### ISSUE TITLE
MVP catch up - Server template

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#28647]
# Description

We want to have templates for all Wazuh central components that follow common criteria when defining the default certificates paths and names.

Also, we want the different network connections to listen and connect to assuming we are deploying a single host environment. This is meant to expedite central components deployments for single host environment scenarios.

# Tasks 

## Wazuh server template before the cluster removal

```
server:
  nodes:
    - master
  node:
    name: server-1
    type: master
    ssl:
      key: /etc/wazuh-server/certs/server-1-key.pem
      cert: /etc/wazuh-server/certs/server-1.pem
      ca: /etc/wazuh-server/certs/root-ca.pem
indexer:
  hosts:
    - host: 127.0.0.1
      port: 9200
  username: admin
  password: admin
  ssl:
    use_ssl: true
    key: /etc/wazuh-server/certs/server-1-key.pem
    certificate: /etc/wazuh-server/certs/server-1.pem
    certificate_authorities:
      - /etc/wazuh-server/certs/root-ca.pem
communications_api:
  host: 0.0.0.0
  port: 27000
  ssl:
    key: /etc/wazuh-server/certs/server-1-key.pem
    cert: /etc/wazuh-server/certs/server-1.pem
    use_ca: false
    ca: /etc/wazuh-server/certs/root-ca.pem
management_api:
  host:
    - "0.0.0.0"
    - "::"
  port: 55000
  ssl:
    key: /etc/wazuh-server/certs/server-1-key.pem
    cert: /etc/wazuh-server/certs/server-1.pem
    use_ca: false
    ca: /etc/wazuh-server/certs/root-ca.pem
```

## Wazuh server template after the cluster removal

```
communications_api:
  host: 0.0.0.0
  port: 27000
  ssl:
    use_ssl: true
    key: /etc/wazuh-server/certs/server-1-key.pem
    certificate: /etc/wazuh-server/certs/server-1.pem
    certificate_authorities:
      - /etc/wazuh-server/certs/root-ca.pem
management_api:
  host:
    - "0.0.0.0"
    - "::"
  port: 55000
  ssl:
    use_ssl: true
    key: /etc/wazuh-server/certs/server-1-key.pem
    certificate: /etc/wazuh-server/certs/server-1.pem
    certificate_authorities:
      - /etc/wazuh-server/certs/root-ca.pem
indexer:
  hosts:
    - host: 127.0.0.1
      port: 9200
  username: admin
  password: admin
  ssl:
    use_ssl: true
    key: /etc/wazuh-server/certs/server-1-key.pem
    certificate: /etc/wazuh-server/certs/server-1.pem
    certificate_authorities:
      - /etc/wazuh-server/certs/root-ca.pem
```
