### ISSUE TITLE
Invalid rule format - CIS policy

### ISSUE THREAD

**Issue by bartoszmp** [wazuh/wazuh#28979]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.11.2 | CIS/SCA | Manager | Packages/Sources | Debian 6.1.129-1 |

Issue link to google forum: https://groups.google.com/u/1/g/wazuh/c/lGepYb0BrdU
Problem with CIS windows policy, part of log:
{"timestamp":"2025/04/04 01:08:18","tag":"sca","level":"warning","description":"Invalid check 27004: Invalid rule format."}
{"timestamp":"2025/04/04 01:08:18","tag":"sca","level":"warning","description":"Error found while validating policy file: '/var/ossec/ruleset/sca/cis_win2022.yml'. Skipping it."}

The policies for Windows Server 2022, Windows Server 2019, and Windows 11 Enterprise are failing. When I comment out the rule 27004 in the .yml file, it throws an error for 27008: Invalid rule format. When I comment out the rule 27004 in the .yml file, it throws an error for 27008: Invalid rule format.

**Comment by Sabba5** [comment]
I got the same problem, any fixes? 

Don't see any issues with permissions or syntax.

**Comment by fredycibersec** [comment]
## Additional diagnostic data — confirmed on 4.14.4-rc2 and third-party Windows SCA policies

We hit the same issue while maintaining the [ENS-Wazuh-integration](https://github.com/fredycibersec/ENS-Wazuh-integration) project (SCA policies for the Spanish National Security Framework). Sharing our full diagnostic findings to help the team identify the root cause.

---

### Environment

| Wazuh version | Component | Install type | Platform |
|---|---|---|---|
| 4.14.4-rc2 | SCA / wazuh-modulesd | Manager | Ubuntu (Linux) |

- Manager: Linux host
- Windows agents enrolled: ~199 agents in `ens-windows` group

---

### Symptoms

All Windows SCA policies — including Wazuh's **own built-in** `cis_win2022.yml` — fail with:

```
sca: WARNING: Invalid check <N>: Invalid rule format.
sca: WARNING: Error found while validating policy file: '...'. Skipping it.
```

The error always points to the **first check** in the file, cascades to the next if that check is commented out, and occurs regardless of check content — even checks with no regex at all (pure literal registry matches) fail.

---

### Minimal reproduction

Create `/var/ossec/ruleset/sca/test_win.yml`:

```yaml
policy:
  id: "test_win"
  file: "test_win.yml"
  name: "Test Windows"
  description: "Minimal Windows registry test"

requirements:
  title: "Windows"
  description: "Requires Windows"
  condition: all
  rules:
    - 'r:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion -> ProductName -> r:Windows'

checks:
  - id: 99001
    title: "Test registry check"
    description: "Minimal test"
    rationale: "Debug"
    remediation: "N/A"
    condition: all
    rules:
      - 'r:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion -> ProductName -> r:Windows'
```

Restart the manager → error is reproduced:

```
sca: WARNING: Invalid check 99001: Invalid rule format.
sca: WARNING: Error found while validating policy file: '.../test_win.yml'. Skipping it.
```

This confirms the issue is **not specific to any regex pattern or policy structure** — any Windows registry rule (`r:HKLM\...`) in a check fails on a Linux manager.

---

### Root cause hypothesis

The SCA engine appears to have changed the validation order. The expected behaviour is:

1. Parse YAML → OK
2. Evaluate `requirements` → fails on Linux (HKLM check returns false) → **skip policy silently**

The observed behaviour in affected versions is:

1. Parse YAML → OK
2. **Validate all check rule formats across the entire file** → rejects `r:HKLM\...` on Linux → error + skip

The `requirements` block is designed precisely to prevent Windows-only policies from being evaluated on Linux managers. Validating check rule formats before evaluating `requirements` makes the gate useless and breaks all cross-platform policies.

This is also confirmed by Wazuh's own built-in CIS Windows policies failing on Linux managers in the same way, as reported by the original author and reproduced in our environment.

---

### Workaround (until fixed)

Deploy Windows SCA policies **only to Windows agent groups** via the agent's `ossec.conf`, bypassing the manager's own SCA scan:

```xml
<wodle name="sca">
  <enabled>yes</enabled>
  <policies>
    <policy>/var/ossec/ruleset/sca/ens_windows.yml</policy>
  </policies>
</wodle>
```

---

### Request

Please restore the original validation order: **evaluate `requirements` before validating check rule formats**. This is both the documented behaviour and the only design that makes cross-platform policies viable.

Happy to provide additional logs or test cases if useful. Thanks for the great work on Wazuh.
