### ISSUE TITLE
Failing test `4_testcomponent_vulnerability-scanner` due to missing `bc` dependency

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#29112]
### Description
The test `4_testcomponent_vulnerability-scanner` is currently failing due to a missing dependency: `bc` (basic calculator utility).

You can see the failing workflow run here:  
[Workflow run](https://github.com/wazuh/wazuh/actions/runs/14328994757/job/40167998861)

The test requires the `bc` utility to be installed, but it is not currently included in the GitHub Actions dependencies for the vulnerability scanner workflow.

### Proposed fix  
We need to add `bc` to the dependencies list in the following file:  
`.github/actions/vulnerability_scanner_deps/action.yml`

```yaml
- name: General dependencies
  shell: bash
  run: |
    sudo apt-get update -y
    sudo apt-get install -y libc6-dbg bc
```
