### ISSUE TITLE
Duplicated sca check IDs Windows Server 2025

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#29174]
### Description
It has been detected in https://github.com/wazuh/wazuh/issues/29043  unexpected duplicate ID warnings in Windows Server 2025 after the upgrade: 
```
2025/04/10 16:18:54 sca: WARNING: Found duplicated check ID: 27000. First appearance at policy 'cis_win2022'
2025/04/10 16:18:54 sca: WARNING: Error found while validating policy file: 'C:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2025.yml'. Skipping it.
```

Both `cis_win2025` and `cis_win2022` are indeed present in the sca ruleset:

![Image](https://github.com/user-attachments/assets/afeb2fee-c37e-4a8d-928e-31921eed7f62)

With the duplicated check

<details>

<summary> cis_win2022</summary>

```
policy:
  id: "cis_win2022"
  file: "cis_win2022.yml"
  name: "CIS Microsoft Windows Server 2022 Benchmark v2.0.0"
  description: "This document provides prescriptive guidance for establishing a secure configuration posture for Microsoft Windows Server 2022. Please note that the rules provide accurate results for Microsoft Windows Server 2022 Operating Systems with the System language set to English. The SCA policy will work with other languages but the results will be less accurate due to some of the rules that depend on the System language."
  references:
    - https://www.cisecurity.org/cis-benchmarks/

requirements:
  title: "Check that the Windows platform is Windows Server 2022"
  description: "Requirements for running the CIS benchmark under Windows Server 2022"
  condition: all
  rules:
    - 'r:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion -> ProductName -> r:^Windows Server 2022'

checks:
  # 1.1.1 (L1) Ensure 'Enforce password history' is set to '24 or more password(s)' (Automated)
  - id: 27000
```

</details>

<details>

<summary> cis_win2025</summary>

```

policy:
  id: "cis_win2025"
  file: "cis_win2025.yml"
  name: "CIS Microsoft Windows Server 2025 Benchmark"
  description: "This document provides prescriptive guidance for establishing a secure configuration posture for Microsoft Windows Server 2025. Please note that the rules provide accurate results for Microsoft Windows Server 2025 Operating Systems with the System language set to English. The SCA policy will work with other languages but the results will be less accurate due to some of the rules that depend on the System language. This document is based on Center for Internet Security Benchmark for Microsoft Windows Server 2022 v2.0.0."
  references:
    - https://www.cisecurity.org/cis-benchmarks/

requirements:
  title: "Check that the Windows platform is Windows Server 2025"
  description: "Requirements for running the CIS benchmark under Windows Server 2025"
  condition: all
  rules:
    - 'r:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion -> ProductName -> r:^Windows Server 2025'

checks:
  # 1.1.1 (L1) Ensure 'Enforce password history' is set to '24 or more password(s)' (Automated)
  - id: 27000

```

</details>

### Steps to reproduce
- Deploy a Windows Server 2025 agent
- Check agent logs
