### ISSUE TITLE
[Spike] Expand `engine-test` to support any event type and YAML configuration

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#29243]
## Description
We need to explore changing `engine-test` so it can handle raw events of any type, not just logcollector data. This includes allowing a YAML-based configuration file rather than the current JSON structure. Below is an example of the proposed YAML format:

```yaml
- integration-name-file:
    agent: {}
    module: logcollector
    collector: file
    template:
      type: logcollector
      aditional.fields: 
        log.file.path: /tmp/log
    config:
      collect-mode: windows-eventchannel | single-line | dinamic-multi-line

- integration-name-windows:
    module: logcollector
    collector: windows-eventlog
    template:
      type: logcollector
      aditional.fields: 
        event.provider: channel
    config:
      collect-mode: windows-eventchannel

- integration-name-linux:
    module: inventory
    collector: package
    template:
      type: ndjson

- sca-checks:
    agent: {}
    module: sca
    collector: check
    template:
      type: ndjson

- sca-policies:
    agent: {}
    module: sca
    collector: policy
    template:
      type: ndjson


```

## Task
1. **Evaluate feasibility**: Determine how difficult it would be to support raw events and switch to a YAML-based configuration.
2. **Assess impact**: Understand how these changes might affect tools like `engine-health-test` and scripts that generate or consume the current configuration.
3. **Identify compatibility Issues**: Investigate any potential conflicts with existing workflows or legacy JSON configs.

## Expected Outcome
A clear understanding of the changes required in `engine-test` to accept arbitrary events and YAML-based configurations, along with a plan to address any compatibility or integration concerns with related tools.

**Comment by NahuFigueroa97** [comment]
## Update

- Study engine-test package
- Study differents events formats
- Study template bullder

**Comment by NahuFigueroa97** [comment]
## Update

The changes are viable, since the engine-test should be changed to handle YAML files instead of JSON files, and the data structures should be reorganized to obtain the header, subheader, and event only in cases of a logcollector-type tableplate, since it is already complete in cases of ndjson types. The way data is stored and handled should be changed. The health tests should then be updated with the new configuration files.

**Comment by JcabreraC** [comment]
ETA extended by priority in other issues: https://github.com/wazuh/wazuh/issues/29302

**Comment by NahuFigueroa97** [comment]
📌 **Context**

Currently, the `engine-test` package uses a `engine-test.conf` file in JSON format to define integrations to be tested. This approach has limitations in clarity and maintainability, especially when multiple inputs need to be defined within the same integration.

This spike aims to **migrate to using YAML files**, one per integration, with a clear and structured schema to define multiple test entries.

✅ **Spike Objective**

- Replace the use of `engine-test.conf` with a `engine-conf.yml` file per integration.
- Each `engine-conf.yml` can contain multiple definitions depending on the inputs to test.
- Update `engine-test` and its commands to support the new format.
- Improve `engine-health-test`, which is currently confusing.
- Migrate all integrations in `intelligence-data` to the new format.
- **Update integration documentation** to reflect the new flow.

📂 **New YAML Format**

Each integration will have its own `engine-conf.yml` file with entries defined like this:

```yaml
- file-log:
    agent: {}
    module: logcollector
    collector: file
    template:
      type: logcollector
      aditional.fields: 
        log.file.path: /tmp/log
    config:
      collect-mode: single-line

- win-channel:
    module: logcollector
    collector: windows-eventlog
    template:
      type: logcollector
      aditional.fields: 
        event.provider: channel
    config:
      collect-mode: windows-eventchannel

- package-check:
    module: inventory
    collector: package
    template:
      type: ndjson

- sca-checks:
    agent: {}
    module: sca
    collector: check
    template:
      type: ndjson

- sca-policies:
    agent: {}
    module: sca
    collector: policy
    template:
      type: ndjson
```

🔹 Each entry defines an input to test. The YAML file is placed at the root of each integration folder.

🔧 **Technical Tasks**

1. **`conf` module (parser and structure)**

   - Read a single `engine-conf.yml` per integration.
   - Interpret multiple entries within the YAML.
   - Use `template.type` to determine whether to run using `run` or `run-raw`.
   - Add extra fields to the event if `template.type: logcollector`.

2. **CLI Adaptation (`engine-test`)**

   - `engine-test run` will use the integration’s YAML file.
   - `engine-test create-config` and `engine-test add` must support YAML.
   - Ensure compatibility with multiple entries per execution.

3. **`engine-health-test`**

   - Improve how entries are read and validated from YAML.
   - Automatically determine whether to use `run` or `run-raw`.
   - Avoid misinterpretation errors based on the current schema.

4. **Migration of `intelligence-data` integrations**

   - Each folder in `intelligence-data/integrations/` will use an `engine-conf.yml`.
   - Convert existing JSON configurations to the new YAML format.
   - Validate functionality of each test after migration.

5. **Update documentation**

   - Modify the integrations section to describe:
     - Structure of the `engine-conf.yml` file.
     - Differences between `template.type: logcollector` and `ndjson`.
     - How to add new integrations and entries.
     - How to run tests with the new format.

🧪 **Validation**

- Run all current tests under the new YAML system.
- Ensure `engine-test run`, `run-raw`, and `engine-health-test` work as expected.
- Validate error handling for missing required fields or invalid values.
- Confirm behavior is equivalent or improved compared to the current system.

✅ **Expected Outcome**

- `engine-test` becomes more flexible and decoupled from JSON.
- Improved maintainability and clarity when defining test inputs.
- Clear and updated documentation.
- All integrations in `intelligence-data` updated, validated, and aligned with the new schema.
