### ISSUE TITLE
Engine - HLP/CSV/DSV field names are misinterpreted when mapping with dot (.) and slash (/)

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#29364]
## Description:

There is a bug in how field names are interpreted in the `parse_csv` function when mapping data. Specifically, the dot (`.`) is treated as a literal character rather than a sublevel indicator, while the slash (`/`) behaves as expected and creates sublevels.

## Steps to reproduce:

Using the following decoder:
```yml
name: decoder/test/0
metadata:
  description: Accept all

parents:
  - decoder/core-localfile/0

parse|event.original:
  - <message> # "\"value1\"|value2|value3|valueN

map:
  - outmap: parse_csv($message, ',akey/anotherkey, test)
  - outmap1: parse_csv($message, ',akey.anotherkey, test)
  - outmap2: parse_csv($message, \',akey/anotherkey, test)
  - outmap3: parse_csv($message, k1, K2, k3)
```

## Expected behavior:

The parser should interpret both `akey/anotherkey` and `akey.anotherkey` as nested fields, mapping the values correctly in the resulting JSON.
