### ISSUE TITLE
FIM on Windows incorrectly ignores files with German umlauts (e.g., ä, ö, ü) due to "non-UTF8" error despite PR #26289 in v4.12.x

### ISSUE THREAD

**Issue by etwas7B** [wazuh/wazuh#29885]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.12.0 | Wazuh Manager / Agent | Agent | Package | Windows Server 2016/2022 |

### Problem Description:
The Wazuh agent's File Integrity Monitoring (FIM) on Windows systems is incorrectly ignoring files and directories that contain German umlauts (e.g., ä, ö, ü, ß) and possibly other non-ASCII characters in their names. The agent log (ossec.log) shows a WARNING: (6955): Ignoring file ... due to unsupported name (non-UTF8). message for these files.

This issue persists even though PR #26289, which aimed to fix UTF-8 handling in FIM, has been merged and is understood to be included in the agent version mentioned above. As noted in recent comments on PR #26289, other users also appear to be experiencing this persistent problem.

### Steps to Reproduce:

1. Install Wazuh agent v4.12.x on a Windows Server system (e.g., Windows Server 2016 or 2022).
2. Configure FIM in agent.conf to monitor a directory. For example:
```
<syscheck>
  <directories check_all="yes" alert_new_files="yes" whodata="yes" recursive="yes" realtime="yes">E:\test_fim_umlauts</directories>
</syscheck>
```
3. Within the monitored directory (E:\test_fim_umlauts), create a file or directory with German umlauts in its name. Examples:
```
E:\test_fim_umlauts\Prüfungsunterlagen.docx
E:\test_fim_umlauts\Anleitungen für Geräte.pdf
E:\test_fim_umlauts\Geschäftsplan So Müsste Es Sein.xlsx
```
4. Observe the Wazuh agent log (ossec.log).

### Actual Behavior:
The Wazuh agent log shows a warning (error code 6955), and the file/directory is ignored by FIM. Example log entries previously observed:

`2025/05/23 13:15:50 wazuh-agent[10920] create_db.c:648 at fim_checker(): WARNING: (6955): Ignoring file 'e:\test_fim_umlauts\Prüfungsunterlagen.docx' due to unsupported name (non-UTF8).`

### Impact:
This bug significantly impairs FIM's effectiveness and completeness on Windows systems in environments where filenames legitimately contain umlauts or other non-ASCII characters common in German and many other languages. This can result in unmonitored file changes, potentially compromising security monitoring and compliance requirements.

Thank you for your attention to this matter.

**Comment by eandry77** [comment]
It seems that the issue is that Windows with NTFS uses UTF-16, not UTF-8 to encode filenames :

Source : http://xahlee.info/comp/unicode_utf16.html

**Comment by borges-br** [comment]
I’m experiencing the same issue on Wazuh Agent 4.12.0 running on Windows Server 2022, but with Portuguese UTF-8 characters in filenames (such as Ç, Ã, É, Í, À, etc).

Example logs:

2025/06/19 02:02:39 wazuh-agent: WARNING: (6955): Ignoring file 'd:\share\suporte\assinaturas\png\wagner.butinhão.png' due to unsupported name (non-UTF8).
2025/06/19 02:02:40 wazuh-agent: WARNING: (6955): Ignoring file 'd:\share\suporte\documentação' due to unsupported name (non-UTF8).

These are valid UTF-8 filenames used in a production environment. It seems the fix from PR #26289 didn't fully resolve the issue for extended Latin characters. This severely affects FIM coverage in Portuguese-speaking environments.

Would appreciate any updates or suggestions for a workaround.

**Comment by vikman90** [comment]
Dear @etwas7B @borges-br,

Thank you for your patience, and apologies for the delayed response.

We have successfully reproduced the issue on our side with filenames containing extended Latin characters, as shown in the example below:

![Image](https://github.com/user-attachments/assets/1fd1541f-6983-4cdb-9973-6fd24819385f)

```
2025/06/24 11:06:08 wazuh-agent: WARNING: (6955): Ignoring file 'd:\test\cole��o.txt' due to unsupported name (non-UTF8).
2025/06/24 11:06:08 wazuh-agent: WARNING: (6955): Ignoring file 'd:\test\v�ctor.txt' due to unsupported name (non-UTF8).
2025/06/24 11:06:08 wazuh-agent: WARNING: (6955): Ignoring file 'd:\test\�bergro�e datei.txt' due to unsupported name (non-UTF8).
```

## Root cause

As discussed in https://github.com/wazuh/wazuh/pull/26289#issuecomment-2949361065 by @zbalkan, the core of the issue lies in how filenames are handled internally in Windows. Specifically, the FIM logic receives `char*` strings without converting from the native `wchar_t*` used by the Windows API. As a result, filenames with valid UTF-16 characters (such as German umlauts, Portuguese accents, or Cyrillic) are misinterpreted as invalid UTF-8, triggering the `(6955)` warning.

The current implementation does not perform the necessary UTF-16 to UTF-8 conversion before validating the filename. This explains why the initial fix did not fully resolve the issue for all non-ASCII characters.

## Next steps

Unfortunately, we are not aware of any valid workaround at this time. We have added this issue to our internal backlog to propose a fix in an upcoming patch release.

We will keep this thread updated as progress is made.

Thanks again to everyone who provided detailed reports and examples.

**Comment by TomasTurina** [comment]
## Update

Problem reproduced:

![Image](https://github.com/user-attachments/assets/073f5b64-c3b4-4cf3-9000-f67f391ad0e4)

Working on the solution.

Working branch: https://github.com/wazuh/wazuh/tree/fix/29885-fim-utf8

I've managed to avoid the warning, but no alerts are generated yet for paths with these characters.

**Comment by vikman90** [comment]
## Update

After conducting several tests on the Windows agent with the **UTF-8 validation check disabled**, we observed the following behavior across different syscheck modes:

### Scheduled scan

✅ Working as expected:

* Inventory is generated
* Alerts are triggered

### Real-time

✅ Working as expected:

* Alerts are generated

### Real-time + report\_changes

⚠️ Not working as expected:

* The alert is triggered, but the diff information is missing.
* Example alert content:

  ```
  What changed:
  Unable to calculate diff due to 'file_size' limit has been reached.
  ```

### Whodata

✅ Working as expected:

* Alerts are generated

## Conclusion

The issue appears to be isolated to the **report\_changes** functionality.

We suggest:

* Reviewing the command and arguments passed to the `fc` utility (Windows equivalent of `diff`)
* Reassessing the underlying problem that was previously addressed in #23354

This could help identify whether similar encoding or buffer limitations are involved in the diff calculation stage.

**Comment by TomasTurina** [comment]
## Update

### Testing

In addition to the issue with `report_chages` reported by @vikman90, I have also identified that `deleted` alerts are not being generated with these paths.

Example:

1. Alerts `added` and `modified` successfully generated:

```
** Alert 1750975654.1139920: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2025 Jun 26 19:07:34 (tomas) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File 'c:\test\tomásss.txt' added
Mode: realtime

Attributes:
 - Size: 12
 - Permissions: Administradores (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES, SYSTEM (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES, Usuarios (allowed): READ_CONTROL|SYNCHRONIZE|READ_DATA|READ_EA|EXECUTE|READ_ATTRIBUTES, Authenticated Users (allowed): DELETE|READ_CONTROL|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES
 - Date: Thu Jun 26 21:58:09 2025
 - Inode: 0
 - User: tomas (S-1-5-21-4286430651-602233976-113644424-1001)
 - MD5: 1fb0e331c05a52d5eb847d6fc018320d
 - SHA1: 0071877d20a65c02d9a1654f109b97dc61416d1a
 - SHA256: a2c96d518f1099a3b6afe29e443340f9f5fdf1289853fc034908444f2bcb8982
 - File attributes: ARCHIVE

** Alert 1750975679.1142833: - ossec,syscheck,syscheck_entry_modified,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2025 Jun 26 19:07:59 (tomas) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File 'c:\test\tomásss.txt' modified
Mode: realtime
Changed attributes: size,mtime,md5,sha1,sha256
Size changed from '12' to '16'
Old modification time was: '1750985889', now it is '1750986476'
Old md5sum was: '1fb0e331c05a52d5eb847d6fc018320d'
New md5sum is : '3dd0cd797a7399b56c470612887108eb'
Old sha1sum was: '0071877d20a65c02d9a1654f109b97dc61416d1a'
New sha1sum is : '131c471c8b4edf662dd0ebf7adf3c3d7365838b9'
Old sha256sum was: 'a2c96d518f1099a3b6afe29e443340f9f5fdf1289853fc034908444f2bcb8982'
New sha256sum is : '5e8b64da785f1572e6da780648eaaffa009152d297bde80f852f068b0ec2989f'

Attributes:
 - Size: 16
 - Permissions: Administradores (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES, SYSTEM (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES, Usuarios (allowed): READ_CONTROL|SYNCHRONIZE|READ_DATA|READ_EA|EXECUTE|READ_ATTRIBUTES, Authenticated Users (allowed): DELETE|READ_CONTROL|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES
 - Date: Thu Jun 26 22:07:56 2025
 - Inode: 0
 - User: tomas (S-1-5-21-4286430651-602233976-113644424-1001)
 - MD5: 3dd0cd797a7399b56c470612887108eb
 - SHA1: 131c471c8b4edf662dd0ebf7adf3c3d7365838b9
 - SHA256: 5e8b64da785f1572e6da780648eaaffa009152d297bde80f852f068b0ec2989f
 - File attributes: ARCHIVE
```

2. I rename the file to something with special characters and it only generates an alert for the new file:

```
** Alert 1750975694.1144677: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2025 Jun 26 19:08:14 (tomas) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File 'c:\test\tomássss.txt' added
Mode: realtime

Attributes:
 - Size: 16
 - Permissions: Administradores (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES, SYSTEM (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES, Usuarios (allowed): READ_CONTROL|SYNCHRONIZE|READ_DATA|READ_EA|EXECUTE|READ_ATTRIBUTES, Authenticated Users (allowed): DELETE|READ_CONTROL|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES
 - Date: Thu Jun 26 22:07:56 2025
 - Inode: 0
 - User: tomas (S-1-5-21-4286430651-602233976-113644424-1001)
 - MD5: 3dd0cd797a7399b56c470612887108eb
 - SHA1: 131c471c8b4edf662dd0ebf7adf3c3d7365838b9
 - SHA256: 5e8b64da785f1572e6da780648eaaffa009152d297bde80f852f068b0ec2989f
 - File attributes: ARCHIVE
```

3. I rename the file to something without special characters and it only generates an alert for the new file:

```
** Alert 1750975701.1145978: - ossec,syscheck,syscheck_entry_added,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2025 Jun 26 19:08:21 (tomas) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File 'c:\test\tomassss.txt' added
Mode: realtime

Attributes:
 - Size: 16
 - Permissions: Administradores (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES, SYSTEM (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES, Usuarios (allowed): READ_CONTROL|SYNCHRONIZE|READ_DATA|READ_EA|EXECUTE|READ_ATTRIBUTES, Authenticated Users (allowed): DELETE|READ_CONTROL|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES
 - Date: Thu Jun 26 22:07:56 2025
 - Inode: 0
 - User: tomas (S-1-5-21-4286430651-602233976-113644424-1001)
 - MD5: 3dd0cd797a7399b56c470612887108eb
 - SHA1: 131c471c8b4edf662dd0ebf7adf3c3d7365838b9
 - SHA256: 5e8b64da785f1572e6da780648eaaffa009152d297bde80f852f068b0ec2989f
 - File attributes: ARCHIVE
```

4. Finally, I rename the file to its old name, and now it only generates the `deleted` alert for the file without special characters, not the `added` alert for the new one. I assume that since the `deleted` alert for this file has never been generated before, it doesn't assume it's something new:

```
** Alert 1750975781.1149226: - ossec,syscheck,syscheck_entry_deleted,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2025 Jun 26 19:09:41 (tomas) any->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File 'c:\test\tomassss.txt' deleted
Mode: realtime

Attributes:
 - Size: 16
 - Permissions: Administradores (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES, SYSTEM (allowed): DELETE|READ_CONTROL|WRITE_DAC|WRITE_OWNER|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES, Usuarios (allowed): READ_CONTROL|SYNCHRONIZE|READ_DATA|READ_EA|EXECUTE|READ_ATTRIBUTES, Authenticated Users (allowed): DELETE|READ_CONTROL|SYNCHRONIZE|READ_DATA|WRITE_DATA|APPEND_DATA|READ_EA|WRITE_EA|EXECUTE|READ_ATTRIBUTES|WRITE_ATTRIBUTES
 - Date: Thu Jun 26 22:07:56 2025
 - Inode: 0
 - User: tomas (S-1-5-21-4286430651-602233976-113644424-1001)
 - MD5: 3dd0cd797a7399b56c470612887108eb
 - SHA1: 131c471c8b4edf662dd0ebf7adf3c3d7365838b9
 - SHA256: 5e8b64da785f1572e6da780648eaaffa009152d297bde80f852f068b0ec2989f
 - File attributes: ARCHIVE
```

Logging sequence:

```
2025/06/26 19:07:31 wazuh-agent: INFO:  ==== fim_checker: c:\test\tom�sss.txt ====
2025/06/26 19:07:32 wazuh-agent: WARNING: (6955): Ignoring file 'c:\test\tom�sss.txt' due to unsupported name (non-UTF8). (but not ignoring)
2025/06/26 19:07:56 wazuh-agent: INFO:  ==== fim_checker: c:\test\tom�sss.txt ====
2025/06/26 19:07:56 wazuh-agent: WARNING: (6955): Ignoring file 'c:\test\tom�sss.txt' due to unsupported name (non-UTF8). (but not ignoring)
2025/06/26 19:08:12 wazuh-agent: INFO:  ==== fim_checker: c:\test\tom�ssss.txt ====
2025/06/26 19:08:12 wazuh-agent: WARNING: (6955): Ignoring file 'c:\test\tom�ssss.txt' due to unsupported name (non-UTF8). (but not ignoring)
2025/06/26 19:08:18 wazuh-agent: INFO:  ==== fim_checker: c:\test\tomassss.txt ====
2025/06/26 19:09:38 wazuh-agent: INFO:  ==== fim_checker: c:\test\tomassss.txt ====
2025/06/26 19:09:38 wazuh-agent: INFO:  ==== fim_checker: c:\test\tom�ssss.txt ====
2025/06/26 19:09:38 wazuh-agent: WARNING: (6955): Ignoring file 'c:\test\tom�ssss.txt' due to unsupported name (non-UTF8). (but not ignoring)
```

### Analysis

Regarding the problem with `report_changes`, I think it's in this function:

```c
HANDLE wCreateFile(LPCSTR   lpFileName,
                    DWORD   dwDesiredAccess,
                    DWORD   dwShareMode,
                    LPSECURITY_ATTRIBUTES lpSecurityAttributes,
                    DWORD   dwCreationDisposition,
                    DWORD   dwFlagsAndAttributes,
                    HANDLE  hTemplateFile) {

    if (is_network_path(lpFileName)) {
        errno = EACCES;
        mwarn(NETWORK_PATH_EXECUTED, lpFileName);
        return (INVALID_HANDLE_VALUE);
    }
    return CreateFile(lpFileName,
                      dwDesiredAccess,
                      dwShareMode,
                      lpSecurityAttributes,
                      dwCreationDisposition,
                      dwFlagsAndAttributes,
                      hTemplateFile);
}
```

I have tried this version of the function without success (returns file not found) that uses `CreateFileW`:

```c
HANDLE wCreateFile(LPCSTR   lpFileName,
                    DWORD   dwDesiredAccess,
                    DWORD   dwShareMode,
                    LPSECURITY_ATTRIBUTES lpSecurityAttributes,
                    DWORD   dwCreationDisposition,
                    DWORD   dwFlagsAndAttributes,
                    HANDLE  hTemplateFile) {

    if (!lpFileName) {
        errno = EINVAL;
        mwarn("lpFileName is NULL");
        return INVALID_HANDLE_VALUE;
    }

    if (is_network_path(lpFileName)) {
        errno = EACCES;
        mwarn(NETWORK_PATH_EXECUTED, lpFileName);
        return INVALID_HANDLE_VALUE;
    }

    // Convert UTF-8 to UTF-16
    int wlen = MultiByteToWideChar(CP_UTF8, 0, lpFileName, -1, NULL, 0);
    if (wlen <= 0) {
        errno = EINVAL;
        merror("UTF-8 to UTF-16 conversion failed for: %s", lpFileName);
        return INVALID_HANDLE_VALUE;
    }

    wchar_t *wpath = NULL;
    os_calloc(wlen, sizeof(wchar_t), wpath);

    if (MultiByteToWideChar(CP_UTF8, 0, lpFileName, -1, wpath, wlen) == 0) {
        errno = EINVAL;
        merror("UTF-8 to UTF-16 conversion failed for: %s", lpFileName);
        os_free(wpath);
        return INVALID_HANDLE_VALUE;
    }

    HANDLE h = CreateFileW(wpath,
                           dwDesiredAccess,
                           dwShareMode,
                           lpSecurityAttributes,
                           dwCreationDisposition,
                           dwFlagsAndAttributes,
                           hTemplateFile);

    os_free(wpath);
    return h;
}
```

### Next steps

- Confirm that the problem is in `wCreateFile`.
  - The `CreateFile` function does not work with special characters.
  - There may be other functions with similar issues.
- Continue searching for a solution.
