### ISSUE TITLE
Install script does not create necessary user for vulnerability scanner

### ISSUE THREAD

**Issue by landon-lengyel** [wazuh/wazuh#30090]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.12.0 | wazuh-indexer / installer | Manager | Install script | Debian 12 |

Hi,
I experienced the issue's described by many users in #24074 and none of those solutions worked for me. I ultimately found the source of the problem, and I believe the install script needs to be updated to reflect it. I will also look at updating the troubleshooting documentation to note this case, for users who have not used the install script (or used an older version of the install script).

ossec.log shows
```
indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-wazuh01', retrying until the connection is successful.
```

The symptoms of the problem are that Vulnerability Detector does not update the vulnerability list for the agents in the Wazh UI. This is due to the Vulnerability Detector module(?) not being able to communicate with Wazuh-Indexer/OpenSearch. A lot of the current documentation and community suggestions surrounding this is centered around ensuring that the keystore contains credentials to authenticate with. This works well if the user has not modified the OpenSearch security configuration. However, if the user has modified it in a certain way then it will cause issues.

The curl suggestions by @MiguelazoDS include both the basic authentication, and client certificate authentication commands. It looks like the client certificate is mostly unused with the default OpenSearch security configuration and it's really authenticating with the user credentials. In fact, you can omit those user certs entirely and it will still work.
```shell
curl -u <user>:<pass> --cacert <path.pem> --cert <path-client.pem> --key <path-client-key.pem> -X GET "https://<IP>/_cluster/health"
```
In the case where where user has modified the OpenSearch security configuration to look like mine, they will no longer be able to authenticate:
```yaml
    authc:
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: https://login.microsoftonline.com...
            openid_connect_idp:
              enable_ssl: true
              verify_hostnames: true
              #pemtrustedcas_filepath: /etc/opensearch/opensearch-security/DigiCertGlobalRootCA.crt.pem
              pemtrustedcas_content: |-
                -----BEGIN CERTIFICATE-----
                MIIDrzCCApegAwIBAgIQCDvgVp...
                -----END CERTIFICATE-----
        authentication_backend:
          type: noop
      clientcert_auth_domain:
        description: "Authenticate via SSL client certificates issued by AD CS"
        http_enabled: true
        transport_enabled: false
        order: 2
        http_authenticator:
          type: clientcert
          config:
            username_attribute: cn
          challenge: false # This may need to be true to prompt for alternative authentication
        authentication_backend:
          type: noop
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 3
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
```

The Vulnerability Detector appears to be unable to authenticate because it is attempting certificate authentication first due to the `order` and certificate authentication is explicitly allowed on the HTTP API layer `http_enabled: true`. Unfortunately, it is not correctly falling back to basic authentication. This can be seen in the OpenSearch log file `wazuh-cluster.log`:
```
[2025-06-03T14:10:12,907][INFO ][o.o.s.p.PrivilegesEvaluatorImpl] [node-1] No index-level perm match for User [name=wazuh-server, backend_roles=[], requestedTenant=null] Resolved [aliases=[], allIndices=[wazuh-alerts-4.x-2025.06.03], types=[*], originalRequested=[<wazuh-alerts-4.x-{2025.06.03||/d{yyyy.MM.dd|UTC}}>], remoteIndices=[]]: Insufficient permissions for the referenced index [Action [indices:data/write/bulk[s]]] [RolesChecked [own_index]]
[2025-06-03T14:10:12,908][INFO ][o.o.s.p.PrivilegesEvaluatorImpl] [node-1] Index to privilege matrix:
                            | indices:data/write/bulk[s] | indices:data/write/index |
wazuh-alerts-4.x-2025.06.03 | MISSING                    | MISSING                  |
```

You can see that it is using default certificate generated by the install script, who's `CN=wazuh-server`
If you add a user named `wazuh-server` and give it full permissions, then it will start to work.

My suggestion is that either the install script be updated to actually create this `wazuh-user` or the Vulnerability Detector module be updated to not use certificate authentication, as it already seems redundant and unused by default.

Thank you for your work on this project.
