### ISSUE TITLE
Refactor the SCA internal logic engine

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#3249]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v3.9.0 | SCA | Agent | All | All |

Currently, the logic to determine if a check is `passed` or `failed` in the SCA module is inverted. Let's see it with an example:

```
- id: 10577
   title: "Set SSH Protocol to 2"
   description: "SSH supports two different and incompatible protocols: SSH1 and SSH2. SSH1 was the original protocol and was subject to security issues. SSH2 is more advanced and secure."
   rationale: "SSH v1 suffers from insecurities that do not affect SSH v2."
   remediation: "Edit the /etc/ssh/sshd_config file to set the parameter as follows: Protocol 2"
   compliance:
    - cis: "9.3.1"
   condition: any
   rules:
     - 'f:/etc/ssh/sshd_config -> IN !r:^# && r:Protocol 1;'
     - 'f:/etc/ssh/sshd_config -> !r:^Protocol 2$;'
```

We want to ensure the SSH protocol is set to 2 instead of 1. The rule to mark this check to `pass` is to look for the lack of the desired output `protocol 2`. In other words, when the rule matches, the result of the check is fail.

The correct syntax to write this check should be the following one:

```
- id: 5035
   title: "Ensure SSH Protocol is set to 2"
   description: "Older versions of SSH support two different and incompatible protocols: SSH1 and SSH2. SSH1 was the original protocol and was subject to security issues. SSH2 is more advanced and secure."
   rationale: "SSH v1 suffers from insecurities that do not affect SSH v2."
   remediation: "Edit the /etc/ssh/sshd_config file to set the parameter as follows: Protocol 2"
   compliance:
    - cis_csc: "14.4"
    - cis: "5.2.4"
    - pci_dss: "4.1"
   condition: any
   rules:
     - 'f:/etc/ssh/sshd_config -> IN !r:^# && r:Protocol\.+2;'
```

Here, if we found a line which matches with `!r:^# && r:Protocol\.+2`, the check is passed.

On the other side, the use of `IN/NIN` (included or not included) to negate a whole rule makes the rules more complexes to be understood. It will be replaced by `not` to negate a complete rule:

This rule looks for a non-commented line (`!r:^#`) which contains `Protocol\.+2`.
```
- 'f:/etc/ssh/sshd_config -> !r:^# && r:Protocol\.+2;'
```

However, the next rule looks for the opposite (not to find any rule that matches that regex):
```
- 'f:/etc/ssh/sshd_config -> not !r:^# && r:Protocol\.+2;'
```

By default, the `not` operator should be lowercase, but NOT should be supported as well.

The last change for this issue is to remove the final semicolon of every rule, which is unuseful.

### Task summary

- [x] Invert the check logic for the SCA rules

- [x] Replace the `IN/NIN` for `not`

- [x] Remove the semicolon `;` of every rule

- [x] Improve the debug logging

**Comment by JuantAldea** [comment]
Requirements conditions `all/any/none required` are redundant  to `all/any/none` as they are **required** by definition, hence I will be deprecating the "required" modifier, defaulting requirements using them to their equivalent.

**Comment by JuantAldea** [comment]
Tests
For Requirements
- [ ] ALL/ANY/NONE with several checks. With checks returning 0/1/2.
- [ ] ALL/ANY/NONE with a single check. With check returning 0/1/2.

**Comment by JuantAldea** [comment]
We have been discussing about the where to place the `not` operator and we have concluded that the best location is at the beginning of the rule. For example:
```yaml
 - id: 99302
   title: FAIL Test to check if value data is not found
   condition: any
   rules:
     - not r:HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion -> SoftwareType -> System
```
