### ISSUE TITLE
Syscheck SUID enhancement

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#3304]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.0 | FIM | Manager/Agent | Packages/Sources | All platforms |

### SUID bit detection

As for now FIM (ossec-syscheckd) is unable to detect if the SUID bit is set on a monitored file, not generating an alert when it changes.

Rootcheck has the ability to do that but the code logic is wrong and not well designed, for example the user cannot set a directory to be monitored for SUID changes on the files inside it.

Taking a look at the source code:

```C
    /* Open output files */
    if (rootcheck.notify != QUEUE) {
        _wx = fopen("rootcheck-rw-rw-rw-.txt", "w");
        _ww = fopen("rootcheck-rwxrwxrwx.txt", "w");
        _suid = fopen("rootcheck-suid-files.txt", "w");
    } else {
        _wx = NULL;
        _ww = NULL;
        _suid = NULL;
}
```

We can clearly see that it will store the files with the SUID bit activated on the `rootcheck-suid-files.txt` which is not good enough, it should al least generate an alert.

**Comment by vikman90** [comment]
Hi team.

As far as we know, FIM now detects permission changes in SUID.

Test:
```sh
chmod +s /root/test/compare
```

Alert:
```
** Alert 1610360526.11995: - ossec,syscheck,syscheck_entry_modified,syscheck_file,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2021 Jan 11 11:22:06 groovy->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/root/test/compare' modified
Mode: realtime
Changed attributes: permission
Permissions changed from 'rwxr-xr-x' to 'rwsr-sr-x'

Attributes:
 - Size: 17280
 - Permissions: rwsr-sr-x
 - Date: Tue Nov 24 18:26:10 2020
 - Inode: 531276
 - User: root (0)
 - Group: root (0)
 - MD5: d9d09525ddbf6af15b54457fb08a5eee
 - SHA1: 1e6291f02f5e9613de41fb8397bacc762e4c5381
 - SHA256: c6ab639c1b60c214b7db63633715878b7e8f6d2dd0620c046795a4fe42e3ab24
```

We will take a look at Rootcheck.
Best regards!
