### ISSUE TITLE
[Filebeat][7.x] Do not remove fields for renaming

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#3512]
**Description**

Since Elastic 7.x we modified the way to enable GeoLocation for the Elastic stack, old Logstash filters were replaced with some processors in the Filebeat configuration. 

Here is an example:

```yml
  - rename:
      fields:
        - from: "data.srcip"
          to: "@src_ip"
      ignore_missing: true
      fail_on_error: false
      when:
        regexp:
          data.srcip: \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b
```

The problem here is that renaming in Filebeat also removes the original field, which may cause custom dashboards to fail and to lose critical fields from the event.

**Proposal**

We must find a different way to achieve the same thing. Filebeat has no "copy" method so it's not as easy as we would like, however, I've been playing around with a combination of `dissect`+ `rename` processors and it might be the solution, further details will be added to this ticket.

**Comment by jesusgn90** [comment]
**Update**

Hi team, struggling with Filebeat configurations I think we have a first iteration which doesn't remove fields and which I think is a better practice for this use case.

## Proposal

Here is the new proposal for the configuration (it still may change):

```yml
# Wazuh - Filebeat configuration file

# Input
filebeat.inputs:
  - type: log
    paths:
      - '/var/ossec/logs/alerts/alerts.json'

# Mapping for Wazuh alerts in JSON
setup.template.json.enabled: true

# The template file location
setup.template.json.path: "/etc/filebeat/wazuh-template.json"

# The name for the template in Elasticsearch
setup.template.json.name: "wazuh"

# Overwrite the template named "wazuh" if it already exists in Elasticsearch
setup.template.overwrite: true

# Parse and enrich events before forwarding them
processors:

  # Decode the message, from string to JSON
  - decode_json_fields:
      fields: ['message']
      process_array: true
      max_depth: 200
      target: ''
      overwrite_keys: true

  # Drop fields added by the Elastic stack
  - drop_fields:
      fields: ['message', 'ecs', 'beat', 'input_type', 'tags', 'count', '@version', 'log', 'offset', 'type', 'host']

  # Copy data.aws.sourceIPAddress in extracted_address.data.aws.sourceIPAddress
  - dissect:
      tokenizer: "%{data.aws.sourceIPAddress}"
      field: data.aws.sourceIPAddress
      target_prefix: "extracted_address"

  # Copy data.srcip in extracted_address.data.srcip
  - dissect:
      tokenizer: "%{data.srcip}"
      field: data.srcip
      target_prefix: "extracted_address"

  # Copy data.win.eventdata.ipAddress in extracted_address.data.win.eventdata.ipAddress
  - dissect:
      tokenizer: "%{data.win.eventdata.ipAddress}"
      field: data.win.eventdata.ipAddress
      target_prefix: "extracted_address"

  # Try to rename common IP fields to @src_ip
  - rename:
      fields:
        - from: "extracted_address.data.aws.sourceIPAddress"
          to: "@src_ip"
        - from: "extracted_address.data.srcip"
          to: "@src_ip"
        - from: "extracted_address.data.win.eventdata.ipAddress"
          to: "@src_ip"
      # Do not crash if the field is missing
      ignore_missing: true
      # Do not crash if an error occurred even if the field exists
      fail_on_error: false
      # Condition for when to do the renaming
      when:
        or:
          - regexp.extracted_address.data.aws.sourceIPAddress: \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b
          - regexp.extracted_address.data.srcip: \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b
          - regexp.extracted_address.data.win.eventdata.ipAddress: \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b

  # Remove extracted_address field if it exists
  - drop_fields:
      when.has_fields: ['extracted_address']
      fields: ['extracted_address']

# Output
# The Elasticsearch host(s) setting indicates where the events must be sent
# The index setting is the name for the destination index in Elasticsearch
output.elasticsearch:
  hosts: ['http://172.16.1.4:9200']
  indices:
    - index: 'wazuh-alerts-3.x-%{+yyyy.MM.dd}'
```

## How it works now?

**The `dissect` processors**

```yml
  - dissect:
      tokenizer: "%{<FIELD_NAME>}"
      field: <FIELD_NAME>
      target_prefix: "extracted_address"
```

It is the only way to copy field values into a new field when using Filebeat that I found. 

Steps a `dissect` block does:

1. If the field doesn't exist this processor is ignored, it stops at this point.
2. If the field exists, then create a new field named "extracted_address.<FIELD_NAME>" with the same value as the <FIELD_NAME> has.

Example:

Let's say we have a field named `foo` with value `bar`, then we have the next processor:

```yml
  - dissect:
      tokenizer: "%{foo}"
      field: foo
      target_prefix: "extracted_address"
```
Our event looks like this:

```
{ ..., "foo": "bar", ... }
```

After the `dissect` block, the event now looks like this:

```
{ ..., "foo": "bar", "extracted_address": {"foo": "bar" }, ... }
```

**The `rename` processor**

```yml
  - rename:
      fields:
        - from: "extracted_address.<FIELD_NAME>"
          to: "@src_ip"
      ignore_missing: true
      fail_on_error: false
      when:
        or:
          - regexp.extracted_address.<FIELD_NAME>: \b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b
```

Steps this `rename` block does:

1. If the field doesn't exist this processor is ignored, it stops at this point.
2. If the processor fails, it's ignored too, it stops at this point.
3. If the field exists, which means, we have a field named `extracted_address.<FIELD_NAME>` it must match with the regexp `\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b` which means it must be a valid IP address.
4. If step 3) is valid, then the field `extracted_address.<FIELD_NAME>` is renamed to `@src_ip` so it's removed and its value is now in `@src_ip`.

Example:

Let's say we have the next event after the `dissect` processors:

```
{..., "data": {"srcip": "192.168.1.2" }, { "extracted_address": { "data": { "srcip": "192.168.1.1" } } }, ... }
```

Now, the processor will rename `extracted_address.data.srcip" to `@src_ip` so our event now looks like this:

```
{..., "data": {"srcip": "192.168.1.2" }, { "@src_ip": "192.168.1.1" }, ... }
```
 
**The `drop_fields` processor**

```
  - drop_fields:
      when.has_fields: ['extracted_address']
      fields: ['extracted_address']
```

When it would be useful?

When the event comes with a common IP field, but the renaming processor failed because the IP is not a valid IP, then the event keeps the `extracted_address` field because it was not be renamed.

Steps a `drop_fields` block does:

1. If the field doesn't exist, ignore it, it stops at this point.
2. Just in case the event still has `extracted_address` field (for any reason), then delete it from the event.

Example:

Let's say we have the next event after the `dissect` and the `rename` processors:

```
{..., "data": {"srcip": "192.168.1.2" }, { "extracted_address": { "data": { "srcip": "fakeaddress" } } }, ... }
```

After the processor, the event looks like this:

```
{..., "data": {"srcip": "192.168.1.2" }, ... }
```

**Are the original fields preserved?**

Yes, the above logic always keeps the original field as it.

## Tests with "geoip" pipeline disabled

Using the above configuration I've done some tests with different kind of alerts, trying all the use cases.

_Note: the content of the alerts was altered from a single alert, so the fields don't reflect the real nature of that alert and that rule._

**Alert with none of the common IP fields**

```json
{"timestamp":"2019-06-11T08:29:26.125+0000","rule":{"level":3,"description":"Service startup type was changed","id":"61104","info":"This does not appear to be logged on Windows 2000","firedtimes":2,"mail":false,"groups":["windows"," windows_systempolicy_changed"],"pci_dss":["10.6"],"gdpr":["IV_35.7.d"]},"agent":{"id":"010","name":"windows-ag","ip":"10.0.2.15"},"manager":{"name":"master"},"id":"1560241766.129973","cluster":{"name":"wazuh","node":"node01"},"decoder":{"name":"windows_eventchannel"},"data":{"foo":"bar"},"location":"EventChannel"}
```

It was indexed properly with no problems.

**Alert with data.srcip valid address**

```json
{"timestamp":"2019-06-11T08:29:26.125+0000","rule":{"level":3,"description":"Service startup type was changed","id":"61104","info":"This does not appear to be logged on Windows 2000","firedtimes":2,"mail":false,"groups":["windows"," windows_systempolicy_changed"],"pci_dss":["10.6"],"gdpr":["IV_35.7.d"]},"agent":{"id":"010","name":"windows-ag","ip":"10.0.2.15"},"manager":{"name":"master"},"id":"1560241766.129973","cluster":{"name":"wazuh","node":"node01"},"decoder":{"name":"windows_eventchannel"},"data":{"foo":"bar", "srcip": "192.168.1.2"},"location":"EventChannel"}
```

It was indexed properly, the original field `data.srcip` is preserved, the `@src_ip` appears and the `extracted_address.data.srcip` is removed.

**Alert with data.srcip invalid address**

```json
{"timestamp":"2019-06-11T08:29:26.125+0000","rule":{"level":3,"description":"Service startup type was changed","id":"61104","info":"This does not appear to be logged on Windows 2000","firedtimes":2,"mail":false,"groups":["windows"," windows_systempolicy_changed"],"pci_dss":["10.6"],"gdpr":["IV_35.7.d"]},"agent":{"id":"010","name":"windows-ag","ip":"10.0.2.15"},"manager":{"name":"master"},"id":"1560241766.129973","cluster":{"name":"wazuh","node":"node01"},"decoder":{"name":"windows_eventchannel"},"data":{"foo":"bar", "srcip": "fakeaddress"},"location":"EventChannel"}
```

It was indexed properly, the original field `data.srcip` is preserved, the `@src_ip` doesn't exist and the `extracted_address.data.srcip` is removed.

**Alert with data.aws.sourceIPAddress valid address**

```json
{"timestamp":"2019-06-11T08:29:26.125+0000","rule":{"level":3,"description":"Service startup type was changed","id":"61104","info":"This does not appear to be logged on Windows 2000","firedtimes":2,"mail":false,"groups":["windows"," windows_systempolicy_changed"],"pci_dss":["10.6"],"gdpr":["IV_35.7.d"]},"agent":{"id":"010","name":"windows-ag","ip":"10.0.2.15"},"manager":{"name":"master"},"id":"1560241766.129973","cluster":{"name":"wazuh","node":"node01"},"decoder":{"name":"windows_eventchannel"},"data":{"foo":"bar", "aws":{ "sourceIPAddress":"192.168.1.2"}},"location":"EventChannel"}
```
It was indexed properly, the original field `data.aws.sourceIPAddress` is preserved, the `@src_ip` appears and the `extracted_address.data.aws.sourceIPAddress` is removed.

**Alert with data.aws.sourceIPAddress invalid address**

```json
{"timestamp":"2019-06-11T08:29:26.125+0000","rule":{"level":3,"description":"Service startup type was changed","id":"61104","info":"This does not appear to be logged on Windows 2000","firedtimes":2,"mail":false,"groups":["windows"," windows_systempolicy_changed"],"pci_dss":["10.6"],"gdpr":["IV_35.7.d"]},"agent":{"id":"010","name":"windows-ag","ip":"10.0.2.15"},"manager":{"name":"master"},"id":"1560241766.129973","cluster":{"name":"wazuh","node":"node01"},"decoder":{"name":"windows_eventchannel"},"data":{"foo":"bar", "aws":{ "sourceIPAddress":"fakeaddress"}},"location":"EventChannel"}
```

It was indexed properly, the original field `data.aws.sourceIPAddress` is preserved, the `@src_ip` doesn't exist and the `extracted_address.data.aws.sourceIPAddress` is removed.

**Alert with data.win.eventdata.ipAddress valid address**

```json
{"timestamp":"2019-06-11T08:29:26.125+0000","rule":{"level":3,"description":"Service startup type was changed","id":"61104","info":"This does not appear to be logged on Windows 2000","firedtimes":2,"mail":false,"groups":["windows"," windows_systempolicy_changed"],"pci_dss":["10.6"],"gdpr":["IV_35.7.d"]},"agent":{"id":"010","name":"windows-ag","ip":"10.0.2.15"},"manager":{"name":"master"},"id":"1560241766.129973","cluster":{"name":"wazuh","node":"node01"},"decoder":{"name":"windows_eventchannel"},"data":{"foo":"bar", "win":{ "eventdata":{"ipAddress":"192.168.1.2"}}},"location":"EventChannel"}
```

It was indexed properly, the original field `data.win.eventdata.ipAddress` is preserved, the `@src_ip` appears and the `extracted_address.data.win.eventdata.ipAddress` is removed.

**Alert with data.win.eventdata.ipAddress invalid address**

```json
{"timestamp":"2019-06-11T08:29:26.125+0000","rule":{"level":3,"description":"Service startup type was changed","id":"61104","info":"This does not appear to be logged on Windows 2000","firedtimes":2,"mail":false,"groups":["windows"," windows_systempolicy_changed"],"pci_dss":["10.6"],"gdpr":["IV_35.7.d"]},"agent":{"id":"010","name":"windows-ag","ip":"10.0.2.15"},"manager":{"name":"master"},"id":"1560241766.129973","cluster":{"name":"wazuh","node":"node01"},"decoder":{"name":"windows_eventchannel"},"data":{"foo":"bar", "win":{ "eventdata":{"ipAddress":"fakeaddress"}}},"location":"EventChannel"}
```

It was indexed properly, the original field `data.win.eventdata.ipAddress` is preserved, the `@src_ip` doesn't exist and the `extracted_address.data.win.eventdata.ipAddress` is removed.

**References**

- Processor conditions: https://www.elastic.co/guide/en/beats/filebeat/current/defining-processors.html#conditions
- Processors `dissect`: https://www.elastic.co/guide/en/beats/filebeat/current/dissect.html
- Processors `rename`: https://www.elastic.co/guide/en/beats/filebeat/current/rename-fields.html
- Processors `drop_fields`: https://www.elastic.co/guide/en/beats/filebeat/current/drop-fields.html

**Next steps**

Do the same tests against a "geoip" ingest pipeline enabled.
