### ISSUE TITLE
SCA: Field 'condition' is neither shown in events nor stored in the database

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh#3598]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.0-31003 | SCA | Manager/Agent | Packages/Sources | Any |

The field `condition`, which can be set to the values, `all`, `any` or `none`, should be added to the databases and alerts. 
For example, the next check:
```
  - id: 10511
    title: "Ensure auditd service is enabled"
    description: "Turn on the auditd daemon to record system events."
    rationale: "The capturing of system events provides system administrators with information to allow them to determine if unauthorized access to their system is occurring."
    remediation: "Run the following command to enable auditd: # systemctl enable auditd"
    compliance:
      - cis: "4.1.2"
      - cis_csc: "6.2, 6.3"
    condition: all
    rules:
      - 'c:systemctl is-enabled auditd -> r:^enabled'
```

In the databases should be shown as follows:
```
1623104015|10511|cis_debian8_L2|Ensure auditd service is enabled|Turn on the auditd daemon to record system events.|The capturing of system events provides system administrators with information to allow them to determine if unauthorized access to their system is occurring.|Run the following command to enable auditd: # systemctl enable auditd|||||systemctl is-enabled auditd||passed||all
```

And in the alerts:
```

** Alert 1561981287.117612: - sca,gdpr_IV_35.7.d
2019 Jul 01 13:41:27 (d8) any->sca
Rule: 19007 (level 7) -> 'CIS benchmark for Debian/Linux 8 L2: Ensure auditd service is enabled'
{"type":"check","id":660330283,"policy":"CIS benchmark for Debian/Linux 8 L2","policy_id":"cis_debian8_L2","check":{"id":10511,"title":"Ensure auditd service is enabled","description":"Turn on the auditd daemon to record system events.","rationale":"The capturing of system events provides system administrators with information to allow them to determine if unauthorized access to their system is occurring.","remediation":"Run the following command to enable auditd: # systemctl enable auditd","compliance":{"cis":"4.1.2","cis_csc":"6.2, 6.3"},"rules":["c:systemctl is-enabled auditd -> r:^enabled"],"command":"systemctl is-enabled auditd","result":"failed"}}
sca.type: check
sca.scan_id: 660330283
sca.policy: CIS benchmark for Debian/Linux 8 L2
sca.check.id: 10511
sca.check.title: Ensure auditd service is enabled
sca.check.description: Turn on the auditd daemon to record system events.
sca.check.rationale: The capturing of system events provides system administrators with information to allow them to determine if unauthorized access to their system is occurring.
sca.check.remediation: Run the following command to enable auditd: # systemctl enable auditd
sca.check.compliance.cis: 4.1.2
sca.check.compliance.cis_csc: 6.2, 6.3
sca.check.command: ["systemctl is-enabled auditd"]
sca.check.result: failed
sca.check.condition: all
```
With the new field `sca.check.condition`.
