### ISSUE TITLE
Upgrade Elasticsearch/Kibana from 6.8 to 7.0 

### ISSUE THREAD

**Issue by John33000** [wazuh/wazuh#3962]
Hello
I can open the issue : https://github.com/wazuh/wazuh/issues/3848 
So I open other issue. Can you answer my last question in issue #3848 please

Bests regards,

**Comment by John33000** [comment]
Hi,

I resolve the issue, but know after update in 7.0. The Kibana interface say : Kibana server is not yet and when I refresh I have : Error 502 bad gateway nginx.

Before update I had Nginx proxy, I follow this guide for install https://documentation.wazuh.com/3.9/installation-guide/installing-elastic-stack/protect-installation/kibana_ssl.html?highlight=nginx

And now in log nginx I have this :   `PID file /var/run/nginx.pid not readable (yet?) after start.`

My /etc/nginx/nginx.conf it's this : 

```
user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


/bin/bash: q : commande introuvable
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
```

**Comment by pablotr9** [comment]
Hi @John33000 ,

Have Filebeat, Kibana and Elasticsearch the same version?
Could you please share with us your Nginx configuration file `/etc/nginx/conf.d/default.conf`
Could you also check Kibana and Elasticsearch status? `systemctl status kibana -l` and `systemctl status elasticsearch -l`

Regards,
Pablo Torres

**Comment by John33000** [comment]
Hi,

Yes Kibana, Elastic and Filebeat are the same version.

```
server {
    listen 443 default_server;
    listen [::]:443;
    ssl on;
    ssl_certificate     /etc/pki/tls/certs/<CERT>.crt;
    ssl_certificate_key /etc/pki/tls/private/kibana-access.key;
    access_log            /var/log/nginx/access.log;
    error_log            /var/log/nginx/error.log;
    location / {
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/conf.d/kibana.htpasswd;
        proxy_pass https://127.0.0.1:5601/;
    }
}
```

```
● kibana.service - Kibana
   Loaded: loaded (/etc/systemd/system/kibana.service; enabled; vendor preset: disabled)
   Active: active (running) since ven. 2019-09-13 13:58:27 CEST; 8s ago
 Main PID: 4543 (node)
    Tasks: 21
   CGroup: /system.slice/kibana.service
           └─4543 /usr/share/kibana/bin/../node/bin/node --no-warnings --max-http-header-size=65536 /usr/share/kibana/bin/../src/cli -c /etc/kibana/kibana.yml

sept. 13 13:58:27  systemd[1]: Started Kibana.
sept. 13 13:58:30  kibana[4543]: {"type":"log","@timestamp":"2019-09-13T11:58:30Z","tags":["info","plugins-system"],"pid":4543,"message":"Setting up [1] plugins: [translations]"}
sept. 13 13:58:30  kibana[4543]: {"type":"log","@timestamp":"2019-09-13T11:58:30Z","tags":["info","plugins","translations"],"pid":4543,"message":"Setting up plugin"}
sept. 13 13:58:30  kibana[4543]: {"type":"log","@timestamp":"2019-09-13T11:58:30Z","tags":["info","plugins-system"],"pid":4543,"message":"Starting [1] plugins: [translations]"}
```
```
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
   Active: active (running) since ven. 2019-09-13 11:20:13 CEST; 2h 39min ago
     Docs: http://www.elastic.co
 Main PID: 24332 (java)
    Tasks: 57
   CGroup: /system.slice/elasticsearch.service
           ├─24332 /usr/share/elasticsearch/jdk/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.io.tmpdir=/tmp/elasticsearch-7067692315845012221 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/elasticsearch -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Djava.locale.providers=COMPAT -Dio.netty.allocator.type=unpooled -XX:MaxDirectMemorySize=536870912 -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/etc/elasticsearch -Des.distribution.flavor=default -Des.distribution.type=rpm -Des.bundled_jdk=true -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch/elasticsearch.pid --quiet
           └─24432 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller

sept. 13 11:20:13  systemd[1]: Started Elasticsearch.
sept. 13 11:20:14 elasticsearch[24332]: OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
```
Regards,

**Comment by John33000** [comment]
Before the update it worked, after the update it works more. And I don't touch configuration of Nginx

**Comment by pablotr9** [comment]
Hi @John33000 ,

Thanks for the output.
Have you tried this command and re-trying to enter to Kibana interface?
` setsebool -P httpd_can_network_connect 1`

If that didn't work, could you check Nginx error logs and paste here the output?
`tail /var/log/nginx/nginx.error.log`

Let me know if it helps

Best regards,
Pablo Torres

**Comment by John33000** [comment]
Hi,

Yes I tried this command.
In nginx.error.log I had : `connect() failed (111: Connection refused) while connecting to upstream, client:`

But .. we don't understand why after the update we have this.

And in : `journalctl -u nginx` :  `PID file /var/run/nginx.pid not readable (yet?) after start.`

We do a revert of snapshot, because the update have break the nginx. We retry the update the next week. We update filebeat, elasticsearch, kibana and wazuh why nginx do this ? The IP or port  does not change

**Comment by John33000** [comment]
After the revert... Elasticsearch don't want start : 

 ```
tail elasticsearch.log
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.8.0.jar:6.8.0]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:692) [elasticsearch-6.8.0.jar:6.8.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) [elasticsearch-6.8.0.jar:6.8.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.8.0.jar:6.8.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[2019-09-12T15:16:43,675][WARN ][o.e.c.r.a.DiskThresholdMonitor] [GcnprKI] high disk watermark [42gb] exceeded on [GcnprKI4QDifzKuNsP2qiA][GcnprKI][/var/lib/elasticsearch/nodes/0] free: 34.5gb[70.2%], shards will be relocated away from this node
[2019-09-12T15:16:43,675][INFO ][o.e.c.r.a.DiskThresholdMonitor] [GcnprKI] rerouting shards: [high disk watermark exceeded on one or more nodes]
```

**Comment by pablotr9** [comment]
Hi @John33000 ,

Could you please paste some more logs so we can try to find what is causing that error?
`tail -n 100 /var/log/elasticsearch/elasticsearch.log`

Regards,
Pablo Torres

**Comment by John33000** [comment]
Hi @pablotr9 

I have nothing... 

![image](https://user-images.githubusercontent.com/46779058/64939780-6a1a1680-d862-11e9-8c89-1e3ec727716a.png)

**Comment by pablotr9** [comment]
Hi @John33000 ,

Check your `elasticsearch.yml` (`/etc/elasticsearch/elasticsearch.yml`), you will see there the Elasticsearch cluster name and the path where logs are being stored:
```
cluster.name: "<cluster-name>"
path.logs: /var/log/elasticsearch
```
Then you can find Elasticsearch logs in that path:
`/var/log/elasticsearch/<cluster-name>.log`

**Comment by John33000** [comment]
The path logs it's the same :
`path.logs: /var/log/elasticsearch`

**Comment by John33000** [comment]
But in /var/log/elasticsearch I have this : 
![image](https://user-images.githubusercontent.com/46779058/64940937-997e5280-d865-11e9-83c5-4f47ceaf5977.png)

**Comment by John33000** [comment]
I understand in `systemctl status elasticsearch`, my index was corrupted, I can erase all my index and restart at the begin ? For regenerate new index for elasticsearch start.

**Comment by pablotr9** [comment]
Hi @John33000 ,
Removing the index will make you lose all the data inside that index, this is only recommended if you are 100% sure that you want to lose that data, 
What is the output of this command? 
`journalctl -xe | grep elasticsearch -i`

**Comment by John33000** [comment]
![image](https://user-images.githubusercontent.com/46779058/64945479-e7e51e80-d870-11e9-9958-42ab8beada53.png)



Yes I'm sure, I want elasticsearch start.

**Comment by pablotr9** [comment]
Hi @John33000 ,

We are trying to find out the origin of the error, still don't have enough information,
Could you please try to start Elasticsearch manually, this should print the error that causes Elasticsearch to fail:
`sudo -u elasticsearch /usr/share/elasticsearch/bin/elasticsearch`
Could you please paste here the output of above command?

**Comment by John33000** [comment]
Yes : 
```
/usr/share/elasticsearch/bin/elasticsearch
Creating home directory for elasticsearch.
Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: org.apache.lucene.index.CorruptIndexException: misplaced codec footer (file extended?): remaining=17, expected=16, fp=183 (resource=BufferedChecksumIndexInput(SimpleFSIndexInput(path="/etc/elasticsearch/elasticsearch.keystore")))
Likely root cause: org.apache.lucene.index.CorruptIndexException: misplaced codec footer (file extended?): remaining=17, expected=16, fp=183 (resource=BufferedChecksumIndexInput(SimpleFSIndexInput(path="/etc/elasticsearch/elasticsearch.keystore")))
        at org.apache.lucene.codecs.CodecUtil.validateFooter(CodecUtil.java:497)
        at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:414)
        at org.elasticsearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:260)
        at org.elasticsearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:230)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:295)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93)
Refer to the log for complete error details.

```

**Comment by John33000** [comment]
Maybe it's more simple to delete index no ? We can try.

**Comment by pablotr9** [comment]
Hi @John33000 ,

How many nodes do you have in your Elasticsearch cluster?
Could you please share your `elasticsearch.yml` ? (`etc/elasticsearch/elasticsearch.yml`)
I can see in your previous message (https://github.com/wazuh/wazuh/issues/3962#issuecomment-531251860) one of your nodes was having system disk space usage issues, could you check that all your nodes have less than 70% of used space? 
You can run this command to check system disk space usage on every node of your cluster: `df -h`

**Comment by John33000** [comment]
Hi,

I have one node 

elasticsearch.yml : 

```
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: my-application
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: /var/lib/elasticsearch
#
# Path to log files:
#
path.logs: /var/log/elasticsearch
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
#xpack.security.enabled: false
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 172.17.2.9
#
# Set a custom port for HTTP:
#
http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
discovery.zen.ping.unicast.hosts: ["172.17.2.9"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes:
#
# For more information, consult the zen discovery module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true

```

df -h :
```
Sys. de fichiers           Taille Utilisé Dispo Uti% Monté sur
/dev/mapper/vg_sys-lv_root   7,8G    5,2G  2,3G  70% /
devtmpfs                     3,9G       0  3,9G   0% /dev
tmpfs                        3,9G       0  3,9G   0% /dev/shm
tmpfs                        3,9G     28M  3,8G   1% /run
tmpfs                        3,9G       0  3,9G   0% /sys/fs/cgroup
/dev/sda1                   1014M    286M  729M  29% /boot
/dev/mapper/vg_sys-lv_var     50G     12G   36G  25% /var
/dev/mapper/vg_sys-lv_opt    4,8G    265M  4,3G   6% /opt
/dev/mapper/vg_sys-lv_home   976M    125M  784M  14% /home
tmpfs                        783M     12K  783M   1% /run/user/42
tmpfs                        783M       0  783M   0% /run/user/1129603191
tmpfs                        783M       0  783M   0% /run/user/1129604151
```

**Comment by pablotr9** [comment]
Hi @John33000 ,

Thanks for the output, I can see the Elasticsearch cluster name is `my-application`, could you please paste here  the output of Elasticsearch logs?
`tail -n 150 /var/log/elasticsearch/my-application.log`

**Comment by John33000** [comment]
I have nothing..

![image](https://user-images.githubusercontent.com/46779058/64960701-16282580-d894-11e9-8c41-fae79c7b9372.png)


If I delete index, the issue can be resolve ?

**Comment by John33000** [comment]
I found the log, there was not enought  of disk space for index rebuilt. I increased the disk and the elasticsearch was restart. In journalctl there was not error of space disk.

**Comment by pablotr9** [comment]
Hi @John33000 ,

Now that Elasticsearch is up and running, we should check its status and indices, so we can see if any of them is corrupted:
Could you please run these command and paste here the output?
- Check Elasticsearch indices
`curl 172.17.2.9:9200/_cat/indices`
- Check Cluster health:
`curl 172.17.2.9:9200/_cluster/health`

Regards,
Pablo Torres

**Comment by John33000** [comment]
Hi,

For : `curl 172.17.2.9:9200/_cat/indices `I have many indice in yellow and green so it's good
and for `curl 172.17.2.9:9200/_cluster/health`

`{"cluster_name":"my-application","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":878,"active_shards":878,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":535,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":62.13729653220099}`

How  I can save my database ? My server is backup, when I revert my server the index can be corrupted ? How I can backup index, database ? 

Regards,

**Comment by pablotr9** [comment]
Hi @John33000 ,

The reason of your corrupt indices was caused by reaching the disk usage threshold, to avoid that error you can increase the disk space or modify disk-based shard allocation settings, you can find more info in this link: [Disk-based shard allocation](https://www.elastic.co/guide/en/elasticsearch/reference/current/disk-allocator.html)

Regarding your question, you can take a snapshot of your Elasticsearch cluster data and then you can restore the snapshot into a Elasticsearch cluster using the restore API. I recommend you to read these Elastic docs to learn more about its capabilities and how to backup and restore your data in Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html

I can see your cluster status is yellow, and you have 535 unassigned shards (only 62% percent of shards are active).  If you want to fix the cluster status and need help in this process, please let us know so we can give you further assistance.

Kind regards,
Pablo Torres

**Comment by John33000** [comment]
Hi,

Thanks you for your help, yes I would like help for clean the shard, I think many of shards is useless.

**Comment by pablotr9** [comment]
Hi @John33000 ,

You are welcome, let's start finding out what is causing those unassigned shards, could you please paste here the output of the following commands:
- Check Elasticsearch indices (if the output is too big, paste here only the first 10-20 lines):
`curl 172.17.2.9:9200/_cat/indices`
- Check cluster allocation status:
`curl  172.17.2.9:9200/_cluster/allocation/explain?pretty`
- One more command that will give us information about the unassigned shards and explain why are these shards unassigned:
`curl -XGET  172.17.2.9:9200/_cat/shards?h=index,shard,prirep,state,unassigned.reason,node | grep -i unassigned`

Regards,
Pablo Torres

**Comment by John33000** [comment]
Hi,

For `curl 172.17.2.9:9200/_cat/indices` : 

```
green  open wazuh-monitoring-3.x-2019.05.29 AFtvfOVcQNCCJWBwqte6QQ 2 0      38      0 194.6kb 194.6kb
yellow open filebeat-6.8.0-2019.07.09       XRLlWOtGRHaMnjqBa-sX9g 5 1       0      0   1.2kb   1.2kb
yellow open filebeat-6.8.0-2019.07.17       J13sNlDXSSm5WOzXdGTAAw 5 1       0      0   1.2kb   1.2kb
green  open wazuh-monitoring-3.x-2019.05.20 Zv56eqgpSQy7NJEEZAglow 2 0      96      0 277.3kb 277.3kb
yellow open filebeat-6.8.0-2019.06.21       lZRnQuLvTMOARtl0aQ_MHQ 5 1       0      0   1.2kb   1.2kb
yellow open filebeat-6.8.0-2019.08.07       yW3FR1S2Qpq4_JervnTVEQ 5 1       0      0   1.2kb   1.2kb
green  open wazuh-alerts-3.x-2019.09.09     imjoioRtSC2g0kcaKkkInQ 3 0    4302      0   3.5mb   3.5mb
green  open .monitoring-es-6-2019.09.10     7UMlJGhURhq5JOC-91wTtA 1 0 4386128  21969   1.1gb   1.1gb
green  open wazuh-monitoring-3.x-2019.07.16 _6KOHMSVQ5ycK4iHQThinA 2 0     475      0 350.5kb 350.5kb
yellow open filebeat-6.8.0-2019.08.06       kShEy6HaTEWLDtZWGYHUkA 5 1       0      0   1.2kb   1.2kb
yellow open filebeat-6.8.0-2019.06.29       bpx-zHIPRwqW4OgT4uf5Aw 5 1       0      0   1.2kb   1.2kb
yellow open filebeat-6.8.0-2019.07.13       p8J_4DrkTxOm-T4Zs969Bw 5 1       0      0   1.2kb   1.2kb
yellow open filebeat-6.8.0-2019.08.10       OjB53SSYTkKKcRrJrW1IeA 5 1       0      0   1.2kb   1.2kb
green  open wazuh-monitoring-3.x-2019.06.07 1ojfQG3IR6Kyzf0liM94Ag 2 0      38      0 194.3kb 194.3kb
green  open .kibana_1                       W_6lfRmhS2G_l5tsyzJysA 1 0       3      0  48.1kb  48.1kb
green  open wazuh-monitoring-3.x-2019.07.13 BgN9vZW8QmWAfffdesqD6g 2 0     480      0 483.5kb 483.5kb
yellow open filebeat-6.8.0-2019.08.08       yEIToIiOTUGr0U8qOuI5jw 5 1       0      0   1.2kb   1.2kb
green  open wazuh-monitoring-3.x-2019.09.01 RA958_nZTC22U1M-o392kw 2 0     576      0   375kb   375kb
green  open .monitoring-es-6-2019.09.11     sG6tS1-9RNCl_5Uwhmea-g 1 0 4491695  13850   1.1gb   1.1gb
green  open wazuh-monitoring-3.x-2019.07.07 XrM-NoolSluCtBuyBzBiYA 2 0     384      0   337kb   337kb
yellow open filebeat-6.8.0-2019.09.06       unSDvxWJSly1BKp-WqsbVw 5 1       0      0   1.2kb   1.2kb
green  open wazuh-alerts-3.x-2019.08.20     S6zJsUzyQqaZmgovP43hGQ 3 0    3885      0     3mb     3mb
green  open wazuh-monitoring-3.x-2019.06.03 IcWK2vJ6SlyGGCXOyynmfg 2 0      56      0 347.9kb 347.9kb
green  open wazuh-monitoring-3.x-2019.06.30 0GzFPnadRHmmxYe9BnvTXw 2 0     288      0 209.1kb 209.1kb
green  open wazuh-monitoring-3.x-2019.08.12 963X1RM8RPGs5yhheJJ3pA 2 0     576      0 290.4kb 290.4kb
yellow open filebeat-6.8.0-2019.08.22       KEtKyNxVSQijIadY_xXXKw 5 1       0      0   1.2kb   1.2kb
green  open wazuh-alerts-3.x-2019.09.06     wijgr303TCeTC0hbwDfTDA 3 0    3951      0   3.1mb   3.1mb
yellow open filebeat-6.8.0-2019.07.10       oebECsZxT0GV7OjEBV2xGQ 5 1       0      0   1.2kb   1.2kb
green  open wazuh-monitoring-3.x-2019.07.05 f-2TJiHoQG-RGgPeTwuF4A 2 0     380      0 353.3kb 353.3kb
yellow open filebeat-6.8.0-2019.07.20       jBUehevzRe21R2xV7pgG1A 5 1       0      0   1.2kb   1.2kb
green  open wazuh-monitoring-3.x-2019.05.19 j8yB_SvVSHOcy2jicfAwkA 2 0      96      0 130.2kb 130.2kb
yellow open filebeat-6.8.0-2019.09.02       q3c_ZUPiSXKfCd9phoGyrA 5 1       0      0   1.2kb   1.2kb
yellow open filebeat-6.8.0-2019.06.12       VLSzfYsgR062uQrH2z82NQ 5 1       0      0   1.2kb   1.2kb
green  open wazuh-alerts-3.x-2019.09.17     4IrcAkH3RDSaee6Yjx0X3w 3 0    2222      0   3.8mb   3.8mb
yellow open filebeat-6.8.0-2019.06.05       ugswgCpNTf28isVLroxbog 5 1       0      0   1.2kb   1.2kb
green  open wazuh-monitoring-3.x-2019.08.27 oO0AbBiLRvSwEogpOluN6w 2 0     570      0 288.7kb 288.7kb
green  open wazuh-monitoring-3.x-2019.08.06 mUWhVxIWRi2MNm9ckWHb8A 2 0     402      0 229.1kb 229.1kb
green  open wazuh-monitoring-3.x-2019.08.25 BbvyJ7S2QQaY-sKDqX9UDg 2 0     576      0 322.9kb 322.9kb
yellow open filebeat-6.8.0-2019.06.19       4PiJd6lvQFGhaMj65n_2Og 5 1       0      0   1.2kb   1.2kb
green  open wazuh-monitoring-3.x-2019.06.08 h_H_t7agS8Wk3ZV1p9cRdQ 2 0      95      0 260.6kb 260.6kb
green  open wazuh-monitoring-3.x-2019.06.18 mgiPdPCoRAqneNeMhuwnZw 2 0     285      0 279.2kb 279.2kb
yellow open filebeat-6.8.0-2019.06.18       V20kUuXmRdG2LHUWmRTtOg 5 1       0      0   1.2kb   1.2kb

```
For : `curl 172.17.2.9:9200/_cluster/allocation/explain?pretty`
```
{
  "index" : "filebeat-6.8.0-2019.07.29",
  "shard" : 4,
  "primary" : false,
  "current_state" : "unassigned",
  "unassigned_info" : {
    "reason" : "CLUSTER_RECOVERED",
    "at" : "2019-09-16T13:56:49.747Z",
    "last_allocation_status" : "no_attempt"
  },
  "can_allocate" : "no",
  "allocate_explanation" : "cannot allocate because allocation is not permitted to any of the nodes",
  "node_allocation_decisions" : [
    {
      "node_id" : "GcnprKI4QDifzKuNsP2qiA",
      "node_name" : "GcnprKI",
      "transport_address" : "172.17.2.9:9300",
      "node_attributes" : {
        "ml.machine_memory" : "8201719808",
        "xpack.installed" : "true",
        "ml.max_open_jobs" : "20",
        "ml.enabled" : "true"
      },
      "node_decision" : "no",
      "deciders" : [
        {
          "decider" : "same_shard",
          "decision" : "NO",
          "explanation" : "the shard cannot be allocated to the same node on which a copy of the shard already exists [[filebeat-6.8.0-2019.07.29][4], node[GcnprKI4QDifzKuNsP2qiA], [P], s[STARTED], a[id=VAr-Bj4xTIevbkl-IuO7qA]]"
        }
      ]
    }
  ]
}
```
And for `curl -XGET 172.17.2.9:9200/_cat/shards?h=index,shard,prirep,state,unassigned.reason,node | grep -i unassigned`

They are many filebeat unssigned from June, I suppose we go to delete the shards of June ?

**Comment by pablotr9** [comment]
Hi @John33000 ,

Wazuh indices (wazuh-alerts-* and wazuh-monitoring-*), indeed the problem is with `filebeat-*` indices as they are being created daily with 5 shards and 1 replicas. Are you monitoring any other file with Filebeat? (apart from our `/var/ossec/logs/alerts/alerts.json`)
Could you please share your `filebeat.yml`?  This file can be found here `/etc/filebeat/filebeat.yml`

Regards,
Pablo Torres

**Comment by John33000** [comment]
Hi @pablotr9 

```
filebeat:
 prospectors:
  - type: log
    paths:
     - "/var/ossec/logs/alerts/alerts.json"
    document_type: json
    json.message_key: log
    json.keys_under_root: true
    json.overwrite_keys: true

output:
 logstash:
   # The Logstash hosts
   hosts: ["172.17.2.9:5000"]
#   ssl:
#     certificate_authorities: ["/etc/filebeat/logstash.crt"

output:
 elasticsearch:
  hosts: ["http://172.17.2.9:9200"]
  username: "elastic"
  password: "<PASSWORD>"
setup.kibana:
  host: "http://172.17.2.9"
```

I need to delete indices `wazuh-alerts-*` from June no ? and `wazuh-monitoring` from July ?

Regards

**Comment by pablotr9** [comment]
Hi @John33000 ,
No, you shouldn't delete any index if you are not sure of it. In your case, you should reduce the number of replicas of your old `filebeat-*` indices as they have 5 shards and 1 replica shard.
Wazuh alerts and Wazuh monitoring indices contains all alerts generated by Wazuh, if you delete these indices the data will be removed permanently. You should only delete indices that you are sure you don't need them anymore, for example indices older than 1month, but it just depends on your specific needs.

If you want to reduce the number of replica shards, there are alternatives to permanently deleting indices, e.g:
- Close/Open indices (https://www.elastic.co/guide/en/elasticsearch/reference/6.8/indices-open-close.html) . A closed index is blocked for read/write operations, closing an index does not mean that the index is going to be deleted and these closed indices can be reopened again. 


An easy solution to fix your cluster yellow status (without removing any indices):
1. Reduce number of replicas:
`curl -XPUT '172.17.2.9:9200/*/_settings' -H 'Content-Type: application/json' -d '{ "index": { "number_of_replicas": "0" } }'
`
2. Ensure that routing allocation is enabled:
`curl -XPUT '172.17.2.9:9200/_cluster/settings'  -H 'Content-Type: application/json'  -d '{ "transient": { "cluster.routing.allocation.enable" : "all" } }'
`
3. Restart Elasticsearch:
`systemctl restart elasticsearch`

Wait some minutes and launch a watcher to check the `active_shards_percent_as_number` value, you should see that the value is increasing until 100%:
`watch -n0 'curl -s 172.17.2.9:9200/_cluster/health?pretty | grep "active_shards_percent"'`

Let me know if it helps,
Best regards,
Pablo Torres

**Comment by John33000** [comment]
In one previous issue, you or your teamate, help me to do this : 

```
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 30 days (based on index name), for wazuh-alerts-3.x-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: wazuh-alerts-3.x-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 30
```
I want only indice of filebeat, wazuh, elastic 1 month, July, June, we can delete this I'm sure. I want only 1 month.

**Comment by pablotr9** [comment]
Hi, 

In that case, you can manually delete June-July indices with these requests:
- Delete Filebeat indices:
June
` curl -XDELETE http://172.17.2.9:9200/filebeat-6.8.3-2019.06*`
July
` curl -XDELETE http://172.17.2.9:9200/filebeat-6.8.3-2019.07*`

- Delete Wazuh-alerts indices:
June
`curl -XDELETE http://172.17.2.9:9200/wazuh-alerts-3.x-2019.06*`
July
`curl -XDELETE http://172.17.2.9:9200/wazuh-alerts-3.x-2019.07*`

- Delete Wazuh-monitoring indices:
June
`curl -XDELETE http://172.17.2.9:9200/wazuh-monitoring-3.x-2019.06*`
July
`curl -XDELETE http://172.17.2.9:9200/wazuh-monitoring-3.x-2019.07*`

Regards,
Pablo Torres

**Comment by John33000** [comment]
Okey, thank you, I can add this in my curator ? 
Like : 
  ```
2:
    action: delete_indices
    description: >-
      Delete indices older than 30 days (based on index name), for wazuh-alerts-3.x-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: wazuh-monitoring-3.x-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 30

```
And this for filebeat too ?

Thanks

**Comment by pablotr9** [comment]
Hi @John33000 ,

Yes, the Curator action file was only removing `wazuh-alerts*` indices, if you want to automatically remove filebeat and Wazuh monitoring indices this should be the Curator action file:

- Edit  `~/.curator/delete_indices.yaml`:
```
actions:
  1:
    action: delete_indices
    description: >-
      Delete indices older than 30 days (based on index name), for wazuh-alerts-3.x-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: wazuh-alerts-3.x-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 30
  2:
    action: delete_indices
    description: >-
      Delete indices older than 30 days (based on index name), for wazuh-monitoring-3.x-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: wazuh-monitoring-3.x-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 30
  3:
    action: delete_indices
    description: >-
      Delete indices older than 30 days (based on index name), for filebeat-6.8.0-
      prefixed indices. Ignore the error if the filter does not result in an
      actionable list of indices (ignore_empty_list) and exit cleanly.
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: filebeat-6.8.0-
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 30

```

Regards,
Pablo Torres
