### ISSUE TITLE
Fix dev-flask-poc after merges from 3.10 and 3.11

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#3986]
Hello team,

This issue aims to fix new API development branch `dev-flask-poc` after merges from 3.10 and 3.11. 

The results from integration tests suggest some of the introduced changes affect the new development.

Best regards,

David J. Iglesias

Tasks:
- [x] Active Response
 - Results: 
   - 1 failed, 1 passed, 1 warnings in 0.47 seconds
- [x] Agents
 - Results: 
   - 7 passed, 1 warnings in 0.85 seconds
   - 113 passed, 1 skipped, 1 warnings in 6.49 seconds
   - 5 passed, 1 warnings in 0.69 seconds
   - 7 passed, 1 skipped, 1 warnings in 10.98 seconds
- [x] CIS-CAT
 - Results:
   - 11 passed, 1 warnings in 2.34 seconds
- [x] Cluster
 - Results:
   - 56 passed, 2 warnings in 7.59 seconds
- [x] Decoders
 - Results:
   - 23 passed, 1 warnings in 3.68 seconds
- [x] Default
 - Results:
   - 1 passed, 1 warnings in 2.42 seconds
- [x] Experimental
  - Not merged yet in dev-flask-poc #2957
- [x] Lists
 - Results:
   - 3 passed, 1 warnings in 1.31 seconds
- [x] Manager
 - Results:
   - 31 passed, 1 warnings in 9.03 seconds
- [x] Overview
 - Results:
   - 1 passed, 1 warnings in 0.41 seconds
- [x] Rules
 - Results:
   - 10 passed, 7 warnings in 15.73 seconds
- [x] SCA
 - Results:
   - 4 failed, 4 passed, 1 warnings in 3.00 seconds
- [x] Security
 - Results:
   - 1 passed, 1 warnings in 0.75 seconds
   - 1 passed, 1 warnings in 0.59 seconds
   - 2 passed, 1 warnings in 0.40 seconds
   - 1 passed, 1 warnings in 0.40 seconds
   - 2 passed, 1 warnings in 0.58 seconds
   - 3 passed, 1 warnings in 0.84 seconds
   - 4 passed, 1 warnings in 0.85 seconds
   - 5 passed, 2 warnings in 0.73 seconds
- [x] Syscheck
 - Results:
   - 37 passed, 1 warnings in 4.65 seconds
- [x] Syscollector
 - Results:
   - 160 passed, 1 warnings in 12.77 seconds

**Comment by davidjiglesias** [comment]
Active Response test error:

**Comment by davidjiglesias** [comment]
### **Cluster test error:** 
```
Source test stage (line 1608):
  - name: Request {node_id}
    request: &get_cluster_logs
      url: "{protocol:s}://{host:s}:{port:d}/cluster/{node_id}/logs"
      method: GET
      headers:
        Authorization: "Bearer {test_login_token}"
    response:
      status_code: 200
      body:
        data:
          items: !anything
          totalItems: !anyint


Formatted stage:
  name: Request worker2
  request:
    headers:
      Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YXp1aCIsImlhdCI6MTU2ODg5MDAxNywiZXhwIjoxNTY4ODkxODE3LCJzdWIiOiJ3YXp1aCIsInJiYWNfcG9saWNpZXMiOnt9LCJtb2RlIjp0cnVlfQ.rTtjjt54PeUiIU5mbsTv5FbBzDNxP8Yk_HHfwwugkC8
    method: GET
    url: 'http://localhost:55000/cluster/worker2/logs'
  response:
    body:
      data:
        items: !anything ''
        totalItems: !anyint ''
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Request {node_id}' failed:
    - Status code was 500, expected 200
    - Value mismatch in body: Structure of returned data was different than expected  - Extra keys in response: {'status', 'detail', 'title', 'type'} - Keys missing from response: {'data'} (expected = '{'data': {'items': <tavern.util.loader.AnythingSentinel object at 0x7f4fd07f4940>, 'totalItems': <tavern.util.loader.IntSentinel object at 0x7f4fd05c8630>}}' (type = <class 'dict'>), actual = '{'detail': "'2019-09-19 10:46:55' is not a 'date-time'\n\nFailed validating 'format' in schema['allOf'][1]['properties']['data']['allOf'][1]['properties']['items']['items']['properties']['timestamp']:\n    {'format': 'date-time', 'type': 'string'}\n\nOn instance['data']['items'][0]['timestamp']:\n    '2019-09-19 10:46:55'", 'status': 500, 'title': 'Response body does not conform to specification', 'type': 'about:blank'}' (type = <class 'dict'>))
```
