### ISSUE TITLE
Upgrade Elasticsearch/Kibana from 6.8 to 7.0

### ISSUE THREAD

**Issue by John33000** [wazuh/wazuh#4044]
Hi,

I update elasticsearch and filebeat to 7.4.0 and Kibana to 7.3.2. 
But I have an error with filebeat :

```
oct. 02 17:20:47  systemd[1]: filebeat.service: main process exited, code=exited, status=1/FAILURE
oct. 02 17:20:47  systemd[1]: Unit filebeat.service entered failed state.
oct. 02 17:20:47 systemd[1]: filebeat.service failed.
oct. 02 17:20:47  systemd[1]: filebeat.service holdoff time over, scheduling restart.
oct. 02 17:20:47  systemd[1]: Stopped Filebeat sends log files to Logstash or directly to Elasticsearch..
oct. 02 17:20:47 systemd[1]: start request repeated too quickly for filebeat.service
oct. 02 17:20:47  systemd[1]: Failed to start Filebeat sends log files to Logstash or directly to Elasticsearch..
oct. 02 17:20:47 systemd[1]: Unit filebeat.service entered failed state.
oct. 02 17:20:47  systemd[1]: filebeat.service failed.

```

I want Filebeat sends directly to Elasticsearch and remove Logstash.

```
filebeat.yml : 
filebeat:
 prospectors:
  - type: log
    paths:
     - "/var/ossec/logs/alerts/alerts.json"
    document_type: json
    json.message_key: log
    json.keys_under_root: true
    json.overwrite_keys: true

#output:
# logstash:
   # The Logstash hosts
#   hosts: ["<SERVER>:5000"]
#   ssl:
#     certificate_authorities: ["/etc/filebeat/logstash.crt"

output.elasticsearch.hosts: ['<SERVER>:9200']

output:
 elasticsearch:
  hosts: ["<SERVER>:9200"]
  username: "elastic"
  password: "<elastic>"
setup.kibana:
  host: "SERVER"
 
```

Can you help me again please

Best Regards
