### ISSUE TITLE
The alerts from renaming a folder in Whodata Windows doesn't prompt properly in the redesign of FIM

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh#4321]
|Related issue|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|---|
|https://github.com/wazuh/wazuh/issues/3319| 3.11 | Syscheck | Agent | Sources | Windows |

Since Wazuh version 3.9.1 (https://github.com/wazuh/wazuh/pull/2888), Syscheck will show 2 alerts for each file (Remove and add) after renaming a monitored subfolder. Those alerts have audit information and are prompt in real-time.

```
** Alert 1575381928.436000: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2019 Dec 03 14:05:28 (win-3.10) any->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File 'c:\users\pablo\desktop\test-whodata\cambio_de_nombre\new text document.txt' was deleted.

Attributes:
 - (Audit) User name: pablo
 - (Audit) Process id: 2144
 - (Audit) Process name: C:\Windows\explorer.exe

** Alert 1575381928.436436: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2019 Dec 03 14:05:28 (win-3.10) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File 'c:\users\pablo\desktop\test-whodata\name_change\new text document.txt' was added.

Attributes:
 - Size: 0
 - Permissions: SYSTEM (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Administrators (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, pablo (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes
 - Date: Tue Dec  3 13:28:11 2019
 - User: pablo (S-1-5-21-1087345056-2530757087-3950806551-1000)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - File attributes: ARCHIVE

```

After the redesign of FIM, those changes are detected during the scheduled scan, and the alerts don't show any audit information.
The function `w_update_sacl` is unused in the redesign of FIM and it was the function that enables this behaviour.

```
** Alert 1575381240.419980: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2019 Dec 03 13:54:00 (windows) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File 'c:\users\pablo\desktop\poc_replace\namechanged\rootcheck.template' added
Mode: scheduled

Attributes:
 - Size: 51
 - Permissions: SYSTEM (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Administradores (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, pablo (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes
 - Date: Mon Oct 14 07:34:37 2019
 - User: pablo (S-1-5-21-4181897701-2688429609-2145492800-1001)
 - MD5: 24c1f37a73d24835fa9cdf9a8b6c7ab5
 - SHA1: 445c7a1b80b9778e0a7209ae0c4df599ab527d29
 - SHA256: 7b749eafcf988cc2dd41b765579493fe5123e36c0e035d38f3593a93cb979159
 - File attributes: ARCHIVE

** Alert 1575381240.421142: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2019 Dec 03 13:54:00 (windows) any->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File 'c:\users\pablo\desktop\poc_replace\name_changed\rootcheck.template' deleted
Mode: scheduled

Attributes:
 - Size: 320
 - Permissions: SYSTEM (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Administradores (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, pablo (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes
 - Date: Mon Oct 14 07:34:56 2019
 - User: pablo (S-1-5-21-4181897701-2688429609-2145492800-1001)
 - MD5: 929cbc238a06e0575e7401455fe565ca
 - SHA1: 0413085e26973d1d048f27b8f8c9640caa4c86cb
 - SHA256: 4cd11fcc5434b8c7653b48c0051f7cfa36016f5101453d50e7ec1ab5fe253388
 - File attributes: ARCHIVE
```
