### ISSUE TITLE
Fim does not monitor in Windows with other encodings

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#4612]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12 | Fim | Windows Agent | Packages/Sources | OS version |

Hello team,

File integrity monitoring does not work properly with some encodings.

## Description
When monitoring files with some encodings, the folder path is added but no alerts are generated. Then, we see an error that we can't monitor that path.
```
2020/02/18 10:50:24 ossec-agent: INFO: (6003): Monitoring directory: 'c:\testr\?³?µ???±', with options 'perm | size | owner | group | md5sum | sha1sum | sha256sum | realtime | mtime | inode | attributes'.

2020/02/18 10:50:44 ossec-agent: ERROR: (6617): Unable to add directory to real time monitoring: 'c:\testr\?³?µ???±'.
```

## How to reproduce the error

With the following configuration in the `ossec.conf` file:

``` xml
  <syscheck>
	<disabled>no</disabled>
	<directories check_all="yes" realtime="yes">C:\testR\Ξ³ΞµΞΉΞ±</directories>
  </syscheck>
```
We start Wazuh and see the following message:
```
2020/02/18 10:50:24 ossec-agent: INFO: (6003): Monitoring directory: 'c:\testr\?³?µ???±', with options 'perm | size | owner | group | md5sum | sha1sum | sha256sum | realtime | mtime | inode | attributes'.
```
And later we see the following error message if it's version 3.11:
```
2020/02/18 10:50:44 ossec-agent: ERROR: (6617): Unable to add directory to real time monitoring: 'c:\testr\?³?µ???±'.
```

## Expected behavior
When we monitor a file with another encoding, it should be monitored without a problem.

With the following example configuration:
``` xml
<syscheck>
	<disabled>no</disabled>
	<directories check_all="yes" whodata="yes">C:\test\Ξ³ΞµΞΉΞ±</directories>
  </syscheck>
```
When creating, modifying or deleting a file in that folder, an alert should be shown:
```
# echo > C:\test\Ξ³ΞµΞΉΞ±\hello.txt

** Alert 1582025180.2403656: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 18 12:26:20 cabrera-Machine->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File 'C:\test\Ξ³ΞµΞΉΞ±\hello.txt' added
Mode: whodata

Attributes:
 - Size: 1
 - Permissions: rw-r--r--
 - Date: Tue Feb 18 12:26:19 2020
 - Inode: 8912901
 - User: root (0)
 - Group: root (0)
 - MD5: 68b329da9893e34099c7d8ad5cb9c940
 - SHA1: adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
 - SHA256: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
 - (Audit) User name: root
 - (Audit) Audit name: cabrera
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 4868
 - (Audit) Process name: /bin/bash
```
