### ISSUE TITLE
Lost alerts when modifying hard links

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#4648]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| fim-rework | Syscheck | Manager/Agent | Packages/Sources | OS version |

Hello team, I found another unexpected behavior when the content of a hard link is modified. Deeper information:

## Description

When a hard link is modified, only an alert is generated for the modified file, and not for the linked file. 

If we have the file `regular` and the link `link`, when modifying `regular` we see the following output in the `alerts.log`:
```
** Alert 1582286798.525832: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 21 13:06:38 cabrera-Machine->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/testdir/regular' modified
Mode: scheduled
Changed attributes: size,mtime,md5,sha1,sha256
Size changed from '6' to '12'
Old modification time was: '1582286731', now it is '1582286779'
Old md5sum was: 'fde19fa49661fb638dac5f30ab0f661e'
New md5sum is : '8262bdbdfb13596ee30146637163c8f1'
Old sha1sum was: '63b76b20dd24f5a4104e9c412be1ba8e71b6b05c'
New sha1sum is : '33135f722214f215b3f5b2b84c21ab8ee23d17e1'
Old sha256sum was: '3000dfe470d85e4b32dc78f083da866f24d6183c48d83b42b36da98e64701ade'
New sha256sum is : '793c40ce8729a3dafb7d2e440cf1d7bddb3fc20a461d2208c8fa44677f248aa7'

Attributes:
 - Size: 12
 - Permissions: rw-r--r--
 - Date: Fri Feb 21 13:06:19 2020
 - Inode: 5898242
 - User: root (0)
 - Group: root (0)
 - MD5: 8262bdbdfb13596ee30146637163c8f1
 - SHA1: 33135f722214f215b3f5b2b84c21ab8ee23d17e1
 - SHA256: 793c40ce8729a3dafb7d2e440cf1d7bddb3fc20a461d2208c8fa44677f248aa7
```
and another alert should be generated for `link`

## How to reproduce the error

The following configuration in the `ossec.conf` file:
``` xml
  <syscheck>
	<disabled>no</disabled>
        <frequency>30</frequency>
	<directories check_inode="yes">/testdir</directories></syscheck>
  </syscheck>
```
We create a file in the monitored directory: 
``` bash
echo > /testdir/regular
```
And we created two hard links to that file:
``` python
import os
os.link("regular", "link0")
os.link("regular", "link1")
```
Once the frequency time has passed, the following added alerts are generated:
```
** Alert 1582286456.520288: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 21 13:00:56 cabrera-Machine->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/testdir/regular' added
Mode: scheduled

Attributes:
 - Size: 5
 - Permissions: rw-r--r--
 - Date: Fri Feb 21 13:00:38 2020
 - Inode: 5898242
 - User: root (0)
 - Group: root (0)
 - MD5: 916f4c31aaa35d6b867dae9a7f54270d
 - SHA1: 63bbfea82b8880ed33cdb762aa11fab722a90a24
 - SHA256: 133ee989293f92736301280c6f14c89d521200c17dcdcecca30cd20705332d44

** Alert 1582286549.520877: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 21 13:02:29 cabrera-Machine->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/testdir/link0' added
Mode: scheduled

Attributes:
 - Size: 5
 - Permissions: rw-r--r--
 - Date: Fri Feb 21 13:00:38 2020
 - Inode: 5898242
 - User: root (0)
 - Group: root (0)
 - MD5: 916f4c31aaa35d6b867dae9a7f54270d
 - SHA1: 63bbfea82b8880ed33cdb762aa11fab722a90a24
 - SHA256: 133ee989293f92736301280c6f14c89d521200c17dcdcecca30cd20705332d44

** Alert 1582286549.521464: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 21 13:02:29 cabrera-Machine->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/testdir/link1' added
Mode: scheduled

Attributes:
 - Size: 5
 - Permissions: rw-r--r--
 - Date: Fri Feb 21 13:00:38 2020
 - Inode: 5898242
 - User: root (0)
 - Group: root (0)
 - MD5: 916f4c31aaa35d6b867dae9a7f54270d
 - SHA1: 63bbfea82b8880ed33cdb762aa11fab722a90a24
 - SHA256: 133ee989293f92736301280c6f14c89d521200c17dcdcecca30cd20705332d44
```
And if we modified the file `regular`, only see one alert in output of `alerts.log` file:
```
** Alert 1582286581.522051: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 21 13:03:01 cabrera-Machine->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/testdir/regular' modified
Mode: scheduled
Changed attributes: size,mtime,md5,sha1,sha256
Size changed from '5' to '11'
Old modification time was: '1582286438', now it is '1582286576'
Old md5sum was: '916f4c31aaa35d6b867dae9a7f54270d'
New md5sum is : 'bbdd7b3e3c6bb0f797462b65f8b76bda'
Old sha1sum was: '63bbfea82b8880ed33cdb762aa11fab722a90a24'
New sha1sum is : '0a99729c41d2006d08f4337b57e2dcdc93b788e0'
Old sha256sum was: '133ee989293f92736301280c6f14c89d521200c17dcdcecca30cd20705332d44'
New sha256sum is : '0ebfb93c62f35ca0382b7ebe7a39b166de774b67d8090d3a8c21b213213113dd'
```
When there should have been three alerts, one for the `regular` file and two for its hard links.

## Expected behavior
When the `regular` file is modified, a modification alert should be shown for each of its hard links.

The following configuration in the `ossec.conf` file:
``` xml
  <syscheck>
	<disabled>no</disabled>
        <frequency>30</frequency>
	<directories check_inode="yes">/testdir</directories></syscheck>
  </syscheck>
```
We create a file in the monitored directory: 
``` bash
echo > /testdir/regular
```
And we created two hard links to that file:
``` python
import os
os.link("regular", "link0")
os.link("regular", "link1")
```
Once the frequency time has passed and the added alerts are generated, we modify the 'regular' file:
``` bash
echo "test" > /testdir/regular
```
And three alerts should be generated, one for the file and two more for its hard links:
```
** Alert 1582288990.534549: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 21 13:43:10 cabrera-Machine->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/testdir/regular' modified
Mode: scheduled
Changed attributes: size,mtime,md5,sha1,sha256
Size changed from '1' to '7'
Old modification time was: '1582288898', now it is '1582288965'
Old md5sum was: '68b329da9893e34099c7d8ad5cb9c940'
New md5sum is : 'b747e8172ca26ae6fcd5cc87d2c0f5ee'
Old sha1sum was: 'adc83b19e793491b1c6ea0fd8b46cd9f32e592fc'
New sha1sum is : 'f8a05a4784203b5b3665602de29a652ce89b2290'
Old sha256sum was: '01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b'
New sha256sum is : '6245f381b8b5260352854cd7c8103f0d5864f84ad9a8826f87672175801fc0f0'
Attributes:
 - Size: 7
 - Permissions: rw-r--r--
 - Date: Fri Feb 21 13:42:45 2020
 - Inode: 5898242
 - User: root (0)
 - Group: root (0)
 - MD5: b747e8172ca26ae6fcd5cc87d2c0f5ee
 - SHA1: f8a05a4784203b5b3665602de29a652ce89b2290
 - SHA256: 6245f381b8b5260352854cd7c8103f0d5864f84ad9a8826f87672175801fc0f0
** Alert 1582288990.535677: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 21 13:43:10 cabrera-Machine->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/testdir/link0' modified
Mode: scheduled
Changed attributes: size,mtime,md5,sha1,sha256
Size changed from '1' to '7'
Old modification time was: '1582288898', now it is '1582288965'
Old md5sum was: '68b329da9893e34099c7d8ad5cb9c940'
New md5sum is : 'b747e8172ca26ae6fcd5cc87d2c0f5ee'
Old sha1sum was: 'adc83b19e793491b1c6ea0fd8b46cd9f32e592fc'
New sha1sum is : 'f8a05a4784203b5b3665602de29a652ce89b2290'
Old sha256sum was: '01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b'
New sha256sum is : '6245f381b8b5260352854cd7c8103f0d5864f84ad9a8826f87672175801fc0f0'
Attributes:
 - Size: 7
 - Permissions: rw-r--r--
 - Date: Fri Feb 21 13:42:45 2020
 - Inode: 5898242
 - User: root (0)
 - Group: root (0)
 - MD5: b747e8172ca26ae6fcd5cc87d2c0f5ee
 - SHA1: f8a05a4784203b5b3665602de29a652ce89b2290
 - SHA256: 6245f381b8b5260352854cd7c8103f0d5864f84ad9a8826f87672175801fc0f0
** Alert 1582288990.536803: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 21 13:43:10 cabrera-Machine->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/testdir/link1' modified
Mode: scheduled
Changed attributes: size,mtime,md5,sha1,sha256
Size changed from '1' to '7'
Old modification time was: '1582288898', now it is '1582288965'
Old md5sum was: '68b329da9893e34099c7d8ad5cb9c940'
New md5sum is : 'b747e8172ca26ae6fcd5cc87d2c0f5ee'
Old sha1sum was: 'adc83b19e793491b1c6ea0fd8b46cd9f32e592fc'
New sha1sum is : 'f8a05a4784203b5b3665602de29a652ce89b2290'
Old sha256sum was: '01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b'
New sha256sum is : '6245f381b8b5260352854cd7c8103f0d5864f84ad9a8826f87672175801fc0f0'
Attributes:
 - Size: 7
 - Permissions: rw-r--r--
 - Date: Fri Feb 21 13:42:45 2020
 - Inode: 5898242
 - User: root (0)
 - Group: root (0)
 - MD5: b747e8172ca26ae6fcd5cc87d2c0f5ee
 - SHA1: f8a05a4784203b5b3665602de29a652ce89b2290
 - SHA256: 6245f381b8b5260352854cd7c8103f0d5864f84ad9a8826f87672175801fc0f0
```
