### ISSUE TITLE
FIM v2.0: Deleted events being sent as scheduled instead of whodata

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh#4663]
| Wazuh version | Component        | Install type          | Install method        |
|----------------|-----------------|-----------------|--------------------|
| 3.12                   | ossec-syscheck | Manager/Agent  | Packages/Sources |

## Bug description

When moving a folder with a file in it from a monitored directory to a non monitored directory or when moving a folder from a subfolder in a monitored directory to the monitored directory itself, the `deleted` event appears as `scheduled` instead of `whodata`, losing also the `audit` information.

## Alert example

```
** Alert 1582708903.12460: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 26 09:21:43 agentUbuntu19->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File '/testdir2/subdir2/regular2' deleted
Mode: scheduled

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Wed Feb 26 09:21:40 2020
 - Inode: 1029503
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

Mode should be `whodata` and it should include `Audit` information.

## Remediation

In `fim_db.c`, `deleted` events are hardcoded to be in `scheduled` mode:
https://github.com/wazuh/wazuh/blob/c7a2c86919bdb59949ced64987af1f85e2083dc5/src/syscheckd/fim_db.c#L1117-L1118  

This should be parametrized.

**Comment by jesusjimsa** [comment]
This is happening also in `realtime`:

```
** Alert 1582718371.12727: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 26 11:59:31 agentUbuntu19->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File '/testdir/f2/f1/file_1' deleted
Mode: scheduled

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Wed Feb 26 07:53:55 2020
 - Inode: 1024004
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

** Alert 1582718391.13307: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 26 11:59:51 agentUbuntu19->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/testdir/f2/f1/file_1' added
Mode: real-time

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Wed Feb 26 07:53:55 2020
 - Inode: 1024004
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```
