### ISSUE TITLE
FIM: loss of delete alerts in Windows Whodata

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#4670]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| fim-rework-sqlite | Wazuh component | Win Agent | Packages/Sources | OS version |

Hello team, I found another unexpected behavior when a file is deleted in a folder monitored with Whodata.  Deeper information:

## Description
When we delete on file in a folder monitored with Whodata, an alert is generated or not depending on the type of deletion:
- If we delete the file with 'supr' by sending it to the recycle bin, the delete alert is generated.
- If we delete the file definitively with `shift + supr` or the `del` command from the windows console, no delete alert is generated.

## How to reproduce the error
The following configuration in the `ossec.conf` file:
``` xml
  <syscheck>
	<disabled>no</disabled>
        <frequency>30</frequency>
	<directories check_all="yes" whodata="yes">c:\testdir\</directories></syscheck>
  </syscheck>
```
The 'test.txt' file is created inside the monitored folder, generating the following alert:
```
** Alert 1582726583.34433468: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 26 14:16:23 (windows7) 172.19.0.1->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File 'c:\testdir\test.txt' added
Mode: whodata
Attributes:
 - Size: 0
 - Permissions: Administradores (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, SYSTEM (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Usuarios (allowed): read_control|synchronize|read_data|read_ea|execute|read_attributes, Usuarios autentificados (allowed): delete|read_control|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes
 - Date: Wed Feb 26 14:16:19 2020
 - User: Administradores (S-1-5-32-544)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - File attributes: ARCHIVE
 - (Audit) User name: jmv74211
 - (Audit) Process id: 2332
 - (Audit) Process name: C:\Windows\explorer.exe
```
If the file is deleted with the `supr` key or `right click - > delete`, the next alert is generated:
```
** Alert 1582726701.34436060: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2020 Feb 26 14:18:21 (windows7) 172.19.0.1->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File 'c:\testdir\test.txt' deleted
Mode: whodata
Attributes:
 - Size: 0
 - Permissions: Administradores (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, SYSTEM (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Usuarios (allowed): read_control|synchronize|read_data|read_ea|execute|read_attributes, Usuarios autentificados (allowed): delete|read_control|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes
 - Date: Wed Feb 26 14:16:19 2020
 - User: Administradores (S-1-5-32-544)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - File attributes: ARCHIVE
 - (Audit) User name: jmv74211
 - (Audit) Process id: 2332
 - (Audit) Process name: C:\Windows\explorer.exe
```
But if the file is deleted with the key combination `shift + supr` or with the `del` command in the windows console, no alert is generated.

This happens because the EventID of the rule that generates the audit is different in each case:
- If we delete the file with 'supr' by sending it to the recycle bin, the EventID is `4663`.
- If we delete the file definitively with `shift + supr` or the `del` command from the windows console, the EventID is `4659`.

Currently, in Wazuh, EventID `4659` is not contemplated, so deletion alerts cannot be generated with that ID.
