### ISSUE TITLE
Download shared configuration files

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#468]
Add an option to make the agent get configuration files from an URL.

We will split this task into some subtasks:

- [x] Shared function to download a file from an HTTP URL.

I propose to create a function like:
```c
int wurl_get_http(const char * url, const char * dest);
```

Write this function into a file like `src/shared/url.c`
Declare it into a file like `src/headers/url.h`

- [x] Shared function to download a file from an HTTPS URL.

The same function but using HTTPS, and a switching function to abstract both protocols:

```c
int wurl_get_https(const char * url, const char * dest);
int wurl_get(const char * url, const char * dest);
```

- [x] Trap file to list files to be downloaded.

I suggest to use a hidden file with name `etc/shared/files.yml`, with a content such:
```yml
group-a:
  files:
    name: test_profile
    agent.conf: http://example.com/agent.conf
    rootcheck.txt: https://example.com/rootcheck.txt
  poll: 60
  
group-b:
  files:
    name: test_profile
    agent.conf: http://otherexample.com/agent.conf
    rootcheck.txt: https://otherexample.com/rootcheck.txt
  poll: 120
```

The `poll` time must be greater or equal to the internal option `remoted.shared_reload`.

You may want to use an external library to parse YAML, like https://github.com/yaml/libyaml.

- [x] Catch and validate merged files.

If any of the files has name "merged.mg", do not download any other file. Validate the downloaded file. If the file is not valid, log an error and create an empty file (containing only the header:

```
#group\n
```

The function [`MergeFiles()`](https://github.com/wazuh/wazuh/blob/master/src/shared/file_op.c#L711) may inspire you.
