### ISSUE TITLE
Support for aws inspector

### ISSUE THREAD

**Issue by rverma-jm** [wazuh/wazuh#5103]
In place of wazuh agent, is it possible to digest aws inspector reports for wazuh findings?

**Comment by Selutario** [comment]
Hello @rverma-jm,

I've been doing some research and it seems feasible to carry out your suggestion. It would be necessary to create a [custom SSM document](https://docs.aws.amazon.com/systems-manager/latest/userguide/create-ssm-doc.html) that specifies the agent installation steps, using the [unattended-installation](https://documentation.wazuh.com/3.12/user-manual/reference/unattended-installation.html#agent) option.

It can be a useful development for the rest of the community. Therefore we will try to put it on our roadmap and study a solution more deeply.

Thank you very much for the suggestion and for participating in the community. We will inform in this same issue of any future development.

Best regards,
Selu.

**Comment by kevpatts** [comment]
Here's one that works pretty well for me:
`---
schemaVersion: '2.2'
description: "Install Wazuh Agent"
parameters:
  serverAddress:
    type: String
    description: This is the address the agent uses to communicate with the server. Enter an IP address or a fully qualified domain name (FQDN).
    default: ''
  groupName:
    type: String
    description: This is the address the group that the agent will be joined into.
    default: ''
  useInstanceID:
    type: String
    description: Recommended. If True the instance ID will be used to identify the endpoint in Wazuh. If set to false the server hostname is used instead.
    default: 'True'
    allowedValues:
    - "True"
    - "False"
  purgeExistingWazuhPackage:
    type: String
    description: Recommended. This purges any partially installed or failed installations of the wazuh-agent package.
    default: 'True'
    allowedValues:
    - "True"
    - "False"
mainSteps:
- action: aws:runShellScript
  name: updateRepositories
  inputs:
    runCommand:
    - "apt-get update"
- action: aws:runShellScript
  name: purgeExistingAgent
  precondition:
    StringEquals:
    - "{{ purgeExistingWazuhPackage }}"
    - "True"
  inputs:
    runCommand:
    - "dpkg --purge wazuh-agent"
- action: aws:runShellScript
  name: downloadPackage
  inputs:
    runCommand:
    - "wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.8.0-1_amd64.deb"
- action: aws:runShellScript
  name: installWithInstanceID
  precondition:
    StringEquals:
    - "{{ useInstanceID }}"
    - "True"
  inputs:
    runCommand:
    - "AWS_INSTANCE_ID=`curl -s http://169.254.169.254/latest/meta-data/instance-id`; WAZUH_MANAGER='{{ serverAddress }}' WAZUH_AGENT_GROUP='{{ groupName }}' WAZUH_AGENT_NAME=$AWS_INSTANCE_ID dpkg -i wazuh-agent_4.8.0-1_amd64.deb"
- action: aws:runShellScript
  name: installWithoutInstanceID
  precondition:
    StringEquals:
    - "{{ useInstanceID }}"
    - "False"
  inputs:
    runCommand:
    - "WAZUH_MANAGER='{{ serverAddress }}' WAZUH_AGENT_GROUP='{{ groupName }}' dpkg -i wazuh-agent_4.8.0-1_amd64.deb"
- action: aws:runShellScript
  name: startService
  inputs:
    runCommand:
    - "if [ -f /usr/sbin/update-rc.d ]; then update-rc.d wazuh-agent defaults; service wazuh-agent start; else systemctl daemon-reload; systemctl enable wazuh-agent; systemctl start wazuh-agent; fi"`

**Comment by kevpatts** [comment]
Here's the equivalent for Amazon Linux 1:
```
---
schemaVersion: '2.2'
description: "Install Wazuh Agent"
parameters:
  serverAddress:
    type: String
    description: This is the address the agent uses to communicate with the server. Enter an IP address or a fully qualified domain name (FQDN).
    default: ''
  groupName:
    type: String
    description: This is the address the group that the agent will be joined into.
    default: ''
  useInstanceID:
    type: String
    description: Recommended. If True the instance ID will be used to identify the endpoint in Wazuh. If set to false the server hostname is used instead.
    default: 'True'
    allowedValues:
    - "True"
    - "False"
  purgeExistingWazuhPackage:
    type: String
    description: Recommended. This purges any partially installed or failed installations of the wazuh-agent package.
    default: 'True'
    allowedValues:
    - "True"
    - "False"
mainSteps:
- action: aws:runShellScript
  name: purgeExistingAgent
  precondition:
    StringEquals:
    - "{{ purgeExistingWazuhPackage }}"
    - "True"
  inputs:
    runCommand:
    - "yum -y remove wazuh-agent"
- action: aws:runShellScript
  name: downloadPackage
  inputs:
    runCommand:
    - "curl -o wazuh-agent-4.8.0-1.x86_64.rpm https://packages.wazuh.com/4.x/yum/wazuh-agent-4.8.0-1.x86_64.rpm"
- action: aws:runShellScript
  name: installWithInstanceID
  precondition:
    StringEquals:
    - "{{ useInstanceID }}"
    - "True"
  inputs:
    runCommand:
    - "AWS_INSTANCE_ID=`curl -s http://169.254.169.254/latest/meta-data/instance-id`; WAZUH_MANAGER='{{ serverAddress }}' WAZUH_AGENT_GROUP='{{ groupName }}' WAZUH_AGENT_NAME=$AWS_INSTANCE_ID rpm -ihv wazuh-agent-4.8.0-1.x86_64.rpm"
- action: aws:runShellScript
  name: installWithoutInstanceID
  precondition:
    StringEquals:
    - "{{ useInstanceID }}"
    - "False"
  inputs:
    runCommand:
    - "WAZUH_MANAGER='{{ serverAddress }}' WAZUH_AGENT_GROUP='{{ groupName }}' rpm -ihv wazuh-agent-4.8.0-1.x86_64.rpm"
- action: aws:runShellScript
  name: startService
  inputs:
    runCommand:
    - "chkconfig wazuh-agent on; service wazuh-agent start"
```
