### ISSUE TITLE
Filebeat doesn't show info in kibana's Dashboard

### ISSUE THREAD

**Issue by Datorrespr** [wazuh/wazuh#5188]
Hi, I'm new on Wazuh.

I just have installed Wazuh on a server and I'm watching manager logs in Discover section, but I don't see GeoLocation Function that works with Filebeat module and no other function of Filebeat.

![Captura](https://user-images.githubusercontent.com/66637305/84059700-a48f8a80-a980-11ea-939b-54d7755b42f6.PNG)

my Filebeat.yml conf:

```
Wazuh - Filebeat configuration file
     filebeat.modules:
     module: wazuh
     alerts:
        enabled: true
     archives:
        enabled: false
     setup.template.json.enabled: true
     setup.template.json.path: '/etc/filebeat/wazuh-template.json'
     setup.template.json.name: 'wazuh'
     setup.template.overwrite: true
     setup.ilm.enabled: false
     output.elasticsearch.hosts: ['http://192.168.150.10:9200']
     setup.kibana:
        host: 192.168.150.10:5601
```

I've already installed all Templates: 

`curl -so /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/v3.12.3/extensions/elasticsearch/7.x/wazuh-template.json
chmod go+r /etc/filebeat/wazuh-template.json`

What can I do to take advantage of FileBeat alerts?
I hope your answers. Thanks
