### ISSUE TITLE
Yara active reponse don't work 

### ISSUE THREAD

**Issue by shadobot** [wazuh/wazuh#5556]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13 | active response | Agent | Packages | CentOS 7 |

Hi,
I tried to set up within wazuh via an active response a yara scan when detecting a new file on the agent by following the following tutorial https://wazuh.com/blog/how-to-integrate-yara-with-wazuh/
However when I create a new file with items to be detected by my yara rule no alert is triggered.

manager ossec.conf active response configuration :
```
<command>
    <name>yara</name>
    <executable>yara.sh</executable>
    <expect>filename</expect>
    <extra_args>-yara_path /usr/bin/ -yara_rules /var/ossec/active-response/bin/yara-rules/</extra_args>
    <timeout_allowed>no</timeout_allowed>
  </command>
```

  <active-response>
    <command>yara</command>
    <location>local</location>
    <rules_id>550,554</rules_id>
  </active-response>

new file detection alert:

```
** Alert 1595673761.120281182: - local,syslog,sshd,syscheck,pci_dss_11.5,
2020 Jul 25 10:42:41 (ip-172-16-4-4.us-east-2.compute.internal) any->syscheck
Rule: 554 (level 10) -> 'File added to the system.'
File '/etc/example.txt' added
Mode: whodata

Attributes:
 - Size: 152
 - Permissions: rw-r--r--
 - Date: Sat Jul 25 10:42:30 2020
 - Inode: 13203625
 - User: root (0)
 - Group: root (0)
 - MD5: 8d1e7c7383d9aa4d5499ac7a713b712b
 - SHA1: 138ba3dbc5970c3efa96c8126911c2381b87a30f
 - SHA256: c1bd45e61677fc69f11518d9624fe9903dfe66c5a58d5cac024a5a7b372e4c23
 - (Audit) User name: root
 - (Audit) Audit name: reader
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 27618
 - (Audit) Process name: /usr/bin/mv
 - (Audit) Process cwd: /var/ossec/active-response/bin
 - (Audit) Parent process name: /usr/bin/bash
 - (Audit) Parent process id: 13357
 - (Audit) Parent process cwd: /var/ossec/active-response/bin

```

The active response seems to be launched in view of the auditd alerts.

```
** Alert 1595673761.120283966: - audit,audit_watch_execute,gdpr_IV_30.1.g,
2020 Jul 25 10:42:41 (ip-172-16-4-4.us-east-2.compute.internal) any->/var/log/audit/audit.log
Rule: 80789 (level 3) -> 'Audit: Watch - Execute access: '
type=SYSCALL msg=audit(1595673761.339:675987): arch=c000003e syscall=59 success=no exit=-2 a0=12b18b0 a1=12b1f50 a2=12b53b0 a3=7fff31c82aa0 items=1 ppid=27619 pid=27634 auid=1000 uid=0 gid=994 euid=0 suid=0 fsuid=0 egid=994 sgid=994 fsgid=994 tty=(none) ses=52 comm="yara.sh" exe="/usr/bin/bash" key="audit-wazuh-x" type=CWD msg=audit(1595673761.339:675987):  cwd="/var/ossec/active-response" type=PATH msg=audit(1595673761.339:675987): item=0 name="-yara_path/yara" objtype=UNKNOWN cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0 type=PROCTITLE msg=audit(1595673761.339:675987): proctitle=2F62696E2F62617368002F7661722F6F737365632F6163746976652D726573706F6E73652F62696E2F796172612E736800616464002D002D00313539353637333736312E31323032373934303900353534002869702D3137322D31362D342D342E75732D656173742D322E636F6D707574652E696E7465726E616C2900616E79
audit.type: SYSCALL
audit.id: 675987
audit.arch: c000003e
audit.syscall: 59
audit.success: no
audit.exit: -2
audit.ppid: 27619
audit.pid: 27634
audit.auid: 1000
audit.uid: 0
audit.gid: 994
audit.euid: 0
audit.suid: 0
audit.fsuid: 0
audit.egid: 994
audit.sgid: 994
audit.fsgid: 994
audit.tty: (none)
audit.session: 52
audit.command: yara.sh
audit.exe: /usr/bin/bash
audit.key: audit-wazuh-x
audit.cwd: /var/ossec/active-response

** Alert 1595673761.120285490: - audit,audit_watch_execute,gdpr_IV_30.1.g,
2020 Jul 25 10:42:41 (ip-172-16-4-4.us-east-2.compute.internal) any->/var/log/audit/audit.log
Rule: 80789 (level 3) -> 'Audit: Watch - Execute access: /var/ossec/active-response/bin/yara.sh'
type=SYSCALL msg=audit(1595673761.322:675984): arch=c000003e syscall=59 success=yes exit=0 a0=68fc22 a1=7ffdad6970c0 a2=7ffdad697538 a3=7ffdad684420 items=3 ppid=26197 pid=27619 auid=1000 uid=0 gid=994 euid=0 suid=0 fsuid=0 egid=994 sgid=994 fsgid=994 tty=(none) ses=52 comm="yara.sh" exe="/usr/bin/bash" key="audit-wazuh-x" type=EXECVE msg=audit(1595673761.322:675984): argc=14 a0="/bin/bash" a1="/var/ossec/active-response/bin/yara.sh" a2="add" a3="-" a4="-" a5="1595673761.120279409" a6="554" a7="(ip-172-16-4-4.us-east-2.compute.internal)" a8="any->syscheck" a9="/etc/example.txt" a10="-yara_path" a11="/usr/bin/" a12="-yara_rules" a13="/var/ossec/active-response/bin/yara-rules/" type=CWD msg=audit(1595673761.322:675984):  cwd="/" type=PATH msg=audit(1595673761.322:675984): item=0 name="/var/ossec/active-response/bin/yara.sh" inode=12661630 dev=fd:01 mode=0100750 ouid=0 ogid=994 rdev=00:00 objtype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0 type=PATH msg=audit(1595673761.322:675984): item=1 name="/bin/bash" inode=12604406 dev=fd:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 objtype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0 type=PATH msg=audit(1595673761.322:675984): item=2 name="/lib64/ld-linux-x86-64.so.2" inode=276844 dev=fd:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 objtype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0 type=PROCTITLE msg=audit(1595673761.322:675984): proctitle=2F62696E2F62617368002F7661722F6F737365632F6163746976652D726573706F6E73652F62696E2F796172612E736800616464002D002D00313539353637333736312E31323032373934303900353534002869702D3137322D31362D342D342E75732D656173742D322E636F6D707574652E696E7465726E616C2900616E79
audit.type: SYSCALL
audit.id: 675984
audit.arch: c000003e
audit.syscall: 59
audit.success: yes
audit.exit: 0
audit.ppid: 26197
audit.pid: 27619
audit.auid: 1000
audit.uid: 0
audit.gid: 994
audit.euid: 0
audit.suid: 0
audit.fsuid: 0
audit.egid: 994
audit.sgid: 994
audit.fsgid: 994
audit.tty: (none)
audit.session: 52
audit.command: yara.sh
audit.exe: /usr/bin/bash
audit.key: audit-wazuh-x
audit.execve.a0: /bin/bash
audit.execve.a1: /var/ossec/active-response/bin/yara.sh
audit.execve.a2: add
audit.execve.a3: -
audit.execve.a4: -
audit.execve.a5: 1595673761.120279409
audit.execve.a6: 554
audit.execve.a7: (ip-172-16-4-4.us-east-2.compute.internal)
audit.cwd: /
audit.file.name: /var/ossec/active-response/bin/yara.sh
audit.file.inode: 12661630
audit.file.mode: 0100750

** Alert 1595673761.120288271: - audit,audit_watch_execute,gdpr_IV_30.1.g,
2020 Jul 25 10:42:41 (ip-172-16-4-4.us-east-2.compute.internal) any->/var/log/audit/audit.log
Rule: 80789 (level 3) -> 'Audit: Watch - Execute access: /bin/dirname'
type=SYSCALL msg=audit(1595673761.326:675986): arch=c000003e syscall=59 success=yes exit=0 a0=12b1dd0 a1=12b2280 a2=12b1720 a3=7fff31c82ba0 items=2 ppid=27619 pid=27620 auid=1000 uid=0 gid=994 euid=0 suid=0 fsuid=0 egid=994 sgid=994 fsgid=994 tty=(none) ses=52 comm="dirname" exe="/usr/bin/dirname" key="audit-wazuh-x" type=EXECVE msg=audit(1595673761.326:675986): argc=2 a0="dirname" a1="/var/ossec/active-response/bin/yara.sh" type=CWD msg=audit(1595673761.326:675986):  cwd="/" type=PATH msg=audit(1595673761.326:675986): item=0 name="/bin/dirname" inode=12613434 dev=fd:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 objtype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0 type=PATH msg=audit(1595673761.326:675986): item=1 name="/lib64/ld-linux-x86-64.so.2" inode=276844 dev=fd:01 mode=0100755 ouid=0 ogid=0 rdev=00:00 objtype=NORMAL cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0 type=PROCTITLE msg=audit(1595673761.326:675986): proctitle=6469726E616D65002F7661722F6F737365632F6163746976652D726573706F6E73652F62696E2F796172612E7368
audit.type: SYSCALL
audit.id: 675986
audit.arch: c000003e
audit.syscall: 59
audit.success: yes
audit.exit: 0
audit.ppid: 27619
audit.pid: 27620
audit.auid: 1000
audit.uid: 0
audit.gid: 994
audit.euid: 0
audit.suid: 0
audit.fsuid: 0
audit.egid: 994
audit.sgid: 994
audit.fsgid: 994
audit.tty: (none)
audit.session: 52
audit.command: dirname
audit.exe: /usr/bin/dirname
audit.key: audit-wazuh-x
audit.execve.a0: dirname
audit.execve.a1: /var/ossec/active-response/bin/yara.sh
audit.cwd: /
audit.file.name: /bin/dirname
audit.file.inode: 12613434
audit.file.mode: 0100755
```
Can you help me please ?
