### ISSUE TITLE
wazuh user id not being displayed

### ISSUE THREAD

**Issue by DavidOrtice** [wazuh/wazuh#5608]
Hello guys am trying to get the user id of the person who made changes to a file but i cant view it from my side.

This is what i can see, i need to see the person who made changes to file..who data config is already added to the wazuh-agent but i cant see the user id of the person who made changes to the file.

Rule: 550 fired (level 7) -> "Integrity checksum changed."
Portion of the log(s):

File '/home/dootieno/epl.txt' modified
Mode: real-time
Changed attributes: size,mtime,md5,sha1,sha256
Old modification time was: '1596062498', now it is '1596148828'
Old md5sum was: 'b83a9d3b420cf4f7bfd68c0dc58cbe14'
New md5sum is : '4a03d1c4f93cdd900191e0e722ed8d89'
Old sha1sum was: '28609fa713d54bf979b8b75995357b2dd0c8051e'
New sha1sum is : '0677c9faaed444112e52ee00f76ae7c6a2ccfd3e'
Old sha256sum was: 'e2d99c4f180340acc36b89e49b9538ec4f77169bf5128e2c21c9ac1c29391b35'
New sha256sum is : '92ddfd7786cf7ad01553fde34cb2b5549957ab9a6a79d7f94662ac19a4ac335f'

**Comment by antoniomanuelfr** [comment]
Hi @DavidOrtice 

Could you please share with us the `ossec.conf` file and tell us the wazuh version and the OS that you are using?

This error may be caused because you don't have audit installed on your OS. In order to install it on ubuntu just run `sudo apt install auditd` in the terminal.

And it will generate alerts where you can see the user that created, modified or deleted any file in `/home/vagrant/test`: 
```
** Alert 1596181383.3389: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2020 Jul 31 07:43:03 ubuntumanager->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '/home/vagrant/test/test-file' added
Mode: whodata

Attributes:
 - Size: 0
 - Permissions: rw-r--r--
 - Date: Fri Jul 31 07:43:02 2020
 - Inode: 142695
 - User: root (0)
 - Group: root (0)
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 - (Audit) User name: root
 - (Audit) Audit name: vagrant
 - (Audit) Effective name: root
 - (Audit) Group name: root
 - (Audit) Process id: 3098
 - (Audit) Process name: /bin/touch
 - (Audit) Process cwd: /var/ossec
 - (Audit) Parent process name: /bin/bash
 - (Audit) Parent process id: 2933
 - (Audit) Parent process cwd: /var/ossec
```

I hope this information is useful. If you have any doubts, don't hesitate in contact us.

Kind regards. 
Antonio.
