### ISSUE TITLE
Wazuh 1000 authorization while adding sample data.

### ISSUE THREAD

**Issue by rahul29564** [wazuh/wazuh#6041]
I have added wazuh on kibana.
installed wazuh-manager, wazuh-api and filebeat on one machine.
Added wazuh-agent on other machine.

Open all required ports and kibana is able to connect to wazuh-api.

Facing error 1000 authorization while trying to add sample wazuh data.

PFB logs:
2020/09/16 21:11:44  ERROR  Authorization Exception
2020/09/16 21:11:44  ERROR  Authorization Exception
2020/09/16 21:11:44  ERROR  Could not check if the index wazuh-monitoring-3.x-2020.09.16 exists due to Authorization Exception
2020/09/16 21:11:44  INFO  App ready to be used.
2020/09/16 21:11:54  ERROR  socket hang up
2020/09/16 21:14:34  ERROR  socket hang up
2020/09/16 21:14:45  ERROR  socket hang up
2020/09/16 21:15:10  ERROR  socket hang up
2020/09/16 21:20:07  ERROR  socket hang up
2020/09/16 21:20:18  ERROR  socket hang up
2020/09/16 21:20:28  ERROR  socket hang up
2020/09/16 21:20:28  ERROR  socket hang up
2020/09/16 21:20:38  ERROR  socket hang up
2020/09/16 21:20:38  ERROR  socket hang up
2020/09/16 21:20:38  ERROR  socket hang up
2020/09/16 21:20:48  ERROR  socket hang up
2020/09/16 21:21:49  INFO  Kibana index: .kibana
2020/09/16 21:21:49  INFO  App revision: 0884
2020/09/16 21:21:49  INFO  Total RAM: 3943MB
2020/09/16 21:21:49  ERROR  Authorization Exception
2020/09/16 21:21:49  ERROR  Authorization Exception
2020/09/16 21:21:49  ERROR  Could not check if the index wazuh-monitoring-3.x-2020.09.16 exists due to Authorization Exception
2020/09/16 21:21:49  INFO  App ready to be used.
2020/09/16 21:22:42  ERROR  Error adding sample alerts to wazuh-alerts-3.x-sample-security index

**Comment by rahul29564** [comment]
FYI... I am using the below.

[root@ip-10-0-3-194 config]# cat /usr/share/kibana/plugins/wazuh/package.json | grep version
  "version": "3.13.1",
    "version": "7.8.1"

**Comment by rahul29564** [comment]
![image](https://user-images.githubusercontent.com/19564218/93363261-a1037d80-f864-11ea-8fc1-a982ea4b4de6.png)

Both required indexes are created but no data in it.

**Comment by rahul29564** [comment]
![image](https://user-images.githubusercontent.com/19564218/93363438-de680b00-f864-11ea-9c6b-e23a4eb333fa.png)
FYI

**Comment by rahul29564** [comment]
![image](https://user-images.githubusercontent.com/19564218/93364240-effde280-f865-11ea-95d6-64ab8a0f0ba5.png)
FYI

**Comment by pablotr9** [comment]
Hi @rahul29564 !

Are you using any of the available security plugin? XPACK or OPENDISTRO?
```
2020/09/16 21:21:49 ERROR Authorization Exception
2020/09/16 21:21:49 ERROR Could not check if the index wazuh-monitoring-3.x-2020.09.16 exists due to Authorization Exception
2020/09/16 21:22:42 ERROR Error adding sample alerts to wazuh-alerts-3.x-sample-security index
```

Could you please check the user that is configured in your `kibana.yml` and then check its permissions in Kibana DevTools:
Xpack
```
GET /_xpack/security/user/USERNAME
```
Opendisto:
```
GET _opendistro/_security/api/internalusers/USERNAME
```
Please replace USERNAME with the username that is being used in the kibana.yml and share the output with me .

The user configured in the `kibana.yml` needs some minimum permissions, such as read/write on wazuh-* indices, and I think the lack of these permissions its causing those errors

Best Regards,
Pablo Torres

**Comment by rahul29564** [comment]
Hi,

I am using XPACK.

**Comment by pablotr9** [comment]
Hi @rahul29564, thanks for the output

`elastic` is the user configured in the kibana.yml. Which user are you using to log in to Kibana?

Does this happen every time you try to add sample data? Could you also check the response in the browser DevTools?
Just open the browser DevTools while using the Wazuh app (press F12 in Chrome and Firefox) and go to `Network` tab. Once the network tab is opened, try to add sample data in the Wazuh Kibana app and you will see a failed request, please click on it and see its response and share it with me. thanks!
![image](https://user-images.githubusercontent.com/35685689/93438567-c37db100-f8cd-11ea-896f-2f75512377e4.png)

Best Regards,
Pablo Torres

**Comment by rahul29564** [comment]
Hi Pablo,

I am using elastic user to login to kibana too.

Yes, it happens every time when I try to add sample data.

PFB
![image](https://user-images.githubusercontent.com/19564218/93448158-ebcad700-f8f0-11ea-97fc-f84f8482ed85.png)

**Comment by rahul29564** [comment]
FYI... I am using certificates generated by using certutil to secure the Kibana cluster.

PFB filebeat.yml
====================
```
# Wazuh - Filebeat configuration file
filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.template.overwrite: true
setup.ilm.enabled: false

output.elasticsearch.hosts: ["https://x.x.x.x:9200", "https://x.x.x.x:9200", "https://x.x.x.x:9200"]
output.elasticsearch.ssl.certificate_authorities: ["/etc/filebeat/ca.crt"]
output.elasticsearch.ssl.certificate: "/etc/filebeat/ca.crt"
output.elasticsearch.ssl.key: "/etc/filebeat/ca.key"
output.elasticsearch.cacert.ssl_certificate_verification: false
output.elasticsearch.username: "elastic"
output.elasticsearch.password: "pass"


```

**Comment by rahul29564** [comment]
Here is /usr/share/kibana/optimize/wazuh/config/wazuh.yml

```
hosts:
  - ELK-XYZ:
     url: https://X.X.X.X
     port: 55000
     user: user
     password: pass
```
