### ISSUE TITLE
[Feature Request] Allow to override the date_rounding and index_name_format fields in wazuh filebeat module

### ISSUE THREAD

**Issue by jeroen-vankelecom** [wazuh/wazuh#6179]
Through the `filebeat.yml`, it is possible to override the index prefix to be used to create Elastic indices for alerts and archives. Unfortunately, there is no possibility to choose the date format, nor can you choose to create weekly or monthly indices (instead of a daily index).

|version|Component|
|---|---|
| 0.1 | Wazuh Filebeat module  |

For example, your `/etc/filebeat/filebeat.yml` would look like this if you want to have a monthly alert index:
```

filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
      var.index_prefix: wazuh-alerts-3.x-
      var.index_format: yyyy.MM
      var.date_rounding: M
    archives:
      enabled: false
```
