### ISSUE TITLE
Update analysisd to support FIM's new Windows registries fields

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh#6230]
| Wazuh version | Component       | Install type | Install method   | Platform |
| ------------- | --------------- | ------------ | ---------------- | -------- |
| 4.0.0         | ossec-analysisd | Manager      | Packages/Sources | Linux    |

## Description

With branch `fim-registry-improvements`, we have added some improvements to the scan of Windows registries in FIM. With this improvements, we have also added some new fields that need to be added to FIM alerts:
Here is an event from a registry key:
```json
{
    "type": "event",
    "data": {
        "path": "HKEY_LOCAL_MACHINE\\System\\TEST\\clave",
        "mode": "scheduled",
        "type": "modified",
        "arch": "[x32]",
        "timestamp": 0,
        "attributes": {
            "type": "registry",
            "perm": "HomeUsers (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, Usuarios (allowed): read_control|read_data|read_ea|write_ea, Usuarios (allowed): generic_read, Administradores (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, Administradores (allowed): generic_all, SYSTEM (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, SYSTEM (allowed): generic_all, CREATOR OWNER (allowed): generic_all",
            "uid": "S-1-5-32-544",
            "user_name": "Administradores",
            "gid": "S-1-5-21-3527455827-79240758-596275861-513",
            "group_name": "",
            "mtime": 1602076090,
            "checksum": "2034381065124a46ae89e095ff96ea8a51196a24"
        },
        "changed_attributes": [
            "mtime"
        ],
        "old_attributes": {
            "type": "registry",
            "perm": "HomeUsers (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, Usuarios (allowed): read_control|read_data|read_ea|write_ea, Usuarios (allowed): generic_read, Administradores (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, Administradores (allowed): generic_all, SYSTEM (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, SYSTEM (allowed): generic_all, CREATOR OWNER (allowed): generic_all",
            "uid": "S-1-5-32-544",
            "user_name": "Administradores",
            "gid": "S-1-5-21-3527455827-79240758-596275861-513",
            "group_name": "",
            "mtime": 1602069465,
            "checksum": "3ada66fcc6f29c143035a39123046db13e13d4aa"
        }
    }
}
```
Its new fields are:
* `gid`
* `group_name`
* `arch`

Here is an event from a registry value:
```json
{
    "type": "event",
    "data": {
        "path": "HKEY_LOCAL_MACHINE\\System\\TEST\\clave",
        "mode": "scheduled",
        "type": "modified",
        "arch": "[x64]",
        "value_name": "stringtest",
        "timestamp": 1602667733,
        "attributes": {
            "type": "registry",
            "value_type": "REG_SZ",
            "size": 18,
            "hash_md5": "6b133c7efae2cbcbd8aa18ed37696bc7",
            "hash_sha1": "266275c25336c4f7b86642f077b900d8051935db",
            "hash_sha256": "c70b0e3a870d3402be7c0f0a1304de2907a709c8ef56bf306c177f9b4117aab8",
            "checksum": "bbcfd4d6d9dd6875cddc14b04811cc0fa75ef8f4"
        },
        "changed_attributes": [
            "size",
            "md5",
            "sha1",
            "sha256"
        ],
        "old_attributes": {
            "type": "registry",
            "value_type": "REG_SZ",
            "size": 9,
            "hash_md5": "4715007394735645cf12f7f67be55df1",
            "hash_sha1": "d78aa7a0a90029fd079aa46915ec52e8ed89870f",
            "hash_sha256": "1e82e81cb776db520378a67e0978591690941c1bbe88323725299972567595b7",
            "checksum": "728d469a152429b79fc16a13f9bc38ebea7f2b61"
        }
    }
}
```
Its new fields are:
* `arch`
* `value_name`
* `value_type`

We should also send a different alert depending on the `type` attribute, saying it comes from a _registry_ instead of a _file_.

This is how _analysisd_ displays the previous events as alerts currently:

```
** Alert 1602076139.375029: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2020 Oct 07 13:08:59 (jmv74211-PC) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File 'HKEY_LOCAL_MACHINE\System\TEST\clave' modified
Mode: scheduled
Changed attributes: mtime
Old modification time was: '1602069465', now it is '1602076090'

Attributes:
 - Permissions: HomeUsers (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, Usuarios (allowed): read_control|read_data|read_ea|write_ea, Usuarios (allowed): generic_read, Administradores (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, Administradores (allowed): generic_all, SYSTEM (allowed): delete|read_control|write_dac|write_owner|read_data|write_data|append_data|read_ea|write_ea|execute, SYSTEM (allowed): generic_all, CREATOR OWNER (allowed): generic_all
 - Date: Wed Oct  7 13:08:10 2020
 - User: Administradores (S-1-5-32-544)

 ** Alert 1602076139.376163: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2020 Oct 07 13:08:59 (jmv74211-PC) any->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File 'HKEY_LOCAL_MACHINE\System\TEST\clave\h' added
Mode: scheduled

Attributes:
 - Size: 1
 - MD5: d41d8cd98f00b204e9800998ecf8427e
 - SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
 - SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```
