### ISSUE TITLE
Error parsing group configuration in framework.

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#6276]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.0 | Framework | Manager | 

Hi team!

## Description

Multiple problems have been reported related to the endpoints below:
- GET /groups/{group_id}/config
- PUT /groups/{group_id}/config

The problem arises when the agent.conf file has some configuration where there is an inner XML. For example, when a configuration like this is pasted directly into agent.conf file:
```XML
<agent_config>
<localfile>
    <location>System</location>
    <log_format>eventchannel</log_format>
    <query>
       \<QueryList>
            \<Query Id="0" Path="System">
                \<Select Path="System">*[System[(Level&lt;=3)]]\</Select>
            \</Query>
        \</QueryList>
    </query>
</localfile>
</agent_config>
```
Everything inside `<query>` tags is incorrectly retrieved when using method GET:
```YAML
{
  "data": {
    "total_affected_items": 1,
    "affected_items": [
      {
        "filters": {},
        "config": {
          "localfile": [
            {
              "location": "System",
              "log_format": "eventchannel",
              "query": "\n       \\"
            }
          ]
        }
      }
    ]
  },
  "error": 0
}
```

The problem is similar when trying to use `PUT` method in order to upload said configuration:
```YAML
{
  "title": "Bad Request",
  "detail": "Wazuh syntax error: Error reading XML file '/var/ossec/tmp/api_tmp_file_1602584384.528841_102.xml': XMLERR: Element ' Syscheck remote configuration in '/var/ossec/tmp/api_tmp_file_1602584384.528841_102.xml' is corrupted.",
  "dapi_errors": {
    "master-node": {
      "error": "Wazuh syntax error: Error reading XML file '/var/ossec/tmp/api_tmp_file_1602584384.528841_102.xml': XMLERR: Element ' Syscheck remote configuration in '/var/ossec/tmp/api_tmp_file_1602584384.528841_102.xml' is corrupted."
    }
  },
  "error": 1114
}
```

In addition, if we pay attention to the inner XML, we can see that only `<` is escaped. This makes no sense and is not consistent with [the example in our docu](https://documentation.wazuh.com/3.13/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html#filtering-events-from-windows-event-channel-with-queries). However, if we try to use the example of the link, there is another error:
```YAML
{
  "title": "Bad Request",
  "detail": "XML syntax error: not well-formed (invalid token): line 6, column 19",
  "remediation": "Please, ensure file content has correct XML",
  "dapi_errors": {
    "master-node": {
      "error": "XML syntax error: not well-formed (invalid token): line 6, column 19"
    }
  },
  "error": 1113
}
```

A similar issue is reported here https://github.com/wazuh/wazuh/issues/4947.

Best regards,
Selu.
