### ISSUE TITLE
Wazuh alerts are missing

### ISSUE THREAD

**Issue by jangel97** [wazuh/wazuh#6385]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.2-1 | x | Manager/Agent | Packag rpm | CentOS 7.8 |

Hello, 

I am new to Wazuh and I am finding some trouble with its integration with Elastic Stack. 

Whenever I enter into Kibana Wazuh section and click into my agent, the following error appears.
![image](https://user-images.githubusercontent.com/38217290/96890527-0233f780-1488-11eb-97b1-14c9f37cb42e.png)

Besides, there are no wazuh-alerts documents:
![image](https://user-images.githubusercontent.com/38217290/96891954-715e1b80-1489-11eb-94a9-370d86e00d29.png)

I just deployed Wazuh following the steps mentioned in the documentation, fresh installation. 
I have one agent (CentOS) and the Wazuh Server which communicates directly to ES via Filebeat.

There are logs in the file /var/ossec/logs/alerts/alerts.json

Filebeat export config:

```
[root@elk0 ~]# filebeat export config
filebeat:
  modules:
  - alerts:
      enabled: true
    archives:
      enabled: false
    module: wazuh
output:
  elasticsearch:
    hosts:
    - http://localhost:9200
path:
  config: /etc/filebeat
  data: /var/lib/filebeat
  home: /usr/share/filebeat
  logs: /var/log/filebeat
setup:
  ilm:
    enabled: false
  template:
    json:
      enabled: true
      name: wazuh
      path: /etc/filebeat/wazuh-template.json
    overwrite: true
```
```
[root@elk0 ~]# filebeat test output
elasticsearch: http://localhost:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: ::1, 127.0.0.1
    dial up... OK
  TLS... WARN secure connection disabled
  talk to server... OK
  version: 7.9.1
```
Any help is welcome, do not hesitate in asking me any information in case you need it.

Thanks in advance,
