### ISSUE TITLE
Loss of delete alerts in Windows realtime

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh#6673]
| Wazuh version | Component | Install type | Install method   | Platform |
| ------------- | --------- | ------------ | ---------------- | -------- |
| 4.0.1         | FIM       | Agent        | Packages/Sources | Windows  |

## Description

Some delete events are being lost in realtime in Windows when the monitored folder is removed using `shift+del`. When removing the monitored folder by sending it to the recycle bin, the alerts are generated.

I have added some extra debug messages locally and have found that `RTCallBack` is not being called when using `shift+del` while it is called three times when using the recycle bin.

Also, when removing the folder with the `shift+del` method, these debug messages appear:
```
DEBUG: The attributes for 'c:\kuntal' could not be obtained. Error '5'.
DEBUG: The attributes for 'c:\kuntal' could not be obtained. Error '2'.
```

Only the second one (error `2`) appears with the other method.

Error `2` is `ERROR_FILE_NOT_FOUND` and error `5` is `ERROR_ACCESS_DENIED`: https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-

## How to reproduce the error

Ths is the configuration used to reproduce the bug:

```xml
<syscheck>
    <disabled>no</disabled>

    <frequency>43200</frequency>

    <directories realtime="yes">c:\testfolder</directories>
</syscheck>
```

When removing `c:\testfolder` using _Right-click > Delete_ we get these alerts

```
** Alert 1605789533.346651: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2020 Nov 19 12:38:53 (jmv74211-PC) any->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File 'c:\testfolder\1.txt' deleted
Mode: realtime

Attributes:
 - Size: 1
 - Permissions: Administradores (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, SYSTEM (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Usuarios (allowed): read_control|synchronize|read_data|read_ea|execute|read_attributes, Usuarios autentificados (allowed): delete|read_control|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes
 - Date: Thu Nov 19 11:38:11 2020
 - User: Administradores (S-1-5-32-544)
 - MD5: 0cc175b9c0f1b6a831c399e269772661
 - SHA1: 86f7e437faa5a7fce15d1ddcb9eaeaea377667b8
 - SHA256: ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb
 - File attributes: ARCHIVE

** Alert 1605789533.347875: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2020 Nov 19 12:38:53 (jmv74211-PC) any->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File 'c:\testfolder\2.txt' deleted
Mode: realtime

Attributes:
 - Size: 1
 - Permissions: Administradores (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, SYSTEM (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Usuarios (allowed): read_control|synchronize|read_data|read_ea|execute|read_attributes, Usuarios autentificados (allowed): delete|read_control|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes
 - Date: Thu Nov 19 11:38:20 2020
 - User: Administradores (S-1-5-32-544)
 - MD5: 8fa14cdd754f91cc6554c9e71929cce7
 - SHA1: 4a0a19218e082a343a1b17e5333409af9d98f0f5
 - SHA256: 252f10c83610ebca1a059c0bae8255eba2f95be4d1d7bcfa89d7248a82d9f111
 - File attributes: ARCHIVE

** Alert 1605789533.349099: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2020 Nov 19 12:38:53 (jmv74211-PC) any->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File 'c:\testfolder\3.txt' deleted
Mode: realtime

Attributes:
 - Size: 1
 - Permissions: Administradores (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, SYSTEM (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Usuarios (allowed): read_control|synchronize|read_data|read_ea|execute|read_attributes, Usuarios autentificados (allowed): delete|read_control|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes
 - Date: Thu Nov 19 11:38:26 2020
 - User: Administradores (S-1-5-32-544)
 - MD5: 8fa14cdd754f91cc6554c9e71929cce7
 - SHA1: 4a0a19218e082a343a1b17e5333409af9d98f0f5
 - SHA256: 252f10c83610ebca1a059c0bae8255eba2f95be4d1d7bcfa89d7248a82d9f111
 - File attributes: ARCHIVE
```

But when removing the folder using `shift+del`, we only get one alert:
```
** Alert 1605789870.354025: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,tsc_PI1.4,tsc_PI1.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2020 Nov 19 12:44:30 (jmv74211-PC) any->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File 'c:\testfolder\1.txt' deleted
Mode: realtime

Attributes:
 - Size: 2
 - Permissions: Administradores (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, SYSTEM (allowed): delete|read_control|write_dac|write_owner|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes, Usuarios (allowed): read_control|synchronize|read_data|read_ea|execute|read_attributes, Usuarios autentificados (allowed): delete|read_control|synchronize|read_data|write_data|append_data|read_ea|write_ea|execute|read_attributes|write_attributes
 - Date: Thu Nov 19 11:41:25 2020
 - User: Administradores (S-1-5-32-544)
 - MD5: 4124bc0a9335c27f086f24ba207a4912
 - SHA1: e0c9035898dd52fc65c41454cec9c4d2611bfb37
 - SHA256: 961b6dd3ede3cb8ecbaacbd68de040cd78eb2ed5889130cceb4c49268ea4d506
 - File attributes: ARCHIVE
```
