### ISSUE TITLE
SCA not detecting correctly for Windows Core

### ISSUE THREAD

**Issue by mackov83** [wazuh/wazuh#6878]
I have just started testing out Wazuh in a lab using the all-in-one virtual appliance. I love the concept of the SCA tool, however after implementing all the recommendations via GPO, I have noticed that SCA still reports the same issues. However I have narrowed it down to Windows Core as the GUI based variants seem to have reacted positively to the GPO.

Having checked the relevant registry settings that could be implemented as an alternative to using GPO, the settings appear to be in place.

Is this a known issue and something that you are working on? 
Is it an inherent issue for Windows Core?
If not, please let me know and I can upload whatever information you believe you require. 

**Server version**: 4.0.3
**Agent version**: 4.0.3 (Mostly Windows Server 2019)
Both were updated based on trying to resolve the issues

Items failing checks:
![image](https://user-images.githubusercontent.com/72140072/102003358-87d27600-3d5a-11eb-95ad-86d9f2ae53b1.png)

**Comment by chemamartinez** [comment]
Hi @mackov83,

I am glad you are happy with the SCA component. We are highly working on improving the available policies extending support for the most common operating systems. [Here](https://github.com/wazuh/wazuh-ruleset/pull/776) you can see the latest additions which hope are available in the next release.

Let's try to find out why is SCA still reporting fixed checks. The first question I think when reading you are using GPO is, are you applying the policies to a specific Windows user? notice that all the registries that SCA is evaluating belong to `HKEY_LOCAL_MACHINE`, not to a particular user.

Please, let me ask you a couple of things to know more about your case:

- What do you mean with Windows core exactly?
- Did you manually checked that the registry entry that these checks are evaluating changed when applying the new policies?

For example, the first check from your screenshot looks like:

```yml
id: 14009
title: "Ensure 'Interactive logon: Do not display last user name' is set to 'Enabled'"
description: "This policy setting determines whether the account name of the last user to log on to the client computers in your organization will be displayed in each computer's respective Windows logon screen. Enable this policy setting to prevent intruders from collecting account names visually from the screens of desktop or laptop computers in your organization. The recommended state for this setting is: Enabled."
rationale: "An attacker with access to the console (for example, someone with physical access or someone who is able to connect to the server through Remote Desktop Services) could view the name of the last user who logged on to the server. The attacker could then try to guess the password, use a dictionary, or use a brute-force attack to try and log on."
remediation: "To establish the recommended configuration via GP, set the following UI path to Enabled: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Local Policies\\Security Options\\Interactive logon: Do not display last user name."
compliance:
  - cis_csc: ["13"]
condition: all
rules:
  - 'r:HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System -> DontDisplayLastUserName -> 1'
```

This check will pass yes and only yes the key `DontDisplayLastUserName` from the registry entry `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies\System` is set to 1. Otherwise, it will fail as it is happening in your case.
