### ISSUE TITLE
RBAC experimental api integration test

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#7215]
|Wazuh version|Component|
|---|---|
| master | API tavern tests |

## Description

Hi team!

There seems to be strange behaviour in the tests of `test_rbac_black_experimental_endpoints.tavern.yaml`. 
https://github.com/wazuh/wazuh/blob/170cc4abbb0fc05b2ed8697990e89d64c9168e18/api/test/integration/test_rbac_black_experimental_endpoints.tavern.yaml#L141-L165

For example, in the snippet above, when requesting hardware information for the agents `001,002,006,007` in `GET /experimental/syscollector/hardware`, agents `001` and `007` should be returning a 4000 error code. However, when running said endpoint with those parameters in the same environment where the test has been run, it returns the information of every agent:

```YAML
{
  "data": {
    "affected_items": [
      {
        "cpu": {
          "cores": 8,
          "mhz": 2811.341,
          "name": "Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz"
        },
        "ram": {
          "free": 755532,
          "total": 16230024,
          "usage": 96
        },
        "scan": {
          "id": 2045358622,
          "time": "2021-01-19T08:38:39Z"
        },
        "board_serial": "BSS-0123456789",
        "agent_id": "001"
      },
      {
        "cpu": {
          "cores": 8,
          "mhz": 3694.801,
          "name": "Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz"
        },
        "ram": {
          "free": 897048,
          "total": 16230024,
          "usage": 95
        },
        "scan": {
          "id": 191174415,
          "time": "2021-01-19T08:38:20Z"
        },
        "board_serial": "BSS-0123456789",
        "agent_id": "002"
      },
      {
        "cpu": {
          "cores": 8,
          "mhz": 2868.081,
          "name": "Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz"
        },
        "ram": {
          "free": 644792,
          "total": 16230024,
          "usage": 97
        },
        "scan": {
          "id": 1874054448,
          "time": "2021-01-19T08:38:42Z"
        },
        "board_serial": "BSS-0123456789",
        "agent_id": "006"
      },
      {
        "cpu": {
          "cores": 8,
          "mhz": 3007.623,
          "name": "Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz"
        },
        "ram": {
          "free": 654424,
          "total": 16230024,
          "usage": 96
        },
        "scan": {
          "id": 352075412,
          "time": "2021-01-19T08:38:42Z"
        },
        "board_serial": "BSS-0123456789",
        "agent_id": "007"
      }
    ],
    "total_affected_items": 4,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All specified syscollector information was returned",
  "error": 0
}
```

The strange part is that even though the answer doesn't match what is expected, the test is passing correctly:
![imagen](https://user-images.githubusercontent.com/23361101/105013467-9558db00-5a3f-11eb-998d-c80bcf84c5df.png)

It is necessary to check if this is still happening, if it happens in more tests and what is the reason, since it could hide bugs.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Selu.
