### ISSUE TITLE
GET /groups not affected by RBAC. 

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#7328]
|Wazuh version|Component|
|---|---|
| 4.0.0+ | RBAC |

## Description 
Hi team!

Currently (and since RBAC was implemented), there is a bug related to the access to GET /groups endpoint. When querying the list of groups, all of them are shown even though the user does not have permissions for said action.

## How to reproduce the error
- Get a token as wazuh:wazuh (`GET /security/user/authenticate`)
- Create a new user without any role assigned (`POST /security/users`)
- Login with said new user (`GET /security/user/authenticate`)
- Try to obtain groups (`GET /groups`). 

Groups will be returned as shown below:
```YAML
{
  "data": {
    "affected_items": [
      {
        "name": "default",
        "count": 0,
        "mergedSum": "fd756ba04d9c32c8848d4608bec41251",
        "configSum": "ab73af41699f13fdd81903b5f23d8d00"
      },
      {
        "name": "ubuntu",
        "count": 0,
        "mergedSum": "e23aa0fffa1263b9359daa6d173b236a",
        "configSum": "ab73af41699f13fdd81903b5f23d8d00"
      }
    ],
    "total_affected_items": 2,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected groups information was returned",
  "error": 0
}
```

even though the response from other endpoints (for example, ´GET /groups/{group_id}/agents´) for the same user is this: 
```YAML
{
  "title": "Permission Denied",
  "detail": "Permission denied: Resource type: group:id",
  "remediation": "Please, make sure you have permissions to execute the current request. For more information on how to set up permissions, please visit https://documentation.wazuh.com/current/user-manual/api/rbac/configuration.html",
  "dapi_errors": {
    "unknown-node": {
      "error": "Permission denied: Resource type: group:id"
    }
  },
  "error": 4000
}
``` 

Current user information:
```YAML
{
  "data": {
    "affected_items": [
      {
        "id": 100,
        "username": "test",
        "allow_run_as": false,
        "roles": []
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Current user information was returned",
  "error": 0
}
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Selu.
