### ISSUE TITLE
Standardize API data validation

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#7544]
|Wazuh version|Component|
|---|---|
| 4.x | Wazuh API |

## Description
Currently, we are doing API data validation with two different methods:
- Spec validation (`pattern` option)

  ```yaml
     xml_filename:
       in: query
       name: filename
       description: "Filter by filename of one or more rule or decoder files."
       schema:
         type: array
         items:
           type: string
           pattern: '^[\w\-]+\.xml(,[\w\-]+\.xml)*$'
  ```

- Using validator.py functions

  `spec.yaml`

    ```yaml
        get_dirnames_path:
        in: query
        name: relative_dirname
        description: "Filter by relative directory name"
        schema:
            type: string
            format: get_dirnames_path
    ```

  `validator.py`

  ```python
    @draft4_format_checker.checks("get_dirnames_path")
    def format_get_dirnames_path(relative_path):
        """
        Function to check if a relative path is allowed to be read
        :param relative_path: path string to check
        :return: True if path is OK, False otherwise
        """
        if not is_safe_path(relative_path):
            return False

        return check_exp(relative_path, _get_dirnames_path)
  ```

We need to find the most scalable and simplest method and apply it to all validations.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Víctor Fernández
