### ISSUE TITLE
SCA variables cannot be inserted inside commands

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#7712]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.1-40110 | SCA | Agent | All | All |

### Description

[SCA variables](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating_custom_policies.html) are only replaced when the rule where they appear starts with the variable. Here the code where the replacement is done https://github.com/wazuh/wazuh/blob/0fd7b0d255a32bfad5d6661b7149ff0b1608dcf8/src/wazuh_modules/wm_sca.c#L1088

To be able to apply them to situations like:

```yml
variables:
  $file: /tmp/file

checks:
  - id: 100001
    title: "Check md5sum for file."
    description: "-"
    rationale: "-"
    condition: any
    rules:
      - 'c:md5sum $file -> r:^d41d8cd98f00b204e9800998ecf8427e'
```

The module should look for the variables across the whole rule, not just the first character.

### Rationale

This behavior is inherited from the Rootcheck policy monitoring, where the available checks were `files`, `directories`, `registries` and `processes`. In these kinds of rules, variables were used to create lists of items. However, it was not designed for being replaced in commands.
