### ISSUE TITLE
Define a new rule syntax using YML as rule file language. 

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#7720]
This issue will include details on new rule syntax, rule components, and many other definitions 

Among others, those are some actions we will include: 

- YML rule format and structure.
- Folder and files naming convention. New rules and files organization.
- Current rules capabilities moved to YML syntax.
- Request and add new capabilities on syntax that will require new capabilities on correlation engine.
- Migration plan, from current to new syntax/format.

**Comment by DGawr** [comment]
I don't know how far along you are internally with this rule redesing but maybe the [Sigma](https://github.com/SigmaHQ/sigma) SIEM rule syntax would be worth a look at? It might not fit the Wazuh engine completely but in general the structure might be interesting as well as the capabilities for future additions to the correlation engine.
Besides it could enable (easy) conversion of Sigma rules to Wazuh rules in the future.

**Comment by branchnetconsulting** [comment]
I think it would be great to align the future Wazuh rule syntax as much as possible with the Sigma format so that SIEM-formatted rules available out there could easily be converted into Wazuh's exact rule format.  That would put the Wazuh product in good company with a variety of other enterprise grade SIEM solutions like Splunk, ArcSight, Qradar, Qualys, Logpoint, etc... for which Sigma-formatted rules can readily be converted to their vendor specific rule formats.  See [here](https://github.com/SigmaHQ/sigma#supported-targets).

**Comment by 72nomada** [comment]
Draft - Rule Skeleton 

```
title: Suspicious PowerShell Download
id: 60002
status: experimental
notification: no_full_log|alert_by_email|etc 
name: Invalid user connection
description: an user has f
tags:
    - attack.execution
    - attack.t1059.001
    - IDS
author: Florian Roth
date: 2017/03/05
type: alert. # can be alert or telemetry
logsource:
    vendor: windows
    module: sysmon
detection:
    log:
        event.syslog|contains|all:
            - Invalid user          
    sip:
        source.ip|contains|all:
            - 127.0.0.1   
    if_matched_sid:
            id: 60001
            frequency: 5
            timeframe: 8
    if_matched_group:#!low_usage
            frequency:
            timeframe:
            group:
    condition: (if_matched_sid or if_matched_group) and log and not ip
    condition: (if_matched_sid or if_matched_group) and log and not ip and (source.ip != destination.ip)
    condition: (if_matched_sid or if_matched_group) and log and not source.ip in [127.0.0.1, 192.168.0.*]
falsepositives:
    - User may have an automation script
	
```

**Comment by JavierBejMen** [comment]
# Detection YML tag --WIP--
This tags aims to encapsulate all logic afecting rule triggering, making it more user friendly while being able to support more degree of correlation.
## Template

```yml
detection:
    var_1:
        field[|operand_modifier]: value

    var_2:
        field[|operand_modifier]|multiplicity_modifier:
            - value_1
            - value_2
            .
            .
            .
            - value_n
    .
    .
    .
    var_n: ...

    condition: # logic expression between variables
```

## detection [required]
Indicates detection block begin, atleast one variable must be defined and condition must appear.
```yml
detection:
    variable: ...

    condition: ...
```
### variable [required]
Variable name, a variable to be evaluated on condition, must be unique in the same detection block. Takes true or false acording to their child (field).
```yml
detection:
    variable_A:...
    variable_B:...
    .
    .
    .
```
#### field [required]
```yml
detection:
    variable_A:
        field[|modifiers]: ... # modifier dependant
```
Specifies what is going to be evaluated, value depends on modifier, In a similar fashion as [Sigma modifiers](https://github.com/SigmaHQ/sigma/wiki/Specification#modifier-types), especifies how to process field value.

Allowed fields and modifiers:
- `normalized.field`: evaluates value of a extracted field, i.e., source.ip, event.type, event.category,...

  `context_field`: evaluates value of current context field, i.e., category, group, ...
  - **operand** modifiers (mutually exclusive, only one is accepted):
    - ```contains``` (**default**): field is matched against a regex (PCRE2)
    - ```not_contains```: field is matched against a regex (PCRE2) and negated
    - ```equals```: field is matched against a value, i.e., ```source.ip|equals: 192.168.1.2```
    - ```not_equals```: field is matched against a value and negated
  - **multiplicity** modifiers (mutually exclusive)(a list of values is espected):
    - if none multiplicity modifier present a single value is expected.
    - ```all```: every value must match.
    - ```any```: atleast one value must match.
- `requires`: indicates that a previous rule or requiremente must be matched
  - **multiplicity** modifiers (mutually exclusive)(a list of values is espected):
    - if none multiplicity modifier present a single value is expected.
    - ```all```: every value must match.
    - ```any```: atleast one value must match.
  - **frequency** modifier (exclusive, can't appear with other modifiers):
    - `frequency`: check if required item was matched multiple times, when this modifier is present accepts the following child tags:
      - `id` [required]:
      - `times`:
      - `timeframe`:
      - `samefield`:

### condition [required]
```yml
detection:
    variable_A: ...
    .
    .
    .

    condition:
```
Logic expresiont between variables, must me evaluated to true in order to allow alert trigger, operands:
- ```and```: Conjunction
- ```or```: Disjunction
- ```not```: Negation
- ```()```: Grouping

I.e., ```condition: var_a and (not var_b or var_c)```
