### ISSUE TITLE
Fix API integration test test_rbac_white_all and add test case for the endpoint PUT /security/users/{user_id}/run_as

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#7997]
Hi team,

When the new endpoint to enable/disable `run_as` (`PUT /security/users/{user_id}/run_as`) was created in this PR: https://github.com/wazuh/wazuh/pull/7588, the test `test_rbac_white_all_endpoints.tavern.yaml` wasn't modified.

The following test case is failing in that test as the endpoint `POST /security/users` is no longer assigning the `run_as` value to the user created. Remove `allow_run_as: true` from the test case.

```
---
test_name: POST /security/users

stages:
  - name: Try to add API user
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/security/users"
      method: POST
      json:
        username: newUser
        password: stringA1!
        allow_run_as: true
      headers:
        Authorization: "Bearer {test_login_token}"
    response:
      <<: *permission_denied
```

We also need to add a test case to `test_rbac_white_all_endpoints.tavern.yaml` to test the new endpoint `PUT /security/users/{user_id}/run_as`.

- [x] Fix `POST /security/users` test case
- [x] Add a test case to test the endpoint `PUT /security/users/{user_id}/run_as`

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)
