### ISSUE TITLE
Define translation map between decoder XML elements and YML language 

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#8010]
# Wazuh decoder specification
This is the documentation for the new Wazuh YAML decoders

## **Straightforward conversion from XML to YML**

Below are all posible XML tags and attributes with their direct conversion to YML: 

| XML  |  YML | 
|---|---|
| | decoders: <list of decoder type objects\> |
| <decoder <br> &nbsp;&nbsp;&nbsp;&nbsp;name="<string\>" <br> \>| &nbsp;- name: <string\> <br> |
|  &nbsp;&nbsp;&nbsp;&nbsp;<parent\>string</parent\> |  &nbsp;&nbsp;&nbsp;&nbsp;parent: <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text: <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<accumulate /\> | &nbsp;&nbsp;&nbsp;&nbsp;accumulate: <null\> |
|  &nbsp;&nbsp;&nbsp;&nbsp;<program_name <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type="<string\>" <br> &nbsp;&nbsp;&nbsp;&nbsp;\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;</program_name\> |  &nbsp;&nbsp;&nbsp;&nbsp;program_name: <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text: <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<prematch <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type="<string\>" <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;offset="<string\>" <br> &nbsp;&nbsp;&nbsp;&nbsp;\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;</prematch\> |  &nbsp;&nbsp;&nbsp;&nbsp;prematch: <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;offset: <string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text: <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<regex <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type="<string\>" <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;offset="<string\>" <br> &nbsp;&nbsp;&nbsp;&nbsp;\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;</regex\> |  &nbsp;&nbsp;&nbsp;&nbsp;regex: <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;offset: <string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text: <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<order\>list,of,strings</order\> | &nbsp;&nbsp;&nbsp;&nbsp;order:  <list of strings\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<fts\>list,of,strings</fts\> | &nbsp;&nbsp;&nbsp;&nbsp;fts:  <list of strings\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<ftscomment\>string</ftscomment\> | &nbsp;&nbsp;&nbsp;&nbsp;ftscomment:  <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<plugin_decoder <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;offset="<string\>" <br> &nbsp;&nbsp;&nbsp;&nbsp;\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;</plugin_decoder\> |  &nbsp;&nbsp;&nbsp;&nbsp;plugin_decoder: <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;offset: <string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text: <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<use_own_name\>string</use_own_name\> | &nbsp;&nbsp;&nbsp;&nbsp;use_own_name:  <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<json_null_field\>string</json_null_field\> | &nbsp;&nbsp;&nbsp;&nbsp;json_null_field:  <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<json_array_structure\>string</json_array_structure\> | &nbsp;&nbsp;&nbsp;&nbsp;json_array_structure:  <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<type\>string</type\> | &nbsp;&nbsp;&nbsp;&nbsp;type:  <string\>|
|  </decoder\> | |
| | variables: <list of var type objects\> |
| <var <br> &nbsp;&nbsp;&nbsp;&nbsp;name="<string\>" <br> \> <br> &nbsp;&nbsp;&nbsp;&nbsp;<string\> <br> </var\>|&nbsp;&nbsp;&nbsp;&nbsp;- name: <string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;text: <string\> |

## **Suggested conversion from XML to YML**

Below are all posible XML tags and attributes with their suggested conversion to YML: 

| XML  |  YML | 
|---|---|
| | decoders: <list of decoder type objects\> |
| <decoder <br> &nbsp;&nbsp;&nbsp;&nbsp;name="<string\>" <br> \>| &nbsp;- name: <string\> <br> |
|  &nbsp;&nbsp;&nbsp;&nbsp;<parent\>string</parent\> | &nbsp;&nbsp;&nbsp;&nbsp;parent:  <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<accumulate /\> | &nbsp;&nbsp;&nbsp;&nbsp;accumulate: <string\> |
|  &nbsp;&nbsp;&nbsp;&nbsp;<program_name <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type="<string\>" <br> &nbsp;&nbsp;&nbsp;&nbsp;\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;</program_name\> |  &nbsp;&nbsp;&nbsp;&nbsp;program_name:  <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<prematch <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type="<string\>" <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;offset="<string\>" <br> &nbsp;&nbsp;&nbsp;&nbsp;\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;</prematch\> |  &nbsp;&nbsp;&nbsp;&nbsp;prematch: <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;offset: <string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pattern: <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<regex <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;type="<string\>" <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;offset="<string\>" <br> &nbsp;&nbsp;&nbsp;&nbsp;\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;</regex\> |  &nbsp;&nbsp;&nbsp;&nbsp;match: <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;offset: <string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;pattern: <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<order\>list,of,strings</order\> | &nbsp;&nbsp;&nbsp;&nbsp;order:  <list of strings\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<fts\>list,of,strings</fts\> | &nbsp;&nbsp;&nbsp;&nbsp;fts:  <list of strings\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<ftscomment\>string</ftscomment\> | &nbsp;&nbsp;&nbsp;&nbsp;ftscomment:  <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<plugin_decoder <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;offset="<string\>" <br> &nbsp;&nbsp;&nbsp;&nbsp;\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;</plugin_decoder\> |  &nbsp;&nbsp;&nbsp;&nbsp;plugin_decoder: <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;offset: <string\> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;plugin: <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<use_own_name\>string</use_own_name\> | &nbsp;&nbsp;&nbsp;&nbsp;use_own_name:  <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<json_null_field\>string</json_null_field\> | &nbsp;&nbsp;&nbsp;&nbsp;json_null_field:  <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<json_array_structure\>string</json_array_structure\> | &nbsp;&nbsp;&nbsp;&nbsp;json_array_structure:  <string\>|
|  &nbsp;&nbsp;&nbsp;&nbsp;<type\>string</type\> | &nbsp;&nbsp;&nbsp;&nbsp;type:  <string\>|
|  </decoder\> | |
| <var <br> &nbsp;&nbsp;&nbsp;&nbsp;name="<string\>" <br> \> <br> &nbsp;&nbsp;&nbsp;&nbsp;<string\> <br> </var\>|  variables: <list of key:value pairs\> <br> |

## **Straightforward schema**
```yaml
variables:
  - name: <string>
    text: <string>

decoders:
  - name: <string>
    parent: <string>
    accumulate: <null>   
    program_name: 
      type: <string>
      text: <string> 
    prematch:
      type: <string>
      offset: <string>
      text: <string> 
    regex:
      type: <string>
      offset: <string>
      text: <string> 
    order: <list of strings>
    fts: <list of strings>
    ftscomment: <string>
    plugin_decoder: 
      offset: <string>
      text: <string>
    use_own_name: <string>
    json_null_field: <string>
    json_array_structure: <string>
    type: <string>
```
## **Suggested schema**
```yaml
variables: <list of key:value pairs>
  <string>: <string> # This structure can be repeated multiple times
  ...
  <string>: <string>

decoders: <list of decoder type objects>
  - decoder: <set of decoder attributes> # This structure can be repeated multiple times
      name: <string>
      parent: <string>
      accumulate: <string>   
      program_name: <string> 
      prematch:
        offset: <string>
        pattern: <string> 
      match:
        offset: <string>
        pattern: <string> 
      order: <list of strings>
      fts: <list of strings>
      ftscomment: <string>
      plugin_decoder: 
        offset: <string>
        plugin: <string>
      use_own_name: <string>
      json_null_field: <string>
      json_array_structure: <string>
      type: <string>
```
### **decoders**
**Type**: _List of decoder type objects_

General container for the "decoder" type of objects.

Example:
```yaml
decoders:
  - name: 'netscaler'
    ...
  - name: 'netscaler-SSLVPN-LOGIN'
    parent: 'netscaler'
    ...
```
### **parent**
**Type**: _String_

It is used to link a subordinate decoder to its parent. A parent decoder can have many child decoders but take into account that a child decoder cannot be a parent. It is possible to create what we call sibling decoders, which is a handy decoding strategy to handle dynamic logs.

Allowed values: _Any decoder name_

Example:

Decoder_junior will enter only if decoder_parent has previously matched.

```yaml
decoders:
  - name: 'decoder_junior'
    parent: 'decoder_parent'
  ...
```
### **accumulate**
**Type**: _String_

Allows Wazuh to track events over multiple log messages based on a decoded id. 

_Suggested change_: allow to use `yes` and `no` as possible `accumulate` values instead of using `accumulate` as a value-less key.

Example:
```yaml
accumulate: 'yes'
```
### **program_name**
**Type**: _String_

It defines the name of the program which the decoder is associated with. The program name of a log will be obtained, if possible, in the pre-decoding phase. Allows to set a PCRE2-type regular expression.

Example:

Define that the decoder is related with the test, TEST or equivalent (case-insensitive) process:
```yaml
decoders:
  - name: 'test_decoder'
    program_name: '(?i)test'
  ...
```

### **prematch**

It attempts to find a match within the log for the string defined. It is used as a condition to enter the decoder, if it finds a match, the current decoder will be used and the search for a decoder will stop and only its child decoders will be able to match. It is important to be as specific as possible to avoid matching with wrong events.

The "text" attribute allows to set a PCRE2-type regular expression.

The "offset" attribute allows to discard some of the content of the entry. Accepted values: after_regex, after_parent.

### **regex**

Regular expressions or _regex_ are sequences of characters that define a pattern. Decoders use them to find words or other patterns into the rules. The decoder will only extract those fields that are contained within parentheses.

Examples:

An example is this regex that matches any numeral:
```yaml
decoders:
  - name: 'sudo-fields'
    parent: 'sudo'
    prematch:
      text: '\s'
    regex:
      text: '^\s*(\S+)\s*:'
    order:
      - 'user.name'
    fts:
      - 'user.full_name'
      - 'user.name'
      - 'geo.location'
    ftscomment: 'First time user executed the sudo command'
```

### **order*
**Type**: _List of strings_

It defines what the parenthesis groups contain and the order in which they were received. It requires a _regex_ label defined on the same decoder.

Default Value: n/a
Static fields: srcuser, dstuser, user, srcip, dstip, srcport, dstport, protocol, system_name, id, url, action, status, data, extra_data.
Dynamic fields: Any string not included in the previous list

### **fts**
**Type**: _List of Strings_

Fist time seen. It is used to designate a decoder as one in which the first time it matches the administrator would like to be alerted.
The decoder will consider this option if the decoded event triggers a rule that uses if_fts.

Default Value: n/a
Allowed values: srcuser, dstuser, user, srcip, dstip, srcport, dstport, protocol, system_name, id, url, action, status, data, extra_data.

Example:

The following decoder will extract the user who generated the alert and the location from where it comes:
```yaml

  fts:
    - 'user.name'
    - 'geo.location'
...
```
### **ftscomment**
**Type**: _String_

It adds a comment to a decoder when _fts_ is used.
Allowed values: Any string

### ** plugin_decoder**

Use a specific plugin decoder to decode the incoming fields. It is useful for particular cases where it would be tricky to extract the fields by using regexes.

Default Value: n/a
Allowed values: PF_Decoder, SymantecWS_Decoder, SonicWall_Decoder, OSSECAlert_Decoder, JSON_Decoder

The attribute "offset" is optional, it allows to start the decode process after a particular point of the log.
Allowed values: after_parent, after_prematch.

### **use_own_name**
**Type**: _String_

Allows setting the name of the child decoder from the name attribute instead of using the name of the parent decoder.

Default Value: n/a
Allowed values: true

#### **json_null_field**
**Type**: _String_

Specifies how to treat the NULL fields coming from the JSON events. (Only for the JSON decoder).

Default Value: string.
Allowed values: string, discard.

#### **json_array_structure**
**Type**: _String_

Specifies how to treat the array structures coming from the JSON events. Only for the JSON decoder.

Default Value: array.
Allowed values: array, csv.

### **var**
**Type**: _key:value pair_
*Syntaxis*
var: 
  <string>: <string>
  <string>: <string>

Defines a variable that may be used in any place of the same file.

Example:
```yaml

header: 'myprog'
offset: 'after'
type: 'syscall'

```

#### **type**
**Type**: _List of strings_

It sets the type of log that the decoder is going to match.

Default Value: syslog.
Allowed values: firewall, ids, web-log, syslog, squid, windows, host-information, ossec.

Example:

Set type of decoder to syslog:
```yaml
decoder:
  type: 'syslog'
...
```
