### ISSUE TITLE
Provide method to disable API max_requests_per_minute

### ISSUE THREAD

**Issue by fhielpos** [wazuh/wazuh#8110]
|Wazuh version|Component|
|---|---|
| 4.1.x | wazuh-apid |

Hello team,

This feature request is to address the necessity to have a method to disable the `max_requests_per_minute` setting on the Wazuh API.

A current workaround is to set this setting on a high number, instead, it could have a toggle switch or the ability to set it to 0 to disable it.

For example:
```
# Access parameters
 access:
  max_login_attempts: 50
  block_time: 300
  max_request_per_minute: 0
```

Being `0 == disabled`

Regards,
Franco
