### ISSUE TITLE
API configuration validator does not accept lists in CORS

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#8485]
|Wazuh version|Component|
|---|---|
| 4.2 | Wazuh API |

## Description

Hi team!

Right now, the API configuration validator returns an error if a configuration like this is used in the `api.yaml`:
```YAML
cors:
  enabled: yes
  source_route: "https://test_url.com"
  expose_headers:
    - "Test-expose"
    - "another-expose"
  allow_headers:
    - "Content-type"
  allow_credentials: true
```

It is because right now, the schema does not accept arrays in the `expose_headers` and `allow_headers` fields. However, lists were supported before so the schema should be updated.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Selu.
