### ISSUE TITLE
Unable to authenticate wazuh filebeat to elasticsearch with opendistro plugin following documentation.

### ISSUE THREAD

**Issue by GuazP** [wazuh/wazuh#9004]
|Wazuh version|Component|Install type|Install method|Platform|Kernel|
|---|---|---|---|---|
| 4.1 | SSL authentiaction | Multinode elasticsearch with opendistro addon + Wazuh singlenode | Packages | Oracle Linux Server 8.3 | Kernel 5.4.17 |

Hello.
I followed steps described in step-by-step installation-guide, but generally that directed me to bug I am unable to debug and fix.
Precisely this is about last step at page:
https://documentation.wazuh.com/current/installation-guide/open-distro/distributed-deployment/step-by-step-installation/wazuh-cluster/wazuh_single_node_cluster.html#wazuh-single-node-cluster
It could work when I enable password authentication, but my case requires certificate based authentication.
There is error when I try to filebeat test output, after restarting services:
```
# filebeat test output
elasticsearch: https://10.10.10.107:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 10.10.10.107
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... ERROR 401 Unauthorized: Unauthorized
```

When basic steps from wazuh doc didn't work, I tried to fix it with following steps at opendistro wiki:
https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/client-auth/
https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/configuration/
I tried even basic config for ELK:
https://www.elastic.co/guide/en/elasticsearch/reference/current/pki-realm.html

Nothing worked really, but password authentication goes fine.
Configuration of /etc/elasticsearch/elasticsearch.yml: # Elastic master node
```
network.host: 10.10.10.107
node.name: machine1
cluster.name: wazuh-elastic-prod
cluster.initial_master_nodes:
        - machine1
        - machine2
        - machine3
discovery.seed_hosts:
        - 10.10.10.107
        - 10.10.10.108
        - 10.10.10.109

node.master: true
node.data: true
node.ingest: true

opendistro_security.ssl.transport.pemcert_filepath: /etc/elasticsearch/certs/elasticsearch.pem
opendistro_security.ssl.transport.pemkey_filepath: /etc/elasticsearch/certs/elasticsearch.key
opendistro_security.ssl.transport.pemtrustedcas_filepath: /etc/elasticsearch/certs/root-ca.pem
opendistro_security.ssl.transport.enforce_hostname_verification: false
opendistro_security.ssl.transport.resolve_hostname: false
opendistro_security.ssl.http.enabled: true
opendistro_security.ssl.http.pemcert_filepath: /etc/elasticsearch/certs/elasticsearch_http.pem
opendistro_security.ssl.http.pemkey_filepath: /etc/elasticsearch/certs/elasticsearch_http.key
opendistro_security.ssl.http.pemtrustedcas_filepath: /etc/elasticsearch/certs/root-ca.pem
opendistro_security.nodes_dn:
- CN=machine1,OU=Operations,O=<censored>,L=<some-city>,C=DE
- CN=machine2,OU=Operations,O=<censored>,L=<some-city>,C=DE
- CN=machine3,OU=Operations,O=<censored>,L=<some-city>,C=DE
opendistro_security.authcz.admin_dn:
- CN=admin,OU=Operations,O=<censored>,L=<some-city>,C=DE
opendistro_security.ssl.http.clientauth_mode: OPTIONAL


opendistro_security.audit.type: internal_elasticsearch
opendistro_security.enable_snapshot_restore_privilege: true
opendistro_security.check_snapshot_restore_write_privileges: true
opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
cluster.routing.allocation.disk.threshold_enabled: false
node.max_local_storage_nodes: 3

path.data: /opt/elasticsearch
path.logs: /var/log/elasticsearch
```
Configuration of plugins/opendistro_security/securityconfig/config.yml # Elastic master node
```
---
_meta:
  type: "config"
  config_version: 2
config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: "192\\.168\\.0\\.10|192\\.168\\.0\\.11"
    authc:
      kerberos_auth_domain:
        http_enabled: false
        transport_enabled: false
        order: 6
        http_authenticator:
          type: "kerberos"
          challenge: true
          config:
            krb_debug: false
            strip_realm_from_principal: true
        authentication_backend:
          type: "noop"
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 4
        http_authenticator:
          type: "basic"
          challenge: true
        authentication_backend:
          type: "intern"
      proxy_auth_domain:
        description: "Authenticate via proxy"
        http_enabled: false
        transport_enabled: false
        order: 3
        http_authenticator:
          type: "proxy"
          challenge: false
          config:
            user_header: "x-proxy-user"
            roles_header: "x-proxy-roles"
        authentication_backend:
          type: "noop"
      jwt_auth_domain:
        description: "Authenticate via Json Web Token"
        http_enabled: false
        transport_enabled: false
        order: 0
        http_authenticator:
          type: "jwt"
          challenge: false
          config:
            signing_key: "base64 encoded HMAC key or public RSA/ECDSA pem key"
            jwt_header: "Authorization"
            jwt_url_parameter: null
            roles_key: null
            subject_key: null
        authentication_backend:
          type: "noop"
      clientcert_auth_domain:
        description: "Authenticate via SSL client certificates"
        http_enabled: true
        transport_enabled: true
        order: 2
        http_authenticator:
          type: "clientcert"
          config:
            username_attribute: "cn"
          challenge: false
        authentication_backend:
          type: "noop"
      ldap:
        description: "Authenticate via LDAP or Active Directory"
        http_enabled: false
        transport_enabled: false
        order: 5
        http_authenticator:
          type: "basic"
          challenge: false
        authentication_backend:
          type: "ldap"
          config:
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: true
            hosts:
            - "localhost:8389"
            bind_dn: null
            password: null
            userbase: "ou=people,dc=example,dc=com"
            usersearch: "(sAMAccountName={0})"
            username_attribute: null
    authz:
      roles_from_myldap:
        description: "Authorize via LDAP or Active Directory"
        http_enabled: false
        transport_enabled: false
        authorization_backend:
          type: "ldap"
          config:
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: true
            hosts:
            - "localhost:8389"
            bind_dn: null
            password: null
            rolebase: "ou=groups,dc=example,dc=com"
            rolesearch: "(member={0})"
            userroleattribute: null
            userrolename: "disabled"
            rolename: "cn"
            resolve_nested_roles: true
            userbase: "ou=people,dc=example,dc=com"
            usersearch: "(uid={0})"
      roles_from_another_ldap:
        description: "Authorize via another Active Directory"
        http_enabled: false
        transport_enabled: false
        authorization_backend:
          type: "ldap"
```
Configuration of /etc/filebeat/filebeat.yml #Wazuh node
```
# Wazuh - Filebeat configuration file
output.elasticsearch:
  enabled: true
  hosts: ["10.10.10.107:9200", "10.10.10.108:9200", "10.10.10.109:9200"]
  #username and password censored - but case is with password authentication it works
  protocol: https
  ssl.certificate_authorities: ["/etc/filebeat/certs/root-ca.pem"]
  ssl.certificate: "/etc/filebeat/certs/filebeat.pem"
  ssl.key: "/etc/filebeat/certs/filebeat.key"
  ssl.verification_mode: certificate
setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.ilm.overwrite: true
setup.ilm.enabled: false

filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false
```

Certificates are double-checked if are valid, and I don't think there is a problem.

Just in case if that could be filebeat <-> elasticsearch error, I tried to connect kibana from wazuh node:
```

server.host: "0.0.0.0"
elasticsearch.hosts: ["https://10.10.10.107:9200", "https://10.10.10.108:9200", "https://10.10.10.109:9200"]
server.port: 443
elasticsearch.ssl.verificationMode: certificate
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
opendistro_security.multitenancy.enabled: true
opendistro_security.readonly_mode.roles: ["kibana_read_only"]
server.ssl.enabled: true
server.ssl.key: "/etc/kibana/certs/kibana.key"
server.ssl.certificate: "/etc/kibana/certs/kibana.pem"
elasticsearch.ssl.certificateAuthorities: ["/etc/kibana/certs/root-ca.pem"]
server.defaultRoute: /app/wazuh?security_tenant=global

```

But that doesn't work either. 
My only guess is something missing in wazuh-documentation related to opendistro configuration.

All configs are censored at some places, but I had to do this. If should I send something more to help you reproduce error, feel free to ask.
How could I connect using certificates?

Thanks in advance!
