### ISSUE TITLE
Review RBAC agent API integration tests expected response

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#9695]
|Wazuh version|Component|
|---|---|
| 4.2.0-rc13 | API |

After reviewing the API integration tests in the issue https://github.com/wazuh/wazuh/issues/9689, we have seen that there are some RBAC tests that expect certain fields in the response. These tests must only check the status code as they aim to test the RBAC permissions.

For instance, this test:

https://github.com/wazuh/wazuh/blob/39b4ff30a8a6f9b034240798ebbf43f4623ab625/api/test/integration/test_rbac_white_agent_endpoints.tavern.yaml#L238-L266

It should be like this:

```yaml
---
test_name: GET /agents/{agent_id}/stats/{component}

stages:

 - name: Try to get logcollector stats from agent 002 (Allowed)
   request:
     verify: False
     url: "{protocol:s}://{host:s}:{port:d}/agents/002/stats/logcollector"
     method: GET
     headers:
       Authorization: "Bearer {test_login_token}"
   response:
     status_code: 200
```
